Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2021-06, with the labels that each got.

#996 Update Rule “do-you-know-how-to-claim-expense-reimbursements/rule”
  rules/do-you-know-how-to-claim-expense-reimbursements/rule.md
Labels: netlify-cms/pending_publish

#998 Update Rule “spec-do-you-conduct-a-specification-review-ask-for-a-coffee-not-a-marriage/rule”
  rules/spec-do-you-conduct-a-specification-review-ask-for-a-coffee-not-a-marriage/rule.md
Labels: netlify-cms/pending_publish

#999 Create Rule “do-you-test-netlify/rule”
  rules/do-you-test-netlify/rule.md
Labels: netlify-cms/pending_review

#997 Update Rule “404-error-avoid-changing-the-url/rule”
  rules/404-error-avoid-changing-the-url/rule.md
Labels: netlify-cms/pending_publish

#1005 Update Rule “do-you-understand-the-value-of-consistency/rule”
  rules/do-you-understand-the-value-of-consistency/rule.md
Labels: netlify-cms/pending_publish

#1011 Update Rule “agreements-do-you-know-who-pays-for-bugs/rule”
  rules/agreements-do-you-know-who-pays-for-bugs/rule.md
  rules/agreements-do-you-know-who-pays-for-bugs/white-ssw-wallpaper-with-tagline.png
Labels: netlify-cms/pending_publish

#1012 Update Rule “make-your-site-easy-to-maintain/rule”
  rules/make-your-site-easy-to-maintain/rule.md
Labels: netlify-cms/draft

#1010 Update Rule “do-you-know-how-to-claim-expense-reimbursements/rule”
  rules/do-you-know-how-to-claim-expense-reimbursements/rule.md
Labels: netlify-cms/pending_review

#1025 Update Rule “do-you-understand-the-value-of-consistency/rule”
  rules/do-you-understand-the-value-of-consistency/rule.md
Labels: netlify-cms/pending_review

#1055 Update Rule “Employee-YOLO-Day/rule”
  rules/Employee-YOLO-Day/rule.md
Labels: netlify-cms/pending_publish

#1057 Update Rule “do-you-understand-the-value-of-consistency/rule”
  rules/do-you-understand-the-value-of-consistency/rule.md
Labels: netlify-cms/pending_publish

#1100 Update Rule “use-sql-views/rule”
  rules/use-sql-views/rule.md
Labels: netlify-cms/pending_publish

#1101 Update Rule “use-sql-views/rule”
  rules/use-sql-views/rule.md
Labels: netlify-cms/pending_publish
