Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2023-06, with the labels that each got.

#5646 Update rule.md
  rules/apple-google-pay-for-expenses/rule.md
Labels: rubber stamp

#5643 Added to category + general improvements "developer-console-screenshots"
  categories/marketing-and-video/rules-to-better-video-recording.md
  rules/developer-console-screenshots/rule.md
Labels: rubber stamp

#5672 fixed small bug "project-setup"
  rules/project-setup/rule.md
Labels: rubber stamp

#5689 Added code language "print-url"
  rules/print-url/rule.md
Labels: codeauditor fix

#5687 From absolute to relative link "mobile-device-policy"
  rules/dev-mobile-device-policy/rule.md
Labels: codeauditor fix

#5686 Links from absolute to relative "override-branch-protection"
  rules/override-branch-protection/rule.md
Labels: codeauditor fix

#5685 added a line break and moved Notes down "share-private-link-wp"
  rules/do-you-know-how-to-share-a-private-link-of-a-draft-post/rule.md
Labels: rubber stamp

#5684 removed broken link
  rules/do-you-know-these-important-git-commands/rule.md
Labels: codeauditor fix

#5705 removed extra space which caused a bug + from zero to 0 "avoid-decimals"
  rules/avoid-using-too-many-decimals/rule.md
Labels: rubber stamp

#5706 Cropped image for better reading "less-is-more"
  rules/less-is-more/good-example-clarity.jpg
  rules/less-is-more/responding-bad-example.jpg
Labels: rubber stamp

#5747 Added related "less-is-more"
  rules/less-is-more/rule.md
Labels: rubber stamp

#5770 Fixed broken link "network-hardware"
  rules/keep-your-network-hardware-reliable/rule.md
Labels: codeauditor fix

#5771 Removed broken link taken down by amex "criticism"
  rules/how-to-take-feedback-or-criticism/rule.md
Labels: codeauditor fix

#5782 Created script to detect unused images
  .github/workflows/check-images.yml
  scripts/find-unreferenced-images/.gitignore
  scripts/find-unreferenced-images/find-unreferenced-images.js
  scripts/find-unreferenced-images/package-lock.json
  scripts/find-unreferenced-images/package.json
Labels: code change

#5825 Added check to see if directory exists
  scripts/find-unreferenced-images/find-unreferenced-images.js
Labels: code change

#5862 Update Rule “do-you-know-to-do-data-you-need-caml/rule”
  rules/do-you-know-to-do-data-you-need-caml/rule.md
Labels: codeauditor fix

#5863 Update Rule “is-your-first-aim-to-customize-a-sharepoint-webpart/rule”
  rules/is-your-first-aim-to-customize-a-sharepoint-webpart/rule.md
Labels: codeauditor fix

#5864 Update Rule “do-you-use-field-and-list-item-validation-in-2010/rule”
  rules/do-you-use-field-and-list-item-validation-in-2010/rule.md
Labels: codeauditor fix

#5874 Update Rule “sharepoint-online-do-you-get-rid-of-classic-features/rule”
  rules/sharepoint-online-do-you-get-rid-of-classic-features/rule.md
Labels: codeauditor fix

#5865 Update Rule “do-you-know-how-to-work-with-document-versions/rule”
  rules/do-you-know-how-to-work-with-document-versions/rule.md
Labels: codeauditor fix

#5866 Update Rule “do-you-turn-off-auto-activation-on-farm-and-web-application-scope-features/rule”
  rules/do-you-turn-off-auto-activation-on-farm-and-web-application-scope-features/rule.md
Labels: codeauditor fix

#5873 Update Rule “do-you-confirm-there-is-no-checked-out-data/rule”
  rules/do-you-confirm-there-is-no-checked-out-data/rule.md
Labels: codeauditor fix

#5872 Update Rule “do-you-clean-useless-calendars-in-sharepoint/rule”
  rules/do-you-clean-useless-calendars-in-sharepoint/rule.md
Labels: codeauditor fix

#5871 Update Rule “do-you-ensure-your-application-pool-is-always-running/rule”
  rules/do-you-ensure-your-application-pool-is-always-running/rule.md
Labels: codeauditor fix

#5870 Update Rule “do-you-use-gzip/rule”
  rules/do-you-use-gzip/rule.md
Labels: codeauditor fix

#5869 Update Rule “enable-sql-connect-to-the-common-data-service/rule”
  rules/enable-sql-connect-to-the-common-data-service/rule.md
Labels: codeauditor fix

#5868 Update Rule “do-you-make-batch-files-for-deployment-to-test-and-production-servers/rule”
  rules/do-you-make-batch-files-for-deployment-to-test-and-production-servers/rule.md
Labels: codeauditor fix

#5867 Update Rule “never-dispose-objects-from-spcontext-current/rule”
  rules/never-dispose-objects-from-spcontext-current/rule.md
Labels: codeauditor fix

#5877 🗑️ Remove unnessercary check
  .github/workflows/TriggerDevOpsBuild.yml
  .workflow/cancelPreviousBuilds.ps1
Labels: code change
