Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2023-12, with the labels that each got.

#7365 Update Rule “azure-budgets/rule”
  rules/azure-budgets/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7385 XS✔ ◾ Markdown lint action - No longer run on forked branches
  .github/workflows/validate-markdown.yml
Labels: Age: 🥚 - New

#7387 XS✔ ◾ Improve formatting for 'Do you identify Development, Test and Production Web Servers by colors?'
  rules/do-you-identify-development-test-and-production-crm-web-servers-by-colors/rule.md
Labels: Age: 🥚 - New

#7384 XS✔ ◾ Add files via upload
  rules/do-you-have-a-call-to-action-on-your-web-pages-aka-the-banana-rule/BadBananaQantas.png
  rules/do-you-have-a-call-to-action-on-your-web-pages-aka-the-banana-rule/rule.md
Labels: Age: 🥚 - New

#7396 Update Rule “efcore-in-memory-provider/rule”
  rules/efcore-in-memory-provider/rule.md
Labels: Age: 🥚 - New

#7389 XS✔ ◾ Update and rename rule title and uri
  categories/infrastructure-and-networking/rules-to-better-security.md
  rules/migrate-an-existing-user-store-to-an-externalauthprovider/rule.md
Labels: Age: 🥚 - New

#7399 XS✔ ◾ Added tips to avoid overuse of golden moments
  rules/golden-moment/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7402 XS✔ ◾ Adding new /avoid-using-share-functionality to category
  categories/communication/rules-to-better-email.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7403 Added markdown file type to rules-to-better-yarp category file
  categories/software-development/rules-to-better-yarp.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7406 XS✔ ◾ Update rule.md - added semantic changes and a an additional redirect
  rules/migrate-an-existing-user-store-to-an-externalauthprovider/rule.md
Labels: Age: 🥚 - New

#7410 XS✔ ◾ Mention Done video in PR description
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#7413 XS✔ ◾ CodeAuditor Scan - Fix JK's broken profile image
  rules/do-you-create-a-migration-plan/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7418 XS✔ ◾ CodeAuditor Scan - Update Rule "Do you use the Pomodoro Technique?"
  rules/pomodoro/rule.md
Labels: codeauditor fix, Age: 🐣 - Young

#7420 XS✔ ◾ fix name of rule
  categories/management/rules-to-better-sales.md
  rules/do-you-know-what-currency-to-quote-overseas/rule.md
Labels: Age: 🐣 - Young

#7425 XS✔ ◾ Added redirect from old URI /positive-tone/
  rules/positive-tone/rule.md
Labels: rubber stamp, Age: 🐥 - Adolescent

#7423 XS✔ ◾ Shorten URL /schedule-followup-meeting-after-spec-review
  categories/management/rules-to-better-sales.md
  rules/schedule-followup-meeting-after-spec-review/rule.md
Labels: Age: 🐥 - Adolescent

#7424 XS✔ ◾ Making link clickable /manage-product-feedback
  rules/manage-product-feedback/rule.md
Labels: Age: 🐤 - Mature

#7427 Create Rule “ab-testing-social-paid-campaigns/rule”
  rules/ab-testing-social-paid-campaigns/rule.md
Labels: Age: 🐓 - Old

#7438 Update Rule “do-you-know-what-currency-to-quote-overseas/rule”
  rules/do-you-know-what-currency-to-quote-overseas/rule.md
Labels: Age: 🐣 - Young

#7430 Update Rule “do-you-involve-stakeholders-in-pi-planning/rule”
  rules/do-you-involve-stakeholders-in-pi-planning/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7429 Update Rule “shadow-spec-reviews/rule”
  rules/shadow-spec-reviews/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7436 Update Rule “avoid-using-too-many-decimals/rule”
  rules/avoid-using-too-many-decimals/rule.md
Labels: Age: 🐣 - Young

#7431 XS✔ ◾ Update 'When to go for a tender' to fix comma placement
  rules/when-to-go-for-a-tender/rule.md
Labels: Age: 🐓 - Old

#7440 XS✔ ◾ Added experts and consutling info to .Net 8 migration category
  categories/software-development/rules-to-better-net8-migrations.md
Labels: Age: 🐣 - Young

#7441 XS✔ ◾ Added experts and consutling info to CRM category
  categories/management/rules-to-better-crm.md
Labels: Age: 🥚 - New

#7426 XS✔ ◾ Fixed archived rule and link
  categories/marketing-and-video/rules-to-better-video-recording.md
  rules/post-production-do-you-know-how-to-get-your-videos-approved/rule.md
  rules/test-please-for-video/rule.md
Labels: Age: 🐓 - Old

#7442 XS✔ ◾ fixed common spelling mistakes
  categories/application-lifecycle-management-alm/rules-to-better-version-control-with-tfs-aka-source-control.md
  rules/asp-net-vs-sharepoint-development-do-you-know-deployment-is-different/rule.md
  rules/avoid-deploying-source-code-on-the-production-server/rule.md
  rules/avoid-using-web-site-projects/rule.md
  rules/do-you-add-a-redirect-from-http-to-https-for-owa/rule.md
  rules/do-you-add-an-exception-for-hosts-file-on-windows-defender/rule.md
  rules/do-you-avoid-using-a-counter/rule.md
  rules/do-you-deploy-to-azure-from-team-foundation-service/rule.md
  rules/do-you-document-the-details-of-your-sharepoint-2007-web-application/rule.md
  rules/do-you-have-a-dog-aka-digital-on-screen-graphic-on-your-videos/rule.md
  rules/do-you-know-the-easiest-way-to-continuously-deploy-is-to-use-visualstudio-com-and-azure/rule.md
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
  rules/do-you-publish-simple-websites-directly-to-windows-azure-from-visual-studio-online/rule.md
  rules/do-you-separate-javascript-functionality-aka-unobtrusive-javascript/rule.md
  rules/do-you-use-an-internet-intranet-for-sharing-common-information-such-as-company-standards/rule.md
  rules/do-you-use-the-kent-beck-philosophy/rule.md
  rules/forgot-password-do-you-read-their-mind/rule.md
  rules/how-to-add-a-group-for-all-staff-who-answer-live-chats/rule.md
  rules/keep-dynamics-365-online-synced-with-azure-ad/rule.md
  rules/modernize-your-app/rule.md
  rules/responsive-design/rule.md
  rules/spike-in-azure-resource-costs/rule.md
  rules/the-touch-it-once-principle/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7444 XS✔ ◾ fixed aka spelling
  rules/angular-read-and-write-to-the-model-never-to-the-page/rule.md
  rules/do-a-retrospective/rule.md
  rules/dont-push-your-pull-requests/rule.md
  rules/mockups-and-prototypes/rule.md
  rules/tools-to-manage-apis/rule.md
  rules/where-to-find-nice-icons/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7421 XS✔ ◾ Improved headings /migrate-an-existing-user-store-to-an-externalauthp…
  rules/migrate-an-existing-user-store-to-an-externalauthprovider/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7432 Update Rule “separate-your-angular-components-into-container-and-presentational/rule”
  rules/separate-your-angular-components-into-container-and-presentational/rule.md
Labels: Age: 🐓 - Old

#7451 Update Rule “do-you-email-clients-as-soon-as-you-realise-you-will-overrun-your-original-estimate/rule”
  rules/do-you-email-clients-as-soon-as-you-realise-you-will-overrun-your-original-estimate/rule.md
Labels: Age: 🥚 - New

#7457 Csharp collection expressions
  categories/software-development/rules-to-better-code.md
  rules/do-you-use-collection-expressions/rule.md
Labels: Age: 🐣 - Young

#7458 Added primary constructors rule
  categories/software-development/rules-to-better-code.md
  rules/do-you-use-primary-constructors/rule.md
Labels: Age: 🐣 - Young

#7456 XS✔ ◾ CodeAuditor Scan - Fix JK's broken image
  rules/migrating-web-apps/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#7464 XS✔ ◾ Fix url for rule /what-currency-to-quote
  rules/do-you-know-what-currency-to-quote-overseas/rule.md
Labels: Age: 🥚 - New

#7463 XS✔ ◾ Added redirect to /do-you-have-catering
  rules/do-you-have-catering/rule.md
Labels: Age: 🐣 - Young

#7466 💄 Add examples for active language
  rules/do-you-use-active-language-in-your-emails/rule.md
Labels: Age: 🥚 - New

#7467 Update Rule “triaging-do-you-correctly-triage-additional-item-requests/rule”
  rules/triaging-do-you-correctly-triage-additional-item-requests/rule.md
Labels: Age: 🥚 - New

#7465 XS⚠️ ◾ Validating all frontmatter for issues
  .github/workflows/validate-frontmatter-all.yml
  scripts/frontmatter-validator/frontmatter-validator.js
Labels: Age: 🐥 - Adolescent

#7475 XS✔ ◾ fix linting on this rule
  rules/do-you-manage-clients-expectations/rule.md
Labels: Age: 🥚 - New

#7476 XS✔ ◾ Another potential fix
  rules/tweet-rules-you-follow/rule.md
Labels: Age: 🥚 - New

#7477 XS✔ ◾ Move archivereason to the bottom
  rules/tweet-rules-you-follow/rule.md
Labels: Age: 🥚 - New

#7461 XS✔ ◾ Added good example to /avoid-using-share-functionality
  rules/avoid-using-share-functionality/rule.md
Labels: Age: 🐓 - Old

#7473 XS✔ ◾ ✨Create rule | Do you use text formatting to mention email subjects
  categories/communication/rules-to-better-microsoft-teams.md
  rules/do-you-use-text-formatting-to-mention-email-subjects/bad-example.png
  rules/do-you-use-text-formatting-to-mention-email-subjects/good-example.png
  rules/do-you-use-text-formatting-to-mention-email-subjects/rule.md
Labels: Age: 🐓 - Old

#7484 XS✔ ◾ Rename rule and update uri
  categories/design-and-presentation/rules-to-better-interfaces-windows-applications.md
  rules/sound-message-box/rule.md
Labels: Age: 🥚 - New

#7481 Cms/ash anil/ssw.rules.content/rule/do you make your team meetings easy to find/rule
  rules/do-you-make-your-team-meetings-easy-to-find/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7483 Update and rename local-copies-to-avoid-race-condition/rule.md
  rules/local-copies-to-resolve-race-condition/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7480 Added bullet points to brain storming idea farming rule
  rules/brainstorming-idea-farming/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7486 Update Rule “include-annual-cost/rule”
  rules/include-annual-cost/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7487 New Rule - Salary Sacrificing -Electronic Devices
  categories/management/rules-to-better-accounting.md
  rules/salary-sacrificing-eletronic-devices/rule.md
Labels: Age: 🐤 - Mature

#7488 XS✔ ◾ Updated rule on good and bad examples
  categories/communication/rules-to-better-technical-documentation.md
  rules/use-bad-and-good-examples/rule.md
Labels: Age: 🐣 - Young

#7489 XS✔ ◾ Fixed link in archived reason
  rules/do-you-keep-your-client-informed-of-progress/rule.md
Labels: rubber stamp, Age: 🐣 - Young

#7494 XS✔ ◾ Revert "XS✔ ◾ Fixed link in archived reason"
  rules/do-you-keep-your-client-informed-of-progress/rule.md
Labels: Age: 🥚 - New

#7492 XS✔ ◾ Update scrum team contact rule.md
  rules/scrum-team-contract/rule.md
Labels: Age: 🥚 - New

#7491 Update Rule “do-you-manage-clients-expectations/rule”
  rules/do-you-manage-clients-expectations/rule.md
Labels: Age: 🥚 - New

#7495 XS✔ ◾ Add files via upload
  rules/linkedin-creator-mode/Gert.png
Labels: Age: 🥚 - New

#7496 XS✔ ◾ Update rule.md
  rules/linkedin-creator-mode/rule.md
Labels: Age: 🥚 - New

#7498 XS✔ ◾ removed abs links
  rules/do-you-manage-clients-expectations/rule.md
  rules/do-you-use-built-in-authentication-from-ms/rule.md
Labels: Age: 🥚 - New

#7497 XS✔ ◾ Disable rule - no inline html
  .markdownlint/config.json
Labels: Age: 🥚 - New

#7500 XS✔ ◾ Update rules-to-better-websites-layout-and-formatting.md
  categories/websites/rules-to-better-websites-layout-and-formatting.md
Labels: Age: 🥚 - New

#7501 Added ADR image
  rules/do-you-use-architectural-decision-records/adr.png
  rules/do-you-use-architectural-decision-records/rule.md
Labels: Age: 🥚 - New

#7504 XS✔ ◾ Small improvements to the banana rule
  rules/cta-banana-rule/rule.md
  rules/production-do-you-add-a-call-to-action/rule.md
Labels: Age: 🥚 - New

#7513 XS✔ ◾ Archived generic rule on interfaces
  categories/websites/rules-to-better-websites-tuning-and-maintenance.md
  rules/continually-improve-ui/rule.md
Labels: Age: 🥚 - New

#7514 XS✔ ◾ Updated link and moved from content to related
  rules/do-you-know-how-to-structure-a-project-for-github/rule.md
Labels: Age: 🥚 - New

#7508 XS✔ ◾ "banana" in quotes for consistency
  rules/cta-banana-rule/rule.md
Labels: rubber stamp, Age: 🐥 - Adolescent

#7520 XS✔ ◾ Add files via upload
  rules/consistent-content-across-social-media/Consistent.png
  rules/consistent-content-across-social-media/Inconsistent.png
  rules/consistent-content-across-social-media/rule.md
Labels: Age: 🥚 - New

#7519 XS✔ ◾ Moved link from content to related
  rules/quality-do-you-implement-an-error-logger-that-has-notifications/rule.md
Labels: Age: 🥚 - New

#7518 XS✔ ◾ Removed unnecessary redirect
  rules/do-you-show-your-phone-number-in-skype/rule.md
Labels: Age: 🥚 - New

#7517 XS✔ ◾ Fixed links to be descriptive /graphql-when-to-use
  rules/graphql-when-to-use/rule.md
Labels: Age: 🥚 - New

#7516 XS✔ ◾ Updated example with the new URL
  rules/track-project-documents/rule.md
Labels: Age: 🐣 - Young

#7515 XS✔ ◾ Removed unnecessary redirect + Small improvements to /give-clients-a-warm-welcome
  rules/give-clients-a-warm-welcome/rule.md
Labels: Age: 🐣 - Young

#7512 XS✔ ◾ Updated links /analyze-your-website-stats/
  rules/analyze-your-website-stats/rule.md
Labels: Age: 🐥 - Adolescent

#7511 XS✔ ◾ Updated old link
  rules/do-you-know-the-quickest-way-to-get-your-windows-soe-up-and-running/rule.md
  rules/do-you-know-to-make-sure-that-you-book-the-next-appointment-before-you-leave-the-client/rule.md
  rules/do-you-timebox-approval-requests/rule.md
  rules/how-to-handle-errors-in-raygun/rule.md
  rules/improve-performance-with-lazy-loading-of-media-assets/rule.md
  rules/keep-business-logic-out-of-the-presentation-layer/rule.md
  rules/quality-do-you-make-your-templates-accessible-to-everyone-in-your-organisation/rule.md
  rules/set-up-your-mailbox-in-crm/rule.md
  rules/the-different-types-of-test/rule.md
Labels: rubber stamp, Age: 🐥 - Adolescent

#7510 XS✔ ◾ Updated old link on archived
  rules/add-quality-control-to-dones/rule.md
  rules/avoid-empty-lines-at-the-start-of-character-columns/rule.md
  rules/do-you-know-how-to-use-balloons-in-screenshots-for-instructions/rule.md
  rules/do-you-turn-off-auto-update-on-your-sharepoint-servers/rule.md
  rules/do-you-use-email-signatures/rule.md
  rules/image-size-instagram/rule.md
  rules/maximum-row-size-for-a-table/rule.md
  rules/mention-when-you-make-a-pull-request-or-comment-on-github/rule.md
  rules/submit-all-dates-to-sql-server-in-iso-format/rule.md
  rules/the-best-ide-for-react/rule.md
  rules/use-css-class-form-horizontal-to-arrange-fields-and-labels/rule.md
  rules/use-the-mediator-pattern-with-cqrs/rule.md
Labels: Age: 🐥 - Adolescent

#7509 XS✔ ◾ Updated old link + fixed markdown for images "dynamics-crm-install-the-dynamics-365-app-for-outlook"
  rules/dynamics-crm-install-the-dynamics-365-app-for-outlook/rule.md
Labels: Age: 🐥 - Adolescent

#7521 XS✔ ◾ followupthen - improve example
  rules/follow-up-effectively/rule.md
Labels: Age: 🥚 - New

#7507 XS✔ ◾ Fixed old link
  rules/call-sysadmins-before-formatting-company-owned-laptops/rule.md
Labels: Age: 🐥 - Adolescent

#7506 XS✔ ◾ Updated link on archived
  rules/know-that-no-carriage-returns-without-line-feed/rule.md
  rules/use-emojis-in-you-channel-names/rule.md
Labels: Age: 🐤 - Mature

#7505 XS✔ ◾ Updated old rules links + improvements
  rules/do-you-send-tasks-one-email-at-a-time/rule.md
Labels: Age: 🐤 - Mature

#7527 XS✔ ◾ Create rule.md
  categories/design-and-presentation/rules-to-better-designers.md
  categories/marketing-and-video/rules-to-better-social-media-for-business.md
  rules/when-to-use-canva/bad-social.png
  rules/when-to-use-canva/good-meme.png
  rules/when-to-use-canva/rule.md
Labels: Age: 🥚 - New

#7503 XS✔ ◾ Several improvements to the "checked by" rule
  rules/checked-by-xxx/rule.md
Labels: Age: 🐤 - Mature

#7524 XS✔ ◾ Update guidance on converting emails into PBIs
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🐣 - Young

#7534 XS✔ ◾ Correct formatting in email examples
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🥚 - New

#7530 XS✔ ◾ Update rule/use-robots-txt-effectively.md
  rules/use-robots-txt-effectively/rule.md
Labels: Age: 🐥 - Adolescent

#7535 XS✔ ◾ Add placeholder rule for novated leases
  rules/salary-sacrifice-electronic-devices/rule.md
  rules/salary-sacrifice-novated-lease/rule.md
Labels: Age: 🐤 - Mature

#7537 XS✔ ◾ Fixed old links
  rules/add-a-bot-signature-on-automated-emails/rule.md
  rules/answer-im-questions-in-order/rule.md
  rules/do-you-have-a-dress-code/rule.md
  rules/do-you-hold-regular-company-meetings/rule.md
  rules/do-you-know-how-to-get-approval-to-book-a-flight/rule.md
  rules/do-you-know-how-to-use-social-media-effectively-in-china/rule.md
  rules/do-you-know-when-to-use-full-stops-at-the-end-of-bullet-points/rule.md
  rules/do-you-reward-your-employees-for-doing-their-timesheets-on-time/rule.md
  rules/follow-up/rule.md
  rules/have-a-definition-of-ready/rule.md
  rules/how-to-create-a-rule-category/rule.md
  rules/how-to-create-a-rule/rule.md
  rules/how-to-use-ssw-style-in-radhtmlcontrol/rule.md
  rules/httphandlers-sections-in-webconfig-must-contain-a-clear-element/rule.md
  rules/is-everyone-in-your-team-a-standards-watchdog/rule.md
  rules/production-do-you-use-multiple-cameras/rule.md
  rules/rename-a-rule/rule.md
  rules/the-standard-naming-conventions-for-tests/rule.md
  rules/use-the-brains-of-your-company/rule.md
  rules/use-triggers-for-denormalized-fields/rule.md
  rules/what-metrics-to-collect-stage-3/rule.md
  rules/when-to-hire-more-people/rule.md
  rules/who-is-in-charge-of-keeping-the-schedule/rule.md
Labels: Age: 🐥 - Adolescent

#7536 XS✔ ◾ Fixed links /do-you-manage-clients-expectations
  rules/do-you-manage-clients-expectations/rule.md
Labels: Age: 🐥 - Adolescent

#7538 XS✔ ◾ Add salary sacrifice rules to accounting category
  categories/management/rules-to-better-accounting.md
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🥚 - New

#7540 XS✔ ◾ Salary terms - clean up levis name
  rules/salary-terminology/rule.md
Labels: Age: 🥚 - New

#7541 XS✔ ◾ Update rule.md
  rules/when-to-use-canva/rule.md
Labels: Age: 🥚 - New

#7542 Create Rule “use-scim-for-identity-management/rule”
  categories/infrastructure-and-networking/rules-to-better-security.md
  rules/use-scim-for-identity-management/bad-example-no-scim.jpg
  rules/use-scim-for-identity-management/good-example-scim.jpg
  rules/use-scim-for-identity-management/rule.md
Labels: Age: 🥚 - New

#7545 XS✔ ◾ Update rule.md
  rules/salary-terminology/rule.md
Labels: Age: 🥚 - New

#7544 XS✔ ◾ Update rule.md
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🥚 - New

#7543 XS✔ ◾ migrated-rule---when-to-use-reporting-services
  rules/when-to-use-reporting-services/RSRulesUseRS1.gif
  rules/when-to-use-reporting-services/rule.md
Labels: Age: 🥚 - New

#7547 XS✔ ◾ Update rule.md
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🥚 - New

#7548 XS✔ ◾ Salary Sacrifice - update video link
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🥚 - New

#7550 XS✔ ◾ Update rule.md
  rules/salary-terminology/rule.md
Labels: Age: 🥚 - New

#7554 XS✔ ◾ Small improvements to /salary-sacrifice-electronic-devices
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🐣 - Young

#7552 XS✔ ◾ Suggestions to improve /brand-your-assets
  rules/brand-your-assets/rule.md
Labels: Age: 🐣 - Young

#7556 XS✔ ◾ Added link to /salary-sacrifice-electronic-devices and /brand-your-assets
  rules/brand-your-assets/rule.md
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🥚 - New

#7558 XS✔ ◾ Update rule.md
  rules/salary-terminology/rule.md
Labels: Age: 🥚 - New

#7551 XS✔ ◾ Update rule.md
  rules/salary-terminology/rule.md
Labels: Age: 🐤 - Mature

#7560 XS✔ ◾ Update rule.md
  rules/salary-terminology/rule.md
Labels: Age: 🥚 - New

#7559 XS✔ ◾ Add rule to category
  categories/reporting-solutions/rules-to-better-reporting-services.md
Labels: Age: 🥚 - New

#7561 XS✔ ◾ Migrated rule - Do you check that "Report Server Configuration Manager" is all green ticks?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/check-that-rs-configuration-manager-is-all-green-ticks/RsConfigAllGreen-updated.png
  rules/check-that-rs-configuration-manager-is-all-green-ticks/RsConfigAllGreen.gif
  rules/check-that-rs-configuration-manager-is-all-green-ticks/RsConfigRed.gif
  rules/check-that-rs-configuration-manager-is-all-green-ticks/rule.md
Labels: Age: 🥚 - New

#7564 XS✔ ◾ 📝 Update Markdown lint action text + 🔧 Update lint config
  .github/workflows/validate-markdown.yml
  .markdownlint/config.json
Labels: Age: 🥚 - New

#7566 XS✔ ◾ Migrated rule - Do you check out the built-in samples?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/check-out-built-in-samples/Folders2008R2.gif
  rules/check-out-built-in-samples/rule.md
Labels: Age: 🥚 - New

#7568 XS✔ ◾ Add acronym explanation and link
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🥚 - New

#7569 XS✔ ◾ Make the benefit line more clear
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🥚 - New

#7565 XS✔ ◾ Co creation update
  rules/do-you-use-co-creation-patterns/rule.md
Labels: Age: 🥚 - New

#7570 XS✔ ◾ Update rule.md
  rules/salary-sacrifice-electronic-devices/rule.md
Labels: Age: 🥚 - New

#7575 XS✔ ◾ Migrated rule - Do you print and display your report on the web correctly?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/check-out-built-in-samples/rule.md
  rules/print-and-display-report-on-web/RSRuleMoreTopBottomPDF.png
  rules/print-and-display-report-on-web/RulesSQLRS7.jpg
  rules/print-and-display-report-on-web/reportbodywidth.gif
  rules/print-and-display-report-on-web/reportpagewidth.gif
  rules/print-and-display-report-on-web/rule.md
Labels: Age: 🥚 - New

#7577 XS✔ ◾ Migrated rule - Do you include a useful footer at the bottom of your reports?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/include-useful-footer/RSRulesBadFooter.gif
  rules/include-useful-footer/RSRulesGoodFooter.gif
  rules/include-useful-footer/footerInDesigner.gif
  rules/include-useful-footer/rule.md
Labels: Age: 🥚 - New

#7578 XS✔ ◾ Migrated rule - Do you avoid using word 'Report' in your reports?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/avoid-using-word-report/BadWordinReport.jpg
  rules/avoid-using-word-report/NoBadWordinReport.jpg
  rules/avoid-using-word-report/rule.md
Labels: Age: 🥚 - New

#7579 XS✔ ◾ Migrated rule - Do you underline items with Hyperlink Action?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/underline-items-with-hyperlink-action/NoUnderline4Hyperlink.jpg
  rules/underline-items-with-hyperlink-action/NoUnderline4Hyperlink_designer.jpg
  rules/underline-items-with-hyperlink-action/Underline4Hyperlink.jpg
  rules/underline-items-with-hyperlink-action/Underline4Hyperlink_designer.jpg
  rules/underline-items-with-hyperlink-action/rule.md
Labels: Age: 🥚 - New

#7580 XS✔ ◾ Migrated rule - Do you show errors in Red?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/show-errors-in-red/RSErrorMessageT1.jpg
  rules/show-errors-in-red/RSErrorMessageT2.jpg
  rules/show-errors-in-red/RSErrorMessageT3.jpg
  rules/show-errors-in-red/RSErrorMessageT4.gif
  rules/show-errors-in-red/RSErrorMessageT5.gif
  rules/show-errors-in-red/rule.md
Labels: Age: 🥚 - New

#7581 XS✔ ◾ Adding related rule
  rules/getting-a-busy-person-into-the-meeting/rule.md
Labels: Age: 🥚 - New

#7582 XS✔ ◾ Migrated rule - Do you have consistent report name?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/consistent-report-name/ReportNameConsistency_bad.gif
  rules/consistent-report-name/ReportNameConsistency_good.gif
  rules/consistent-report-name/rule.md
Labels: Age: 🥚 - New

#7584 XS✔ ◾ Migrated rule - Do you include feedback information in the report?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/include-feedback-information-in-report/ReportFeedback.gif
  rules/include-feedback-information-in-report/rule.md
Labels: Age: 🥚 - New

#7586 XS✔ ◾ Migrated rule - Do you know which version of Reporting Services you are running?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/reporting-services-version/ReportingServiceVersion.png
  rules/reporting-services-version/VersionBad.png
  rules/reporting-services-version/VersionGood.png
  rules/reporting-services-version/rule.md
Labels: Age: 🥚 - New

#7587 XS✔ ◾ Migrated rule - Do you put content as less as possible in page header?
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/least-content-in-page-header/RS_PageHeader_Bad.gif
  rules/least-content-in-page-header/RS_PageHeader_Good.gif
  rules/least-content-in-page-header/rule.md
Labels: Age: 🥚 - New

#7576 Create new rule generate insightful reports via company emails
  categories/reporting-solutions/rules-to-better-power-bi.md
  rules/generate-insightful-reports-via-company-emails/eagleeyepbireport.jpg
  rules/generate-insightful-reports-via-company-emails/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7588 XS✔ ◾ fixed old url
  rules/the-standard-naming-conventions-for-tests/rule.md
Labels: Age: 🥚 - New

#7590 XS✔ ◾ removed absolute urls
  rules/do-you-use-co-creation-patterns/rule.md
  rules/do-you-zz-old-files-rather-than-deleting-them/rule.md
Labels: Age: 🥚 - New

#7593 XS✔ ◾ EF Core Migrations Rule
  rules/use-code-migrations/rider-ef-core.png
  rules/use-code-migrations/rule.md
Labels: Age: 🥚 - New

#7594 XS✔ ◾ Archived rule - fix broken link
  rules/screenshots-do-you-know-how-to-show-wanted-actions/rule.md
Labels: Age: 🥚 - New

#7596 XS✔ ◾ fixed 404s
  rules/add-quality-control-to-dones/rule.md
  rules/avoid-empty-lines-at-the-start-of-character-columns/rule.md
  rules/bench-master/rule.md
  rules/do-you-add-width-and-height-properties-to-images-in-user-controls/rule.md
  rules/do-you-conduct-a-test-please-internally-and-then-with-the-client/rule.md
  rules/do-you-do-a-retro/rule.md
  rules/do-you-keep-a-hard-copy-diary/rule.md
  rules/do-you-know-how-to-use-balloons-in-screenshots-for-instructions/rule.md
  rules/do-you-know-when-to-branch/rule.md
  rules/do-you-know-when-to-use-full-stops-at-the-end-of-bullet-points/rule.md
  rules/do-you-label-your-form-buttons-consistently/rule.md
  rules/do-you-reference-which-email-template-youre-using/rule.md
  rules/do-you-run-acceptance-tests/rule.md
  rules/do-you-share-when-you-upgrade-an-application/rule.md
  rules/do-you-use-a-dataadapter-to-insert-rows-into-your-database/rule.md
  rules/do-you-use-built-in-authentication-from-ms/rule.md
  rules/do-you-use-email-signatures/rule.md
  rules/do-you-use-service-accounts/rule.md
  rules/do-you-use-slack-as-part-of-your-devops/rule.md
  rules/email-should-be-email-without-the-hyphen/rule.md
  rules/how-to-optimize-your-google-ads/rule.md
  rules/image-size-instagram/rule.md
  rules/keep-webpages-under-101kb/rule.md
  rules/know-that-no-carriage-returns-without-line-feed/rule.md
  rules/manage-costs-azure/rule.md
  rules/management-do-you-have-a-release-update-debrief-meeting-on-a-weekly-basis/rule.md
  rules/meetings-do-you-know-the-way-meetings-should-work/rule.md
  rules/mention-when-you-make-a-pull-request-or-comment-on-github/rule.md
  rules/microsoft-recommended-frameworks-for-automated-ui-driven-functional-testing/rule.md
  rules/reports-do-you-understand-the-implied-contract-promises-between-members-of-the-scrum-team/rule.md
  rules/start-versioning-at-0-1-and-change-to-1-0-once-approved/rule.md
  rules/submit-all-dates-to-sql-server-in-iso-format/rule.md
  rules/the-application-do-you-make-sure-that-the-database-structure-is-handled-automatically-via-3-buttons-create-upgrade-and-reconcile/rule.md
  rules/the-application-do-you-understand-the-danger-and-change-permissions-so-schema-changes-can-only-be-done-by-the-schema-master/rule.md
  rules/the-best-ide-for-react/rule.md
  rules/use-cannot-and-website-instead-of-separated-words/rule.md
  rules/use-the-mediator-pattern-with-cqrs/rule.md
  rules/useful-information-on-changes/rule.md
  rules/using-a-password-manager/rule.md
  rules/when-you-follow-a-rule-do-you-know-to-refer-to-it-including-the-icon/rule.md
  rules/where-to-find-nice-icons/rule.md
Labels: Age: 🥚 - New

#7597 Update Rule “include-useful-footer/rule”
  rules/include-useful-footer/rule.md
Labels: codeauditor fix

#7598 Update Rule “show-errors-in-red/rule”
  rules/show-errors-in-red/rule.md
Labels: codeauditor fix

#7599 Update Rule “include-feedback-information-in-report/rule”
  rules/include-feedback-information-in-report/rule.md
Labels: codeauditor fix

#7600 Update Rule “do-you-have-a-devops-checklist/rule”
  rules/do-you-have-a-devops-checklist/rule.md
Labels: codeauditor fix

#7606 XS✔ ◾ Formatting improvements
  rules/train-gpt/rule.md
Labels: Age: 🥚 - New

#7607 XS✔ ◾ Added a text formatting tip in a rule
  rules/make-the-communication-more-efficient-by-referring-back-to-a-subject-of-an-email/good-example---use-formatting.png
  rules/make-the-communication-more-efficient-by-referring-back-to-a-subject-of-an-email/rule.md
Labels: Age: 🥚 - New

#7605 XS✔ ◾ changed link from PDF to rule to improve maintenance /the-war-room-does-your-scrum-room-have-the-best-scrum-image
  rules/the-war-room-does-your-scrum-room-have-the-best-scrum-image/rule.md
Labels: Age: 🐥 - Adolescent

#7595 Update Rule “8-steps-to-scrum” with new PDF Url
  rules/8-steps-to-scrum/rule.md
Labels: Age: 🐓 - Old

#7608 XS✔ ◾ Archive and redirect the rule Do you use text formatting to mention email subjects?
  rules/do-you-use-text-formatting-to-mention-email-subjects/rule.md
Labels: Age: 🥚 - New

#7604 XS✔ ◾ Fixed bold formatting /using-markdown-to-store-your-content
  rules/using-markdown-to-store-your-content/rule.md
Labels: rubber stamp, Age: 🐤 - Mature

#7610 XS✔ ◾ Co-creation patterns - Add video
  rules/do-you-use-co-creation-patterns/rule.md
Labels: Age: 🥚 - New

#7609 Update gather data from company emails rule
  rules/checked-by-xxx/rule.md
  rules/generate-insightful-reports-via-company-emails/rule.md
Labels: Age: 🥚 - New

#7611 XS✔ ◾ Changed URI to exclude "do-you-"
  categories/communication/rules-to-better-microsoft-teams.md
  rules/make-the-communication-more-efficient-by-referring-back-to-a-subject-of-an-email/rule.md
  rules/use-text-formatting-to-mention-email-subjects/bad-example.png
  rules/use-text-formatting-to-mention-email-subjects/good-example.png
  rules/use-text-formatting-to-mention-email-subjects/rule.md
Labels: Age: 🥚 - New

#7612 XS✔ ◾ Updating the rule to include new functionality
  rules/do-you-use-sharepoints-news-feature/rule.md
Labels: Age: 🥚 - New

#7613 XS✔ ◾ what to measure - change jotform to a lightbox
  rules/things-to-measure/rule.md
Labels: Age: 🥚 - New

#7617 XS✔ ◾ Adding benefits to the rule
  rules/screenshots-avoid-walls-of-text/rule.md
Labels: Age: 🥚 - New

#7616 XS✔ ◾ pair programming - add co-author commits
  rules/do-you-use-co-creation-patterns/rule.md
Labels: Age: 🥚 - New

#7619 XS✔ ◾ Updated text content in two rules
  rules/make-the-communication-more-efficient-by-referring-back-to-a-subject-of-an-email/rule.md
  rules/use-text-formatting-to-mention-email-subjects/rule.md
Labels: Age: 🥚 - New

#7622 XS✔ ◾ Image not working
  rules/do-you-use-sharepoints-news-feature/rule.md
Labels: Age: 🥚 - New

#7624 XS✔ ◾ DevOps - what to measure - remove duplicate text
  rules/things-to-measure/rule.md
Labels: Age: 🥚 - New

#7626 XS✔ ◾ Updating image
  rules/do-you-use-sharepoints-news-feature/rule.md
Labels: Age: 🥚 - New

#7621 XS✔ ◾ DevOps - update intro text
  categories/software-development/rules-to-better-devops.md
Labels: Age: 🥚 - New

#7623 XS✔ ◾ DevOps - what to measure - fix title color
  rules/things-to-measure/rule.md
Labels: Age: 🥚 - New
