Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2023-07, with the labels that each got.

#5906 Remove schedule trigger
  .github/workflows/TriggerDevOpsBuild.yml
Labels: code change

#5911 added argv check
  scripts/find-unreferenced-images/find-unreferenced-images.js
Labels: code change

#5924 Update rule.md "sprint-forecast"
  rules/sprint-forecast/rule.md
Labels: codeauditor fix

#5927 Update rule.md "best-applicant-tracking-system"
  rules/the-best-applicant-tracking-system/rule.md
Labels: codeauditor fix

#5931 Update rule.md "sharepoint-usage"
  rules/sharepoint-usage/rule.md
Labels: codeauditor fix

#5925 Update rule.md "customization-do-you-have-your-customizations-documen…
  rules/customization-do-you-have-your-customizations-documented/rule.md
Labels: codeauditor fix

#5926 Update rule.md "do-you-use-filtered-views-or-fetch-for-crm-custom-rep…
  rules/do-you-use-filtered-views-or-fetch-for-crm-custom-reports/rule.md
Labels: codeauditor fix

#5930 Update rule.md "do-you-apply-crm-2015-update-rollup-1-before-upgradin…
  rules/do-you-apply-crm-2015-update-rollup-1-before-upgrading-to-2016/rule.md
Labels: codeauditor fix

#5928 Update rule.md "convert-crm-managed-solution-to-unmanaged"
  rules/how-to-convert-crm-managed-solution-to-unmanaged/rule.md
Labels: codeauditor fix

#5929 Update rule.md "keep-dynamics-365-online-synced-with-azure-ad"
  rules/keep-dynamics-365-online-synced-with-azure-ad/rule.md
Labels: codeauditor fix

#5954 Update rule.md "do-you-use-a-data-warehouse"
  rules/do-you-use-a-data-warehouse/rule.md
Labels: rubber stamp

#5970 Added reciprocal links
  rules/as-per-our-conversation-emails/rule.md
  rules/warn-then-call/rule.md
Labels: rubber stamp

#5988 Deleted do-you-keep-your-content-creators-informed
  rules/do-you-keep-your-content-creators-informed/rule.md
Labels: rubber stamp

#5986 Update rule "use-digits-instead-of-words"
  rules/use-digits-instead-of-words/rule.md
Labels: rubber stamp

#6017 Fixed image path + improved links on Rule "how-to-generate-an-ai-image"
  rules/how-to-generate-an-ai-image/rule.md
Labels: codeauditor fix

#6022 Added check to ensure argv[2] exists before attempting to access it
  scripts/find-unreferenced-images/find-unreferenced-images.js
Labels: code change

#6060 Fixed BUG - double brackets "teams-usage"
  rules/teams-usage/rule.md
Labels: rubber stamp

#6033 Update Rule “do-you-have-a-label-tag-for-the-fields-associated-with-your-input/rule”
  rules/do-you-have-a-label-tag-for-the-fields-associated-with-your-input/rule.md
Labels: codeauditor fix

#6035 Update Rule “do-your-windows-forms-have-border-protection/rule”
  rules/do-your-windows-forms-have-border-protection/rule.md
Labels: codeauditor fix

#6036 Update Rule “close-quotations-of-html-attributes/rule”
  rules/close-quotations-of-html-attributes/rule.md
Labels: codeauditor fix

#6041 Update Rule “have-a-companywide-word-template/rule”
  rules/have-a-companywide-word-template/rule.md
Labels: codeauditor fix

#6043 Update Rule “do-you-use-tryupdatemodel-instead-of-updatemodel/rule”
  rules/do-you-use-tryupdatemodel-instead-of-updatemodel/rule.md
Labels: codeauditor fix

#6045 Update Rule “do-you-use-model-binding-instead-of-formcollection/rule”
  rules/do-you-use-model-binding-instead-of-formcollection/rule.md
Labels: codeauditor fix

#6046 Update Rule “do-you-force-ssl-on-sensitive-methods-like-login-or-register/rule”
  rules/do-you-force-ssl-on-sensitive-methods-like-login-or-register/rule.md
Labels: codeauditor fix

#6047 Update Rule “do-you-use-view-models-instead-of-viewdata/rule”
  rules/do-you-use-view-models-instead-of-viewdata/rule.md
Labels: codeauditor fix

#6103 Update Rule “do-pagination-database-side/rule”
  rules/do-pagination-database-side/rule.md
Labels: codeauditor fix

#6048 Update Rule “do-you-use-redirecttoaction-instead-of-returning-a-view-thats-not-named-the-same-as-the-action/rule”
  rules/do-you-use-redirecttoaction-instead-of-returning-a-view-thats-not-named-the-same-as-the-action/rule.md
Labels: codeauditor fix

#6049 Update Rule “do-you-use-the-authorize-attribute-to-secure-actions-or-controllers/rule”
  rules/do-you-use-the-authorize-attribute-to-secure-actions-or-controllers/rule.md
Labels: codeauditor fix

#6050 Update Rule “do-you-use-html-helpers-and-partial-views-to-simplify-views/rule”
  rules/do-you-use-html-helpers-and-partial-views-to-simplify-views/rule.md
Labels: codeauditor fix

#6051 Update Rule “do-you-avoid-hardcoding-urls-or-and-use-url-action-or-html-actionlink-instead/rule”
  rules/do-you-avoid-hardcoding-urls-or-and-use-url-action-or-html-actionlink-instead/rule.md
Labels: codeauditor fix

#6052 Update Rule “do-you-use-bundling-to-package-script-and-css-files/rule”
  rules/do-you-use-bundling-to-package-script-and-css-files/rule.md
Labels: codeauditor fix

#6053 Update Rule “do-you-use-anti-forgery-tokens-on-any-page-that-takes-a-post/rule”
  rules/do-you-use-anti-forgery-tokens-on-any-page-that-takes-a-post/rule.md
Labels: codeauditor fix

#6054 Update Rule “do-you-use-the-url-as-a-navigation-aid-aka-redirect-to-the-correct-url-if-it-is-incorrect/rule”
  rules/do-you-use-the-url-as-a-navigation-aid-aka-redirect-to-the-correct-url-if-it-is-incorrect/rule.md
Labels: codeauditor fix

#6055 Update Rule “event-storming/rule”
  rules/event-storming/rule.md
Labels: codeauditor fix

#6056 Update Rule “when-to-use-stringbuilder/rule”
  rules/when-to-use-stringbuilder/rule.md
Labels: codeauditor fix

#6057 Update Rule “use-async-await-for-all-io-bound-operations/rule”
  rules/use-async-await-for-all-io-bound-operations/rule.md
Labels: codeauditor fix

#6058 Update Rule “asp-net-core-spa-template-for-angular-uses-the-angular-cli/rule”
  rules/asp-net-core-spa-template-for-angular-uses-the-angular-cli/rule.md
Labels: codeauditor fix

#6063 Update Rule “post-production-do-you-know-how-to-promote-videos/rule”
  rules/post-production-do-you-know-how-to-promote-videos/rule.md
Labels: codeauditor fix

#6064 Update Rule “sound-did-you-know-that-a-message-box-automatically-plays-a-beep/rule”
  rules/sound-did-you-know-that-a-message-box-automatically-plays-a-beep/rule.md
Labels: codeauditor fix

#6077 Update Rule “keep-your-databinder-eval-clean/rule”
  rules/keep-your-databinder-eval-clean/rule.md
Labels: codeauditor fix

#6072 Update Rule “avoid-using-asp-asp-net-tags-in-plain-html/rule”
  rules/avoid-using-asp-asp-net-tags-in-plain-html/rule.md
Labels: codeauditor fix

#6074 Update Rule “avoid-using-mailto-on-your-website/rule”
  rules/avoid-using-mailto-on-your-website/rule.md
Labels: codeauditor fix

#6080 Update Rule “dotnet-upgrade-for-complex-projects/rule”
  rules/dotnet-upgrade-for-complex-projects/rule.md
Labels: codeauditor fix

#6083 Update Rule “do-you-keep-your-assembly-version-consistent/rule”
  rules/do-you-keep-your-assembly-version-consistent/rule.md
Labels: codeauditor fix

#6078 Update Rule “release-build-your-web-applications-before-you-deploy-them/rule”
  rules/release-build-your-web-applications-before-you-deploy-them/rule.md
Labels: codeauditor fix

#6094 Update Rule “do-you-use-resource-file-for-storing-your-static-script/rule”
  rules/do-you-use-resource-file-for-storing-your-static-script/rule.md
Labels: codeauditor fix

#6079 Update Rule “use-301-redirect-on-renamed-or-moved-pages/rule”
  rules/use-301-redirect-on-renamed-or-moved-pages/rule.md
Labels: codeauditor fix

#6099 Update Rule “clean-your-data-before-modelling/rule”
  rules/clean-your-data-before-modelling/rule.md
Labels: codeauditor fix

#6068 Update Rule “do-you-explain-the-logistics/rule”
  rules/do-you-explain-the-logistics/rule.md
Labels: codeauditor fix

#6090 Update Rule “do-you-use-one-class-per-file/rule”
  rules/do-you-use-one-class-per-file/rule.md
Labels: codeauditor fix

#6066 Update Rule “do-you-wrote-your-angular-1-x-directives-in-typescript/rule”
  rules/do-you-wrote-your-angular-1-x-directives-in-typescript/rule.md
Labels: codeauditor fix

#6093 Update Rule “do-you-use-more-meaningful-names-than-hungarian-short-form/rule”
  rules/do-you-use-more-meaningful-names-than-hungarian-short-form/rule.md
Labels: codeauditor fix

#6096 Update Rule “do-you-make-your-projects-regenerated-easily/rule”
  rules/do-you-make-your-projects-regenerated-easily/rule.md
Labels: codeauditor fix

#6076 Update Rule “have-generic-exception-handler-in-your-global-asax/rule”
  rules/have-generic-exception-handler-in-your-global-asax/rule.md
Labels: codeauditor fix

#6095 Update Rule “do-you-avoid-using-duplicate-connection-string-in-web-config/rule”
  rules/do-you-avoid-using-duplicate-connection-string-in-web-config/rule.md
Labels: codeauditor fix

#6067 Update Rule “help-in-powershell-functions-and-scripts/rule”
  rules/help-in-powershell-functions-and-scripts/rule.md
Labels: codeauditor fix

#6071 Update Rule “do-you-know-how-to-create-nice-urls-using-asp-net-4/rule”
  rules/do-you-know-how-to-create-nice-urls-using-asp-net-4/rule.md
Labels: codeauditor fix

#6089 Update Rule “do-you-let-the-adapter-handle-the-connection-for-you/rule”
  rules/do-you-let-the-adapter-handle-the-connection-for-you/rule.md
Labels: codeauditor fix

#6097 Update Rule “do-you-use-comments-not-exclusion-files-when-you-ignore-a-code-analysis-rule/rule”
  rules/do-you-use-comments-not-exclusion-files-when-you-ignore-a-code-analysis-rule/rule.md
Labels: codeauditor fix

#6104 Update Rule “use-tagwith/rule”
  rules/use-tagwith/rule.md
Labels: codeauditor fix

#6101 Update Rule “avoid-using-update/rule”
  rules/avoid-using-update/rule.md
Labels: codeauditor fix

#6100 Update Rule “only-project-properties-you-need/rule”
  rules/only-project-properties-you-need/rule.md
Labels: codeauditor fix

#6065 Update Rule “do-you-provide-a-warning-before-the-program-exits/rule”
  rules/do-you-provide-a-warning-before-the-program-exits/rule.md
Labels: codeauditor fix

#6088 Update Rule “do-you-secure-your-web-services-using-wcf-over-wse3-and-ssl/rule”
  rules/do-you-secure-your-web-services-using-wcf-over-wse3-and-ssl/rule.md
Labels: codeauditor fix

#6081 Update Rule “do-you-keep-clean-on-imports-of-project-property/rule”
  rules/do-you-keep-clean-on-imports-of-project-property/rule.md
Labels: codeauditor fix

#6091 Update Rule “do-you-deploy-your-applications-correctly/rule”
  rules/do-you-deploy-your-applications-correctly/rule.md
Labels: codeauditor fix

#6102 Update Rule “only-explicitly-include-relationships-you-need/rule”
  rules/only-explicitly-include-relationships-you-need/rule.md
Labels: codeauditor fix

#6075 Update Rule “build-criteria-by-using-a-where-clause/rule”
  rules/build-criteria-by-using-a-where-clause/rule.md
Labels: codeauditor fix

#6106 Update Rule “when-to-use-raw-sql/rule”
  rules/when-to-use-raw-sql/rule.md
Labels: codeauditor fix

#6132 removed extra spaces, added commas on Rule "confirm-quotes"
  rules/confirm-quotes/rule.md
Labels: rubber stamp

#6141 Update "use-var" rule.md
  rules/use-var/rule.md
Labels: codeauditor fix, rubber stamp

#6184 Made example link not clickable on Rule "control4-slack"
  rules/do-you-send-control4-notifications-to-a-slack-channel/rule.md
Labels: codeauditor fix
