Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2023-11, with the labels that each got.

#7142 XS✔ ◾ use diff characters to fix frontmatter issue
  rules/do-you-know-the-best-practices-for-frontmatter-in-markdown/rule.md
Labels: Age: 🥚 - New

#7149 XS✔ ◾ Geordie88 patch 2
  categories/management/rules-to-better-sales.md
  rules/do-you-send-some-client-love-a-few-days-after-the-initial-meeting/rule.md
Labels: Age: 🥚 - New

#7148 XS✔ ◾ Updating Sprint Review email with placeholder for deployment and emoji's for retro
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🐣 - Young

#7144 XS✔ ◾ Updating the merge debt message based off feedback from Brady
  .github/workflows/pr-manage-stale.yml
Labels: Age: 🐤 - Mature

#7141 XS✔ ◾ Updating the Rules to Better Clean Architecture intro based off grammarly suggestions
  categories/software-development/rules-to-better-clean-architecture.md
Labels: Age: 🐤 - Mature

#7150 XS✔ ◾ Little small formatting improvements /follow-up-after-spec-review/
  rules/follow-up-after-spec-review/rule.md
Labels: rubber stamp, Age: 🐥 - Adolescent

#7134 XS✔ ◾ Create rule for Teams. md
  rules/connect-client-im/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7147 Edits to make Rule consistent with content on the SSW Mentoring Intranet site
  categories/communication/rules-to-better-technical-documentation.md
  rules/do-you-use-version-control-with-power-bi/Gitignore.png
  rules/do-you-use-version-control-with-power-bi/PBI Cache.png
  rules/mentoring-programs/rule.md
Labels: Age: 🐤 - Mature

#7155 XS✔ ◾ Adding a video for PowerPoint's "Rehearse with Coach" feature
  rules/practice-makes-perfect/rehearsal-report.png
  rules/practice-makes-perfect/rule.md
Labels: Age: 🥚 - New

#7154 Create Rule “integrate-identityserver-with-an-existing-user-store/rule”
  categories/infrastructure-and-networking/rules-to-better-security.md
  rules/integrate-identityserver-with-an-existing-user-store/rule.md
Labels: Age: 🐣 - Young

#7164 XS✔ ◾ Adding steps to using Speaker Coach
  rules/practice-makes-perfect/rule.md
  rules/practice-makes-perfect/start-rehearsing-dialog.png
Labels: Age: 🥚 - New

#7158 XS✔ ◾ Remove broken link on manage-product-feedback
  rules/manage-product-feedback/getsatisfaction.jpg
  rules/manage-product-feedback/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#7157 XS✔ ◾ Update broken link on do-you-know-the-best-visual-studio-extensions-and-nuget-packages-for-angularjs
  rules/do-you-know-the-best-visual-studio-extensions-and-nuget-packages-for-angularjs/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7138 XS✔ ◾ Updated outdated image
  assets/GoodLoginError.gif
  assets/GoodLoginError.png
  rules/login-security-do-you-know-the-correct-error-message-for-an-incorrect-user-name-or-password/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7167 XS✔ ◾ Minor tweaks to the Practice makes perfect rule based on Tiago's feedback
  rules/practice-makes-perfect/rule.md
Labels: Age: 🥚 - New

#7165 XS✔ ◾ Update rules-to-better-meetings.md
  categories/communication/rules-to-better-meetings.md
Labels: Age: 🥚 - New

#7166 XS✔ ◾ Made captions standard /seo-nofollow
  rules/seo-nofollow/rule.md
Labels: rubber stamp, Age: 🥚 - New

#7163 Cms/dhruv 0987/ssw.rules.content/rule/integrate identityserver with an existing user store/rule
  rules/integrate-identityserver-with-an-existing-user-store/rule.md
Labels: Age: 🐤 - Mature

#7162 XS✔ ◾ Update rule.md
  rules/connect-client-im/rule.md
  rules/connect-client-im/teams-rule.png
Labels: Age: 🐓 - Old

#7170 XS✔ ◾ Fixed up some typos and made sentences flow a little better
  rules/migrate-from-edmx-to-ef-core/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7172 XS✔ ◾ Update rule.md
  rules/connect-client-im/rule.md
Labels: Age: 🥚 - New

#7174 XS✔ ◾ Update rules-to-better-sales.md
  categories/communication/rules-to-better-microsoft-teams.md
  categories/management/rules-to-better-sales.md
Labels: Age: 🥚 - New

#7175 XS✔ ◾ Removing white space - broken rule
  rules/connect-client-im/rule.md
Labels: Age: 🥚 - New

#7177 XS✔ ◾ Fix up Daily Scrum Standard
  rules/methodology-daily-scrums/daily-scrum-good.png
  rules/methodology-daily-scrums/rule.md
Labels: Age: 🥚 - New

#7152 XS✔ ◾ Fix broken link on use-icons-to-not-surprise-users
  rules/use-icons-to-not-surprise-users/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#7169 XS✔ ◾ Added additional downside for code modernization
  rules/dotnet-upgrade-assistant/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7173 XS✔ ◾ Add related rules
  rules/migrating-web-apps/rule.md
Labels: Age: 🥚 - New

#7178 XS✔ ◾ Adding quote by Daniel M for co-creation patterns
  rules/do-you-use-co-creation-patterns/rule.md
Labels: Age: 🥚 - New

#7179 XS✔ ◾ Update rule.md
  rules/connect-client-im/rule.md
Labels: Age: 🥚 - New

#7181 XS✔ ◾ Update rule.md
  rules/connect-client-im/rule.md
Labels: Age: 🥚 - New

#7153 XS✔ ◾ Archiving rule as it lacks security concern
  categories/websites/rules-to-better-websites-navigation.md
  rules/forgot-password-do-you-read-their-mind/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7187 XS✔ ◾ Update rule.md
  rules/connect-client-im/rule.md
Labels: Age: 🥚 - New

#7140 XS✔ ◾ 🧠⚡️ Brainstorming improvements
  categories/others/brainstorming-day.png
  categories/others/rules-to-better-brainstorming.md
  rules/brainstorming-agenda/rule.md
  rules/brainstorming-day-retro/rule.md
  rules/brainstorming-idea-farming/rule.md
  rules/brainstorming-team-allocation/rule.md
  rules/digesting-brainstorming/rule.md
  rules/how-brainstorming-works/rule.md
  rules/meetings-do-you-know-the-agenda-for-the-initial-meeting/rule.md
  rules/use-the-brains-of-your-company/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7193 XS✔ ◾ Brainstorming teams - Add share team allocations bit
  rules/brainstorming-team-allocation/rule.md
Labels: Age: 🥚 - New

#7198 XS✔ ◾ Updating communicating expectations PR rule
  rules/use-pull-request-templates-to-communicate-expectations/pr-template-asking-for-context.jpg
  rules/use-pull-request-templates-to-communicate-expectations/rule.md
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#7197 XS✔ ◾ 💄 EditorRequired Blazor Rule - Fix Titles
  rules/editor-required-blazor-component-parameters/rule.md
Labels: Age: 🐥 - Adolescent

#7146 XS✔ ◾ Do you know the best practices for frontmatter in markdown
  categories/websites/rules-to-better-websites-development.md
  rules/do-you-know-the-best-practices-for-frontmatter-in-markdown/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7176 Cms/dhruv 0987/ssw.rules.content/rule/integrate identityserver with an existing user store/rule
  rules/integrate-identityserver-with-an-existing-user-store/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7199 XS✔ ◾ Remove --- from content
  rules/do-you-know-the-best-practices-for-frontmatter-in-markdown/rule.md
Labels: Age: 🥚 - New

#7200 XS✔ ◾ 📝fix markdown validation
  rules/do-you-know-the-best-practices-for-frontmatter-in-markdown/rule.md
Labels: Age: 🥚 - New

#7204 XS✔ ◾ Update broken link on do-you-know-the-best-tool-to-migration-from-tfvc-to-git
  rules/do-you-know-the-best-tool-to-migration-from-tfvc-to-git/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7203 XS✔ ◾ Update broken link on do-you-know-the-best-sample-applications
  rules/do-you-know-the-best-sample-applications/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7201 CodeAuditor scan - Detected missing code block
  rules/dates-do-you-use-calendar-controls-effectively/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7206 XS✔ ◾ Brainstorm digest - add tip for tracking
  rules/digesting-brainstorming/rule.md
Labels: Age: 🐣 - Young

#7207 CodeAuditor - detected spelling mistakes
  rules/authentication-do-you-have-a-user-friendly-registration-and-sign-in-screen/rule.md
  rules/do-you-always-rename-staging-url-on-azure/rule.md
  rules/do-you-create-a-deployment-project-alongside-your-web-application-for-any-additional-deployment-steps/rule.md
  rules/do-you-get-zero-downtime-when-updating-a-server/rule.md
  rules/do-you-help-users-by-selecting-a-default-field/rule.md
  rules/do-you-include-the-number-of-results-in-drop-down-list/rule.md
  rules/do-you-know-how-to-use-google-analytics-content-by-title-reports-to-track-trends/rule.md
  rules/do-you-make-sure-your-website-doesnt-have-multiple-copies-of-the-same-image/rule.md
  rules/do-you-not-install-web-deploy-from-the-web-platform-installer/rule.md
  rules/does-your-sharepoint-site-have-a-favicon/rule.md
  rules/ensure-that-your-contact-details-are-easy-to-find/rule.md
  rules/have-a-schema-master/rule.md
  rules/have-a-validation-page-for-your-web-server/rule.md
  rules/printing-do-you-have-a-print-css-file-so-your-web-pages-are-nicely-printable/rule.md
  rules/use-sso-for-your-websites/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7210 XS✔ ◾ ✨ New rule - limit text on your slides
  rules/craft-and-deliver-engaging-presentations/picture1.png
  rules/craft-and-deliver-engaging-presentations/picture2.png
  rules/no-text-slides/animations-pros-cons.gif
  rules/no-text-slides/cool-timeline.png
  rules/no-text-slides/design-ideas-ppt.gif
  rules/no-text-slides/my-day-bad.png
  rules/no-text-slides/rule.md
  rules/no-text-slides/ugly-timeline.png
Labels: Age: 🥚 - New

#7213 XS✔ ◾ Add ppt text rule to categories
  categories/communication/rules-to-better-powerpoint-presentations.md
Labels: Age: 🥚 - New

#7212 XS✔ ◾ Text on powerpoints - add video
  rules/no-text-slides/rule.md
Labels: Age: 🥚 - New

#7215 XS✔ ◾ Fixed Good Example on Unit Test Rule
  rules/make-sure-that-the-test-can-be-failed/rule.md
Labels: Age: 🥚 - New

#7216 CodeAuditor scan - detected spelling mistakes
  rules/authentication-do-you-have-a-logout-short-cut-next-to-the-user-name/rule.md
  rules/authentication-do-you-use-email-address-instead-of-user-name/rule.md
  rules/do-you-gather-more-personal-information-progressively/rule.md
  rules/do-you-know-how-to-setup-your-outlook-to-send-but-not-receive/rule.md
  rules/do-you-secure-your-web-services-using-wcf-over-wse3-and-ssl/rule.md
  rules/when-to-use-value-objects/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7214 XS✔ ◾ Add related rule to no-text-slides
  rules/no-text-slides/rule.md
Labels: Age: 🥚 - New

#7218 Update Rule “record-teams-meetings/rule”
  rules/record-teams-meetings/rule.md
Labels: Age: 🥚 - New

#7217 Update Rule “creating-action-items/rule”
  rules/creating-action-items/rule.md
Labels: Age: 🥚 - New

#7220 XS✔ ◾ Updates to improve clarity and add in extra points worth mentioning
  rules/tick-and-flick/rule.md
Labels: Age: 🥚 - New

#7221 XS✔ ◾ fix bug
  rules/document-discoveries/rule.md
Labels: Age: 🥚 - New

#7222 XS✔ ◾ fix bug
  rules/tick-and-flick/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7223 Update Rule “use-backchannels-effectively/rule”
  rules/use-backchannels-effectively/rule.md
Labels: Age: 🐓 - Old

#7225 XS✔ ◾ brainstorming outcomes - fix typo
  rules/digesting-brainstorming/rule.md
Labels: Age: 🥚 - New

#7226 Update Rule “do-you-use-co-creation-patterns/rule”
  rules/do-you-use-co-creation-patterns/rule.md
Labels: Age: 🐤 - Mature

#7227 XS✔ ◾ Relating zz files + removing old link
  rules/do-you-know-zz-ed-files-must-not-exist-in-source-control/rule.md
  rules/do-you-zz-old-files-rather-than-deleting-them/rule.md
Labels: Age: 🐣 - Young

#7244 XS✔ ◾ Adding more authors
  rules/use-pull-request-templates-to-communicate-expectations/rule.md
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#7243 XS✔ ◾ Update rule.md
  rules/do-you-zz-old-files-rather-than-deleting-them/rule.md
Labels: Age: 🥚 - New

#7242 XS✔ ◾ Update rule.md
  rules/connect-client-im/rule.md
Labels: Age: 🐣 - Young

#7247 XS✔ ◾ Update rule.md
  rules/do-you-zz-old-files-rather-than-deleting-them/rule.md
Labels: Age: 🥚 - New

#7246 Add a category to my new rule
  categories/software-development/rules-to-better-azure.md
Labels: Age: 🐥 - Adolescent

#7241 XS✔ ◾ CodeAuditor Scan - Fix broken link
  rules/methodology-daily-scrums/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7240 XS✔ ◾ CodeAuditor Scan - Fixed broken link
  rules/brainstorming-agenda/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7239 Update Rule “methodology-daily-scrums/rule”
  rules/methodology-daily-scrums/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7237 Update Rule “know-the-open-source-contribution-etiquette/rule”
  rules/know-the-open-source-contribution-etiquette/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7233 Update Rule “how-to-hand-off-a-new-live-chat-lead-to-a-sales-person/rule”
  rules/how-to-hand-off-a-new-live-chat-lead-to-a-sales-person/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7231 Update Rule “video-reduce-noise/rule”
  rules/video-reduce-noise/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7230 Update Rule “professional-integrity-tools/rule”
  rules/professional-integrity-tools/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7229 Update Rule “use-code-migrations/rule”
  rules/use-code-migrations/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7234 Update Rule “how-to-add-a-group-for-all-staff-who-answer-live-chats/rule”
  rules/how-to-add-a-group-for-all-staff-who-answer-live-chats/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7236 Update Rule “dont-push-your-pull-requests/rule”
  rules/dont-push-your-pull-requests/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7235 Update Rule “the-best-boardroom-av-solution/rule”
  rules/the-best-boardroom-av-solution/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7248 XS✔ ◾ Fixing aka as per https://www.ssw.com.au/rules/avoid-common-mistakes/
  rules/do-you-follow-the-sandwich-rule/rule.md
Labels: Age: 🐣 - Young

#7249 XS✔ ◾ Reordering rules-to-better-technical-documentation.md
  categories/communication/rules-to-better-technical-documentation.md
Labels: Age: 🐣 - Young

#7254 XS✔ ◾ Adding an image
  rules/warn-then-call/rule.md
  rules/warn-then-call/team-status.jpg
Labels: Age: 🥚 - New

#7255 XS✔ ◾ Fix build
  rules/dont-push-your-pull-requests/rule.md
  rules/how-to-add-a-group-for-all-staff-who-answer-live-chats/rule.md
  rules/use-code-migrations/rule.md
Labels: Age: 🥚 - New

#7257 XS✔ ◾ 💄 Mention proactive testing
  rules/conduct-a-test-please/rule.md
Labels: Age: 🥚 - New

#7258 XS✔ ◾ Update image name
  rules/warn-then-call/rule.md
  rules/warn-then-call/team-status-1.jpg
Labels: Age: 🥚 - New

#7259 XS✔ ◾ Refactored brainstorming process to improve idea quality
  markdown/readme.md
  rules/brainstorming-idea-farming/rule.md
Labels: Age: 🥚 - New

#7256 XS✔ ◾ ✨ New Rule - BUnit for Blazor Unit Tests
  categories/software-development/rules-to-better-blazor.md
  rules/bunit-for-blazor-unit-tests/rule.md
Labels: Age: 🐣 - Young

#7260 XS✔ ◾ Update brainstorming rule to clarify where to find
  rules/brainstorming-idea-farming/rule.md
Labels: Age: 🥚 - New

#7245 Create Rule “spike-in-azure-resource-costs/rule”
  rules/spike-in-azure-resource-costs/rule.md
Labels: Age: 🐓 - Old

#7238 Update Rule “use-ai-to-generate-spec-reviews/rule”
  rules/use-ai-to-generate-spec-reviews/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#7228 Update Rule “reports-do-you-have-a-standard-report-footer/rule”
  rules/reports-do-you-have-a-standard-report-footer/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#7262 XS✔ ◾ Improved title and content to make it more clear
  rules/scrum-should-be-capitalized/rule.md
Labels: Age: 🐣 - Young

#7263 XS✔ ◾ Improved title /screenshots-tools/
  rules/screenshots-tools/rule.md
Labels: Age: 🐣 - Young

#7267 XS✔ ◾ brainstorming - Add consulting link
  categories/others/rules-to-better-brainstorming.md
Labels: Age: 🥚 - New

#7252 Updated Rule “avoid-deleting-records-by-flagging-them-as-isdeleted/rule” - extracted the best approach to it into a new paragraph(with example code) from a bullet point
  rules/avoid-deleting-records-by-flagging-them-as-isdeleted/rule.md
Labels: Age: 🐓 - Old

#7270 XS✔ ◾ 🧠⚡️ Brainstorming improvements - get excited
  categories/others/rules-to-better-brainstorming.md
  rules/brainstorming-agenda/rule.md
  rules/brainstorming-day-retro/rule.md
  rules/brainstorming-idea-farming/rule.md
  rules/brainstorming-presentations/rule.md
  rules/brainstorming-team-allocation/rule.md
  rules/digesting-brainstorming/rule.md
  rules/how-brainstorming-works/rule.md
  rules/use-the-brains-of-your-company/rule.md
Labels: Age: 🥚 - New

#7266 XS✔ ◾ CodeAuditor scan - Fixed absolute internal links
  rules/information-intelligence-wisdom/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7269 XS✔ ◾ Update rule.md
  rules/do-pagination-database-side/rule.md
Labels: Age: 🐤 - Mature

#7265 Update Rule “as-per-our-conversation-emails/rule”
  rules/as-per-our-conversation-emails/rule.md
Labels: Age: 🐓 - Old

#7251 Update Rule “write-a-good-pull-request/rule”
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7271 XS✔ ◾ Suggestions to improve /brainstorming-idea-farming
  rules/brainstorming-idea-farming/rule.md
Labels: Age: 🐣 - Young

#7273 XS✔ ◾ brainstorming idea farming - Improve wording
  rules/brainstorming-idea-farming/rule.md
Labels: Age: 🥚 - New

#7250 XS✔ ◾ Added related + improved examples /prefix-on-blog-posts-titles/
  rules/prefix-on-blog-posts-titles/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7264 XS✔ ◾ Making content cleaner /have-urls-to-your-main-services-on-linkedin/
  rules/have-urls-to-your-main-services-on-linkedin/rule.md
Labels: Age: 🐓 - Old

#7274 XS✔ ◾ Brainstorming - grammar improvements
  rules/brainstorming-agenda/rule.md
  rules/brainstorming-day-retro/rule.md
  rules/brainstorming-idea-farming/rule.md
  rules/brainstorming-presentations/rule.md
  rules/brainstorming-team-allocation/rule.md
Labels: Age: 🥚 - New

#7275 XS✔ ◾ Update rule.md
  rules/how-brainstorming-works/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7261 XS✔ ◾ Re-edited rule that broke build
  rules/dont-push-your-pull-requests/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7278 XS✔ ◾ Revert "XS✔ ◾ Re-edited rule that broke build"
  rules/dont-push-your-pull-requests/rule.md
Labels: Age: 🥚 - New

#7276 XS✔ ◾ Update rule.md
  rules/getting-a-busy-person-into-the-meeting/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7277 XS✔ ◾ Update rule.md
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7281 CodeAuditor Scan - Fixed Dhruv's broken image
  rules/integrate-identityserver-with-an-existing-user-store/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#7280 XS✔ ◾ 💄 Update bUnit Rule
  rules/bunit-for-blazor-unit-tests/rule.md
Labels: Age: 🐥 - Adolescent

#7284 XS✔ ◾ add clarification that you must talk to product owner
  rules/unexpected-requests/rule.md
Labels: Age: 🥚 - New

#7285 XS✔ ◾ clarify to put who you did it with
  .github/pull_request_template.md
Labels: Age: 🥚 - New

#7287 XS✔ ◾ Screenshots rule - Added tip on avoiding blank space
  rules/screenshots-avoid-walls-of-text/rule.md
  rules/screenshots-avoid-walls-of-text/screenshot-blank-bad.png
  rules/screenshots-avoid-walls-of-text/screenshot-blank-good.png
Labels: Age: 🥚 - New

#7286 XS✔ ◾ Archived rule on 3rd party how to
  categories/websites/rules-to-better-wordpress.md
  rules/do-you-know-how-to-deploy-changes-from-staging-to-live/rule.md
Labels: Age: 🐥 - Adolescent

#7291 Update Rule “using-mfa/rule” - Added an additional note for the time it takes to reflect those changes from the authenticator app
  rules/using-mfa/rule.md
Labels: Age: 🐤 - Mature

#7282 Create Rule “do-you-know-which-environments-you-need-to-provision-when-starting-a-new-project/rule”
  categories/management/rules-to-successful-projects.md
  categories/software-development/rules-to-better-azure.md
  categories/software-development/rules-to-better-devops.md
  categories/software-development/rules-to-better-testing.md
  rules/do-you-have-separate-development-testing-and-production-environments/rule.md
  rules/do-you-know-which-environments-you-need-to-provision-when-starting-a-new-project/bad-example-skipping-environments.jpg
  rules/do-you-know-which-environments-you-need-to-provision-when-starting-a-new-project/complex-environments.jpg
  rules/do-you-know-which-environments-you-need-to-provision-when-starting-a-new-project/rule.md
  rules/do-you-know-which-environments-you-need-to-provision-when-starting-a-new-project/simple-environments.jpg
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7296 XS✔ ◾ PRs - Remove '/'s and improve formatting
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#7293 XS✔ ◾ Archived old rule on deployments
  categories/application-lifecycle-management-alm/rules-to-better-continuous-deployment-with-tfs.md
  rules/do-you-deploy-to-other-environments/rule.md
Labels: Age: 🐓 - Old

#7298 XS✔ ◾ CodeAuditor Scan - Fixed spelling mistakes and incorrect Scrum terms
  rules/asp-net-vs-sharepoint-development-do-you-know-what-you-get-for-free-out-of-the-box/rule.md
  rules/authentication-do-you-use-email-address-instead-of-user-name/rule.md
  rules/bounces-do-you-know-how-to-correct-a-bounce/rule.md
  rules/connect-client-im/rule.md
  rules/create-PBIs-under-2-days/rule.md
  rules/do-you-add-a-version-number-to-pbis-that-have-multiple-iterations/rule.md
  rules/do-you-consider-seo-in-your-angularjs-application/rule.md
  rules/install-chatgpt-as-an-app/rule.md
  rules/sprint-forecast/rule.md
  rules/technical-debt/rule.md
  rules/use-cannot-and-website-instead-of-separated-words/rule.md
  rules/use-taskbar-instead-of-task-bar/rule.md
  rules/when-to-go-for-a-tender/rule.md
  rules/where-to-keep-your-files/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7301 XS✔ ◾ fix category
  categories/communication/rules-to-better-email.md
Labels: Age: 🐥 - Adolescent

#7300 XS✔ ◾ Brainstorming ideas - improve words
  rules/brainstorming-idea-farming/rule.md
Labels: Age: 🐤 - Mature

#7304 XS✔ ◾ Update Rule "turn-emails-into-pbis" - Add section for pre-existing PBIs
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🥚 - New

#7305 XS✔ ◾ Less is more - Update thumbnail and background images
  rules/less-is-more/Piers-After.jpg
  rules/less-is-more/Piers-Before.jpg
  rules/less-is-more/office-bg-bad.png
  rules/less-is-more/office-bg-good.jpg
  rules/less-is-more/rule.md
Labels: Age: 🥚 - New

#7306 XS✔ ◾ Less is more - Add video link
  rules/less-is-more/rule.md
Labels: Age: 🥚 - New

#7308 XS✔ ◾ Less is more - Update thumbnail and background images (#7305)
  rules/less-is-more/office-bg-good-v2.jpg
  rules/less-is-more/office-bg-good.jpg
  rules/less-is-more/rule.md
Labels: Age: 🥚 - New

#7309 XS✔ ◾ to myself rule update tips to avoid burying headline
  rules/send-to-myself-emails/rule.md
Labels: Age: 🥚 - New

#7310 XS✔ ◾ Update rules-to-better-power-bi.md
  categories/reporting-solutions/rules-to-better-power-bi.md
Labels: Age: 🥚 - New

#7299 Create Rule “power-bi-visualizations/rule”
  rules/power-bi-visualizations/100-stacked-bars.jpg
  rules/power-bi-visualizations/100-stacked-columns.jpg
  rules/power-bi-visualizations/arcgis-map.png
  rules/power-bi-visualizations/area-chart.jpg
  rules/power-bi-visualizations/azure-map.jpg
  rules/power-bi-visualizations/bar-chart.jpg
  rules/power-bi-visualizations/card.jpg
  rules/power-bi-visualizations/clustered-bar-chart.jpg
  rules/power-bi-visualizations/clustered-columns.jpg
  rules/power-bi-visualizations/column-chart.jpg
  rules/power-bi-visualizations/decomposition-tree.png
  rules/power-bi-visualizations/donut.jpg
  rules/power-bi-visualizations/filled-map.jpg
  rules/power-bi-visualizations/funnel-chart.png
  rules/power-bi-visualizations/gauge-chart.png
  rules/power-bi-visualizations/key-influencers.png
  rules/power-bi-visualizations/kpi.png
  rules/power-bi-visualizations/line-and-stacked-column-chart.jpg
  rules/power-bi-visualizations/line-chart.jpg
  rules/power-bi-visualizations/map.jpg
  rules/power-bi-visualizations/matrix.png
  rules/power-bi-visualizations/metrics.png
  rules/power-bi-visualizations/multi-row-card.jpg
  rules/power-bi-visualizations/paginated-reports.png
  rules/power-bi-visualizations/pie-chart.jpg
  rules/power-bi-visualizations/power-app.png
  rules/power-bi-visualizations/power-automate.jpg
  rules/power-bi-visualizations/q-a.png
  rules/power-bi-visualizations/ribbon-chart.jpg
  rules/power-bi-visualizations/rule.md
  rules/power-bi-visualizations/scatter-chart.jpg
  rules/power-bi-visualizations/slicer.jpg
  rules/power-bi-visualizations/smart-narrative.png
  rules/power-bi-visualizations/stacked-area-chart.jpg
  rules/power-bi-visualizations/stacked-bar-chart.jpg
  rules/power-bi-visualizations/stacked-column-chart.jpg
  rules/power-bi-visualizations/table.jpg
  rules/power-bi-visualizations/treemap.jpg
  rules/power-bi-visualizations/treemap.png
  rules/power-bi-visualizations/visualizations.jpg
  rules/power-bi-visualizations/waterfall-chart.png
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7311 XS✔ ◾ ⚡️Update do you implement dev ops practices for continuous delivery
  rules/do-you-implement-DevOps-practices-for-continuous-delivery/Agile_Development.png
  rules/do-you-implement-DevOps-practices-for-continuous-delivery/DevOps_Collaboration.png
  rules/do-you-implement-DevOps-practices-for-continuous-delivery/Risky_deployments.png
  rules/do-you-implement-DevOps-practices-for-continuous-delivery/rule.md
  rules/do-you-utilize-a-release-train/rule.md
Labels: Age: 🥚 - New

#7314 XS✔ ◾ ⚡️Update do you measure success using lean agile metrics
  rules/do-you-measure-success-using-lean-agile-metrics/Data-Driven-Decisions.png
  rules/do-you-measure-success-using-lean-agile-metrics/rule.md
Labels: Age: 🥚 - New

#7315 XS✔ ◾ ⚡️Updated rule content for: Do you regularly inspect and adapt at scale
  rules/do-you-regularly-inspect-and-adapt-at-scale/rule.md
Labels: Age: 🥚 - New

#7316 XS✔ ◾ ⚡️Update content for rule: Do you foster a culture of relentless improvement
  rules/do-you-foster-a-culture-of-relentless-improvement/rule.md
Labels: Age: 🥚 - New

#7320 XS✔ ◾ Update rules-to-better-specification-reviews.md
  categories/management/rules-to-better-specification-reviews.md
Labels: Age: 🥚 - New

#7317 Update Rule “tree-of-thought-prompts-for-complex-reasoning/rule”
  rules/tree-of-thought-prompts-for-complex-reasoning/rule.md
Labels: Age: 🐓 - Old

#7325 XS✔ ◾ Fixing inconsistencies /great-done-video
  rules/making-a-great-done-video/rule.md
Labels: Age: 🥚 - New

#7321 XS✔ ◾ New rule: linkedin-creator-mode
  rules/linkedin-creator-mode/Picture1.png
  rules/linkedin-creator-mode/Picture2.png
  rules/linkedin-creator-mode/Picture3.png
  rules/linkedin-creator-mode/Picture4.png
  rules/linkedin-creator-mode/rule.md
Labels: Age: 🐓 - Old

#7323 XS✔ ◾ Update rule.md
  rules/meetings-are-you-prepared-for-the-initial-meeting/rule.md
Labels: Age: 🐓 - Old

#7312 Update Rule “conduct-a-spec-review/rule”
  rules/conduct-a-spec-review/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7329 XS✔ ◾ added my new rule
  categories/reporting-solutions/rules-to-better-power-bi.md
Labels: Age: 🥚 - New

#7327 Update Rule “awesome-documentation/rule”
  rules/awesome-documentation/rule.md
Labels: codeauditor fix

#7330 Update Rule “architecture-diagram/rule”
  rules/architecture-diagram/rule.md
Labels: codeauditor fix

#7331 Update Rule “do-you-use-co-creation-patterns/rule”
  rules/do-you-use-co-creation-patterns/rule.md
Labels: codeauditor fix

#7332 Update Rule “over-the-shoulder/rule”
  rules/over-the-shoulder/rule.md
Labels: codeauditor fix

#7340 Update Rule “calendar-do-you-know-the-ways-to-share-and-see-others-calendars/rule”
  rules/calendar-do-you-know-the-ways-to-share-and-see-others-calendars/rule.md
Labels: codeauditor fix

#7339 Update Rule “appointments-do-you-show-all-the-necessary-information-in-the-subject/rule”
  rules/appointments-do-you-show-all-the-necessary-information-in-the-subject/rule.md
Labels: codeauditor fix

#7338 Update Rule “do-you-timebox-approval-requests/rule”
  rules/do-you-timebox-approval-requests/rule.md
Labels: codeauditor fix

#7337 Update Rule “do-you-use-source-control-and-backups/rule”
  rules/do-you-use-source-control-and-backups/rule.md
Labels: codeauditor fix

#7333 Update Rule “importance-critical-distance/rule”
  rules/importance-critical-distance/rule.md
Labels: codeauditor fix

#7335 Update Rule “do-you-know-how-important-timesheets-are/rule”
  rules/do-you-know-how-important-timesheets-are/rule.md
Labels: codeauditor fix

#7342 XS✔ ◾ Fixing related section
  rules/linkedin-creator-mode/rule.md
Labels: Age: 🥚 - New

#7334 Update Rule “do-you-know-which-environments-you-need-to-provision-when-starting-a-new-project/rule”
  rules/do-you-know-which-environments-you-need-to-provision-when-starting-a-new-project/rule.md
Labels: codeauditor fix
