Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2023-10, with the labels that each got.

#6874 XS✔ ◾ Add Creating a Teams team as part of the spec review rules
  categories/management/rules-to-better-specification-reviews.md
Labels: Age: 🥚 - New

#6882 XS✔ ◾ CodeAuditor Scan - Fixed Kiki broken image
  rules/secure-password-share/rule.md
Labels: Age: 🥚 - New

#6878 XS✔ ◾ Fixed code syntax and examples "use-the-ready-function"
  rules/do-you-use-the-ready-function/rule.md
Labels: rubber stamp, Age: 🐣 - Young

#6877 XS✔ ◾ Fixed images markdown + code syntax "do-you-streamline-your-developme…
  rules/do-you-streamline-your-development-process-with-npm-and-task-runners/rule.md
Labels: Age: 🐣 - Young

#6876 XS✔ ◾ Fixed broken link + improved others "cool-jquery-plugins"
  rules/the-best-examples-of-visually-cool-jquery-plug-ins/rule.md
Labels: codeauditor fix, Age: 🐣 - Young

#6881 XS✔ ◾ Changing figure
  rules/reflexion/reflexion-figure.png
  rules/reflexion/reflexionresults.png
  rules/reflexion/rule.md
Labels: Age: 🥚 - New

#6888 XS✔ ◾ 💚fix build images
  rules/protect-your-main-branch/protect-branch-bad-1.jpg
  rules/protect-your-main-branch/protect-branch-bad.jpg
  rules/protect-your-main-branch/protect-branch-good-1.jpg
  rules/protect-your-main-branch/protect-branch-good.jpg
Labels: Age: 🥚 - New

#6884 Create Rule “update-a-github-issue/rule”
  rules/update-a-github-issue/bad-example-lots-of-non-descriptive-comments.png
  rules/update-a-github-issue/good-example-adding-context-via-comment.png
  rules/update-a-github-issue/good-example-cc-in-comment.png
  rules/update-a-github-issue/good-example-cc-in-issue.png
  rules/update-a-github-issue/good-example-update.png
  rules/update-a-github-issue/rule.md
Labels: Age: 🐥 - Adolescent

#6891 XS✔ ◾ added rule "keeping-pbis-status-visible" to "rules-to-better-github" category
  categories/software-development/rules-to-better-github.md
Labels: Age: 🐣 - Young

#6886 XS✔ ◾ CodeAuditor Scan - Fix missing double quotes in attribute values
  rules/event-storming/rule.md
Labels: Age: 🐤 - Mature

#6887 XS✔ ◾ CodeAuditor Scan - Fix missing double quotes in attribute values
  rules/event-storming-workshop/rule.md
Labels: Age: 🐤 - Mature

#6885 Add dotnet upgrade assistant CLI image to rule/dotnet-upgrade-assistant
  rules/dotnet-upgrade-assistant/rule.md
  rules/dotnet-upgrade-assistant/upgrade-assistant-CLI.png
Labels: Age: 🐤 - Mature

#6890 adding new rule focus peaking to video category
  categories/marketing-and-video/rules-to-better-video-recording.md
Labels: Age: 🐤 - Mature

#6889 Create Rule “focus-peaking/rule”
  rules/focus-peaking/focus-peaking-church.jpg
  rules/focus-peaking/peaking-outoffocus.jpg
  rules/focus-peaking/rule.md
Labels: Age: 🐤 - Mature

#6875 XS✔ ◾ Improved grammar "send-v2"
  rules/email-send-a-v2/rule.md
Labels: rubber stamp, Age: 🐓 - Old

#6883 Features/52706 update problem details rule
  rules/do-you-return-detailed-error-messages/rule.md
Labels: Age: 🐓 - Old

#6880 ✨ New Rule - Do you know when to use scoped CSS?
  rules/scoped-css/overwritten-style.png
  rules/scoped-css/rule.md
Labels: Age: 🐓 - Old

#6895 XS✔ ◾ Update rule.md
  rules/making-a-great-done-video/rule.md
Labels: Age: 🥚 - New

#6897 XS✔ ◾ 💚Fixes images in a rule + fixes rule
  rules/focus-peaking/rule.md
  rules/protect-your-main-branch/rule.md
Labels: Age: 🥚 - New

#6896 XS✔ ◾ Update rule.md
  rules/duplicate-email-draft/rule.md
Labels: Age: 🐣 - Young

#6899 Create Rule “establish-the-world/rule”
  rules/establish-the-world/rule.md
Labels: Age: 🐤 - Mature

#6900 XS✔ ◾ Update rules-to-better-video-recording.md
  categories/marketing-and-video/rules-to-better-video-recording.md
Labels: Age: 🐤 - Mature

#6902 XS✔ ◾ Update rule.md
  rules/establish-the-world/rule.md
Labels: Age: 🥚 - New

#6909 Adding new rule to tech doc category
  categories/communication/rules-to-better-technical-documentation.md
Labels: Age: 🐤 - Mature

#6904 XS✔ ◾ CodeAuditor Scan - Fix missing paired tags
  rules/the-reasons-why-calling-a-batch-file-from-the-build-process-template-is-better-than-deploying-directly-from-the-build/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#6892 XS✔ ◾ Clarifying reflexion spelling
  rules/reflexion/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6915 XS✔ ◾ Make images the same size
  rules/add-a-spot-of-color-for-emphasis/rule.md
Labels: Age: 🥚 - New

#6914 XS✔ ◾ Fix layout on "Use the Scrum template with Azure DevOps"
  rules/use-devops-scrum-template/rule.md
Labels: Age: 🥚 - New

#6916 XS✔ ◾ Improved table to avoid HTML lists
  rules/the-reasons-why-calling-a-batch-file-from-the-build-process-template-is-better-than-deploying-directly-from-the-build/rule.md
Labels: Age: 🥚 - New

#6901 Add rule: Do you know how to handle errors in Angular?
  categories/websites/rules-to-better-angular.md
  rules/angular-error-handling/angular-scoping-error-handler.png
  rules/angular-error-handling/rule.md
Labels: Age: 🐓 - Old

#6919 XS✔ ◾ Reuploading image to fix size
  rules/add-a-spot-of-color-for-emphasis/chewing-fat-bottom-text.png
Labels: Age: 🥚 - New

#6917 Do-you-know-how-to-analyse-your-web-application-usage-with-application-insights-1
  categories/software-development/rules-to-better-application-insights.md
  rules/analyse-your-web-application-usage-with-application-insights/ContentPack.png
  rules/analyse-your-web-application-usage-with-application-insights/Sugarlearning PowerBi.png
  rules/analyse-your-web-application-usage-with-application-insights/custom-events-in-app-insights.jpg
  rules/analyse-your-web-application-usage-with-application-insights/rule.md
  rules/analyse-your-web-application-usage-with-application-insights/usage-1.png
  rules/do-you-know-how-to-analyse-your-web-application-usage-with-application-insights/rule.md
Labels: Age: 🥚 - New

#6920 XS✔ ◾ 💄Fixing - Caption field rendering not displaying bold correctly
  rules/store-github-secrets-in-keyvault/rule.md
Labels: Age: 🥚 - New

#6923 XS✔ ◾ 📝add info note to category
  categories/design-and-presentation/rules-to-better-interfaces-winforms-controls.md
Labels: Age: 🐥 - Adolescent

#6927 XS✔ ◾ Add PR to the title
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#6925 XS✔ ◾ Added info on promote services or awards at the bottom of the external signature
  rules/great-email-signatures/rule.md
Labels: Age: 🐓 - Old

#6926 XS✔ ◾ Removed extra row + added emojis
  rules/the-reasons-why-calling-a-batch-file-from-the-build-process-template-is-better-than-deploying-directly-from-the-build/rule.md
Labels: rubber stamp, Age: 🍗 - Ancient, 🔥 Merge Debt

#6930 XS✔ ◾ Added info box with a link to BRB suggestion
  rules/minimize-unrelated-interruptions/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6933 XS✔ ◾ fixing broken figure
  rules/close-off-thread/rule.md
Labels: Age: 🥚 - New

#6912 New rule (collated) on avoid common mistakes
  rules/avoid-common-mistakes/rule.md
  rules/commas-and-full-stops-always-should-have-1-space-after-them/rule.md
  rules/do-you-know-when-to-versus-and-verses/rule.md
  rules/do-you-write-the-word-email-in-the-correct-format/rule.md
  rules/dones-do-you-use-email-for-tasks-only-not-communication/rule.md
  rules/style-quotations/rule.md
  rules/use-cannot-and-website-instead-of-separated-words/rule.md
  rules/use-setup-and-set-up-correctly/rule.md
  rules/use-taskbar-instead-of-task-bar/rule.md
  rules/use-try-again-instead-of-retry/rule.md
  rules/use-username-instead-of-user-name/rule.md
  rules/when-to-use-log-on-log-in-and-sign-in/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6913 XS✔ ◾ Add new rule avoid-common-mistakes to categories
  categories/communication/rules-to-better-technical-documentation.md
  categories/design-and-presentation/rules-to-better-content-design.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6906 Change subtitles of the rule and add images/do-you-create-a-migration-plan
  rules/do-you-create-a-migration-plan/good-example-vs-bad-example-tfms.png
  rules/do-you-create-a-migration-plan/legacy-vs-sdk.png
  rules/do-you-create-a-migration-plan/related-runtimes.png
  rules/do-you-create-a-migration-plan/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6941 XS✔ ◾ Fixed grammar issue with sentence
  rules/update-a-github-issue/rule.md
Labels: Age: 🥚 - New

#6921 Update Rule “do-you-make-your-team-meetings-easy-to-find/rule”
  rules/do-you-make-your-team-meetings-easy-to-find/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6937 XS✔ ◾ fixing broken figure
  rules/close-off-thread/rule.md
Labels: Age: 🥚 - New

#6938 XS✔ ◾ Updated "update-a-github-issue" folder to "keeping-pbis-status-visible"
  rules/keeping-pbis-status-visible/bad-example-lots-of-non-descriptive-comments.png
  rules/keeping-pbis-status-visible/good-example-adding-context-via-comment.png
  rules/keeping-pbis-status-visible/good-example-cc-in-comment.png
  rules/keeping-pbis-status-visible/good-example-cc-in-issue.png
  rules/keeping-pbis-status-visible/good-example-update.png
  rules/keeping-pbis-status-visible/rule.md
Labels: Age: 🥚 - New

#6854 update frontmatter validator
  .github/workflows/validate-frontmatter.yml
  scripts/frontmatter-validator/frontmatter-validator.js
Labels: code change, Age: 🦖 - Extinct, 🔥 Merge Debt

#6945 XS✔ ◾ Updating Do you know when to go for a Tender? - making updates on when to go for a tender
  rules/when-to-go-for-a-tender/rule.md
Labels: Age: 🥚 - New

#6944 XS✔ ◾ Brainstorming - Tip to start presentations earlier
  rules/use-the-brains-of-your-company/rule.md
Labels: Age: 🥚 - New

#6942 XS✔ ◾ Fixed Kiki broken image
  rules/control4-agents/rule.md
Labels: Age: 🐣 - Young

#6928 XS✔ ◾ Archived /test-please-for-video
  categories/marketing-and-video/rules-to-better-video-recording.md
  rules/test-please-for-video/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6946 XS✔ ◾ Updated About us link on mission statement rule
  rules/have-a-clear-mission-statement/rule.md
Labels: rubber stamp, Age: 🐣 - Young

#6951 Update rules-to-better-specification-reviews.md
  categories/management/rules-to-better-specification-reviews.md
Labels: Age: 🥚 - New

#6924 XS✔ ◾ Added link to "ensure changes are live"
  rules/dones-do-you-reply-done-and-delete-the-original-email/rule.md
Labels: rubber stamp, Age: 🦖 - Extinct, 🔥 Merge Debt

#6952 XS✔ ◾ fixing email template display
  rules/follow-up-after-spec-review/rule.md
Labels: Age: 🥚 - New

#6947 XS✔ ◾ Create rule.md - Secrets masking in GitHub Actions
  categories/software-development/rules-to-better-devops-using-github.md
  rules/mask-secrets-in-github-actions/rule.md
  rules/mask-secrets-in-github-actions/secret-with-add-mask.png
  rules/mask-secrets-in-github-actions/secret-without-add-mask.png
Labels: Age: 🐣 - Young

#6943 Create new rule/why-upgrade-to-latest-dotnet
  categories/software-development/rules-to-better-net8-migrations.md
  rules/why-upgrade-to-latest-dotnet/rule.md
Labels: Age: 🐓 - Old

#6957 XS✔ ◾ 🧠🌩️ Brainstorming - Update agenda
  rules/use-the-brains-of-your-company/rule.md
Labels: Age: 🥚 - New

#6955 XS✔ ◾ CodeAuditor Scan - Add missing double quotes in attribute values
  rules/event-storming-workshop/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#6949 XS✔ ◾ Update When to go for a Tender
  rules/when-to-go-for-a-tender/rule.md
Labels: Age: 🐤 - Mature

#6929 Update Rule “figma-uses/rule”
  rules/figma-uses/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6960 XS✔ ◾ Update rule
  rules/be-prepared-for-inbound-calls/rule.md
Labels: Age: 🥚 - New

#6962 XS✔ ◾ adding a warning to review GPT content
  rules/use-chatgpt-to-write-a-rule/rule.md
Labels: Age: 🥚 - New

#6961 XS✔ ◾ fixing heading size to be consistent
  rules/use-microsoft-teams-room/rule.md
Labels: Age: 🐣 - Young

#6968 XS✔ ◾ Added redirect to "do-you-know-the-correct-way-to-develop-data-entry-…
  rules/data-entry-forms-for-web/rule.md
Labels: Age: 🥚 - New

#6966 XS✔ ◾ Fix broken links on risk-based-testing
  rules/risk-based-testing/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#6963 XS✔ ◾ Update formatting as "Good" Tick was not displaying
  rules/do-you-know-what-sort-of-insurance-to-buy-when-travelling/rule.md
Labels: Age: 🐓 - Old

#6967 XS✔ ◾ Fixed broken link + captions consistency "do-you-know-the-correct-way-to-develop-data-entry-forms"
  rules/do-you-know-the-correct-way-to-develop-data-entry-forms/rule.md
Labels: Age: 🥚 - New

#6970 XS✔ ◾ Update rules-to-better-security-end-users.md
  categories/infrastructure-and-networking/rules-to-better-security-end-users.md
Labels: Age: 🥚 - New

#6964 XS✔ ◾ Suggesting changes
  rules/establish-the-world/rule.md
Labels: Age: 🐓 - Old

#6973 XS✔ ◾ Adding a category for my rule
  categories/infrastructure-and-networking/rules-to-better-security.md
Labels: Age: 🥚 - New

#6977 XS✔ ◾ change-from-x-to-y---created-new-tip-to-better-organise-styles-in-outlook
  rules/change-from-x-to-y/change-from-x-to-y-organising-styles-bad-example.png
  rules/change-from-x-to-y/change-from-x-to-y-organising-styles-good-example.png
  rules/change-from-x-to-y/rule.md
Labels: Age: 🥚 - New

#6980 XS✔ ◾ Update and rename rule.md to rule.md
  categories/software-development/rules-to-better-pull-requests.md
  rules/over-the-shoulder/rule.md
Labels: Age: 🥚 - New

#6976 Fix validation
  .github/workflows/validate-frontmatter.yml
  scripts/frontmatter-validator/frontmatter-validator.js
  scripts/frontmatter-validator/schema/rule-schema.json
Labels: code change, Age: 🐣 - Young

#6975 XS✔ ◾ Fixing the greybox
  rules/enterprise-password-manager-auditing/rule.md
Labels: Age: 🐣 - Young

#6983 XS✔ ◾ Update rule.md
  rules/testing-tools/rule.md
Labels: Age: 🥚 - New

#6985 FIx video
  rules/ephemeral-environments/rule.md
Labels: Age: 🥚 - New

#6986 XS✔ ◾ fix rule title
  rules/testing-tools/rule.md
Labels: Age: 🥚 - New

#6990 XS✔ ◾ Update rules-to-better-specification-reviews.md
  categories/management/rules-to-better-specification-reviews.md
Labels: Age: 🥚 - New

#6991 XS✔ ◾ Update use-ai-to-generate-spec-reviews/rule.md
  rules/use-ai-to-generate-spec-reviews/rule.md
Labels: Age: 🥚 - New

#6992 XS✔ ◾ Update use-ai-to-generate-spec-reviews/rule.md
  rules/use-ai-to-generate-spec-reviews/rule.md
Labels: Age: 🥚 - New

#6993 XS✔ ◾ Update use-ai-to-generate-spec-reviews/rule.md
  rules/use-ai-to-generate-spec-reviews/rule.md
Labels: Age: 🥚 - New

#6995 XS✔ ◾ Fixed Kiki broken image
  rules/control4-get-help/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#6997 XS✔ ◾ Induction PBIs - Remove join scrum team process
  rules/track-induction-work-in-a-scrum-team/rule.md
Labels: Age: 🥚 - New

#6971 Add rule: Do you properly separate concerns in components?
  categories/websites/rules-to-better-angular.md
  rules/angular-separate-component-concerns/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6998 📝update rule
  rules/less-is-more/rule.md
Labels: Age: 🥚 - New

#6958 Update rule.md - remove unexplained ct variable
  rules/do-pagination-database-side/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7000 Update TriggerDevOpsBuild.yml
  .github/workflows/TriggerDevOpsBuild.yml
Labels: Age: 🐣 - Young

#7004 XS✔ ◾ New content design rule hemmingway-editor
  categories/design-and-presentation/rules-to-better-content-design.md
  hemmingway-editor/hemmingway-bad.png
  hemmingway-editor/hemmingway-good.png
  hemmingway-editor/rule.md
  rules/concise-writing/rule.md
  rules/use-active-voice/rule.md
Labels: Age: 🐤 - Mature

#7008 XS✔ ◾ Update rule.md
  rules/establish-the-world/rule.md
Labels: Age: 🥚 - New

#7007 XS✔ ◾ Update rule.md
  rules/establish-the-world/rule.md
Labels: Age: 🥚 - New

#7006 XS✔ ◾ 💚Fix rules and category names + create date
  categories/management/index.md
  categories/management/rules-to-better-scaled-agile-framework.md
  rules/do-you-ensure-compliance-and-governance-without-compromising-agility/rule.md
  rules/do-you-establish-a-Lean-Agile-mindset-across-all-teams/rule.md
  rules/do-you-foster-a-culture-of-relentless-improvement/rule.md
  rules/do-you-implement-DevOps-practices-for-continuous-delivery/rule.md
  rules/do-you-involve-stakeholders-in-pi-planning/rule.md
  rules/do-you-measure-success-using-lean-agile-metrics/rule.md
  rules/do-you-prioritize-value-streams-over-individual-projects/rule.md
  rules/do-you-regularly-inspect-and-adapt-at-scale/rule.md
  rules/do-you-use-SAFe-to-align-multiple-scrum-teams/rule.md
  rules/do-you-utilize-a-release-train/rule.md
Labels: Age: 🥚 - New

#7009 XS✔ ◾ Update rule.md
  rules/establish-the-world/rule.md
Labels: Age: 🥚 - New

#7010 XS✔ ◾ Fix video figures
  rules/establish-the-world/rule.md
Labels: Age: 🥚 - New

#6974 XS✔ ◾ Create rule.md - Choose correct timezone for your flows
  categories/software-development/rules-to-better-power-platform.md
  rules/power-automate-flows-convert-timezone/comparing-timedate-without-converting.png
  rules/power-automate-flows-convert-timezone/convert-timezone-expression.GIF
  rules/power-automate-flows-convert-timezone/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7012 XS✔ ◾ New content design rule tone-of-voice
  categories/design-and-presentation/rules-to-better-content-design.md
  tone-of-voice/rule.md
Labels: Age: 🐤 - Mature

#7017 XS✔ ◾ Design rules - Move to /rules
  rules/hemmingway-editor/hemmingway-bad.png
  rules/hemmingway-editor/hemmingway-good.png
  rules/hemmingway-editor/rule.md
  rules/tone-of-voice/rule.md
Labels: Age: 🥚 - New

#7021 XS✔ ◾ Fixing formatting
  rules/use-chatgpt-to-write-a-rule/rule.md
Labels: Age: 🥚 - New

#7022 XS✔ ◾ Update Cheat Sheet
  rules/chatgpt-cheat-sheet/rule.md
Labels: Age: 🥚 - New

#7005 XS✔ ◾ CodeAuditor Scan - Fixed broken link
  rules/do-you-use-architectural-decision-records/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7016 XS✔ ◾ Fix broken link on Do You Use Architectural Decision Records? (ADRs)
  rules/do-you-use-architectural-decision-records/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7023 XS✔ ◾ Fixed title /do-you-use-architectural-decision-records
  rules/do-you-use-architectural-decision-records/rule.md
Labels: Age: 🥚 - New

#7013 XS✔ ◾ Update rule.md
  rules/follow-up-after-spec-review/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7011 XS✔ ◾ editing template
  rules/create-appointment-for-flights/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7020 XS✔ ◾ spec review presentation - record it
  categories/management/rules-to-better-specification-reviews.md
  rules/corridor-conversations/ProjectManagement_Suprise.jpg
  rules/corridor-conversations/rule.md
  rules/do-you-have-an-engagement-lifecycle/rule.md
  rules/record-teams-meetings/copy-to-button-stream.png
  rules/record-teams-meetings/rule.md
  rules/record-teams-meetings/stream-move-to-team.png
  rules/spec-do-you-conduct-a-specification-review-ask-for-a-coffee-not-a-marriage/rule.md
  rules/specification-review-presentation/pptx-to-video.png
  rules/specification-review-presentation/rule.md
  rules/specification-review-presentation/spec-review-desision-makers.jpg
  rules/storyboards/rule.md
  rules/what-is-a-spec-review/rule.md
Labels: Age: 🐓 - Old

#7025 XS✔ ◾ Update rule.md
  rules/follow-up-effectively/rule.md
Labels: Age: 🥚 - New

#7024 XS✔ ◾ Updating image of computer with sticky notes
  rules/follow-up-effectively/adobe-firefly-screen-with-sticky-notes.jpg
Labels: Age: 🥚 - New

#7026 XS✔ ◾ CodeAuditor Scan - Fix Kiki's broken image
  rules/zigbee-design-principles/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7014 add new rule for securing application insights telemetry
  categories/software-development/rules-to-better-application-insights.md
  rules/appinsights-authentication/appinsights-assigned-role.png
  rules/appinsights-authentication/appinsights-disable-local-auth-bicep.png
  rules/appinsights-authentication/appinsights-disable-local-auth.png
  rules/appinsights-authentication/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7029 XS✔ ◾ Fix minor typos for Pros and Cons
  rules/appinsights-authentication/rule.md
Labels: Age: 🥚 - New

#7028 XS✔ ◾ add record-teams-meetings to meetings category
  categories/communication/rules-to-better-communication.md
  categories/communication/rules-to-better-meetings.md
  categories/management/rules-to-better-specification-reviews.md
Labels: Age: 🥚 - New

#7030 XS✔ ◾ Update rules-to-better-video-recording.md
  categories/marketing-and-video/rules-to-better-video-recording.md
Labels: Age: 🥚 - New

#7032 XS✔ ◾ Update rule.md - fixing broken image
  rules/power-automate-flows-convert-timezone/convert-timezone-expression.gif
Labels: Age: 🥚 - New

#7033 Create Rule “unique-office-backgrounds/rule”
  rules/unique-office-backgrounds/rule.md
Labels: Age: 🥚 - New

#7035 Update Rule “use-the-right-sharepoint-development-environment/rule”
  rules/use-the-right-sharepoint-development-environment/rule.md
Labels: Age: 🐤 - Mature

#7036 XS✔ ◾ Adding the link of v2 rule to the recall rule
  rules/do-you-know-how-to-recall-an-email/rule.md
Labels: Age: 🥚 - New

#7039 XS✔ ◾ add link to rule
  rules/turn-emails-into-a-github-issue/rule.md
Labels: Age: 🥚 - New

#7045 XS✔ ◾ Fix the format on the rule updated today
  rules/do-you-know-how-to-recall-an-email/rule.md
Labels: Age: 🥚 - New

#7044 Update Rule “what-is-chatgpt/rule”
  rules/what-is-chatgpt/rule.md
Labels: Age: 🐤 - Mature

#7053 Fixed spelling /explain-deleted-or-modified-appointments
  rules/explain-deleted-or-modified-appointments/rule.md
Labels: codeauditor fix, rubber stamp, Age: 🍗 - Ancient, 🔥 Merge Debt

#7050 XS✔ ◾ Fixed typo on title /spec-review-timesheets
  rules/spec-review-timesheets/rule.md
Labels: rubber stamp, Age: 🍗 - Ancient, 🔥 Merge Debt

#7058 XS✔ ◾ Fixed spelling /login-security-do-you-know-the-correct-error-message-for-an-incorrect-user-name-or-password
  rules/login-security-do-you-know-the-correct-error-message-for-an-incorrect-user-name-or-password/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7054 XS✔ ◾ Fixed spelling /calendar-do-you-allow-full-access-to-calendar-admins
  rules/calendar-do-you-allow-full-access-to-calendar-admins/rule.md
Labels: codeauditor fix, rubber stamp, Age: 🍗 - Ancient, 🔥 Merge Debt

#7055 XS✔ ◾ Fixed spelling /generate-interfaces-for-your-dtos
  rules/generate-interfaces-for-your-dtos/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7057 XS✔ ◾ Fixed spelling /bounces-do-you-know-how-to-correct-a-bounce
  rules/bounces-do-you-know-how-to-correct-a-bounce/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#7042 XS✔ ◾ Including the relevant rules
  rules/ask-clients-approval/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7064 Added social media stats rule, updated GA rule
  categories/marketing-and-video/rules-to-better-social-media-personal.md
  rules/do-you-include-google-analytics-in-your-website/rule.md
  rules/do-you-know-how-to-check-your-social-media-stats/rule.md
Labels: Age: 🥚 - New

#7073 XS✔ ◾ Update rules-to-better-sales.md
  categories/management/rules-to-better-sales.md
Labels: Age: 🥚 - New

#7068 XS✔ ◾ fixed 404 pages
  rules/dont-base-your-projects-on-the-angular-io-tutorials/rule.md
  rules/the-best-learning-resources-for-angular/rule.md
  rules/use-microsoft-teams-room/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7066 Update Rule “use-most-recent-language-features-to-slash-the-amount-of-boilerplate-code-you-write/rule”
  rules/use-most-recent-language-features-to-slash-the-amount-of-boilerplate-code-you-write/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7065 Update Rule “comment-each-property-and-method/rule”
  rules/comment-each-property-and-method/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7060 Update Rule “use-report-server-project/rule”
  rules/use-report-server-project/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7061 Update Rule “request-a-test-please/rule”
  rules/request-a-test-please/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7062 Update Rule “the-standard-naming-conventions-for-tests/rule”
  rules/the-standard-naming-conventions-for-tests/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7056 XS✔ ◾ FIxed spelling /structured-website
  rules/improve-performance-with-lazy-loading-of-media-assets/rule.md
  rules/structured-website/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#7048 XS✔ ◾ Update /right-format-to-show-phone-numbers
  rules/right-format-to-show-phone-numbers/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#7047 XS✔ ◾ Added link to phone number /great-email-signatures
  rules/great-email-signatures/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#7052 XS✔ ◾ Updated rule /provide-fresh-content
  rules/do-you-respond-to-each-email-individually/rule.md
  rules/provide-fresh-content/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#7051 XS✔ ◾ Update rule.md /meetings-do-you-know-the-way-meetings-should-work/
  rules/meetings-do-you-know-the-way-meetings-should-work/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#7063 Update Rule “do-you-know-when-to-build-a-wp-app-over-an-iphone-app/rule”
  rules/do-you-know-when-to-build-a-wp-app-over-an-iphone-app/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7049 XS✔ ◾ Update rule.md /make-numbers-more-readable + added related
  rules/make-numbers-more-readable/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7074 Update Rule “dates-do-you-keep-date-formats-consistent-across-your-application/rule”
  rules/dates-do-you-keep-date-formats-consistent-across-your-application/rule.md
Labels: codeauditor fix

#7070 XS✔ ◾ make-phone-no-hyperlinks
  rules/do-you-create-your-own-process-template-to-fit-into-your-environment/rule.md
  rules/do-you-know-the-right-methodology-to-choose-new-project-in-vs-2012/rule.md
  rules/great-email-signatures/rule.md
  rules/make-numbers-more-readable/rule.md
  rules/meetings-do-you-know-the-way-meetings-should-work/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7041 ✨ New Rule: Do you use Prefixes to improve code review communication?
  rules/use-prefixes-to-improve-code-review-communication/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7077 Update rule.md
  rules/choosing-authentication/rule.md
Labels: Age: 🥚 - New

#7078 XS✔ ◾ Update rules-to-better-architecture-and-code-review.md
  categories/software-development/rules-to-better-architecture-and-code-review.md
Labels: Age: 🐤 - Mature

#7083 Create Rule “use-esignature-solutions/rule”
  rules/use-esignature-solutions/rule.md
  rules/use-esignature-solutions/signature_gump.png.img.png
Labels: Age: 🐥 - Adolescent

#7067 XS✔ ◾ Update rule.md
  rules/do-you-catch-and-re-throw-exceptions-properly/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7085 XS✔ ◾ CodeAuditor Scan - Fix absolute internal Url
  rules/make-complaints-a-positive-experience/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7086 XS✔ ◾ Archived rule on CRM phone number
  rules/do-you-know-the-best-way-to-find-a-phone-number-of-a-staff-member/rule.md
  rules/how-to-find-a-phone-number/rule.md
Labels: Age: 🥚 - New
