Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2023-09, with the labels that each got.

#6625 CodeAuditor scan - Add missing code block language
  rules/do-you-verify-that-report-server-authentication-settings-allow-a-wide-range-of-web-browsers/rule.md
Labels: codeauditor fix

#6624 CodeAuditor scan - Add missing code block language
  rules/do-you-know-which-reports-are-being-used/rule.md
Labels: codeauditor fix

#6623 CodeAuditor scan - Add missing code block language
  rules/do-you-keep-track-of-which-reports-are-being-executed/rule.md
Labels: codeauditor fix

#6640 CodeAuditor scan - Add missing code block language
  rules/do-you-exclude-width-and-height-properties-from-image-references-in-content/rule.md
Labels: codeauditor fix

#6656 CodeAuditor scan - Fix absolute internal Url
  rules/escalate-key-updates/rule.md
Labels: codeauditor fix

#6580 Create a new category called '.NET Migrations' and move all related migration rules into it
  categories/software-development/index.md
  categories/software-development/rules-to-better-net-projects.md
  categories/software-development/rules-to-better-net8-migrations.md
Labels: Age: 🦖 - Extinct

#6669 XS✔ ◾ split migration rule into two
  rules/do-you-create-a-migration-plan/rule.md
  rules/migrating-web-apps/rule.md
Labels: Age: 🐓 - Old

#6689 XS✔ ◾ Update rule.md
  rules/conduct-a-test-please-internally-and-then-with-the-client/rule.md
Labels: Age: 🥚 - New

#6690 XS✔ ◾ Update rules-to-successful-projects.md
  categories/management/rules-to-successful-projects.md
Labels: Age: 🥚 - New

#6696 Update rule.md
  rules/do-you-conduct-a-test-please-internally-and-then-with-the-client/rule.md
Labels: Age: 🥚 - New

#6693 XS✔ ◾ Update rule.md
  rules/conduct-a-test-please-internally-and-then-with-the-client/rule.md
Labels: Age: 🥚 - New

#6691 Adding new rule Do you have a standard set of pull request workflows?
  .github/workflows/pr-manage-stale.yml
  .github/workflows/pr-metrics.yml
  categories/software-development/rules-to-better-pull-requests.md
  rules/standard-set-of-pull-request-workflows/pr-age-labels.jpg
  rules/standard-set-of-pull-request-workflows/pr-merge-debt-reminder.jpg
  rules/standard-set-of-pull-request-workflows/pr-metrics.jpg
  rules/standard-set-of-pull-request-workflows/rule.md
Labels: Age: 🥚 - New

#6692 XS✔ ◾ CodeAuditor Scan - Add missing language code block
  rules/do-you-make-your-team-meetings-easy-to-find/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#6694 XS✔ ◾ CodeAuditor Scan - Fixed non capitalized Scrum terms
  rules/ben-darwin-rule/rule.md
  rules/bench-master/rule.md
  rules/devops-board-styles/rule.md
  rules/disaster-recovery-plan/rule.md
  rules/do-you-have-a-war-room-summary/rule.md
  rules/ending-a-sprint-do-you-know-when-to-remove-stories-from-the-sprint/rule.md
  rules/meaningful-pbi-titles/rule.md
  rules/meeting-do-you-know-what-to-prepare-for-each-meeting/rule.md
  rules/mockups-and-prototypes/rule.md
  rules/prioritize-performance-optimization-for-maximum-business-value/rule.md
  rules/reports-do-you-understand-the-implied-contract-promises-between-members-of-the-scrum-team/rule.md
  rules/steps-required-to-implement-a-performance-improvement/rule.md
  rules/the-impact-of-adding-an-urgent-new-feature-to-the-sprint/rule.md
  rules/the-reasons-why-calling-a-batch-file-from-the-build-process-template-is-better-than-deploying-directly-from-the-build/rule.md
  rules/the-war-room-does-your-scrum-room-have-the-best-scrum-image/rule.md
  rules/who-dont-use-full-scrum-should-have-a-mini-review/rule.md
Labels: Age: 🐥 - Adolescent

#6700 XS✔ ◾ Updating rule linkedin-contact info
  rules/linkedin-contact-info/adam-good.png
  rules/linkedin-contact-info/good-twitter.png
  rules/linkedin-contact-info/rule.md
  rules/linkedin-contact-info/seth-bad-2.png
Labels: Age: 🥚 - New

#6701 XS✔ ◾ Changing image name - was duplicate
  rules/linkedin-contact-info/good-twitter-link.png
  rules/linkedin-contact-info/rule.md
Labels: Age: 🥚 - New

#6702 XS✔ ◾ Update rule.md
  rules/conduct-a-test-please-internally-and-then-with-the-client/rule.md
Labels: Age: 🥚 - New

#6697 XS✔ ◾ Update rule.md
  rules/post-production-do-you-know-how-to-conduct-a-test-please-for-video/rule.md
Labels: Age: 🐓 - Old

#6704 XS✔ ◾ added video to rule
  rules/ask-clients-approval/rule.md
Labels: Age: 🥚 - New

#6708 XS✔ ◾ Fix test please rule redirects
  categories/management/rules-to-successful-projects.md
  rules/as-per-our-conversation-emails/rule.md
  rules/checked-by-xxx/rule.md
  rules/conduct-a-test-please/pic16-TestingDoYouWantThemT.gif
  rules/conduct-a-test-please/rule.md
  rules/do-you-conduct-a-test-please-internally-and-then-with-the-client/rule.md
  rules/do-you-use-architectural-decision-records/rule.md
  rules/done-do-you-know-when-to-do-a-test-please-in-scrum/rule.md
  rules/importance-critical-distance/rule.md
  rules/ppt-test-please/rule.md
  rules/request-a-test-please/rule.md
Labels: Age: 🥚 - New

#6713 reduce negativity
  rules/ask-clients-approval/rule.md
Labels: Age: 🥚 - New

#6706 XS✔ ◾ Update rules-to-better-devops-using-github.md
  categories/software-development/rules-to-better-devops-using-github.md
Labels: Age: 🥚 - New

#6715 XS✔ ◾ FIx up wording
  rules/ask-clients-approval/rule.md
Labels: Age: 🥚 - New

#6716 XS✔ ◾ Update rule.md
  rules/linkedin-contact-info/rule.md
Labels: Age: 🥚 - New

#6717 XS✔ ◾ changes from Adam
  rules/ask-clients-approval/MJ-rule-UI-mockup.jpg
  rules/ask-clients-approval/rule.md
Labels: Age: 🥚 - New

#6722 XS✔ ◾ Adding image as per Adam's request
  rules/ask-clients-approval/MJ-signature-mockup.jpg
  rules/ask-clients-approval/rule.md
Labels: Age: 🥚 - New

#6719 XS✔ ◾ Update rule.md
  rules/linkedin-contact-info/rule.md
Labels: Age: 🥚 - New

#6720 Update Rule “ask-clients-approval/rule”
  rules/ask-clients-approval/rule.md
Labels: Age: 🥚 - New

#6718 XS✔ ◾ Archive sharepoint rule
  rules/how-to-move-a-rule/rule.md
Labels: Age: 🥚 - New

#6725 XS✔ ◾ Updated video + added caption + other small improvements "michael-jackson"
  rules/ask-clients-approval/rule.md
Labels: Age: 🐣 - Young

#6723 XS✔ ◾ Update best-libraries-for-icons rule
  rules/best-libraries-for-icons/rule.md
Labels: Age: 🐤 - Mature

#6726 XS✔ ◾ Reorder content in best-libraries-for-icons
  rules/best-libraries-for-icons/rule.md
Labels: Age: 🥚 - New

#6730 XS✔ ◾ Create rule.md
  categories/communication/rules-to-better-im.md
  rules/minimize-unrelated-interruptions/rule.md
Labels: Age: 🥚 - New

#6728 XS✔ ◾ removing line breaks in prompt greyboxes
  rules/use-chatgpt-to-write-a-rule/rule.md
Labels: Age: 🥚 - New

#6736 Adding new rule "Do you use the right site search for your website?"
  categories/management/rules-to-better-search.md
  rules/use-right-site-search-for-your-website/algolia.png
  rules/use-right-site-search-for-your-website/elasticsearch.png
  rules/use-right-site-search-for-your-website/meilisearch.png
  rules/use-right-site-search-for-your-website/rule.md
  rules/use-right-site-search-for-your-website/typesense.png
Labels: Age: 🐤 - Mature

#6740 XS✔ ◾ Update Scrum terms
  rules/azure-devops-permissions/rule.md
  rules/create-PBIs-under-2-days/rule.md
  rules/do-you-incentivize-a-quick-spec-review-sale/rule.md
  rules/do-you-know-the-6-stages-in-the-sales-pipeline/rule.md
  rules/do-you-know-what-happens-at-a-sprint-planning-meeting/rule.md
  rules/do-you-present-project-proposals-as-lots-of-little-releases-rather-than-one-big-price/rule.md
  rules/do-you-schedule-a-followup-meeting-after-a-spec-review/rule.md
  rules/managing-errors-with-code-auditor/rule.md
  rules/specification-levels/rule.md
  rules/when-to-go-for-a-tender/rule.md
  rules/who-dont-use-full-scrum-should-have-a-mini-review/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#6739 Update Rule “awesome-documentation/rule”
  rules/awesome-documentation/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#6738 XS✔ ◾ Update Scrum capitalisation on rules-to-better-architecture-and-code-review
  categories/software-development/rules-to-better-architecture-and-code-review.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#6737 Update Rule “post-production-do-you-know-how-to-get-your-videos-approved/rule”
  rules/post-production-do-you-know-how-to-get-your-videos-approved/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#6735 XS✔ ◾ CodeAuditor scan - Add missing language code block
  rules/do-you-know-how-to-remove-old-boot-to-vhd-entries/rule.md
Labels: Age: 🐤 - Mature

#6734 XS✔ ◾ CodeAuditor scan - Add missing language code block
  rules/have-auto-generated-maintenance-pages/rule.md
Labels: Age: 🐤 - Mature

#6743 XS✔ ◾ from h1 to h2 "migration-plans/"
  rules/do-you-create-a-migration-plan/rule.md
Labels: rubber stamp, Age: 🥚 - New

#6742 XS✔ ◾ Fixed folder name, uri + added author "test-please-for-video"
  rules/test-please-for-video/rule.md
Labels: Age: 🐤 - Mature

#6741 XS✔ ◾ Updated URL for "test-please-for-video" on rules-to-better-video-recording.md
  categories/marketing-and-video/rules-to-better-video-recording.md
Labels: rubber stamp, Age: 🐤 - Mature

#6731 XS✔ ◾ made "scenarios" consistent "dones-include-url"
  rules/dones-do-your-dones-include-a-url/rule.md
Labels: rubber stamp, Age: 🐓 - Old

#6744 XS✔ ◾ Re-enable check images action
  .github/workflows/check-images.yml
Labels: Age: 🥚 - New

#6733 📝Update caption on bad example in use-linq-as-a-query-language
  rules/use-linq-as-a-query-language/rule.md
Labels: Age: 🦖 - Extinct

#6724 Update NextJS setup
  rules/how-to-easily-start-a-react-project/rule.md
Labels: Age: 🦖 - Extinct

#6747 XS✔ ◾ Create rule generative-fill
  categories/artificial-intelligence/rules-to-better-ai-image-generators.md
  categories/design-and-presentation/rules-to-better-designers.md
  rules/photoshop-generative-fill/rule.md
Labels: Age: 🥚 - New

#6750 XS✔ ◾ match uri with file name
  rules/photoshop-generative-fill/rule.md
Labels: Age: 🥚 - New

#6751 XS✔ ◾ Updated url in categories
  categories/artificial-intelligence/rules-to-better-ai-image-generators.md
  categories/design-and-presentation/rules-to-better-designers.md
Labels: Age: 🥚 - New

#6749 XS✔ ◾ CodeAuditor - Fix broken link
  rules/do-you-create-a-migration-plan/rule.md
Labels: Age: 🥚 - New

#6745 XS✔ ◾ Update rule.md
  rules/cross-approvals/rule.md
Labels: Age: 🐤 - Mature

#6754 XS✔ ◾ Fixed caption + moved video out of blurb "no-hello"
  rules/no-hello/rule.md
Labels: rubber stamp, Age: 🥚 - New

#6755 XS✔ ◾ Removed unrelaated video from "warn-then-call"
  rules/warn-then-call/rule.md
Labels: Age: 🥚 - New

#6759 XS✔ ◾ Fixed related + moved image out of blurb "company-name-as-part-of-dis…
  rules/use-your-company-name-as-part-of-your-display-name/rule.md
Labels: Age: 🥚 - New

#6752 XS✔ ◾ New rule: chain-of-density
  categories/artificial-intelligence/rules-to-better-chatgpt-prompt-engineering.md
  rules/chain-of-density/rule.md
Labels: Age: 🥚 - New, Age: 🐓 - Old

#6768 XS✔ ◾ Update rule.md
  rules/chain-of-density/rule.md
Labels: Age: 🥚 - New

#6769 XS✔ ◾ Add related rule `do-you-zz-old-files-rather-than-deleting-them` to `record-a-quick-and-dirty-done-video`
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🥚 - New

#6767 XS✔ ◾ Update rule.md
  rules/use-right-site-search-for-your-website/rule.md
Labels: Age: 🐤 - Mature

#6763 XS✔ ◾ Fixed Tom I broken link
  rules/dotnet-upgrade-for-complex-projects/rule.md
Labels: Age: 🐤 - Mature

#6761 XS✔ ◾ Moving featured video to top of rule
  rules/photoshop-generative-fill/rule.md
Labels: Age: 🐤 - Mature

#6760 XS✔ ◾ Fix bad and good code samples
  rules/do-you-avoid-using-thread-sleep-in-your-silverlight-application/rule.md
Labels: Age: 🐓 - Old

#6771 XS✔ ◾ Creating Tree of thought rule
  categories/artificial-intelligence/rules-to-better-chatgpt-prompt-engineering.md
  rules/do-you-use-tree-of-thought-prompts-for-complex-reasoning/rule.md
Labels: Age: 🥚 - New

#6756 XS✔ ◾ Improved reading "minimize-unrelated-interruptions"
  rules/minimize-unrelated-interruptions/rule.md
Labels: Age: 🐓 - Old

#6773 XS✔ ◾ 3 pbi steps - Markdown typo
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#6774 XS✔ ◾ removed prefix + fixed bold "will not should"
  rules/use-will-not-should/rule.md
Labels: Age: 🥚 - New

#6698 XS✔ ◾ Modernized the rule
  rules/conduct-a-test-please/pic16-TestingDoYouWantThemT.gif
  rules/conduct-a-test-please/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6778 XS✔ ◾ Update rule - add Goldie as author
  rules/conduct-a-test-please/image.png
  rules/conduct-a-test-please/rule.md
Labels: Age: 🥚 - New

#6783 XS✔ ◾ Update and rename rule.md to rule.md "tree-of-thought-prompts-for-complex-reasoning"
  rules/tree-of-thought-prompts-for-complex-reasoning/rule.md
Labels: Age: 🥚 - New

#6780 XS✔ ◾ Rename and update some Rules to Better General Usability Practices
  categories/design-and-presentation/rules-to-better-interfaces-general-usability-practices.md
  rules/always-reduce-complexity/4visualoptions1.png
  rules/always-reduce-complexity/rule.md
  rules/always-reduce-complexity/simpleformsresolution.png
  rules/do-you-make-users-intuitively-know-how-to-use-something/rule.md
  rules/less-is-more-do-you-know-people-scan-not-read/rule.md
  rules/web-users-dont-read/delta-airline.png
  rules/web-users-dont-read/rule.md
Labels: Age: 🐤 - Mature

#6781 Create Rule “reflexion/rule”
  rules/reflexion/reflexionresults.png
  rules/reflexion/rule.md
Labels: Age: 🐥 - Adolescent

#6775 XS✔ ◾ Add a few missing bits
  rules/tree-of-thought-prompts-for-complex-reasoning/rule.md
Labels: Age: 🐤 - Mature

#6732 🗑️Archive best possible bug database Rule
  rules/build-the-backlog/rule.md
  rules/do-you-keep-the-best-possible-bug-database/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6757 XS✔ ◾ Improved title "start-answer-with-yes-or-no"
  rules/start-your-answer-with-yes-or-no-then-say-your-opinion/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6758 XS✔ ◾ Removed unrelated prefix + improved intro "update-delete-mistakes"
  rules/update-or-delete-mistakes/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6770 XS✔ ◾ Create rule.md
  categories/artificial-intelligence/rules-to-better-chatgpt-prompt-engineering.md
  rules/custom-instructions/custom-bad.png
  rules/custom-instructions/custom-good.png
  rules/custom-instructions/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6762 XS✔ ◾ make rule match last time's form
  rules/use-the-brains-of-your-company/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6779 XS✔ ◾ Update rule.md
  rules/follow-up-effectively/rule.md
Labels: Age: 🥚 - New, Age: 🐤 - Mature

#6785 XS✔ ◾ Update rule.md
  categories/artificial-intelligence/rules-to-better-chatgpt-prompt-engineering.md
  rules/reflexion/rule.md
Labels: Age: 🥚 - New

#6790 XS✔ ◾ add video
  rules/conduct-a-test-please/rule.md
Labels: Age: 🥚 - New

#6792 try quoting in the input for referenced images script to fix the workflow
  .github/workflows/check-images.yml
Labels: Age: 🐤 - Mature

#6788 Update Rule "Do you use the right site search for your website?"
  categories/management/rules-to-better-search.md
  categories/websites/rules-to-better-websites-development.md
  rules/use-right-site-search-for-your-website/rule.md
Labels: Age: 🐓 - Old

#6776 Update Rule “pc-do-you-organize-your-hard-disk/rule”
  rules/pc-do-you-organize-your-hard-disk/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6787 XS✔ ◾ Added Drawbacks to GTM rule
  rules/use-google-tag-manager/rule.md
Labels: Age: 🐓 - Old

#6786 XS✔ ◾ Add files via upload
  rules/follow-up-effectively/microsoft-todo-summary-page.jpg
  rules/follow-up-effectively/rule.md
  rules/follow-up-effectively/schedule-send-calendar.jpg
  rules/follow-up-effectively/schedule-send-tab.jpg
Labels: Age: 🐓 - Old

#6795 XS✔ ◾ Add files via upload
  rules/use-microsoft-teams-room/bad-example-too-many-cables.png
Labels: Age: 🥚 - New

#6794 XS✔ ◾ Add files via upload
  rules/use-microsoft-teams-room/Logitech-Rally-Bar-Switch-Tab.png
Labels: Age: 🥚 - New

#6796 XS✔ ◾ Update rule.md
  rules/use-microsoft-teams-room/rule.md
Labels: Age: 🥚 - New

#6777 Updated auth rule
  rules/choosing-authentication/auth.svg
  rules/choosing-authentication/diagram.md
  rules/choosing-authentication/external-auth-decision-flow.png
  rules/choosing-authentication/internal-auth-decision-flowv2.png
  rules/choosing-authentication/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6804 XS✔ ◾ Add cannot attend sprint review to the rules.md
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#6805 XS✔ ◾ ✨ Add new category - Rules to Better Content Design
  categories/communication/rules-to-better-technical-documentation.md
  categories/design-and-presentation/index.md
  categories/design-and-presentation/rules-to-better-content-design.md
  categories/design-and-presentation/rules-to-better-interfaces-general-usability-practices.md
  rules/avoid-acronyms/rule.md
  rules/avoid-full-stops-in-bullet-point-lists/rule.md
  rules/avoid-using-that-when-its-not-needed/rule.md
  rules/avoid-using-unnecessary-words/rule.md
  rules/concise-writing/rule.md
  rules/do-you-use-note-instead-of-nb/rule.md
  rules/use-active-phrases/rule.md
  rules/use-active-voice/rule.md
Labels: Age: 🥚 - New

#6746 📝Add intro to Rules to Better LINQ
  categories/software-development/rules-to-better-linq.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6809 XS✔ ◾ Update diagram.md
  rules/choosing-authentication/diagram.md
Labels: Age: 🥚 - New

#6802 XS✔ ◾ Encode text on use-async-await-for-all-io-bound-operations
  rules/use-async-await-for-all-io-bound-operations/rule.md
Labels: codeauditor fix, Age: 🐣 - Young

#6811 XS✔ ◾ Update and rename diagram.md to diagram.txt
  rules/choosing-authentication/diagram.txt
Labels: Age: 🥚 - New

#6810 Updating the Do you get your "PPTX Testers" to do a 'Test Please'? to specifically mention the Presentation Masters
  categories/communication/rules-to-better-powerpoint-presentations.md
  rules/ppt-test-please/rule.md
Labels: Age: 🐤 - Mature

#6807 XS✔ ◾ Rename how-to-add-quotations for clarity
  categories/communication/rules-to-better-technical-documentation.md
  rules/how-to-add-quotations/how-to-add-quote.jpg
  rules/style-quotations/bad-example-adding-quotations.jpg
  rules/style-quotations/good-example-adding-quotations.jpg
  rules/style-quotations/rule.md
Labels: Age: 🐤 - Mature

#6806 XS✔ ◾ Rename highlight-items-in-your-document for clarity of purpose
  categories/communication/rules-to-better-technical-documentation.md
  categories/design-and-presentation/rules-to-better-interfaces-general-usability-practices.md
  rules/distinguish-keywords-from-content/rule.md
Labels: Age: 🐤 - Mature

#6800 XS✔ ◾ Update rule.md
  rules/use-microsoft-teams-room/rule.md
Labels: Age: 🐓 - Old

#6816 XS✔ ◾ Adding screenshots of Notes in Teams meetings
  rules/creating-action-items/Meeting-Notes-Tasks.jpeg
  rules/creating-action-items/MicrosoftTeams-Meeting-Notes.jpeg
Labels: Age: 🥚 - New

#6821 XS✔ ◾ Update rules-to-better-power-apps.md
  categories/software-development/rules-to-better-power-apps.md
Labels: Age: 🥚 - New

#6812 XS✔ ◾ Code Auditor Scan - Fixed absolute internal Url
  rules/use-tasklists-in-your-pbis/rule.md
Labels: codeauditor fix, Age: 🐣 - Young

#6813 XS✔ ◾ Code Auditor Scan - Fixed absolute internal Url
  rules/escalate-key-updates/rule.md
Labels: codeauditor fix, Age: 🐣 - Young

#6825 XS✔ ◾ Fix Piers' name to fix image
  rules/reflexion/rule.md
Labels: Age: 🥚 - New

#6826 XS✔ ◾ Update rule.md
  rules/placeholder-for-replaceable-text/rule.md
Labels: Age: 🐤 - Mature

#6818 XS✔ ◾ Update rule.md
  rules/creating-action-items/rule.md
Labels: Age: 🐤 - Mature

#6814 XS✔ ◾ Update rule.md
  rules/follow-up-effectively/rule.md
Labels: Age: 🐤 - Mature

#6830 XS✔ ◾ Update rule.md
  rules/creating-action-items/rule.md
Labels: Age: 🥚 - New

#6833 XS✔ ◾ Update rules-to-better-power-apps.md
  categories/software-development/rules-to-better-power-apps.md
Labels: Age: 🥚 - New

#6824 ✨New Rule - "Do you keep Failed Requests clean?"
  categories/software-development/rules-to-better-application-insights.md
  categories/software-development/rules-to-better-devops.md
  rules/clean-failed-requests/bad-example-chart.png
  rules/clean-failed-requests/bad-example-table.png
  rules/clean-failed-requests/failed-requests-logs.png
  rules/clean-failed-requests/good-example-chart.png
  rules/clean-failed-requests/good-example-table.png
  rules/clean-failed-requests/rule.md
  rules/clean-failed-requests/send-to-workbook.png
Labels: Age: 🐓 - Old

#6844 XS✔ ◾ Do you keep Failed Requests clean? - change "spam" to "probing attempts"
  rules/clean-failed-requests/rule.md
Labels: Age: 🥚 - New

#6835 XS✔ ◾ New rule - Do you know users scan web content in an F-shaped pattern?
  categories/design-and-presentation/rules-to-better-content-design.md
  rules/f-shaped-pattern/F-shape-diagram.png
  rules/f-shaped-pattern/rule.md
  rules/web-users-dont-read/rule.md
Labels: Age: 🐓 - Old

#6842 XS✔ ◾ Fix email template formate.md
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🐣 - Young

#6828 XS✔ ◾ Made link a code + small improvements "sprint-forecast/"
  rules/sprint-forecast/rule.md
Labels: rubber stamp, Age: 🐓 - Old

#6843 Update Rule “entra-group-access-reviews/rule”
  rules/entra-group-access-reviews/rule.md
  rules/entra-group-access-reviews/screenshot-2023-09-27-094036.png
Labels: Age: 🥚 - New

#6827 ✨ Add Rules Frontmatter Validator
  .github/workflows/validate-frontmatter.yml
  scripts/frontmatter-validator/.gitignore
  scripts/frontmatter-validator/frontmatter-validator.js
  scripts/frontmatter-validator/package-lock.json
  scripts/frontmatter-validator/package.json
  scripts/frontmatter-validator/schema/category-schema.json
  scripts/frontmatter-validator/schema/rule-schema.json
  scripts/frontmatter-validator/schema/top-category-schema.json
Labels: code change, Age: 🍗 - Ancient, 🔥 Merge Debt

#6837 XS✔ ◾ Fixed examples + updated link + fixed Scrum term
  rules/do-you-document-the-technologies-design-patterns-and-alm-processes/rule.md
Labels: codeauditor fix, rubber stamp, Age: 🐓 - Old

#6847 Update rule "When should you train GPT?"
  rules/train-gpt/rule.md
Labels: Age: 🥚 - New

#6829 XS✔ ◾ Fixed Scrum term + other improvements "schedule-follow-up-spec-review"
  rules/do-you-schedule-a-followup-meeting-after-a-spec-review/rule.md
Labels: codeauditor fix, rubber stamp, Age: 🍗 - Ancient

#6849 XS⚠️ ◾ Update frontmatter-validator.js
  scripts/frontmatter-validator/frontmatter-validator.js
Labels: Age: 🥚 - New

#6851 XS✔ ◾ fix grey box format
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#6841 Update Rule “does-your-domain-have-power/rule”
  rules/does-your-domain-have-power/rule.md
Labels: Age: 🍗 - Ancient

#6855 XS✔ ◾ Improved content "fix-small-web-errors"
  rules/fix-small-web-errors/rule.md
Labels: Age: 🐥 - Adolescent

#6839 Update Rule “do-you-monitor-your-seo-effectively/rule”
  rules/do-you-monitor-your-seo-effectively/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6838 Update Rule “how-google-ranks-pages/rule”
  rules/how-google-ranks-pages/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#6861 XS✔ ◾ Added Next.js Consulting Page to preface of Rules to Better Next.js
  categories/websites/rules-to-better-nextjs.md
Labels: Age: 🥚 - New

#6862 Update image on “rubber-stamp-prs/rule”
  rules/rubber-stamp-prs/rubber-stamp-pr-label.png
  rules/rubber-stamp-prs/rule.md
Labels: Age: 🐓 - Old

#6860 ✨ Create new rule - Do you use embeddings?
  categories/artificial-intelligence/rules-to-better-gpt.md
  rules/use-embeddings/rule.md
  rules/use-embeddings/rules-2d-embeddings.png
Labels: Age: 🐓 - Old

#6868 XS✔ ◾ Update rule.md
  rules/request-a-test-please/rule.md
Labels: Age: 🥚 - New

#6864 XS✔ ◾ Added an extra example "minimize-unrelated-interruptions"
  rules/minimize-unrelated-interruptions/rule.md
Labels: Age: 🐥 - Adolescent

#6859 XS✔ ◾ Update rule close-thread
  rules/close-off-thread/close-thread.jpg
  rules/close-off-thread/rule.md
Labels: Age: 🐓 - Old

#6866 Update Rule “do-you-have-catering/rule”
  rules/do-you-have-catering/rule.md
Labels: Age: 🐥 - Adolescent

#6840 XS✔ ◾ Update rules-to-better-google-rankings-and-seo.md
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#6867 XS✔ ◾ Update rules-to-better-event-management.md
  categories/marketing-and-video/rules-to-better-event-management.md
Labels: Age: 🐥 - Adolescent

#6873 XS✔ ◾ Added "(copy of email)" to the top of email template
  rules/duplicate-email-content-in-a-calendar-appointment/rule.md
Labels: rubber stamp, Age: 🐓 - Old

#6872 XS✔ ◾ Relating and categorizing rules on fixing small issues straight away
  categories/management/rules-to-successful-projects.md
  rules/continual-improvement/rule.md
  rules/do-you-constantly-add-to-the-backlog/rule.md
  rules/fix-small-web-errors/rule.md
Labels: Age: 🐓 - Old

#6871 Done Video | Direct Attention | Examples
  rules/making-a-great-done-video/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt
