Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2023-08, with the labels that each got.

#6225 Fix Camilla photo in author section "best-hashtags"
  rules/find-the-best-hashtags/rule.md
Labels: rubber stamp

#6242 Update rules-to-better-websites-navigation.md
  categories/websites/rules-to-better-websites-navigation.md
Labels: rubber stamp

#6240 Update rules-to-better-marketing.md
  categories/marketing-and-video/rules-to-better-marketing.md
Labels: rubber stamp

#6235 Added redirect to "image-prompt"
  rules/write-an-image-prompt/rule.md
Labels: rubber stamp

#6234 Fixed broken link "generate-ai-image"
  rules/how-to-generate-an-ai-image/rule.md
Labels: codeauditor fix

#6236 Fixed internal links' paths "backlog-refinement"
  rules/backlog-refinement-meeting/rule.md
Labels: codeauditor fix

#6238 Fixed Landon image + improved readability "video-reduce-noise"
  rules/video-reduce-noise/rule.md
Labels: codeauditor fix

#6239 Fixed broken link "subcutaneous-tests"
  rules/subcutaneous-tests/rule.md
Labels: codeauditor fix

#6321 updated intro "happy-clients" category
  categories/management/rules-to-better-software-consultants-happy-clients.md
Labels: rubber stamp

#6297 Added related to rule "browser-add-branding"
  rules/browser-add-branding/rule.md
Labels: rubber stamp

#6334 Update Rule “do-you-look-for-duplicate-code/rule”
  rules/do-you-look-for-duplicate-code/rule.md
Labels: codeauditor fix

#6335 Update Rule “avoid-ui-in-event-names/rule”
  rules/avoid-ui-in-event-names/rule.md
Labels: codeauditor fix

#6336 Update Rule “change-the-connection-timeout-to-5-seconds/rule”
  rules/change-the-connection-timeout-to-5-seconds/rule.md
Labels: codeauditor fix

#6337 Update Rule “declare-member-accessibility-for-all-classes/rule”
  rules/declare-member-accessibility-for-all-classes/rule.md
Labels: codeauditor fix

#6338 Update Rule “do-your-validation-with-exit-sub/rule”
  rules/do-your-validation-with-exit-sub/rule.md
Labels: codeauditor fix

#6339 Update Rule “expose-events-as-events/rule”
  rules/expose-events-as-events/rule.md
Labels: codeauditor fix

#6340 Update Rule “follow-naming-conventions-for-your-boolean-property/rule”
  rules/follow-naming-conventions-for-your-boolean-property/rule.md
Labels: codeauditor fix

#6341 Update Rule “format-environment-newline-at-the-end-of-a-line/rule”
  rules/format-environment-newline-at-the-end-of-a-line/rule.md
Labels: codeauditor fix

#6345 Update Rule “pre-format-your-time-strings-before-using-timespan-parse/rule”
  rules/pre-format-your-time-strings-before-using-timespan-parse/rule.md
Labels: codeauditor fix

#6346 Update Rule “put-exit-sub-before-end-sub/rule”
  rules/put-exit-sub-before-end-sub/rule.md
Labels: codeauditor fix

#6347 Update Rule “put-optional-parameters-at-the-end/rule”
  rules/put-optional-parameters-at-the-end/rule.md
Labels: codeauditor fix

#6350 Update Rule “suffix-unit-test-classes-with-tests/rule”
  rules/suffix-unit-test-classes-with-tests/rule.md
Labels: codeauditor fix

#6358 Update Rule “use-string-empty-instead-of-quotes/rule”
  rules/use-string-empty-instead-of-quotes/rule.md
Labels: codeauditor fix

#6357 Update Rule “use-resource-file-to-store-messages/rule”
  rules/use-resource-file-to-store-messages/rule.md
Labels: codeauditor fix

#6333 Fixed link "defining-pbis"
  rules/defining-pbis/rule.md
Labels: codeauditor fix, rubber stamp

#6332 Fixed punctuation "backlog-refinement-meeting"
  rules/backlog-refinement-meeting/rule.md
Labels: rubber stamp

#6355 Update Rule “use-a-regular-expression-to-validate-an-uri/rule”
  rules/use-a-regular-expression-to-validate-an-uri/rule.md
Labels: codeauditor fix

#6356 Update Rule “use-environment-newline-to-make-a-new-line-in-your-string/rule”
  rules/use-environment-newline-to-make-a-new-line-in-your-string/rule.md
Labels: codeauditor fix

#6354 Update Rule “use-a-regular-expression-to-validate-an-email-address/rule”
  rules/use-a-regular-expression-to-validate-an-email-address/rule.md
Labels: codeauditor fix

#6348 Update Rule “refer-to-form-controls-directly/rule”
  rules/refer-to-form-controls-directly/rule.md
Labels: codeauditor fix

#6353 Update Rule “use-a-helper-extension-method-to-raise-events/rule”
  rules/use-a-helper-extension-method-to-raise-events/rule.md
Labels: codeauditor fix

#6342 Update Rule “initialize-variables-outside-of-the-try-block/rule”
  rules/initialize-variables-outside-of-the-try-block/rule.md
Labels: codeauditor fix

#6395 Update Rule “do-you-follow-up-course-attendees-for-consulting-work/rule”
  rules/do-you-follow-up-course-attendees-for-consulting-work/rule.md
Labels: codeauditor fix

#6396 Update Rule “how-to-send-newsletter-in-microsoft-crm-2016/rule”
  rules/how-to-send-newsletter-in-microsoft-crm-2016/rule.md
Labels: codeauditor fix

#6397 Update Rule “do-you-use-a-wizard-to-help-a-user-through-a-complicated-set-of-steps/rule”
  rules/do-you-use-a-wizard-to-help-a-user-through-a-complicated-set-of-steps/rule.md
Labels: codeauditor fix

#6405 Update Rule “best-trace-logging/rule”
  rules/best-trace-logging/rule.md
Labels: codeauditor fix

#6400 Update Rule “do-you-distribute-a-product-in-release-mode/rule”
  rules/do-you-distribute-a-product-in-release-mode/rule.md
Labels: codeauditor fix

#6402 Update Rule “do-you-know-the-common-design-principles-part-2-example/rule”
  rules/do-you-know-the-common-design-principles-part-2-example/rule.md
Labels: codeauditor fix

#6404 Update Rule “do-you-look-for-opportunities-to-use-linq/rule”
  rules/do-you-look-for-opportunities-to-use-linq/rule.md
Labels: codeauditor fix

#6398 Update Rule “submit-all-dates-to-sql-server-in-iso-format/rule”
  rules/submit-all-dates-to-sql-server-in-iso-format/rule.md
Labels: codeauditor fix

#6399 Update Rule “do-you-know-how-to-restore-your-content-database-to-sharepoint-2010/rule”
  rules/do-you-know-how-to-restore-your-content-database-to-sharepoint-2010/rule.md
Labels: codeauditor fix

#6403 Update Rule “do-you-start-reading-code/rule”
  rules/do-you-start-reading-code/rule.md
Labels: codeauditor fix
