Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-11, with the labels that each got.

#9508 Cms/stephanfakossw/ssw.rules.content/rule/maximize superannuation benefits/rule
  rules/maximize-superannuation-benefits/coumpound-interest-1.jpg
  rules/maximize-superannuation-benefits/coumpound-interest-2.jpg
  rules/maximize-superannuation-benefits/coumpound-interest-3.jpg
  rules/maximize-superannuation-benefits/rule.md
  rules/use-figma-dev-mode/figma-dev-mode.png
  rules/use-figma-dev-mode/figma-preview.png
  rules/use-figma-dev-mode/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9514 XS✔ ◾ Update rule.md
  rules/branding-is-more-than-logo/rule.md
Labels: Age: 🥚 - New

#9515 XS✔ ◾ update-loop-rule
  rules/keep-tasks-handy-for-calls/loop-tab-creation.jpg
  rules/keep-tasks-handy-for-calls/loop-tab-teams.jpg
  rules/keep-tasks-handy-for-calls/rule.md
Labels: Age: 🥚 - New

#9521 XS✔ ◾ adjust-markdown-for-image
  rules/keep-tasks-handy-for-calls/rule.md
Labels: Age: 🥚 - New

#9524 XS✔ ◾ Fixed caption + shorten URL + improved title "add-the-clientid-as-your-email-subject-prefix"
  categories/communication/rules-to-better-outsourcing.md
  rules/add-clientid-as-email-subject-prefix/rule.md
Labels: Age: 🥚 - New

#9511 XS✔ ◾ Small improvements to the rule /close-off-thread/
  rules/close-off-thread/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9525 XS✔ ◾ Too many list items, so changed to bold only
  rules/build-inter-office-interaction/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9532 XS✔ ◾ Create microsoft-planner-for-tasks
  rules/microsoft-planner-for-tasks
Labels: Age: 🥚 - New

#9531 XS⚠️ ◾ 🦺 Validator - Updated validator to flag fields with missing space
  scripts/frontmatter-validator/frontmatter-validator.js
Labels: Age: 🥚 - New

#9533 XS✔ ◾ Update rules-to-better-software-consultants-working-in-a-team.md
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
Labels: Age: 🐤 - Mature

#9528 XS✔ ◾ ✏️ Renamed file for rule 'Operations - Do you have a company compliance sheet?'
  rules/compliance-sheet/rule.md
Labels: Age: 🐓 - Old

#9538 XS✔ ◾ 🚚 moving file for rule 'microsoft-planner-for-tasks' to correct directory
  rules/microsoft-planner-for-tasks/rule.md
Labels: Age: 🥚 - New

#9536 XS✔ ◾ small changes from consistenct "wcag"
  rules/wcag-compliance/rule.md
Labels: Age: 🐣 - Young

#9543 🚧 WIP - Update meta descriptions tag rule
  rules/html-meta-tags/rule.md
Labels: Age: 🥚 - New

#9539 Update naming conventions
  categories/software-engineering/rules-to-better-naming-conventions.md
  rules/avoid-generic-names/rule.md
  rules/avoid-micro-jargon/rule.md
  rules/avoid-using-your-name-in-client-code/rule.md
  rules/consistent-words-for-concepts/rule.md
  rules/follow-naming-conventions/rule.md
  rules/use-clear-meaningful-names/rule.md
  rules/use-meaningful-modifiers/rule.md
  rules/use-nouns-for-class-names/rule.md
  rules/verbs-for-method-names/rule.md
  rules/when-to-use-technical-terms/rule.md
Labels: Age: 🐣 - Young

#9549 XS✔ ◾ Template - add SEO decription
  template/rule.md
Labels: Age: 🥚 - New

#9540 XS✔ ◾ Small improvemnents to rule references
  rules/rule/rule.md
Labels: Age: 🐓 - Old

#9553 XS✔ ◾ ⛓️‍💥 support-send-links: fixed link to tina docs
  rules/support-send-links/rule.md
Labels: Age: 🥚 - New

#9557 Update Rule “avoid-micro-jargon/rule”
  rules/avoid-micro-jargon/rule.md
Labels: Age: 🥚 - New

#9558 XS✔ ◾ ✏️ Added myself to the authors as I recorded the video
  rules/share-your-developer-secrets-securely/rule.md
Labels: Age: 🐓 - Old

#9564 Update Rule “share-your-developer-secrets-securely/rule”
  rules/share-your-developer-secrets-securely/rule.md
Labels: Age: 🥚 - New

#9560 XS✔ ◾ Screen recording - mention GIFs
  rules/recording-screen/rule.md
Labels: Age: 🐓 - Old

#9567 XS✔ ◾ update-email-rule-with-links
  rules/use-the-best-email-templates/rule.md
Labels: Age: 🥚 - New

#9569 XS✔ ◾ Improvements to rule on sharing secrets
  rules/share-your-developer-secrets-securely/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9570 Update Empty Rule - Novated Lease
  rules/salary-sacrifice-novated-lease/novated-how-it-works1.png
  rules/salary-sacrifice-novated-lease/rule.md
Labels: Age: 🐓 - Old

#9574 XS✔ ◾ Improved the Download experience for Little Book of Angular
  rules/the-best-learning-resources-for-angular/rule.md
Labels: Age: 🥚 - New

#9573 XS✔ ◾ Fixed line breaks + updated links on "Retro" rule
  rules/do-a-retrospective/rule.md
Labels: Age: 🐣 - Young

#9577 XS✔ ◾ Modular Monolith Testing Rule
  categories/software-engineering/rules-to-better-modular-monoliths.md
  rules/modular-monolith-testing/rule.md
Labels: Age: 🐤 - Mature

#9578 XS✔ ◾ adding-video-to-email-templates-rule
  rules/use-the-best-email-templates/rule.md
Labels: Age: 🥚 - New

#9582 XS✔ ◾ Improved rule wording "not-to-send-attachments-in-emails/"
  rules/do-you-know-not-to-send-attachments-in-emails/rule.md
Labels: Age: 🥚 - New

#9581 XS✔ ◾ Update rule.md "use-the-best-email-templates"
  rules/use-the-best-email-templates/rule.md
Labels: Age: 🥚 - New

#9583 XS✔ ◾ Static Sites - Add market share table
  rules/best-static-site-tech-stack/rule.md
Labels: Age: 🥚 - New

#9589 XS✔ ◾ Added missing title value to frontmatter
  rules/use-qr-codes-for-urls/rule.md
Labels: Age: 🥚 - New

#9590 XS✔ ◾ Adding another email template
  rules/weekly-ai-meetings/rule.md
Labels: Age: 🥚 - New

#9591 XS✔ ◾ Email templates - update video URL
  rules/use-the-best-email-templates/rule.md
Labels: Age: 🥚 - New

#9587 XS✔ ◾ Update rule.md "turn-emails-into-pbis/"
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🍗 - Ancient

#9592 XS✔ ◾ Adding image + 'share to anyone' recommendation
  rules/new-job-certification-linkedin/rule.md
  rules/new-job-certification-linkedin/share-with-anyone.jpg
Labels: Age: 🥚 - New

#9595 XS✔ ◾ Update rule.md
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🥚 - New

#9596 XS✔ ◾ Update rule.md
  rules/escalate-key-updates/rule.md
Labels: Age: 🥚 - New

#9598 XS✔ ◾ ✏️ Added video and authors
  rules/use-clear-meaningful-names/rule.md
Labels: Age: 🥚 - New

#9601 🖼️ Fixed broken image formatting: turn-emails-into-pbis
  rules/turn-emails-into-pbis/urgent-flowchart.png
Labels: Age: 🐤 - Mature

#9602 XS✔ ◾ Few improvements to "turn-emails-into-pbis"
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9603 XS✔ ◾ Adding a new task
  rules/linkedin-profile/rule.md
Labels: Age: 🥚 - New

#9604 XS✔ ◾ Improved the rule "links-or-attachments-in-emails"
  categories/communication/rules-to-better-email.md
  rules/links-or-attachments-in-emails/rule.md
Labels: Age: 🐥 - Adolescent

#9605 XS✔ ◾ Improvements to the "review-videos-collaboratively" rule
  rules/review-videos-collaboratively/rule.md
Labels: Age: 🐥 - Adolescent

#9606 XS✔ ◾ Improvements to "easy-questions" rule
  rules/do-you-use-the-voting-option-appropriately/rule.md
  rules/easy-questions/rule.md
Labels: Age: 🐥 - Adolescent

#9607 XS✔ ◾ Rule updates for CTF
  rules/use-clear-meaningful-names/rule.md
Labels: Age: 🥚 - New

#9609 XS✔ ◾ Update rule.md
  rules/how-to-do-keyword-planning/rule.md
Labels: Age: 🥚 - New

#9608 XS✔ ◾ Update rule.md
  rules/monitor-budget-and-track-spending-consistently/rule.md
Labels: Age: 🥚 - New

#9610 XS✔ ◾ rule updates for CTF
  rules/avoid-generic-names/rule.md
Labels: Age: 🥚 - New

#9611 XS✔ ◾ Rule changes for CTF
  rules/use-clear-meaningful-names/rule.md
Labels: Age: 🥚 - New

#9612 XS✔ ◾ rule updates for CTF
  rules/avoid-generic-names/rule.md
Labels: Age: 🥚 - New

#9613 Re-order category Rules to Better Naming Conventions
  categories/software-engineering/rules-to-better-naming-conventions.md
Labels: Age: 🥚 - New

#9616 XS✔ ◾ rule updates for ctf
  rules/use-nouns-for-class-names/rule.md
Labels: Age: 🐣 - Young

#9626 XS✔ ◾ Improved "avoid-your-name..." rule
  rules/avoid-using-your-name-in-client-code/rule.md
Labels: Age: 🥚 - New

#9614 XS✔ ◾ Update rule.md
  rules/have-a-bid-strategy-for-your-google-ads/rule.md
Labels: Age: 🐤 - Mature

#9625 XS✔ ◾ Improved "use-meaningful-modifiers" rule
  rules/use-meaningful-modifiers/rule.md
Labels: Age: 🥚 - New

#9624 XS✔ ◾ Improved "when-to-use-technical-terms" rule
  rules/when-to-use-technical-terms/rule.md
Labels: Age: 🥚 - New

#9623 XS✔ ◾ Improved "consistent-words-for-concepts" rule
  rules/consistent-words-for-concepts/rule.md
Labels: Age: 🐣 - Young

#9622 XS✔ ◾ Improved "avoid-micro-jargon" rule
  rules/avoid-micro-jargon/rule.md
Labels: Age: 🐣 - Young

#9621 XS✔ ◾ Improved "verbs-for-method-names" rule
  rules/verbs-for-method-names/rule.md
Labels: Age: 🐣 - Young

#9618 XS✔ ◾ Improvements to "use-clear-meaningful-names/" rule
  rules/use-clear-meaningful-names/rule.md
Labels: Age: 🐥 - Adolescent

#9619 XS✔ ◾ Improved "avoid-generic-names" rule
  rules/avoid-generic-names/rule.md
Labels: Age: 🐥 - Adolescent

#9620 XS✔ ◾ Improved "use-nouns-for-class-names" rule
  rules/use-nouns-for-class-names/rule.md
Labels: Age: 🐥 - Adolescent

#9627 XS✔ ◾ nouns for class names - fix date
  rules/nouns-for-class-names/rule.md
Labels: Age: 🥚 - New

#9629 XS✔ ◾ Backlog refinement - add video
  rules/backlog-refinement-meeting/rule.md
Labels: Age: 🥚 - New

#9631 XS✔ ◾ adding feedback advice
  rules/do-you-offer-specific-criticism/rule.md
Labels: Age: 🥚 - New
