Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-07, with the labels that each got.

#8811 XS✔ ◾ Fixed link words for "number-tasks-questions"
  rules/use-email-for-tasks-only/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8808 XS✔ ◾ Fixed greybox + other improvements "avoid-repetition" rule
  rules/avoid-repetition/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8813 XS✔ ◾ Fixed URL in manage-costs-azure
  rules/manage-costs-azure/rule.md
Labels: Age: 🥚 - New

#8814 XS✔ ◾ Updated where to keep your files rule
  rules/where-to-keep-your-files/Files-saved-on-Desktop.jpg
  rules/where-to-keep-your-files/Files-saved-on-SharePoint.jpg
  rules/where-to-keep-your-files/rule.md
Labels: Age: 🥚 - New

#8810 Create Rule “make-data-fields-obvious/rule”
  rules/make-data-fields-obvious/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8815 XS✔ ◾ Update rule Do you use meta description tags?
  rules/html-meta-tags/rule.md
Labels: Age: 🥚 - New

#8816 XS✔ ◾ Update Do you contact the media from time to time?
  rules/contact-the-media-from-time-to-time/rule.md
Labels: Age: 🥚 - New

#8820 XS✔ ◾ end-user-documentation
  rules/end-user-documentation/rule.md
Labels: Age: 🥚 - New

#8818 XS✔ ◾ Added-rule-authors
  rules/where-to-keep-your-files/rule.md
Labels: Age: 🐓 - Old

#8824 XS✔ ◾ ADT - update image
  rules/software-architecture-decision-tree/architecture-decision-tree-v2.jpg
  rules/software-architecture-decision-tree/architecture-decision-tree.jpg
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#8821 XS✔ ◾ Update Rule Styling
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#8827 XS✔ ◾ ♻️ Reword Proactive Testing Tip
  rules/conduct-a-test-please /good-first-impressions.png
  rules/conduct-a-test-please /rule.md
Labels: Age: 🥚 - New

#8819 Update Rule “do-you-understand-the-enterprise-mvc-request-process/rule”
  rules/do-you-understand-the-enterprise-mvc-request-process/rule.md
Labels: Age: 🍗 - Ancient

#8829 XS✔ ◾ handle redirects - remove duplicate content
  rules/handle-redirects/rule.md
Labels: Age: 🐤 - Mature

#8831 XS✔ ◾ Removed old links
  rules/use-nunit-to-write-unit-tests/rule.md
Labels: Age: 🥚 - New

#8830 XS✔ ◾ Fixed broken link
  rules/show-time-format-clearly/rule.md
Labels: Age: 🐣 - Young

#8832 XS✔ ◾ Added author, related + fixed category
  categories/communication/rules-to-better-powerpoint-presentations.md
  categories/communication/rules-to-better-presentations.md
  rules/do-you-keep-eye-contact-with-the-audience/rule.md
  rules/what-your-audience-sees-is-as-important-as-your-content/rule.md
Labels: Age: 🥚 - New

#8836 XS✔ ◾ ADRs - Add william
  rules/architectural-decision-records/rule.md
Labels: Age: 🥚 - New

#8837 ADRs - Embed video + Tiago's improvements
  rules/architectural-decision-records/rule.md
Labels: Age: 🐥 - Adolescent

#8835 Power BI Version Control Rules - Added Kosta as an author
  rules/do-you-know-powerbi-version-control-features/rule.md
  rules/do-you-use-version-control-with-power-bi/rule.md
Labels: Age: 🐤 - Mature

#8839 XS✔ ◾ Fix video
  rules/architectural-decision-records/rule.md
Labels: Age: 🥚 - New

#8840 XS✔ ◾ Fixed typo in architectural-decision-records
  rules/architectural-decision-records/rule.md
Labels: Age: 🥚 - New

#8844 try to fix broken markdown
  rules/when-to-email-chat-call-or-meet/rule.md
Labels: Age: 🥚 - New

#8843 XS✔ ◾ Fix rules formatting
  rules/have-a-definition-of-ready/rule.md
Labels: Age: 🥚 - New

#8841 Added image “architectural-decision-records/rule”
  rules/architectural-decision-records/rule.md
  rules/architectural-decision-records/ssw-clean-architecture-template-adr.png
Labels: Age: 🥚 - New

#8842 XS✔ ◾ Add related blog post to .NET migration rules
  rules/why-upgrade-to-latest-dotnet/rule.md
Labels: Age: 🥚 - New

#8846 Cms/penny walker/ssw.rules.content/rule/new job certification linkedin/rule
  rules/new-job-certification-linkedin/mscert.jpg
  rules/new-job-certification-linkedin/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8849 XS✔ ◾ Fixed links + captions
  rules/sharepoint-flat-hierarchy/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8850 XS✔ ◾ Fixed links
  rules/3-steps-to-a-pbi/rule.md
  rules/prevent-users-from-running-two-instances-of-your-application/rule.md
  rules/streamline-development-with-npm-and-task-runners/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8852 XS✔ ◾ Added redirect
  rules/problem-steps-recorder/rule.md
Labels: Age: 🥚 - New

#8851 XS✔ ◾ Removed broken link
  rules/upgrade-your-laptop/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8855 XS✔ ◾ ✨ Create Why Blazor is great Rule
  categories/software-engineering/rules-to-better-blazor.md
  rules/why-blazor-is-great/rule.md
Labels: Age: 🥚 - New

#8856 XS✔ ◾ ✨ Create Why Angular is great Rule
  categories/software-engineering/rules-to-better-angular.md
  rules/why-angular-is-great/rule.md
  rules/why-blazor-is-great/rule.md
Labels: Age: 🥚 - New

#8847 Update Rule “unsolicited-feedback/rule”
  rules/unsolicited-feedback/rule.md
Labels: Age: 🐓 - Old

#8858 XS✔ ◾ Add new rule
  categories/software-engineering/rules-to-better-power-apps.md
  rules/build-cost-effective-power-apps/rule.md
Labels: Age: 🥚 - New

#8854 Create Rule “risks-of-deploying-on-fridays/rule”
  rules/risks-of-deploying-on-fridays/risks-of-deploying-on-fridays.png
  rules/risks-of-deploying-on-fridays/rule.md
Labels: Age: 🐣 - Young

#8853 Create Rule “organize-terminal-sessions-with-panes/rule”
  rules/organize-terminal-sessions-with-panes/multiple-windows.jpg
  rules/organize-terminal-sessions-with-panes/one-window.jpg
  rules/organize-terminal-sessions-with-panes/rule.md
Labels: Age: 🐣 - Young

#8861 XS✔ ◾ Backlog refinement - removed duplicated content
  rules/backlog-refinement-meeting/rule.md
Labels: Age: 🥚 - New

#8863 XS✔ ◾ Remove field that doesn't exist
  rules/commitment-to-health-and-safety/rule.md
  rules/organize-terminal-sessions-with-panes/rule.md
  rules/respect-and-protect-human-labor-rights/rule.md
  rules/support-community-indigenous-engagement/rules.md
Labels: Age: 🥚 - New

#8860 XS✔ ◾ Update rules-to-better-command-lines.md
  categories/software-engineering/rules-to-better-command-lines.md
Labels: Age: 🐥 - Adolescent

#8859 XS✔ ◾ Update rules-to-successful-projects.md
  categories/company-operations/rules-to-successful-projects.md
Labels: Age: 🐥 - Adolescent

#8848 Create Rule “angular-reactive-forms-vs-template-driver-forms/rule”
  rules/angular-reactive-forms-vs-template-driver-forms/rule.md
Labels: Age: 🐓 - Old

#8864 XS✔ ◾ Fix frontmatter
  rules/support-community-indigenous-engagement/rules.md
Labels: Age: 🐣 - Young

#8868 XS✔ ◾ Fixed title and lists of Pros and Cons "migrating-legacy-frontend-to-net8"
  rules/migrating-legacy-frontend-to-net8/rule.md
Labels: Age: 🥚 - New

#8870 XS✔ ◾ Fix potentially bad markdown
  rules/best-practices-environmental-sustainability/rule.md
  rules/send-done-videos/rule.md
Labels: Age: 🥚 - New

#8869 XS✔ ◾ making headings and lists standard "/audit-ad"
  rules/audit-ad/rule.md
Labels: Age: 🥚 - New

#8867 XS✔ ◾ Fixed link + title "Migrating Web Apps to .NET"
  rules/migrating-web-apps-to-dotnet/rule.md
Labels: Age: 🥚 - New

#8866 XS✔ ◾ Replaced broken link with content from ChatGPT
  rules/4-quadrants-important-and-urgent/rule.md
Labels: Age: 🥚 - New

#8871 XS✔ ◾ Update Backlog refinement
  rules/backlog-refinement-meeting/rule.md
Labels: Age: 🥚 - New

#8874 XS✔ ◾ Update rules-to-better-angular.md
  categories/software-engineering/rules-to-better-angular.md
Labels: Age: 🐤 - Mature

#8876 Updated rule 'Do you organize your terminal sessions using Windows Terminal panes?'
  rules/organize-terminal-sessions-with-panes/rule.md
Labels: Age: 🐤 - Mature

#8877 XS✔ ◾ Create-rule-monitor-external-reviews
  categories/marketing-and-video/rules-to-better-social-media-for-business.md
  rules/monitor-external-reviews/rule.md
Labels: Age: 🐤 - Mature

#8878 XS✔ ◾ Added Tiago as author
  rules/video-background/rule.md
Labels: Age: 🥚 - New

#8865 Create Rule “google-search-console-vs-google-analytics/rule”
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  rules/google-search-console-vs-google-analytics/rule.md
Labels: Age: 🐓 - Old

#8873 Updated rule 'Do you understand the risks of deploying on Fridays?'
  rules/risks-of-deploying-on-fridays/rule.md
Labels: Age: 🐓 - Old

#8881 XS✔ ◾ Improved readability "backlog-refinement-meeting"
  rules/backlog-refinement-meeting/rule.md
Labels: Age: 🥚 - New

#8882 Create Rule “annual-employment-retro/rule”
  categories/company-operations/rules-to-better-business-management.md
  rules/annual-employment-retro/rule.md
Labels: Age: 🐥 - Adolescent

#8883 Do you have a Product Backlog refinement meeting? - Added description for backlog refinement process
  rules/backlog-refinement-meeting/rule.md
Labels: Age: 🥚 - New

#8885 XS✔ ◾ non-Scrum roles rule - make placeholders shouty again
  rules/know-the-non-scrum-roles/rule.md
Labels: Age: 🥚 - New

#8886 brainstorming agenda - fix email
  rules/brainstorming-agenda/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8884 XS✔ ◾ backlog refinement meeting - change prescription for number of PBIs to refine
  rules/backlog-refinement-meeting/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8889 XS✔ ◾ Problem Steps Recorder - Try fix links
  rules/problem-steps-recorder/rule.md
Labels: Age: 🐤 - Mature

#8888 XS✔ ◾ Dones - Add more stuff to include
  rules/include-useful-details-in-emails/rule.md
Labels: Age: 🐓 - Old

#8892 XS✔ ◾ Fix rules broken format
  rules/escalate-key-updates/rule.md
Labels: Age: 🥚 - New

#8894 employment retro - fix extra field
  rules/annual-employment-retro/rule.md
Labels: Age: 🥚 - New

#8895 XS✔ ◾ Update rules-to-better-business-management.md
  categories/company-operations/rules-to-better-business-management.md
Labels: Age: 🥚 - New

#8896 XS✔ ◾ Update rule.md
  rules/annual-employment-retro/rule.md
Labels: Age: 🥚 - New

#8897 XS✔ ◾ chore: Update Problem Steps Recorder deprecation information
  rules/problem-steps-recorder/rule.md
Labels: Age: 🥚 - New

#8898 📝 Create Rule "Do you use dynamic viewport units"
  categories/software-engineering/rules-to-better-apps-mobile.md
  categories/software-engineering/rules-to-better-websites-development.md
  rules/progressive-web-app/rule.md
  rules/use-dynamic-viewport-units/dvu-bad-example.png
  rules/use-dynamic-viewport-units/dvu-browser-compatibility.png
  rules/use-dynamic-viewport-units/dvu-good-example.png
  rules/use-dynamic-viewport-units/rule.md
Labels: Age: 🐥 - Adolescent

#8893 Update Rule “store-your-secrets-securely/rule”
  rules/store-your-secrets-securely/rule.md
Labels: Age: 🐤 - Mature

#8891 XS✔ ◾ escalate dones - Add calling to the rule
  rules/escalate-key-updates/rule.md
Labels: Age: 🐤 - Mature

#8890 XS✔ ◾ updated-rule-use-the-best-email-templates
  rules/use-the-best-email-templates/rule.md
Labels: Age: 🐓 - Old

#8900 XS✔ ◾ 🔧Fixing incorrectly written md hyperlink
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#8903 XS✔ ◾ new rule awesome-readme
  rules/awesome-readme/rule.md
Labels: Age: 🥚 - New

#8906 XS✔ ◾ adding rule to category for CTF
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  rules/awesome-readme/rule.md
Labels: Age: 🥚 - New

#8908 XS✔ ◾ Update slide-master-do-you-have-your-logo-and-tag-line-at-the-bottom
  rules/slide-master-do-you-have-your-logo-and-tag-line-at-the-bottom/rule.md
Labels: Age: 🐤 - Mature

#8909 XS✔ ◾ Made link descriptive + moved good after bad "awesome-readme"
  rules/awesome-readme/rule.md
Labels: Age: 🐥 - Adolescent

#8901 XS✔ ◾ Improved rule readability + standards "scrum-in-github/"
  rules/scrum-in-github/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8902 XS✔ ◾ Removed backlink
  rules/do-you-calculate-payroll-tax-correctly/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8912 XS✔ ◾ Fixed heading + placeholders "technical-debt"
  rules/technical-debt/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8916 XS✔ ◾ New rule phone number on forms
  categories/client-engagement/rules-to-better-sales.md
  rules/follow-up-online-leads-phone-call/online-form-with-phone-number-mandatory.jpg
  rules/follow-up-online-leads-phone-call/online-form-with-phone-number-not-mandatory.jpg
  rules/follow-up-online-leads-phone-call/online-form-without-phone-number-field.jpg
  rules/follow-up-online-leads-phone-call/rule.md
Labels: Age: 🐤 - Mature

#8918 Update rule.md
  rules/follow-up-online-leads-phone-call/rule.md
Labels: Age: 🥚 - New

#8919 XS✔ ◾ Update rule.md
  rules/follow-up-online-leads-phone-call/rule.md
Labels: Age: 🥚 - New

#8914 XS✔ ◾ new rule - handle unhappy paths
  categories/software-engineering/rules-to-better-code.md
  rules/handle-unhappy-paths/bad-no-validaton.png
  rules/handle-unhappy-paths/good-validation-fields.png
  rules/handle-unhappy-paths/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8917 XS✔ ◾ New rule - Cookie Consent Banner Documentation
  rules/do-you-have-a-cookie-banner/dev-tools-cookie.jpg
  rules/do-you-have-a-cookie-banner/rule.md
  rules/do-you-have-a-cookie-banner/tina-cookie-banner.jpg
  rules/do-you-have-a-cookie-banner/tina-cookie-modal.jpg
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8922 Adding bad and good examples to awesome readme
  rules/awesome-readme/bad-example-gordonbeemingcom.jpg
  rules/awesome-readme/bad-example-pistriker.jpg
  rules/awesome-readme/good-example-sswcleanarchitecture.jpg
  rules/awesome-readme/good-example-tinacms.jpg
  rules/awesome-readme/rule.md
Labels: Age: 🥚 - New

#8923 XS✔ ◾ update title to get rid of 404 image
  rules/do-you-have-a-cookie-banner/rule.md
Labels: Age: 🥚 - New

#8921 XS✔ ◾ Database Performance Techniques
  categories/software-engineering/rules-to-better-sql-databases-performance.md
  rules/sqlperf-avoid-implicit-type-conversions/rule.md
  rules/sqlperf-avoid-looping/rule.md
  rules/sqlperf-join-over-where/rule.md
  rules/sqlperf-minimise-large-writes/rule.md
  rules/sqlperf-reduce-table-size/rule.md
  rules/sqlperf-select-required-columns/rule.md
  rules/sqlperf-too-many-joins/rule.md
  rules/sqlperf-top-for-sampling/rule.md
  rules/sqlperf-use-and-instead-of-or/rule.md
  rules/sqlperf-verify-indexes-used/rule.md
  rules/sqlperf-wildcards/rule.md
Labels: Age: 🐓 - Old

#8920 XS✔ ◾ Database indexing rules
  categories/software-engineering/index.md
  categories/software-engineering/rules-to-better-sql-databases-indexing.md
  rules/sql-indexing-joins/rule.md
  rules/sql-indexing-orderby/rule.md
  rules/sql-indexing-testing/rule.md
  rules/sql-indexing-where/rule.md
  rules/sql-real-world-indexes/rule.md
Labels: Age: 🍗 - Ancient

#8930 XS✔ ◾ Improved captions examples
  rules/add-useful-and-concise-figure-captions/rule.md
Labels: Age: 🐥 - Adolescent

#8933 Update Rule “attention-to-detail/rule”
  rules/attention-to-detail/rule.md
Labels: Age: 🐓 - Old

#8937 Spelling fix - Tools - Do you know what Angular Tools to install for an Angular project?
  rules/angular-the-stuff-to-install/rule.md
Labels: Age: 🥚 - New

#8932 XS✔ ◾ Updated-rule-follow-up-online-leads
  rules/follow-up-online-leads-phone-call/rule.md
Labels: Age: 🐓 - Old

#8929 XS✔ ◾ added video time length
  rules/roadmap/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8938 XS✔ ◾ Update rules-to-better-video-recording.md
  categories/marketing-and-video/rules-to-better-video-recording.md
Labels: Age: 🐣 - Young

#8940 XS✔ ◾ Fix formatting in 'Are you always candid in your communication?'
  rules/are-you-candid-in-your-communication/rule.md
Labels: Age: 🥚 - New

#8941 XS✔ ◾ Moves 'Call SysAdmins' rule to better category
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  categories/infrastructure-and-networking/rules-to-better-system-administrators.md
Labels: Age: 🥚 - New

#8942 Rename rules.md to rule.md
  rules/support-community-indigenous-engagement/rule.md
Labels: Age: 🥚 - New

#8939 Update Rule “why-angular-is-great/rule”
  rules/why-angular-is-great/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8936 Update Rule “disaster-recovery-plan/rule”
  rules/disaster-recovery-plan/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8948 XS✔ ◾ Update rules-to-better-security.md
  categories/infrastructure-and-networking/rules-to-better-security.md
Labels: Age: 🥚 - New

#8950 XS✔ ◾ Update rules-to-better-office-operations.md
  categories/company-operations/rules-to-better-office-operations.md
Labels: Age: 🐤 - Mature

#8949 XS✔ ◾ Update rules-to-better-business-management.md
  categories/company-operations/rules-to-better-business-management.md
Labels: Age: 🐤 - Mature

#8945 Update Rule “respect-and-protect-human-labor-rights/rule”
  rules/respect-and-protect-human-labor-rights/rule.md
Labels: Age: 🐓 - Old

#8872 Create Rule “software-engineers-should-only-roll-forward/rule”
  categories/project-delivery/rules-to-better-continuous-deployment-with-tfs.md
  rules/do-you-only-roll-forward/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8935 XS✔ ◾ Added an image to make the rule nicer
  categories/software-engineering/rules-to-better-sql-databases-indexing.md
  rules/sql-automatic-index-tuning/rule.md
  rules/sql-real-world-indexes/index.png
  rules/sql-real-world-indexes/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8951 XS✔ ◾ Added image to technical debt rule
  rules/technical-debt/rule.md
  rules/technical-debt/technical-debt-graph.png
Labels: Age: 🥚 - New

#8953 XS✔ ◾ share product improvements - Embed tweet
  rules/share-product-improvements/rule.md
Labels: Age: 🥚 - New

#8955 XS✔ ◾ Improved readability on rule 'event-storming-workshop'
  rules/event-storming-workshop/rule.md
Labels: Age: 🐥 - Adolescent

#8958 XS✔ ◾ Make image a bit smaller
  rules/spec-do-you-create-an-initial-release-plan-and-ballpark/rule.md
Labels: Age: 🥚 - New

#8928 XS✔ ◾ Cookie Banner rule feedback
  categories/software-engineering/rules-to-better-website-development-asp-net.md
  rules/do-you-have-a-cookie-banner/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8957 Update Rule “do-you-avoid-replying-to-all-when-you-are-only-bcced/rule”
  rules/do-you-avoid-replying-to-all-when-you-are-only-bcced/replyall.jpg
  rules/do-you-avoid-replying-to-all-when-you-are-only-bcced/rule.md
Labels: Age: 🐤 - Mature

#8961 XS✔ ◾ Made looong heading be an info box "avoid heading 1 in content"
  rules/rule/rule.md
Labels: Age: 🐣 - Young

#8956 XS✔ ◾ Fixed links on rule "evaluate processes"
  rules/do-you-evaluate-the-processes/rule.md
Labels: Age: 🐓 - Old

#8962 XS✔ ◾ Update Sprint Review Retro email with summary video link
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#8963 XS✔ ◾ Update Sprint Planning email with summary video link
  rules/sprint-forecast/rule.md
Labels: Age: 🥚 - New
