Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-01, with the labels that each got.

#7662 XS✔ ◾ Add related rules
  rules/definition-of-done/rule.md
  rules/done-do-you-know-when-to-send-a-done-email-in-scrum/rule.md
  rules/dones-do-you-reply-done-and-delete-the-original-email/rule.md
Labels: Age: 🥚 - New

#7663 XS✔ ◾ Update rule images and authors
  rules/when-to-email-chat-call-or-meet/rule.md
Labels: Age: 🥚 - New

#7665 XS✔ ◾ Fix the urls being wrong.
  categories/software-development/index.md
  rules/sql-server-cpu-pressure/rule.md
  rules/sql-server-io-pressure/rule.md
  rules/sql-server-memory-pressure/rule.md
  rules/use-the-right-data-storage/rule.md
Labels: Age: 🥚 - New

#7667 XS✔ ◾ Update rules-to-better-contractors.md
  categories/management/rules-to-better-contractors.md
Labels: Age: 🥚 - New

#7668 XS✔ ◾ Adding new Figma Category
  categories/design-and-presentation/index.md
  categories/design-and-presentation/rules-to-better-figma.md
Labels: Age: 🥚 - New

#7669 XS✔ ◾ Fixing WCAG rule uri
  categories/design-and-presentation/rules-to-better-accessibility.md
Labels: Age: 🥚 - New

#7670 XS✔ ◾ Fix headings in wcag-compliance rule
  rules/wcag-compliance/rule.md
Labels: Age: 🥚 - New

#7671 XS✔ ◾ Update '8 Steps to Scrum' link
  rules/do-you-have-a-war-room-summary/rule.md
Labels: Age: 🐤 - Mature

#7673 XS✔ ◾ Update '8 Steps to Scrum' image and PDF
  rules/8-steps-to-scrum/8StepstoScrum.png
  rules/8-steps-to-scrum/rule.md
Labels: Age: 🥚 - New

#7676 XS✔ ◾ Make 1 line clearer
  rules/follow-boy-scout-rule/rule.md
Labels: Age: 🥚 - New

#7678 XS✔ ◾ Update Contact before work rule and add related rules
  categories/management/rules-to-better-sales.md
  rules/do-you-enter-into-a-binding-written-contract-with-a-client-before-doing-any-billable-work/rule.md
  rules/do-you-treat-freebies-as-real-customers/rule.md
Labels: Age: 🥚 - New

#7674 Create Rule “figma-prototypes/rule”
  rules/figma-prototypes/User-Cards.jpg
  rules/figma-prototypes/rule.md
Labels: Age: 🐣 - Young

#7682 XS✔ ◾ Find meetings easily - add link to this rule
  rules/do-you-make-your-team-meetings-easy-to-find/rule.md
Labels: Age: 🐥 - Adolescent

#7677 XS✔ ◾ Shorten uri and lowercase zz
  categories/management/rules-to-successful-projects.md
  rules/how-to-name-documents/rule.md
  rules/zz-files/rule.md
Labels: Age: 🐤 - Mature

#7685 XS✔ ◾ Updates to DRY rule
  rules/avoid-repetition/rule.md
Labels: Age: 🥚 - New

#7683 XS✔ ◾ Added info that file names are not changes for public files
  rules/show-version-numbers/rule.md
Labels: Age: 🥚 - New

#7686 XS✔ ◾ trying to fix email template broken by CMS
  rules/checked-by-xxx/rule.md
Labels: Age: 🥚 - New

#7687 XS✔ ◾ "Explaining -" prefix to 2 rules
  rules/add-context-reasoning-to-emails/rule.md
  rules/zooming-in-and-out/rule.md
Labels: Age: 🥚 - New

#7689 XS✔ ◾ Improved context and reasoning rule
  rules/add-context-reasoning-to-emails/rule.md
Labels: Age: 🥚 - New

#7688 XS✔ ◾ Updated Ask for Help formatting
  rules/ask-for-help/rule.md
Labels: Age: 🥚 - New

#7681 XS✔ ◾ Update rule.md
  rules/do-you-know-when-to-branch-in-git/rule.md
Labels: Age: 🐓 - Old

#7698 XS✔ ◾ handover - add a few things
  rules/do-you-know-how-to-handover-a-project/rule.md
Labels: Age: 🥚 - New

#7699 XS✔ ◾ Handovers - add line about project dashboards
  rules/do-you-know-how-to-handover-a-project/rule.md
Labels: Age: 🥚 - New

#7692 XS✔ ◾ Update answer im in order rule
  rules/answer-im-questions-in-order/rule.md
Labels: Age: 🐤 - Mature

#7700 XS✔ ◾ Fixed link https://www.ssw.com.au/rules/spelling-do-you-use-us-english/
  rules/do-you-use-american-spelling-for-your-website/rule.md
Labels: Age: 🥚 - New

#7702 XS✔ ◾ Fixed some punctuation
  rules/business-continuity-services/rule.md
Labels: Age: 🥚 - New

#7701 XS✔ ◾ Update and rename rule.md to rule.md /hand-over
  categories/management/rules-to-successful-projects.md
  rules/hand-over/rule.md
Labels: Age: 🥚 - New

#7703 XS✔ ◾ fixed capitalization for consistency
  rules/hand-over/rule.md
Labels: rubber stamp, Age: 🥚 - New

#7704 XS✔ ◾ Added /centralize-downloadable-files to category + small improvements + updated /structured-website
  categories/websites/rules-to-better-websites-development.md
  rules/centralize-downloadable-files/rule.md
  rules/structured-website/rule.md
Labels: Age: 🥚 - New

#7705 XS✔ ◾ Rename rule.me to rule.md
  rules/tax-invoice-vs-eftpos-receipt/rule.md
Labels: Age: 🥚 - New

#7709 XS✔ ◾ Update rule.md
  rules/separate-messages/rule.md
Labels: Age: 🥚 - New

#7710 XS✔ ◾ ✨ New rule "Do you meet color contrast requirements for accessibility?"
  categories/design-and-presentation/rules-to-better-accessibility.md
  rules/best-practices-around-colour/rule.md
  rules/color-contrast/color-contrast-bad.jpg
  rules/color-contrast/color-contrast-good.jpg
  rules/color-contrast/rule.md
Labels: Age: 🥚 - New

#7711 XS✔ ◾ 💚 fix frontmatter
  rules/tax-invoice-vs-eftpos-receipt/rule.md
Labels: Age: 🥚 - New

#7706 Updated email examples in rule to make it clearer
  rules/hand-over/rule.md
Labels: Age: 🐥 - Adolescent

#7707 Added bus test rule
  categories/management/rules-to-successful-projects.md
  rules/bus-test/rule.md
Labels: Age: 🐥 - Adolescent

#7712 XS✔ ◾ Added 3 more authors (Adam, Daniel M and Brady) to the rule
  rules/gather-data-from-company-emails/rule.md
Labels: Age: 🥚 - New

#7715 XS✔ ◾ Update 'zz' rule to include 'yy' - bis
  rules/zz-files/rule.md
Labels: Age: 🥚 - New

#7713 XS✔ ◾ Adding related rule
  rules/do-you-know-when-to-branch-in-git/rule.md
Labels: Age: 🐣 - Young

#7696 XS✔ ◾ Update rule.md
  rules/connect-client-im/Teams-image.png
  rules/connect-client-im/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7714 XS✔ ◾ Adding rule to rules-to-better-github
  categories/software-development/rules-to-better-github.md
Labels: Age: 🐣 - Young

#7718 XS✔ ◾ Update Daily Scrum rule to relate unblocking
  rules/methodology-daily-scrums/rule.md
  rules/when-to-email-chat-call-or-meet/rule.md
Labels: Age: 🐤 - Mature

#7726 XS✔ ◾ Fixed Spelling - Do you simplify breadcrumbs?
  rules/simplify-breadcrumbs/rule.md
Labels: Age: 🥚 - New

#7721 XS✔ ◾ Create autocorrect-in-outlook
  categories/communication/rules-to-better-outlook.md
  rules/autocorrect-in-outlook/Outlook-image-uly.png
  rules/autocorrect-in-outlook/rule.md
  rules/connect-client-im/rule.md
Labels: Age: 🐓 - Old

#7723 Include ADRs in rule/awesome-documentation
  rules/awesome-documentation/rule.md
Labels: Age: 🐤 - Mature

#7725 XS✔ ◾ Relate rules + improve URIs
  categories/application-lifecycle-management-alm/rules-to-better-scrum.md
  categories/communication/rules-to-better-email.md
  categories/communication/rules-to-better-inbox-management.md
  rules/close-pbis-with-context/rule.md
  rules/reply-done-and-delete-the-email/rule.md
  rules/when-to-send-a-done-email-in-scrum/rule.md
Labels: Age: 🐣 - Young

#7728 XS✔ ◾ Update rule.md
  categories/communication/rules-to-better-email.md
  rules/autocorrect-in-outlook/rule.md
  rules/meeting-bookings/rule.md
Labels: Age: 🥚 - New

#7730 XS✔ ◾ Update rule.md
  rules/autocorrect-in-outlook/rule.md
Labels: Age: 🥚 - New

#7731 XS✔ ◾ Adding related rule to rule for writing rules
  rules/use-chatgpt-to-write-a-rule/rule.md
Labels: Age: 🥚 - New

#7733 Update rule.md
  rules/autocorrect-in-outlook/rule.md
Labels: Age: 🥚 - New

#7734 XS✔ ◾ New rule - Do you know when to use the ampersand?
  categories/design-and-presentation/rules-to-better-content-design.md
  rules/ampersand/rule.md
  rules/avoid-common-mistakes/rule.md
Labels: Age: 🥚 - New

#7732 Update the broken link in the rule 'have-tests-for-performance'
  rules/do-you-avoid-reviewing-performance-without-metrics/rule.md
Labels: Age: 🥚 - New

#7727 XS✔ ◾ fix-frontmatter
  rules/autocorrect-in-outlook/rule.md
Labels: rubber stamp, Age: 🐥 - Adolescent

#7738 Removed extra space
  rules/close-pbis-with-context/rule.md
Labels: rubber stamp, Age: 🥚 - New

#7739 XS✔ ◾ Updated Related + Improved readability with lists
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#7741 XS✔ ◾ Ae cher ssw patch 7
  categories/communication/rules-to-better-email.md
  rules/autocorrect-in-outlook/rule.md
  rules/meeting-bookings/rule.md
Labels: Age: 🥚 - New

#7742 XS✔ ◾ Fix broken link in Ampersand rule
  rules/ampersand/rule.md
Labels: Age: 🥚 - New

#7743 XS✔ ◾ Correct invalid archive links
  rules/avoid-using-that-when-its-not-needed/rule.md
  rules/continually-improve-ui/rule.md
  rules/control-choice-do-you-use-bold-on-the-main-options-to-make-them-clearer/rule.md
  rules/do-you-always-get-your-rules-proof-read/rule.md
  rules/do-you-avoid-the-first-person-narrative/rule.md
  rules/do-you-choose-tfs-git-over-team-foundation-source-control/rule.md
  rules/do-you-have-a-demo-script-for-your-sprint-review-meeting/rule.md
  rules/do-you-have-a-mobile-friendly-website1/rule.md
  rules/do-you-highlight-incomplete-work-with-red-text/rule.md
  rules/do-you-know-the-best-way-of-booking-flights/rule.md
  rules/do-you-know-the-correct-way-to-develop-data-entry-forms/rule.md
  rules/do-you-know-to-slideshare-your-powerpoint-before-the-presentation/rule.md
  rules/do-you-know-what-a-story-owner-is-responsible-for/rule.md
  rules/do-you-know-when-to-versus-and-verses/rule.md
  rules/do-you-label-your-example-with-a-tick-cross-followed-by-the-word-figure/rule.md
  rules/do-you-make-sure-every-customers-and-prospects-email-is-in-your-company-database/rule.md
  rules/do-you-name-your-assemblies-consistently-companyname-componentname/rule.md
  rules/do-you-pursue-short-or-long-term-relationships-with-clients/rule.md
  rules/do-you-send-out-an-email-summary-after-each-meeting/rule.md
  rules/do-you-underline-links-and-include-a-rollover/rule.md
  rules/do-you-use-a-single-general-bit-ly-account-for-all-shortening-in-your-company-department/rule.md
  rules/do-you-use-and-indentation-to-keep-the-context/rule.md
  rules/do-you-use-exploratory-testing-to-create-acceptance-tests/rule.md
  rules/do-you-use-expression-blend-sketchflow-to-create-mock-ups/rule.md
  rules/do-you-use-hibernate/rule.md
  rules/do-you-use-note-instead-of-nb/rule.md
  rules/do-you-use-setfocusonerror-on-controls-that-fail-validation/rule.md
  rules/do-you-use-the-search-tool-to-find-emails-in-outlook/rule.md
  rules/does-your-applications-interface-fit-in-a-small-screen-resolution/rule.md
  rules/generate-ai-images/rule.md
  rules/less-is-more-do-you-realize-that-when-it-comes-to-interface-design-less-is-more/rule.md
  rules/management-do-you-use-xp-scrum-wisely/rule.md
  rules/maximum-row-size-for-a-table/rule.md
  rules/meetings-do-you-ask-clients-the-two-important-questions-at-the-beginning-of-each-meeting/rule.md
  rules/never-share-passwords/rule.md
  rules/post-production-do-you-add-content-to-youtube-to-feed-traffic-to-your-other-sites/rule.md
  rules/production-do-you-know-the-best-way-to-end-a-video/rule.md
  rules/the-right-mobile-tool-for-the-job/rule.md
  rules/transcribe-videos/rule.md
  rules/use-net-maui/rule.md
  rules/use-setup-and-set-up-correctly/rule.md
  rules/use-taskbar-instead-of-task-bar/rule.md
  rules/use-username-instead-of-user-name/rule.md
  rules/using-field-validation/rule.md
  rules/when-to-use-react/rule.md
Labels: Age: 🥚 - New

#7729 XS✔ ◾ Ai in UI design
  categories/artificial-intelligence/rules-to-better-gpt.md
  rules/do-you-use-ai-for-ui/rule.md
Labels: Age: 🍗 - Ancient

#7748 XS✔ ◾ Updated list of benefits and examples - the value of consistency
  rules/the-value-of-consistency/rule.md
Labels: Age: 🥚 - New

#7744 XS✔ ◾ Added intro and other improvements to /mentoring-programs
  rules/mentoring-programs/rule.md
Labels: Age: 🐥 - Adolescent

#7747 XS✔ ◾ Fixed bold + improved title and code examples
  categories/design-and-presentation/rules-to-better-interfaces-forms.md
  categories/websites/rules-to-better-websites-development.md
  rules/use-html-maxlength-to-limit-number-of-characters/rule.md
Labels: Age: 🐣 - Young

#7746 XS✔ ◾ added missing full stop + improved sentence
  rules/design-to-improve-your-google-ranking/rule.md
Labels: rubber stamp, Age: 🐣 - Young

#7754 Update rule.md
  rules/do-you-use-ai-for-ui/rule.md
Labels: Age: 🥚 - New

#7756 Update rules-to-better-accounting.md
  categories/management/rules-to-better-accounting.md
Labels: Age: 🥚 - New

#7755 XS✔ ◾ Update rules-to-better-entity-framework.md
  categories/software-development/rules-to-better-entity-framework.md
Labels: Age: 🥚 - New

#7761 XS✔ ◾ Updating related links for mockups
  rules/generate-ui-mockups-with-ai/rule.md
  rules/mockups-and-prototypes/rule.md
  rules/storyboards/rule.md
Labels: Age: 🥚 - New

#7749 XS✔ ◾ Missing ) in the rule
  rules/definition-of-done/rule.md
Labels: Age: 🐤 - Mature

#7751 XS✔ ◾ Updated TFS to GitHub/Azure DevOps
  rules/do-you-know-the-best-ways-to-keep-track-of-your-time/rule.md
Labels: Age: 🐤 - Mature

#7752 XS✔ ◾ Changed from ancient check-in comments to modern commit messages
  categories/management/rules-to-better-timesheets.md
  rules/how-to-describe-the-work-you-have-done/rule.md
Labels: Age: 🐤 - Mature

#7753 XS✔ ◾ Changed archaic "check in" with modern "commit"
  rules/tasks-when-you-check-in-code-and-associate-it-to-a-task/rule.md
Labels: Age: 🐤 - Mature

#7763 XS✔ ◾ Made links descriptive
  rules/the-team-do-you-help-your-scrum-master-not-scrummaster-protect-and-serve-the-team/rule.md
Labels: Age: 🥚 - New

#7765 XS✔ ◾ Update rule.md
  rules/generate-ui-mockups-with-ai/rule.md
Labels: Age: 🥚 - New

#7766 Update rule/Awesome documentation
  rules/awesome-documentation/rule.md
Labels: Age: 🥚 - New

#7745 XS✔ ◾ Fixed code examples markdown /anchor-names
  rules/chose-efficient-anchor-names/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7736 XS✔ ◾ Improvements to code review prefixes
  rules/use-prefixes-to-improve-code-review-communication/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7769 XS✔ ◾ Update rule.md
  rules/tax-invoice-vs-eftpos-receipt/rule.md
Labels: Age: 🐤 - Mature

#7772 XS✔ ◾ Delete rules/email-do-you-use-the-best-backup-solution/goodexamplebac…
  rules/email-do-you-use-the-best-backup-solution/goodexamplebackups2.jpg
Labels: Age: 🥚 - New

#7773 XS✔ ◾ Update rules-to-better-backups.md
  categories/infrastructure-and-networking/rules-to-better-backups.md
Labels: Age: 🐣 - Young

#7774 XS✔ ◾ Add rule for gpt store
  categories/artificial-intelligence/rules-to-better-gpt.md
  rules/do-you-monetize-your-gpt-model/rule.md
Labels: Age: 🥚 - New

#7775 Update Screenshot for "Do you use and indicate Draft Pull Requests"
  rules/create-draft-pull-requests/github-bad-example.png
  rules/create-draft-pull-requests/github-good-example.png
  rules/create-draft-pull-requests/github-wip.png
Labels: Age: 🐣 - Young

#7776 XS✔ ◾ add context that it isn't only PBIs
  rules/close-pbis-with-context/rule.md
Labels: Age: 🥚 - New

#7779 XS✔ ◾ Update author title to fix profile image
  rules/do-you-know-how-to-configure-yarp/rule.md
Labels: Age: 🥚 - New

#7780 XS✔ ◾ Update rule.md
  rules/use-design-time-data/rule.md
Labels: Age: 🥚 - New

#7778 XS✔ ◾ Update rule.md
  rules/use-mvvm-pattern/rule.md
Labels: Age: 🥚 - New

#7781 XS✔ ◾ CodeAuditor - Fix broken link
  rules/the-value-of-consistency/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#7789 XS✔ ◾ Fixed absolute internal Urls
  rules/ampersand/rule.md
  rules/autocorrect-in-outlook/rule.md
  rules/bus-test/rule.md
  rules/do-you-make-your-team-meetings-easy-to-find/rule.md
  rules/flexible-working-hours/rule.md
  rules/how-to-view-changes-made-to-a-sharepoint-page/rule.md
  rules/meeting-bookings/rule.md
  rules/meetings-do-you-know-the-agenda-for-the-initial-meeting/rule.md
  rules/monitor-packages-for-vulnerabilities/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7788 XS✔ ◾ Remove link to Design Time Data rule
  rules/use-hot-reload/rule.md
Labels: Age: 🥚 - New

#7790 XS✔ ◾ New rule: prefix-job-title
  categories/marketing-and-video/rules-to-better-branding.md
  rules/prefix-job-title/job-title-bad.jpg
  rules/prefix-job-title/job-title-good.jpg
  rules/prefix-job-title/rule.md
Labels: Age: 🥚 - New

#7792 XS✔ ◾ Small improvements
  rules/prefix-job-title/rule.md
Labels: Age: 🥚 - New

#7793 XS✔ ◾ NextJS rule to fetch data - Update sentence to have actions in order
  rules/fetch-data-nextjs/rule.md
  rules/fetch-data-react/rule.md
Labels: Age: 🥚 - New

#7794 XS✔ ◾ adding screenshot to rule
  rules/prefix-job-title/excel-result.png
  rules/prefix-job-title/rule.md
Labels: Age: 🥚 - New

#7786 XS✔ ◾ added info about custom GPT benefits
  rules/do-you-monetize-your-gpt-model/rule.md
Labels: Age: 🐓 - Old

#7798 XS✔ ◾ is RAG is good
  rules/do-you-monetize-your-gpt-model/rule.md
Labels: Age: 🥚 - New

#7799 Adding v0.dev as a mockup tool
  rules/software-for-ux-design/rule.md
Labels: Age: 🥚 - New

#7784 XS✔ ◾ Update rule.md
  rules/optimize-android-builds-and-start-up-times/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7787 XS✔ ◾ Migration tools update
  rules/tools-database-schema-changes/rule.md
  rules/use-code-migrations/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7795 Update SSW Rule - Tax invoice vs Eftpos Receipt - Improve context
  rules/tax-invoice-vs-eftpos-receipt/rule.md
  rules/tax-invoice-vs-eftpos-receipt/tax-invoice-example-au.1678919047955.avif
  rules/tax-invoice-vs-eftpos-receipt/tax-invoice-example-au.1678919047955.jpg
Labels: Age: 🐓 - Old

#7800 XS✔ ◾ fix monetize-gpt-models rule
  rules/monetize-gpt-models/rule.md
Labels: Age: 🥚 - New

#7802 XS✔ ◾ Re-wrote rule on "Sign in"
  categories/communication/rules-to-better-technical-documentation.md
  rules/user-authentication-terms/rule.md
  rules/when-to-use-log-on-log-in-and-sign-in/rule.md
Labels: Age: 🥚 - New

#7803 XS✔ ◾ Rules to better reporting services - Delete duplicate rule
  rules/do-you-know-the-5-user-experiences-of-reporting-services-vanilla-website-email-windows-and-sharepoint/rule.md
  rules/five-user-experiences-of-reporting-services/EmailUExample.jpg
  rules/five-user-experiences-of-reporting-services/ReportingServicesEmailUExample.jpg
  rules/five-user-experiences-of-reporting-services/ReportingServicesSharePointReportingUI.jpg
  rules/five-user-experiences-of-reporting-services/ReportingServicesVanillaExample.jpg
  rules/five-user-experiences-of-reporting-services/ReportingServicesWebsiteUExample.jpg
  rules/five-user-experiences-of-reporting-services/ReportingServicesWindowsUExample.jpg
  rules/five-user-experiences-of-reporting-services/SharePointReportingServices.jpg
  rules/five-user-experiences-of-reporting-services/VanillaExample.jpg
  rules/five-user-experiences-of-reporting-services/WebsiteUExample.jpg
  rules/five-user-experiences-of-reporting-services/WindowsUExample.jpg
  rules/five-user-experiences-of-reporting-services/rule.md
Labels: Age: 🥚 - New

#7808 Create Rule “modular-monoliths/rule”
  categories/software-development/index.md
  categories/software-development/rules-to-better-microservices.md
  categories/software-development/rules-to-better-modular-monoliths
  rules/modular-monoliths/rule.md
Labels: Age: 🥚 - New

#7809 XS✔ ◾ Rename rules-to-better-modular-monoliths to rules-to-better-modular-m…
  categories/software-development/rules-to-better-modular-monoliths.md
Labels: rubber stamp, Age: 🥚 - New

#7810 Update Rule “build-a-yes-ladder-to-your-outbound-script/rule”
  rules/build-a-yes-ladder-to-your-outbound-script/rule.md
Labels: Age: 🥚 - New

#7811 Update Rule “azure-budgets/rule”
  rules/azure-budgets/rule.md
Labels: Age: 🥚 - New

#7813 XS✔ ◾ Ben0189 replace old vb file screenshot
  rules/zz-files/rule.md
  rules/zz-files/zz-file-example.png
Labels: Age: 🐤 - Mature

#7812 XS✔ ◾ Change 'ZZ' to 'zz'
  rules/how-to-prepare-before-migration/rule.md
Labels: Age: 🐤 - Mature

#7806 XS✔ ◾ Rules to better reporting services - Combine duplicate rules
  categories/reporting-solutions/rules-to-better-reporting-services.md
  rules/do-you-know-when-to-use-reporting-services/RSRulesUseRS1.gif
  rules/do-you-know-when-to-use-reporting-services/rule.md
  rules/when-to-use-reporting-services/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7805 Update Rule “do-you-encourage-daily-exercise-at-work/rule”
  rules/do-you-encourage-daily-exercise-at-work/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7814 XS✔ ◾ Improved title and removed unrelated link from related section
  rules/do-you-show-your-phone-number-in-skype/rule.md
Labels: Age: 🥚 - New

#7675 XS✔ ◾ Update Rules about using email for Sprint Review/Retro
  rules/github-sprint-templates/rule.md
  rules/groups-in-microsoft-365/rule.md
  rules/sprint-review-retro-email/ReleaseBurnup.jpg
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7815 XS✔ ◾ Fixed link to Penny's profile
  rules/do-you-take-advantage-of-business-rewards-programs/rule.md
Labels: rubber stamp, Age: 🥚 - New

#7816 XS✔ ◾ Rename folder and URI for MAUI rule
  categories/software-development/rules-to-better-maui.md
  rules/the-best-maui-resources/rule.md
Labels: Age: 🥚 - New

#7797 XS✔ ◾ Archived Xamarin rule that doesn't matter to MAUI
  categories/software-development/rules-to-better-maui.md
  rules/the-best-way-to-manage-assets-in-xamarin/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7817 XS✔ ◾ adding example to rule
  rules/prefix-job-title/rule.md
Labels: Age: 🥚 - New

#7818 XS✔ ◾ New rule: linkedin-profile
  rules/linkedin-profile/good-linkedin.jpg
  rules/linkedin-profile/rule.md
Labels: Age: 🥚 - New

#7820 XS✔ ◾ adding rule to category and small improvements
  categories/marketing-and-video/rules-to-better-social-media-personal.md
  rules/linkedin-profile/good-linkedin.jpg
  rules/linkedin-profile/rule.md
Labels: Age: 🐤 - Mature

#7821 XS✔ ◾ General improvements
  rules/prefix-job-title/rule.md
Labels: Age: 🥚 - New

#7822 XS✔ ◾ updating rule - linkedin profile
  rules/linkedin-profile/good-linkedin.jpg
  rules/linkedin-profile/rule.md
Labels: Age: 🥚 - New

#7823 updateRule/format-new-lines
  rules/format-new-lines/rule.md
Labels: Age: 🥚 - New

#7825 XS✔ ◾ update linkedin rule
  rules/linkedin-profile/rule.md
Labels: Age: 🐣 - Young

#7826 XS✔ ◾ Fix frontmatter error
  rules/build-a-yes-ladder-to-your-outbound-script/rule.md
Labels: rubber stamp, Age: 🥚 - New

#7829 XS✔ ◾ CodeAuditor - Fixed absolute internal links
  rules/how-to-justify-your-rates/rule.md
  rules/linkedin-profile/rule.md
  rules/use-design-time-data/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7828 XS✔ ◾ CodeAuditor - Fix broken content
  rules/do-you-have-a-witadmin-script-to-import-work-item-definitions/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7831 XS✔ ◾ Change NodeJS to JavaScript/TypeScript
  rules/automated-ui-testing/rule.md
Labels: Age: 🥚 - New

#7770 XS✔ ◾ Updated rule - added good and bad example images for framing.
  rules/making-a-great-done-video/BadExample-framing.jpeg
  rules/making-a-great-done-video/GoodExample-framing.jpeg
  rules/making-a-great-done-video/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7833 XS✔ ◾ CodeAuditor - Fix syntax error
  rules/linkedin-profile/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7835 XS✔ ◾ Fixed email template in azure budget rule
  rules/azure-budgets/rule.md
Labels: Age: 🥚 - New

#7839 XS✔ ◾ Added related rule in azure budgets rule
  rules/azure-budgets/rule.md
Labels: Age: 🥚 - New

#7838 XS✔ ◾ Git-based CMS solutions
  categories/websites/rules-to-better-websites-development.md
  rules/do-you-know-the-best-cms-solutions-for-websites/rule.md
  rules/git-based-cms-solutions/rule.md
Labels: Age: 🥚 - New, Age: 🐥 - Adolescent

#7836 XS✔ ◾ Added mass transit rule
  categories/software-development/rules-to-better-architecture-and-code-review.md
  categories/software-development/rules-to-better-microservices.md
  categories/software-development/rules-to-better-modular-monoliths.md
  rules/use-mass-transit/rule.md
Labels: Age: 🐤 - Mature

#7840 Update Rule “do-you-have-a-good-page-speed/rule”
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  rules/do-you-have-a-good-page-speed/rule.md
  rules/website-page-speed/rule.md
Labels: Age: 🐣 - Young

#7832 New Rule - Do you know how to allocate the expenses to the offices?
  categories/management/rules-to-better-accounting.md
  rules/allocate-expenses-per-office/rule.md
  rules/allocate-the-expenses-to-the-offices/Allocate-expense-1.jpg
  rules/allocate-the-expenses-to-the-offices/Allocate-expense-1.png
  rules/allocate-the-expenses-to-the-offices/Allocate-expense-2.jpg
  rules/allocate-the-expenses-to-the-offices/keep-yourself-connected-3.png
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7830 XS✔ ◾ Asher LinkedIn company pages
  rules/automate-reply-messages/linkedin-more.png
  rules/automate-reply-messages/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7827 XS✔ ◾ CodeAuditor - Fixed broken link with wrong redirect
  categories/marketing-and-video/rules-to-better-outbound-calls.md
  rules/harnessing-the-power-of-no/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#7854 XS✔ ◾ Update and rename rule.md to rule.md
  rules/reply-linkedin-messages/rule.md
Labels: Age: 🥚 - New

#7858 XS✔ ◾ Fixing weird sentences
  rules/git-based-cms-solutions/rule.md
Labels: Age: 🥚 - New

#7844 XS✔ ◾ Remove unneeded bullets
  rules/use-mass-transit/rule.md
Labels: Age: 🐓 - Old

#7859 XS✔ ◾ Added async checking section to "Checked by" rule
  rules/checked-by-xxx/rule.md
Labels: Age: 🥚 - New

#7863 XS✔ ◾ Improved sentence on async checked
  rules/checked-by-xxx/rule.md
Labels: Age: 🥚 - New

#7866 XS✔ ◾ New rule: linkedin-job-experience
  categories/marketing-and-video/rules-to-better-social-media-personal.md
  rules/linkedin-contact-info/rule.md
  rules/linkedin-job-experience/linkedin-media-bad.jpg
  rules/linkedin-job-experience/linkedin-media-good.jpg
  rules/linkedin-job-experience/rule.md
  rules/linkedin-profile/rule.md
Labels: Age: 🥚 - New

#7872 Update Rule "Do you use screenshots instead of a 'Wall of Text'?"
  rules/screenshots-avoid-walls-of-text/ArrowBadExample.png
  rules/screenshots-avoid-walls-of-text/ArrowGoodExample.png
  rules/screenshots-avoid-walls-of-text/rule.md
Labels: Age: 🥚 - New

#7869 XS✔ ◾ Added redirect found by Google
  rules/sql-server-io-pressure/rule.md
Labels: Age: 🐥 - Adolescent

#7837 XS✔ ◾ CodeAuditor - Fix and Remove multiple broken links
  rules/add-multilingual-support-on-angular/rule.md
  rules/do-a-quick-test-after-the-upgrade-finishes-tfs2010-migration/rule.md
  rules/do-you-integrate-crm-with-microsoft-lync/rule.md
  rules/do-you-know-how-to-book-better-flights/rule.md
  rules/do-you-know-the-common-design-principles-part-1/rule.md
  rules/great-email-signatures/rule.md
  rules/hand-over/rule.md
  rules/high-level-migration-plan/rule.md
  rules/label-your-assets/rule.md
  rules/power-bi-choosing-the-right-visual/rule.md
  rules/technical-overview/rule.md
  rules/the-best-dependency-injection-container/rule.md
  rules/why-should-a-business-use-tiktok/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#7865 XS✔ ◾ Ben0189 patch 1
  rules/have-a-definition-of-ready/PBI-with-DOR.png
  rules/have-a-definition-of-ready/rule.md
Labels: Age: 🐓 - Old

#7874 XS✔ ◾ Improved title and intro "break messages" rule
  rules/separate-messages/rule.md
Labels: Age: 🥚 - New

#7875 XS✔ ◾ CodeAuditor - Fixed broken image
  rules/label-your-assets/asset-tracking.jpg
  rules/label-your-assets/rule.md
Labels: Age: 🥚 - New

#7876 XS✔ ◾ CodeAuditor - Fix absolute internal path
  rules/linkedin-profile/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7877 XS✔ ◾ Update rule.md
  rules/do-you-create-a-migration-plan/rule.md
Labels: Age: 🥚 - New

#7879 XS✔ ◾ Update rules-to-better-zendesk.md
  categories/products/rules-to-better-zendesk.md
Labels: Age: 🥚 - New

#7881 XS✔ ◾ Update rules-to-better-zendesk.md
  categories/products/rules-to-better-zendesk.md
Labels: Age: 🥚 - New
