Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-08, with the labels that each got.

#8964 XS✔ ◾ Index rule - add good and bad examples
  rules/sql-real-world-indexes/rule.md
Labels: Age: 🥚 - New

#8965 XS✔ ◾ Mention SQL Server 2022
  rules/sql-automatic-index-tuning/rule.md
Labels: Age: 🥚 - New

#8966 XS✔ ◾ Using strong tag in heading changes the text to red
  rules/rule/rule.md
Labels: Age: 🐥 - Adolescent

#8968 XS✔ ◾ Fixed greyboxes
  rules/do-you-know-the-benefits-of-using-source-control/rule.md
  rules/give-clients-a-warm-welcome/rule.md
  rules/make-numbers-more-readable/rule.md
  rules/remove-spaces-from-your-folders-and-filename/rule.md
  rules/rule/rule.md
  rules/use-will-not-should/rule.md
  rules/useful-information-on-changes/rule.md
Labels: rubber stamp, Age: 🥚 - New

#8967 XS✔ ◾ Improved intro + content design on rule "database-indexes"
  rules/sql-real-world-indexes/rule.md
Labels: Age: 🐥 - Adolescent

#8972 XS✔ ◾ Correct formatting of table in Sprint Review Retro template
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#8973 Correct formatting of info box on Sprint Forecast email
  rules/sprint-forecast/rule.md
Labels: Age: 🥚 - New

#8970 XS✔ ◾ Fixed more greyboxes
  rules/acceptance-criteria/rule.md
  rules/answer-im-questions-in-order/rule.md
  rules/avoid-deleting-records-by-flagging-them-as-isdeleted/rule.md
  rules/backup-your-databases-tfs2010-migration/rule.md
  rules/client-love-after-initial-meeting/rule.md
  rules/cloud-architect/rule.md
  rules/contract-before-work/rule.md
  rules/dev-mobile-device-policy/rule.md
  rules/do-a-retrospective/rule.md
  rules/do-you-document-the-technologies-design-patterns-and-alm-processes/rule.md
  rules/do-you-have-a-dress-code/rule.md
  rules/do-you-know-the-right-source-control-to-use/rule.md
  rules/enterprise-password-manager-auditing/rule.md
  rules/make-numbers-more-readable/rule.md
  rules/package-audit-log/rule.md
  rules/password-complexities/rule.md
  rules/prefix-on-blog-posts-titles/rule.md
  rules/prioritize-performance-optimization-for-maximum-business-value/rule.md
  rules/project-setup/rule.md
  rules/uncover-hidden-anchor-client/rule.md
  rules/use-emojis/rule.md
  rules/when-to-use-state-management-in-angular/rule.md
Labels: Age: 🥚 - New

#8971 XS✔ ◾ Update rule.md
  rules/sql-automatic-index-tuning/rule.md
Labels: Age: 🥚 - New

#8974 XS✔ ◾ DB indexes - embed video
  rules/sql-real-world-indexes/rule.md
Labels: Age: 🥚 - New

#8975 XS✔ ◾ Migrate old rules for better reporting services - Part 3/4
  rules/avoid-showing-empty-reports/RSRulesNoEmptyReportT07.jpg
  rules/avoid-showing-empty-reports/RSRulesNoEmptyReportT10.jpg
  rules/avoid-showing-empty-reports/RSRulesNoEmptyReportT11.jpg
  rules/avoid-showing-empty-reports/RSRulesNoEmptyReportT7.jpg
  rules/avoid-showing-empty-reports/RSRulesNoEmptyReportT8.gif
  rules/avoid-showing-empty-reports/RSRulesNoEmptyReportT9.jpg
  rules/avoid-showing-empty-reports/rule.md
  rules/avoid-unnecessary-words-in-parameter/BadParameterlabelBad.png
  rules/avoid-unnecessary-words-in-parameter/BadParameterlabelGood.png
  rules/avoid-unnecessary-words-in-parameter/rule.md
  rules/cache-popular-reports/RSCachedSnapshot.gif
  rules/cache-popular-reports/rule.md
  rules/consistent-parameter-names/ParameterName_Bad.gif
  rules/consistent-parameter-names/ParameterName_Good.gif
  rules/consistent-parameter-names/rule.md
  rules/create-separate-virtual-directory-for-admin-access/RSVirtualDirectory.gif
  rules/create-separate-virtual-directory-for-admin-access/rule.md
  rules/date-format-of-parameters/DateFormat_Parameter.jpg
  rules/date-format-of-parameters/DateFormat_Parameter_2.gif
  rules/date-format-of-parameters/rule.md
  rules/ensure-language-follows-user-regional-settings/RSRulesLanguage1.jpg
  rules/ensure-language-follows-user-regional-settings/RSRulesLanguage2.jpg
  rules/ensure-language-follows-user-regional-settings/RSRulesLanguage3.jpg
  rules/ensure-language-follows-user-regional-settings/RSRulesLanguage4.jpg
  rules/ensure-language-follows-user-regional-settings/rule.md
  rules/language-rule-exception-for-currency-fields/RSCurrency_bad.gif
  rules/language-rule-exception-for-currency-fields/RSCurrency_good_au.gif
  rules/language-rule-exception-for-currency-fields/RSCurrency_good_cn.gif
  rules/language-rule-exception-for-currency-fields/RSCurrency_good_expression.gif
  rules/language-rule-exception-for-currency-fields/RSCurrency_sample_au.gif
  rules/language-rule-exception-for-currency-fields/RSCurrency_sample_cn.gif
  rules/language-rule-exception-for-currency-fields/rule.md
  rules/remove-executiontime-in-subscription-email-subject/RSRulesRemoveTimeNew.gif
  rules/remove-executiontime-in-subscription-email-subject/RSRulesRemoveTimeOld.gif
  rules/remove-executiontime-in-subscription-email-subject/rule.md
  rules/schedule-snapshots-of-slow-reports/KBQ1119699_2.gif
  rules/schedule-snapshots-of-slow-reports/rule.md
  rules/use-date-time-data-type/RSRulesUseDateTimeType1.jpg
  rules/use-date-time-data-type/RSRulesUseDateTimeType2.jpg
  rules/use-date-time-data-type/rule.md
  rules/use-de-normalized-database-fields-for-calculated-values/RSRulesCalculatedBad.gif
  rules/use-de-normalized-database-fields-for-calculated-values/RSRulesCalculatedBest.gif
  rules/use-de-normalized-database-fields-for-calculated-values/RSRulesCalculatedBetter.gif
  rules/use-de-normalized-database-fields-for-calculated-values/rule.md
  rules/use-intergrated-security-for-payroll-reports/RSRulesPayRollByUserIDT1.jpg
  rules/use-intergrated-security-for-payroll-reports/RSRulesPayRollByUserIDT2.jpg
  rules/use-intergrated-security-for-payroll-reports/RSRulesPayRollByUserIDT3.jpg
  rules/use-intergrated-security-for-payroll-reports/rule.md
  rules/use-regional-friendly-formatting/RSCurrencyFormatBad.jpg
  rules/use-regional-friendly-formatting/RSCurrencyFormatGood.jpg
  rules/use-regional-friendly-formatting/RSNumberFormatBad.jpg
  rules/use-regional-friendly-formatting/RSNumberFormatGood.jpg
  rules/use-regional-friendly-formatting/RSPercentageFormatBad.jpg
  rules/use-regional-friendly-formatting/RSPercentageFormatGood.jpg
  rules/use-regional-friendly-formatting/rule.md
  rules/use-sql-ranking-functions/RS_SQLRank.gif
  rules/use-sql-ranking-functions/rule.md
  rules/validate-all-reports/ReportsValidator.gif
  rules/validate-all-reports/ValidatorLink.gif
  rules/validate-all-reports/rule.md
Labels: Age: 🥚 - New, Age: 🐣 - Young

#8946 Create Rule "change-date-of-existing-commit/rule"
  categories/project-delivery/rules-to-better-version-control-with-git.md
  rules/change-date-of-existing-commit/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8976 XS✔ ◾ indexes - fix typo, add space
  rules/sql-real-world-indexes/rule.md
Labels: Age: 🐤 - Mature

#8925 Create Rule “use-autopod-for-editing-multi-camera-interviews/rule”
  rules/use-autopod-for-editing-multi-camera-interviews/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8980 XS✔ ◾ Fixed image syntax + wording
  rules/do-you-provide-a-high-level-project-progress-report-for-clients/rule.md
Labels: Age: 🥚 - New

#8979 XS✔ ◾ Removed broken links
  rules/fixed-price-deliver-the-project-and-start-the-warranty-period/rule.md
  rules/fixed-price-transition-back-to-time-and-materials-at-the-end-of-the-warranty-period/rule.md
  rules/make-sure-you-use-a-consistent-collation-server-wide/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8983 XS✔ ◾ Added SSRS rules to category
  categories/company-operations/rules-to-better-reporting-services.md
Labels: Age: 🥚 - New

#8981 XS✔ ◾ Removed old archived broken links
  rules/tasks-do-you-know-to-ensure-that-relevant-emails-are-attached-to-tasks/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#8978 XS✔ ◾ Merged 2 spelling rules
  rules/are-you-careful-with-your-spelling-grammar-and-punctuation/outlook-spelling.png
  rules/are-you-careful-with-your-spelling-grammar-and-punctuation/rule.md
  rules/do-you-use-spelling-and-grammar-checker-to-make-your-email-professional/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8977 XS✔ ◾ Fixed broken links
  categories/design/rules-to-better-interfaces-popups-and-messages.md
  categories/project-delivery/rules-to-better-version-control-with-git.md
  rules/dates-do-you-use-calendar-controls-effectively/rule.md
  rules/do-you-avoid-bmps-for-the-internet-at-all-times/rule.md
  rules/do-you-first-get-your-cluster-and-san-going/rule.md
  rules/do-you-know-how-to-resolve-the-broken-links-caused-by-page-renaming/rule.md
  rules/dones-do-you-reply-done-using-team-companion-when-using-tfs/rule.md
  rules/information-intelligence-wisdom/rule.md
  rules/re-purpose-your-pillar-content-for-social-media/rule.md
  rules/use-both-english-spelling-on-google-ads/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#8986 Update Rule “ups-send-email/rule”
  rules/ups-send-email/rule.md
Labels: Age: 🐤 - Mature

#8984 XS✔ ◾ Adding a note about Definition of Done
  rules/responsive-design/rule.md
Labels: Age: 🐓 - Old

#8987 Create Rule “how-to-avoid-being-blocked/rule”
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  rules/ask-for-help/rule.md
  rules/how-to-avoid-being-blocked/rule.md
Labels: Age: 🐣 - Young

#8989 XS✔ ◾ adding related rule
  rules/how-to-avoid-being-blocked/rule.md
Labels: Age: 🥚 - New

#8982 XS✔ ◾ Replaced Link Auditor with CodeAuditor
  rules/do-you-know-font-tags-are-no-longer-used/rule.md
  rules/forms-do-you-know-when-to-use-links-and-when-to-use-buttons/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8988 XS✔ ◾ Improving content design and readability
  rules/continual-improvement/rule.md
Labels: Age: 🐥 - Adolescent

#8992 XS✔ ◾ Update rules-to-better-sharepoint.md
  categories/infrastructure-and-networking/rules-to-better-sharepoint.md
Labels: Age: 🥚 - New

#8995 XS✔ ◾ new rule - Do you know how to manage urges?
  rules/manage-urges/rule.md
Labels: Age: 🥚 - New

#8996 XS✔ ◾ Example Rule - Added headings in boxes
  rules/rule/rule.md
Labels: Age: 🥚 - New

#8997 XS✔ ◾ manage urges - fixes
  categories/client-engagement/rules-to-better-software-consultants-happy-clients.md
  categories/communication/rules-to-better-giving-and-taking-feedback.md
  rules/manage-urges/rule.md
Labels: Age: 🥚 - New

#8998 XS✔ ◾ Separating urge from behaviour rule updates
  rules/manage-urges/rule.md
  rules/separate-urge-from-behavior/rule.md
Labels: Age: 🥚 - New

#9000 XS✔ ◾ added seo + category
  categories/communication/rules-to-better-giving-and-taking-feedback.md
  rules/separate-urge-from-behavior/rule.md
Labels: Age: 🐤 - Mature

#9001 XS✔ ◾ Added related rules - spacing in web pages
  rules/format-new-lines/rule.md
  rules/html-css-do-you-know-how-to-create-spaces-in-a-web-page/rule.md
Labels: Age: 🐥 - Adolescent

#8993 Updated rules to include links to PBIs in todos
  categories/software-engineering/rules-to-better-code-commenting.md
  rules/create-task-list-comments-for-your-code/rule.md
  rules/todo-tasks/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9004 XS✔ ◾ added markdown example of using code
  rules/rule/rule.md
  rules/set-language-on-code-blocks/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9005 XS✔ ◾ Add new rule - Do you know how to get code line metrics?
  categories/software-engineering/rules-to-better-code-quality.md
  rules/do-you-know-how-to-get-code-line-metrics/eagleeye-cloc-result.png
  rules/do-you-know-how-to-get-code-line-metrics/rule.md
Labels: Age: 🥚 - New

#9006 XS✔ ◾ Update rule.md
  rules/do-you-know-how-to-get-code-line-metrics/rule.md
Labels: Age: 🐤 - Mature

#9007 XS✔ ◾ Add new rule - Do you use ChatGPT to help you generate charts?
  categories/artificial-intelligence/rules-to-better-gpt.md
  rules/use-chatgpt-to-generate-charts/rule.md
  rules/use-chatgpt-to-generate-charts/timepro-original-vs-migrated.png
Labels: Age: 🐤 - Mature

#9009 XS✔ ◾ update-changes-3-a-rule
  rules/being-a-good-consultant/rule.md
  rules/how-to-take-feedback-or-criticism/rule.md
Labels: Age: 🥚 - New

#9008 XS✔ ◾ Updated screenshot tools rule
  rules/screenshots-tools/rule.md
Labels: Age: 🥚 - New

#9010 XS✔ ◾ ♻️ Remove Zero Width Whitespace Characters
  rules/blazor-appstate-pattern-with-notifications/rule.md
  rules/dynamics-crm-install-the-dynamics-365-app-for-outlook/rule.md
  rules/oxford-comma/rule.md
  rules/using-mfa/rule.md
  rules/when-to-use-canva/rule.md
Labels: Age: 🥚 - New

#9011 XS✔ ◾ ♻️ App State Pattern - Mention Fluxor
  rules/blazor-appstate-pattern-with-notifications/rule.md
Labels: Age: 🥚 - New

#9013 XS✔ ◾ Fix related - make it a list
  rules/being-a-good-consultant/rule.md
Labels: Age: 🥚 - New

#9015 XS✔ ◾ New rule - lasting habits
  categories/company-operations/rules-to-better-health-and-exercise-in-the-workplace.md
  rules/lasting-habits/rule.md
Labels: Age: 🥚 - New

#9016 XS✔ ◾ update typescript config rules
  rules/good-typescript-configuration/rule.md
Labels: Age: 🥚 - New

#9018 XS✔ ◾ Lasting habits - add tips to remember
  rules/lasting-habits/rule.md
Labels: Age: 🥚 - New

#9020 XS✔ ◾ Lasting habits - improve tips
  rules/lasting-habits/rule.md
Labels: Age: 🥚 - New

#9019 XS✔ ◾ Update rule.md
  rules/hand-over-projects/rule.md
Labels: Age: 🐤 - Mature

#9022 Create Rule “make-perplexity-your-default-search-engine/rule”
  categories/artificial-intelligence/rules-to-better-gpt.md
  rules/make-perplexity-your-default-search-engine/google-default.png
  rules/make-perplexity-your-default-search-engine/perplexity-default.png
  rules/make-perplexity-your-default-search-engine/rule.md
Labels: Age: 🥚 - New

#9021 XS✔ ◾ Improved content design - Tine Habits rule
  rules/lasting-habits/rule.md
Labels: Age: 🐥 - Adolescent

#9026 XS✔ ◾ updated Google example from bad to OK
  rules/make-perplexity-your-default-search-engine/rule.md
Labels: Age: 🥚 - New

#9025 XS✔ ◾ Small improvements
  rules/keep-yourself-connected-overseas/rule.md
Labels: Age: 🥚 - New

#9028 XS✔ ◾ Merged anchor links rules + fixed content design and syntax + better categories
  categories/design/rules-to-better-websites-layout-and-formatting.md
  categories/design/rules-to-better-websites-navigation.md
  categories/software-engineering/rules-to-better-websites-development.md
  rules/anchor-links/rule.md
  rules/chose-efficient-anchor-names/rule.md
  rules/do-you-know-how-to-use-named-anchor-links/rule.md
  rules/do-you-use-the-right-anchor-names/rule.md
  rules/efficient-anchor-names/rule.md
  rules/rule/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9031 XS✔ ◾ Rename Find more (1).png to no-match-found-search.png
  rules/do-you-give-option-to-widen-a-search/no-match-found-search.png
  rules/do-you-give-option-to-widen-a-search/rule.md
Labels: Age: 🥚 - New

#9032 XS✔ ◾ Added info box + improved caption - hyperlink-phone-numbers rule
  rules/hyperlink-phone-numbers/rule.md
Labels: Age: 🥚 - New

#9035 Update Rule “sprint-review-retro-email/rule”
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🐤 - Mature

#9029 Update Rule “planned-outage-process/rule”
  rules/planned-outage-process/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9034 Update Rule “creating-action-items/rule”
  rules/creating-action-items/rule.md
Labels: Age: 🐓 - Old

#9036 XS✔ ◾ Added a bunch of extra useful content from ChatGPT "add-captions-to-your-video"
  categories/marketing-and-video/rules-to-better-video-recording.md
  rules/add-text-captions-to-videos/rule.md
  rules/post-production-do-you-add-captions-to-your-video/rule.md
Labels: Age: 🥚 - New

#9038 XS✔ ◾ Added Attendees in Table
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#9037 XS✔ ◾ Removed boxes examples with headings
  rules/rule/rule.md
Labels: Age: 🥚 - New

#9039 Update Rule “do-you-know-the-components-of-a-google-ads-campaign/rule”
  rules/do-you-know-the-components-of-a-google-ads-campaign/rule.md
Labels: Age: 🥚 - New

#9041 XS✔ ◾ Improve SEO tools rule
  rules/google-search-console-vs-google-analytics/rule.md
  rules/seo-tools/rule.md
Labels: Age: 🥚 - New

#9045 XS✔ ◾ Updating-Do you know how to be a good Product Owner
  rules/do-you-know-the-how-to-be-a-good-product-owner/rule.md
Labels: Age: 🥚 - New

#9040 XS✔ ◾ Update good example image
  rules/video-background/jimmy-teams.jpg
  rules/video-background/rule.md
Labels: Age: 🐤 - Mature

#9047 XS✔ ◾ Added blurb to each tool + improved links "seo-tools"
  rules/seo-tools/rule.md
Labels: Age: 🐣 - Young

#9042 Update Rule “explain-deleted-or-modified-appointments/rule”
  rules/explain-deleted-or-modified-appointments/rule.md
Labels: Age: 🐤 - Mature

#9048 Update Rule "creating-action-items/rule"
  rules/creating-action-items/rule.md
Labels: Age: 🥚 - New

#9049 XS✔ ◾ New ai development category
  categories/artificial-intelligence/index.md
  categories/artificial-intelligence/rules-to-better-ai-development.md
  categories/artificial-intelligence/rules-to-better-gpt.md
Labels: Age: 🥚 - New

#9050 XS✔ ◾ Fix search console link
  rules/seo-tools/rule.md
Labels: Age: 🥚 - New

#9051 XS✔ ◾ Improved title and headings for "use-system-prompt"
  rules/use-system-prompt/rule.md
Labels: Age: 🥚 - New

#9052 XS✔ ◾ Made titles consistent + reordering GPT rules
  rules/chatgpt-vs-gpt/rule.md
  rules/connect-chatgpt-with-virtual-assistant/rule.md
  rules/install-chatgpt-as-an-app/rule.md
  rules/train-gpt/rule.md
  rules/what-is-chatgpt/rule.md
  rules/what-is-gpt/rule.md
Labels: Age: 🥚 - New

#9053 XS✔ ◾ Improved the rule overall "use-embeddings"
  rules/use-embeddings/rule.md
Labels: Age: 🥚 - New

#9054 XS✔ ◾ Update rules-to-better-gpt.md
  categories/artificial-intelligence/rules-to-better-ai-development.md
  categories/artificial-intelligence/rules-to-better-ai-generated-media.md
  categories/artificial-intelligence/rules-to-better-gpt.md
Labels: Age: 🥚 - New

#9055 XS✔ ◾ trying to fix broken image
  rules/efficiency-do-you-use-two-monitors/rule.md
  rules/efficiency-do-you-use-two-monitors/two-monitors-better-than-one.jpg
Labels: Age: 🥚 - New

#9056 XS✔ ◾ Update rule.md
  rules/do-you-use-access-packages/rule.md
Labels: Age: 🥚 - New

#9058 XS✔ ◾ Merged image formats rules
  rules/do-you-avoid-bmps-for-the-internet-at-all-times/rule.md
  rules/do-you-know-how-to-save-your-graphics-in-the-right-format/rule.md
  rules/do-you-know-when-to-use-jpg/rule.md
  rules/do-you-know-when-to-use-png/rule.md
  rules/do-you-know-when-to-use-svg/rule.md
  rules/image-formats/rule.md
Labels: Age: 🥚 - New

#9057 XS✔ ◾ Merged quality images rules
  rules/do-you-use-high-quality-images/rule.md
  rules/good-quality-images/rule.md
  rules/high-quality-images/rule.md
  rules/optimize-your-images/rule.md
Labels: Age: 🥚 - New

#9059 XS✔ ◾ Reorder + fix URLs for rules-to-better-websites-graphics.md
  categories/design/rules-to-better-websites-layout-and-formatting.md
  categories/software-engineering/rules-to-better-websites-graphics.md
Labels: Age: 🥚 - New

#9060 XS✔ ◾ Added extra on not having Capital letters in file extensions
  rules/how-to-name-documents/rule.md
Labels: Age: 🥚 - New

#9063 XS✔ ◾ Fix formatting issues in rule - how to be a good Product Owner
  rules/do-you-know-the-how-to-be-a-good-product-owner/rule.md
Labels: Age: 🥚 - New

#9062 XS✔ ◾ fixes from Adam
  rules/hand-over-projects/rule.md
Labels: Age: 🐤 - Mature

#9065 XS✔ ◾ add risk sentence
  rules/create-pbis-under-2-days/rule.md
Labels: Age: 🐤 - Mature

#9066 XS✔ ◾ Add checking PBIs
  rules/standards-watchdog/rule.md
Labels: Age: 🐤 - Mature

#9068 XS✔ ◾ Fixed capitalization + small improvements "importance-of-reconciliation"
  rules/importance-of-reconciliation/rule.md
Labels: Age: 🥚 - New

#9067 Update Rule “the-best-package-manager-for-react/rule”
  rules/best-package-manager-for-node/logo.svg
  rules/best-package-manager-for-node/npm-logo.jpg
  rules/best-package-manager-for-node/pnpm-logo.png
  rules/best-package-manager-for-node/rule.md
  rules/best-package-manager-for-node/yarn-logo.jpg
  rules/the-best-package-manager-for-react/rule.md
Labels: Age: 🐤 - Mature

#9061 XS✔ ◾ Improved title Do you avoid using spaces in folder and file names?
  rules/remove-spaces-from-your-folders-and-filename/rule.md
Labels: Age: 🐓 - Old

#9069 XS✔ ◾ Added related tasks "one email per task"
  rules/communication-are-you-specific-in-your-requirements/rule.md
  rules/do-you-send-tasks-one-email-at-a-time/rule.md
Labels: Age: 🥚 - New

#9070 XS✔ ◾ Added related rules - PBIs title and defining
  rules/defining-pbis/rule.md
  rules/explaining-pbis/rule.md
  rules/meaningful-pbi-titles/rule.md
Labels: Age: 🥚 - New

#9073 XS✔ ◾ Update Categories for the node package manager Rule
  categories/software-engineering/rules-to-better-angularjs.md
  categories/software-engineering/rules-to-better-code.md
  categories/software-engineering/rules-to-better-javascript-and-jquery.md
  categories/software-engineering/rules-to-better-nextjs.md
  categories/software-engineering/rules-to-better-react.md
  categories/software-engineering/rules-to-better-vue.md
  rules/manage-bundle-size/rule.md
  rules/packages-up-to-date/rule.md
  rules/streamline-development-with-npm-and-task-runners/rule.md
Labels: Age: 🥚 - New

#9081 XS✔ ◾ replace image cone of uncertainty
  rules/the-drawbacks-of-fixed-price-fixed-scope-contracts/cone-of-uncertainty-software-price.jpg
  rules/the-drawbacks-of-fixed-price-fixed-scope-contracts/rule.md
Labels: Age: 🥚 - New

#9077 📝Do you know you to handle redirects? - Added additional information
  rules/handle-redirects/rule.md
Labels: Age: 🐤 - Mature
