Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-06, with the labels that each got.

#8637 Split the rule on Power BI version control into 2 rules
  rules/do-you-know-powerbi-version-control-features/Gitignore.png
  rules/do-you-know-powerbi-version-control-features/PBICache.png
  rules/do-you-know-powerbi-version-control-features/ProjectFolders.png
  rules/do-you-know-powerbi-version-control-features/enable-pbip-format.png
  rules/do-you-know-powerbi-version-control-features/rule.md
  rules/do-you-know-powerbi-version-control-features/save-as-pbip.png
  rules/do-you-use-version-control-with-power-bi/good-example-compare-changes-2.png
  rules/do-you-use-version-control-with-power-bi/rule.md
Labels: Age: 🐤 - Mature

#8643 XS✔ ◾ Rename rules.md to rule.md
  rules/linkedin-connect-with-people/rule.md
Labels: Age: 🥚 - New

#8635 XS✔ ◾ Removed broken link
  rules/use-a-conversion-pixel/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#8634 XS✔ ◾ Updated links to Qantas
  rules/do-you-take-advantage-of-business-rewards-programs/rule.md
  rules/missing-flight-invoices/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#8639 Update Rule “do-you-use-version-control-with-power-bi/rule”
  rules/do-you-use-version-control-with-power-bi/rule.md
Labels: Age: 🐓 - Old

#8648 XS✔ ◾ update rule-for-the-record
  rules/for-the-record/rule.md
Labels: Age: 🥚 - New

#8638 Amended Rule-change-link-sharing-default-behaviour
  rules/change-link-sharing-default-behaviour/rule.md
Labels: Age: 🐓 - Old

#8633 XS✔ ◾ Fixed broken link
  rules/do-you-use-datasets-or-create-your-own-business-objects/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#8636 XS✔ ◾ Fixed title + improved rule content
  rules/never-use-password-twice/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#8646 Create Rule “humanise-ai-generated-content/rule”
  rules/humanise-ai-generated-content/rule.md
Labels: Age: 🥚 - New

#8650 XS✔ ◾ Fixed a link
  rules/do-not-bury-your-headline/rule.md
Labels: Age: 🥚 - New

#8653 XS✔ ◾ migrated rule---use-alternating-row-colors
  rules/use-alternating-row-colors/RSRules_alternatingcolors.gif
  rules/use-alternating-row-colors/rule.md
Labels: Age: 🥚 - New

#8651 XS✔ ◾ Move changes to For the record to Backchannels
  rules/for-the-record/rule.md
  rules/use-backchannels-effectively/rule.md
Labels: Age: 🐤 - Mature

#8652 Update Rule “do-not-bury-your-headline/rule”
  categories/communication/rules-to-better-email.md
  rules/do-not-bury-your-headline/rule.md
Labels: Age: 🐤 - Mature

#8655 XS✔ ◾ Reduced example texts for clarity "avoid-using-gendered-pronouns"
  rules/avoid-using-gendered-pronouns/rule.md
Labels: Age: 🥚 - New

#8654 XS✔ ◾ Migrated Rule - Data Layout - Do you have nodes count like Outlook?
  categories/company-operations/rules-to-better-reporting-services.md
  rules/nodes-count-like-outlook/No_number.jpg
  rules/nodes-count-like-outlook/number.jpg
  rules/nodes-count-like-outlook/rule.md
Labels: Age: 🐤 - Mature

#8656 XS✔ ◾ Migrated rule - Avoid using too many decimal places
  categories/company-operations/rules-to-better-reporting-services.md
  rules/avoid-using-too-many-decimals-ssrs/DecimalParameter.gif
  rules/avoid-using-too-many-decimals-ssrs/No_decimal.jpg
  rules/avoid-using-too-many-decimals-ssrs/decimal.jpg
  rules/avoid-using-too-many-decimals-ssrs/rule.md
Labels: Age: 🥚 - New

#8659 XS✔ ◾ Update rule.md
  rules/do-you-calculate-payroll-tax-correctly/rule.md
Labels: Age: 🥚 - New

#8661 XS✔ ◾ add-show-certification-award-accounting
  categories/company-operations/rules-to-better-accounting.md
Labels: Age: 🥚 - New

#8660 XS✔ ◾ added orphaned rule
  categories/software-engineering/rules-to-better-devops-using-azure-devops.md
Labels: Age: 🥚 - New

#8663 XS✔ ◾ Migrated Rule - Consistent height of table row
  categories/company-operations/rules-to-better-reporting-services.md
  rules/avoid-using-too-many-decimals-ssrs/rule.md
  rules/consistent-height-of-table-row/RSRowHeight_NonStandard_design.jpg
  rules/consistent-height-of-table-row/RSRowHeight_Standard_design.jpg
  rules/consistent-height-of-table-row/RowHeight_Bad.gif
  rules/consistent-height-of-table-row/RowHeight_Good.gif
  rules/consistent-height-of-table-row/rule.md
Labels: Age: 🥚 - New

#8666 Update Some Frontmatter
  do-you-know-where-to-host-your-frontend-application/rule.md
  rules/pitch-a-product/rule.md
Labels: Age: 🥚 - New

#8667 XS✔ ◾ Update rule.md
  rules/avoid-using-gendered-pronouns/rule.md
Labels: Age: 🥚 - New

#8668 XS✔ ◾ Fixed Some Formatting
  rules/404-error-avoid-changing-the-url/rule.md
  rules/apply-tags-to-your-azure-resource-groups/rule.md
  rules/attention-to-detail/rule.md
  rules/avoid-common-mistakes/rule.md
  rules/avoid-showing-change-as-percentage/rule.md
  rules/avoid-using-share-functionality/rule.md
  rules/avoid-using-too-many-decimals-ssrs/rule.md
  rules/avoid-using-word-report/rule.md
  rules/best-online-documentation-site/rule.md
  rules/borders-around-white-images/rule.md
  rules/brainstorming-team-allocation/rule.md
  rules/break-tasks/rule.md
  rules/browser-add-branding/rule.md
  rules/build-the-backlog/rule.md
  rules/bus-test/rule.md
  rules/change-link-sharing-default-behaviour/rule.md
  rules/chatgpt-for-email/rule.md
  rules/check-out-built-in-samples/rule.md
  rules/check-that-rs-configuration-manager-is-all-green-ticks/rule.md
  rules/client-love-after-initial-meeting/rule.md
  rules/close-pbis-with-context/rule.md
  rules/consistent-height-of-table-row/rule.md
  rules/developer-experience/rule.md
  rules/humanise-ai-generated-content/rule.md
  rules/inform-others-about-chat-message-updates/rule.md
  rules/train-ai-to-write-in-your-style/rule.md
Labels: Age: 🥚 - New

#8665 XS✔ ◾ Migrate Rule - Display zero number as blank
  categories/company-operations/rules-to-better-reporting-services.md
  rules/display-zero-number-as-blank/AvoidZeroNum_Bad.gif
  rules/display-zero-number-as-blank/AvoidZeroNum_format.gif
  rules/display-zero-number-as-blank/AvoidZeroNum_good.gif
  rules/display-zero-number-as-blank/rule.md
Labels: Age: 🐤 - Mature

#8664 Update Rule “always-get-your-prospects-full-contact-details/rule”
  rules/always-get-your-prospects-full-contact-details/rule.md
Labels: Age: 🐤 - Mature

#8657 Update Rule “use-backchannels-effectively/rule”
  rules/use-backchannels-effectively/rule.md
Labels: Age: 🐤 - Mature

#8670 XS✔ ◾ added orphaned rule + improvements
  categories/software-engineering/rules-to-better-code-quality.md
  categories/software-engineering/rules-to-better-code.md
  rules/do-you-know-the-difference-between-a-clever-and-a-smart-developer/rule.md
Labels: Age: 🥚 - New

#8669 XS✔ ◾ Update image + other improvements
  rules/close-pbis-with-context/closing-pbis-with-context.jpg
  rules/close-pbis-with-context/rule.md
Labels: Age: 🐣 - Young

#8672 XS✔ ◾ Update rule.md "keep-yourself-connected-overseas"
  categories/company-operations/rules-to-better-travel.md
  rules/keep-yourself-connected-overseas/rule.md
Labels: Age: 🥚 - New

#8658 XS✔ ◾ SharePoint rules - added orphaned rule + fixed titles
  categories/software-engineering/rules-to-better-sharepoint-for-developers.md
  rules/are-your-developers-managing-your-projects-with-tfs-with-proven-agile-scrum-and-alm-strategies/rule.md
  rules/asp-net-vs-sharepoint-development-do-you-know-deployment-is-different/rule.md
  rules/asp-net-vs-sharepoint-development-do-you-know-source-control-is-different/rule.md
  rules/asp-net-vs-sharepoint-development-do-you-know-what-you-get-for-free-out-of-the-box/rule.md
  rules/does-your-sharepoint-site-have-a-favicon/rule.md
  rules/how-do-you-deploy-sharepoint/rule.md
  rules/is-your-first-aim-to-customize-a-sharepoint-webpart/rule.md
  rules/never-dispose-objects-from-spcontext-current/rule.md
Labels: Age: 🐓 - Old

#8675 XS✔ ◾ Migrated Rule - Show time format clearly
  categories/company-operations/rules-to-better-reporting-services.md
  rules/show-time-format-clearly/RSTimeFormat_bad.gif
  rules/show-time-format-clearly/RSTimeFormat_good.gif
  rules/show-time-format-clearly/rule.md
Labels: Age: 🥚 - New

#8690 XS✔ ◾ Add new 3 steps poster
  rules/3-steps-to-a-pbi/3-steps-to-a-pbi-V7-2.jpg
  rules/3-steps-to-a-pbi/3-steps-to-a-pbi-V7-2.pdf
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#8691 XS✔ ◾ Update rule.md
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#8680 XS✔ ◾ Update rule.md
  rules/ai-tools-voice-translations/rule.md
Labels: Age: 🐤 - Mature

#8692 XS✔ ◾ 🧙‍♂️ Remove TDD mention from 3 steps to PBI rule.md
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#8676 Added URI for new rule on powerbi version control features
  categories/company-operations/rules-to-better-power-bi.md
Labels: Age: 🐓 - Old

#8681 XS✔ ◾ Update rule use backchannels effectively
  rules/use-backchannels-effectively/rule.md
Labels: Age: 🐤 - Mature

#8696 XS✔ ◾ Update rule.md
  rules/add-callable-link/rule.md
Labels: Age: 🥚 - New

#8695 XS✔ ◾ Fixed placeholder formatting on "/rule"
  rules/rule/rule.md
Labels: Age: 🥚 - New

#8679 XS✔ ◾ Update rule.md
  rules/ai-tools-voice-translations/rule.md
Labels: Age: 🐤 - Mature

#8699 XS✔ ◾ Update rules-to-better-websites-navigation.md
  categories/design/rules-to-better-websites-navigation.md
Labels: Age: 🥚 - New

#8697 XS✔ ◾ Update rule.md
  rules/add-callable-link/rule.md
Labels: Age: 🥚 - New

#8683 XS✔ ◾ Migrated rule - Show all of the report parameters in body
  categories/company-operations/rules-to-better-reporting-services.md
  rules/show-all-report-parameters-in-body/RSReportParameters_bad.gif
  rules/show-all-report-parameters-in-body/RSReportParameters_good.gif
  rules/show-all-report-parameters-in-body/rule.md
Labels: Age: 🐓 - Old

#8698 XS✔ ◾ change to more closely match graphic
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#8700 XS✔ ◾ Migrated rule - Use logical page breaks
  categories/company-operations/rules-to-better-reporting-services.md
  rules/use-logical-page-breaks/RSLogicalPageBreak.jpg
  rules/use-logical-page-breaks/RSLogicalPageBreak_Preview.jpg
  rules/use-logical-page-breaks/rule.md
Labels: Age: 🥚 - New

#8702 XS✔ ◾ Migrate rule - Prevent charts growing with rows
  categories/company-operations/rules-to-better-reporting-services.md
  rules/prevent-charts-growing-with-rows/RS_ChartInRow_Bad.gif
  rules/prevent-charts-growing-with-rows/RS_ChartInRow_Good.gif
  rules/prevent-charts-growing-with-rows/rule.md
Labels: Age: 🥚 - New

#8693 XS✔ ◾ Remove [figure: old version] from rule
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🐓 - Old

#8703 XS✔ ◾ Migrated rule - Use vertical text
  categories/company-operations/rules-to-better-reporting-services.md
  rules/use-vertical-text/RS_VerticalText_1.gif
  rules/use-vertical-text/RS_VerticalText_2.gif
  rules/use-vertical-text/RS_VerticalText_3.gif
  rules/use-vertical-text/rule.md
Labels: Age: 🐓 - Old

#8707 XS✔ ◾ adding authors
  rules/create-gpts/rule.md
Labels: Age: 🥚 - New

#8705 XS✔ ◾ Fixed title as per standards
  rules/stick-to-the-agenda-and-complete-the-meetings-goal/rule.md
Labels: Age: 🍗 - Ancient

#8708 XS✔ ◾ add rule to better accounting
  categories/company-operations/rules-to-better-accounting.md
Labels: Age: 🥚 - New

#8710 XS✔ ◾ add redirects
  rules/show-certification-award/rule.md
Labels: Age: 🥚 - New

#8711 XS✔ ◾ Move show-certification-award to a different category to test it
  categories/company-operations/rules-to-better-accounting.md
  categories/company-operations/rules-to-better-business-management.md
Labels: Age: 🥚 - New

#8712 Remove space
  rules/show-certification-award/rule.md
Labels: Age: 🥚 - New

#8713 XS✔ ◾ Add Giscus to comments rule
  categories/software-engineering/rules-to-better-website-development-asp-net.md
  categories/software-engineering/rules-to-better-websites-development.md
  rules/best-commenting-engine/rule.md
Labels: Age: 🥚 - New

#8716 XS✔ ◾ Comments - Add Dan
  rules/best-commenting-engine/rule.md
Labels: Age: 🥚 - New

#8694 XS✔ ◾ Tiago's changes for better consistency and readability
  rules/use-backchannels-effectively/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8674 XS✔ ◾ Update the labelling rule to ensure that the Sticky note is the prefe…
  rules/label-broken-equipment/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8717 XS✔ ◾ Added orphaned rule + updated consulting link
  categories/software-engineering/rules-to-better-devops-using-azure-devops.md
Labels: Age: 🐣 - Young

#8720 Update rule to new instructions to add link to LinkedIn job experience.md
  rules/linkedin-profile/rule.md
Labels: Age: 🥚 - New

#8718 XS✔ ◾ Improved reading + indentation + shorten URL
  categories/infrastructure-and-networking/rules-to-better-pcs.md
  rules/quickest-way-to-get-windows-soe-up-and-running/ChocolateyScript.jpg
  rules/quickest-way-to-get-windows-soe-up-and-running/LoginScript.jpg
  rules/quickest-way-to-get-windows-soe-up-and-running/NonChocolateyApp.jpg
  rules/quickest-way-to-get-windows-soe-up-and-running/SSWLaptopBranding.jpg
  rules/quickest-way-to-get-windows-soe-up-and-running/choco.png
  rules/quickest-way-to-get-windows-soe-up-and-running/login-script.png
  rules/quickest-way-to-get-windows-soe-up-and-running/rule.md
  rules/quickest-way-to-get-windows-soe-up-and-running/ssw-skin.jpeg
Labels: Age: 🐣 - Young

#8722 XS✔ ◾ Update rule.md
  rules/google-maps-profile/rule.md
Labels: Age: 🥚 - New

#8719 XS✔ ◾ Converted unusual list in paragraphs
  rules/asking-questions/rule.md
Labels: Age: 🐓 - Old

#8725 XS✔ ◾ adding image to rule
  rules/know-that-im-interrupts/focused-developer.jpg
  rules/know-that-im-interrupts/rule.md
Labels: Age: 🥚 - New

#8724 XS✔ ◾ Updated parking lot rule
  rules/keep-track-of-a-parking-lot-for-topics/rule.md
Labels: Age: 🐓 - Old

#8723 XS✔ ◾ Updated Daily Scrum rule
  rules/methodology-daily-scrums/rule.md
Labels: Age: 🐓 - Old

#8726 XS✔ ◾ Update rule.md
  rules/chatgpt-security-risks/rule.md
Labels: Age: 🥚 - New

#8730 XS✔ ◾ ✨ Added embed UI into an AI Chat rule
  categories/artificial-intelligence/rules-to-better-gpt.md
  rules/embed-ui-into-an-ai-chat/rule.md
  rules/embed-ui-into-an-ai-chat/text-based-chat.png
  rules/embed-ui-into-an-ai-chat/ui-based-chat.png
Labels: Age: 🥚 - New

#8734 🐛 Added category for best online documentation site
  categories/software-engineering/rules-to-better-websites-development.md
Labels: Age: 🥚 - New

#8737 XS✔ ◾ Do you uncover the hidden anchor with a client?
  rules/Do you uncover the hidden anchor with a client?
Labels: Age: 🥚 - New

#8736 XS✔ ◾ Archive rule + Add it to a category
  categories/software-engineering/rules-to-better-websites-development.md
  rules/streamline-development-with-npm-and-task-runners/rule.md
Labels: Age: 🥚 - New

#8735 XS✔ ◾ Archived drafts
  rules/do-you-look-for-call-back-over-event-handlers/rule.md
  rules/do-you-look-for-memory-leaks/rule.md
Labels: Age: 🐥 - Adolescent

#8739 XS✔ ◾ Move rule to folder
  rules/uncover-hidden-anchor-client/rule.md
Labels: Age: 🥚 - New

#8727 Migrated rule - Gray color for past data
  categories/company-operations/rules-to-better-reporting-services.md
  rules/gray-color-for-past-data/RS_Color4Prior_Bad.gif
  rules/gray-color-for-past-data/RS_Color4Prior_Good.gif
  rules/gray-color-for-past-data/rule.md
Labels: Age: 🐓 - Old

#8743 XS✔ ◾ added orphaned rule to categories
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
  categories/communication/rules-to-better-meetings.md
Labels: Age: 🐤 - Mature

#8744 Rule on Power BI Version Control - Added 2 bad examples showing lack of version history in Power BI Service
  rules/do-you-use-version-control-with-power-bi/bad-example-no-history-in-powerbi-service-1.png
  rules/do-you-use-version-control-with-power-bi/bad-example-no-history-in-powerbi-service-2.png
  rules/do-you-use-version-control-with-power-bi/rule.md
Labels: Age: 🐓 - Old

#8741 Migrated rule - 3D cylinder in column chart
  categories/company-operations/rules-to-better-reporting-services.md
  rules/use-3d-cylinder-in-column-chart/RS_3DCylinder_Bad.gif
  rules/use-3d-cylinder-in-column-chart/RS_3DCylinder_Good.gif
  rules/use-3d-cylinder-in-column-chart/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8731 XS✔ ◾ ✨ Software architecture cheat sheet
  categories/client-engagement/rules-to-better-specification-reviews.md
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  categories/software-engineering/rules-to-better-clean-architecture.md
  categories/software-engineering/rules-to-better-microservices.md
  categories/software-engineering/rules-to-better-modular-monoliths.md
  rules/software-architecture-decision-tree/architecture-decision-tree.jpg
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8733 XS✔ ◾ Added rule - 'do you know how to encapsulate domain models'
  categories/software-engineering/index.md
  categories/software-engineering/rules-to-better-domain-driven-design.md
  rules/encapsulate-domain-models/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8745 XS✔ ◾ Updated authors on software-architecture-decision-tree rule
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#8742 XS✔ ◾ Adding Front Door vs Cloudflare comparison as CDNs
  categories/software-engineering/rules-to-better-internationalization.md
  rules/do-you-use-cdn-for-js-files/rule.md
  rules/handle-redirects/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8747 XS✔ ◾ Added specification rule
  categories/software-engineering/rules-to-better-clean-architecture.md
  categories/software-engineering/rules-to-better-domain-driven-design.md
  rules/common-design-patterns/rule.md
  rules/use-specification-pattern/rule.md
Labels: Age: 🐣 - Young

#8746 Update Rule “do-you-know-what-happens-at-a-sprint-review-meeting/rule”
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🐤 - Mature

#8749 XS✔ ◾ Updated GUID
  rules/show-all-report-parameters-in-body/rule.md
Labels: Age: 🥚 - New

#8748 XS✔ ◾ ✨ Rich vs anemic domain model
  categories/software-engineering/rules-to-better-clean-architecture.md
  categories/software-engineering/rules-to-better-domain-driven-design.md
  rules/anemic-vs-rich-domain-models/rule.md
Labels: Age: 🥚 - New

#8750 XS✔ ◾ New rule - Screen recording
  categories/marketing-and-video/rules-to-better-video-recording.md
  rules/do-you-know-how-to-record-the-screen-on-a-mac/rule.md
  rules/problem-steps-recorder/psr1.png
  rules/problem-steps-recorder/psr2.png
  rules/problem-steps-recorder/psr3_1710232021939.png
  rules/problem-steps-recorder/rule.md
  rules/record-a-quick-and-dirty-done-video/rule.md
  rules/recording-screen/rule.md
Labels: Age: 🥚 - New

#8751 Added Screenshot to the good example on “add-context-reasoning-to-emails/rule”
  rules/add-context-reasoning-to-emails/rule.md
  rules/add-context-reasoning-to-emails/screenshot-example.png
Labels: Age: 🥚 - New

#8753 Updated screenshot + improved content “dones-do-you-include-useful-details-in-your-done-email/rule”
  categories/communication/rules-to-better-email.md
  rules/dones-do-you-include-useful-details-in-your-done-email/rule.md
  rules/dones-do-you-include-useful-details-in-your-done-email/screenshot-contact-form.png
  rules/include-useful-details-in-emails/rule.md
Labels: Age: 🐣 - Young

#8758 Update Rule “microsoft-defender-365/rule”
  rules/microsoft-defender-365/rule.md
Labels: Age: 🐓 - Old

#8764 XS✔ ◾ Update Triaging to include work prioritization
  rules/triaging-do-you-correctly-triage-additional-item-requests/rule.md
Labels: Age: 🥚 - New

#8765 XS✔ ◾ Add context for PBI prioritization
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🥚 - New

#8766 XS✔ ◾ update-decision-tree
  rules/software-architecture-decision-tree/architecture-decision-tree.jpg
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#8767 XS✔ ◾ decision-tree-typo
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#8763 XS✔ ◾ Improvements for consistency - Rule on Microsoft Defender
  rules/microsoft-defender-365/rule.md
Labels: Age: 🐤 - Mature

#8752 XS✔ ◾ Trying to fix email template
  rules/add-context-reasoning-to-emails/rule.md
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/rule.md
  rules/screenshots-avoid-walls-of-text/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8760 New Rule - Company Compliance Sheet
  categories/company-operations/rules-to-better-accounting.md
  rules/compliance-sheet/compliance-sheet-image-1.jpg
  rules/compliance-sheet/read.md
Labels: Age: 🐤 - Mature

#8759 Migrate rule - center the title in your chart
  rules/center-title-in-chart/RS_TitleCentered_Bad.gif
  rules/center-title-in-chart/RS_TitleCentered_Good.gif
  rules/center-title-in-chart/rule.md
Labels: Age: 🐤 - Mature

#8769 XS✔ ◾ Trying to improve readability "/software-architecture-decision-tree"
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#8762 XS✔ ◾ Updated rule - use vertical text
  rules/use-vertical-text/rule.md
Labels: Age: 🐓 - Old

#8771 Added CA Link to Architecture Decision Tree
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#8770 Update Rule “do-you-use-indentation-for-readability/rule”
  rules/do-you-use-indentation-for-readability/rule.md
Labels: Age: 🥚 - New

#8773 XS✔ ◾ Update rules/make-sure-that-the-test-can-be-failed/rule.md
  rules/make-sure-that-the-test-can-be-failed/rule.md
Labels: Age: 🐤 - Mature

#8774 XS✔ ◾ ➕ point about modularity in VSA
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🐥 - Adolescent

#8779 XS✔ ◾ adding image to rule
  rules/chatgpt-security-risks/rule.md
  rules/chatgpt-security-risks/safe-dev.jpg
Labels: Age: 🥚 - New

#8780 XS✔ ◾ Adding prompt to AI images
  rules/add-useful-and-concise-figure-captions/rule.md
  rules/write-an-image-prompt/rule.md
Labels: Age: 🥚 - New

#8778 XS✔ ◾ Update rule prefix to be more accurate
  rules/website-heatmaps/rule.md
Labels: Age: 🐤 - Mature

#8776 XS✔ ◾ Added rule to category
  categories/company-operations/rules-to-better-reporting-services.md
Labels: Age: 🐤 - Mature

#8784 XS✔ ◾ Improved title + improved links at the end
  rules/customize-dynamics-user-experience/rule.md
Labels: Age: 🥚 - New

#8785 XS✔ ◾ added back archived rule to category
  categories/communication/rules-to-better-microsoft-teams.md
Labels: Age: 🥚 - New

#8786 XS✔ ◾ New rule - share product improvements
  rules/share-product-improvements/rule.md
  rules/share-product-improvements/share-product-improvements-github-discussion.png
  rules/share-product-improvements/share-product-improvements-tweet.png
  rules/type-of-content-marketing-you-should-post/rule.md
Labels: Age: 🐤 - Mature

#8790 XS✔ ◾ Improved readdability + consistency "PPC results rule"
  rules/update-team-on-ppc-advertising-results/rule.md
Labels: Age: 🥚 - New

#8789 XS✔ ◾ CA template - Update rule with new template
  categories/software-engineering/rules-to-better-clean-architecture.md
  rules/clean-architecture-get-started/ca-template-readme.png
  rules/clean-architecture-get-started/rule.md
  rules/clean-architecture-the-best-way-to-get-started/clean-architecture-solution-template.png
  rules/clean-architecture-the-best-way-to-get-started/rule.md
  rules/packages-to-add-to-your-mvc-project/rule.md
  rules/the-best-way-to-generate-your-entities-from-swagger/rule.md
Labels: Age: 🐤 - Mature

#8768 XS✔ ◾ Removed confusing emojis "include links" rule
  rules/include-links-in-emails/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8792 XS✔ ◾ Fix concatenated words in "Touch it once principle"
  rules/the-touch-it-once-principle/rule.md
Labels: Age: 🥚 - New

#8795 Update rule - Compliance Sheet & add new image
  rules/compliance-sheet/compliance-sheet-image-2.png
  rules/compliance-sheet/read.md
Labels: Age: 🐥 - Adolescent

#8791 XS✔ ◾ CA - add Daniel
  rules/the-main-principles-of-clean-architecture/rule.md
Labels: Age: 🐓 - Old

#8793 XS✔ ◾ ca - link to awesome ca
  rules/the-best-clean-architecture-learning-resources/rule.md
Labels: Age: 🐤 - Mature

#8796 XS✔ ◾ Improved Clean Architecture principles rule
  rules/the-main-principles-of-clean-architecture/rule.md
Labels: Age: 🥚 - New

#8755 XS✔ ◾ Improved title and category "fix-ugly-URLs"
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  categories/software-engineering/rules-to-better-website-development-asp-net.md
  rules/fix-ugly-urls/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8797 Create Rule “report-seo-results/rule”
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  rules/report-seo-results/rule.md
  rules/update-team-on-ppc-advertising-results/rule.md
Labels: Age: 🐥 - Adolescent

#8800 XS✔ ◾ Adds "Should the email become a PBI?" section to "Turn Emails into PBIs" Rule
  rules/turn-emails-into-pbis/2014-11-10_13-17-43-compressor.png
  rules/turn-emails-into-pbis/email-example.png
  rules/turn-emails-into-pbis/pbi-example.png
  rules/turn-emails-into-pbis/rule.md
  rules/turn-emails-into-pbis/urgent-flowchart.drawio.svg
Labels: Age: 🥚 - New

#8801 XS✔ ◾ added camilla as author
  rules/report-seo-results/rule.md
Labels: Age: 🥚 - New

#8799 XS✔ ◾ Made title consistent + removed link that didn't work "how-to-find-inbound-links-to-your-pages"
  rules/how-to-find-inbound-links-to-your-pages/rule.md
Labels: Age: 🥚 - New

#8803 XS✔ ◾ Improves flowchart colors.
  rules/turn-emails-into-pbis/urgent-flowchart.drawio.svg
Labels: Age: 🥚 - New

#8804 XS✔ ◾ Clarify confidential detail in "Turn emails into PBIs"
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🥚 - New

#8805 XS✔ ◾ CA - Adding author back
  rules/the-main-principles-of-clean-architecture/rule.md
Labels: Age: 🥚 - New

#8806 XS✔ ◾ fix title frontmatter
  rules/report-seo-results/rule.md
Labels: Age: 🥚 - New

#8807 Update Rule “scrum-master-do-you-schedule-the-3-meetings/rule”
  rules/scrum-master-do-you-schedule-the-3-meetings/rule.md
Labels: Age: 🐤 - Mature

#8809 Fixed greybox "no full stops" rule
  rules/avoid-full-stops-in-bullet-point-lists/rule.md
Labels: Age: 🐤 - Mature

#8812 XS✔ ◾ fixed greybox in ssw.com.au/rules/avoid-repetition
  rules/avoid-repetition/rule.md
Labels: Age: 🐤 - Mature
