Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-04, with the labels that each got.

#8282 XS✔ ◾ Update rule.md
  rules/modular-monoliths/rule.md
Labels: Age: 🥚 - New

#8284 XS✔ ◾ New rule: brainstorming-idea-champion
  categories/company-operations/rules-to-better-brainstorming.md
  rules/brainstorming-idea-champion/rule.md
Labels: Age: 🐤 - Mature

#8283 XS✔ ◾ fix small grammar
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🐓 - Old

#8285 XS✔ ◾ Harry's feedback on rule
  rules/brainstorming-idea-champion/rule.md
Labels: Age: 🥚 - New

#8286 XS✔ ◾ Adding a good example
  rules/brainstorming-idea-champion/github-tags.jpg
  rules/brainstorming-idea-champion/rule.md
Labels: Age: 🥚 - New

#8287 XS✔ ◾ Automated PRs - Updated Committer and Added Explanation
  .github/workflows/check-duplicate-images.yml
Labels: code change, Age: 🥚 - New

#8290 XS✔ ◾ Making (PING) rule more clear
  rules/follow-up-unanswered-email/rule.md
Labels: Age: 🥚 - New

#8289 XS✔ ◾ 📝 Add clearer use case to avoid-acronyms
  rules/avoid-acronyms/rule.md
Labels: Age: 🥚 - New

#8291 XS✔ ◾ adding an extra note
  rules/brainstorming-idea-champion/rule.md
Labels: Age: 🐥 - Adolescent

#8295 XS✔ ◾ Small grammar change
  rules/brainstorming-idea-champion/rule.md
Labels: Age: 🥚 - New

#8297 XS✔ ◾ Made "Idea Champion" term stand out in quotes + made labels a section…
  rules/brainstorming-idea-champion/rule.md
Labels: Age: 🥚 - New

#8296 XS✔ ◾ Update rule.md
  rules/who-is-in-charge-of-keeping-the-schedule/event-agenda.png
  rules/who-is-in-charge-of-keeping-the-schedule/rule.md
Labels: Age: 🥚 - New

#8298 XS✔ ◾ Update rule.md
  rules/brainstorming-idea-champion/rule.md
Labels: Age: 🥚 - New

#8299 Update Rule “brainstorming-idea-champion/rule”
  rules/brainstorming-idea-champion/brainstorming-champion.jpg
  rules/brainstorming-idea-champion/rule.md
  rules/brainstorming-idea-champion/wizard.jpg
Labels: Age: 🥚 - New

#8301 XS✔ ◾ Deleting old image
  rules/brainstorming-idea-champion/brainstorming-champion.jpg
Labels: Age: 🥚 - New

#8278 XS✔ ◾ Made "include URL" rule generic... instead of just for "Dones"
  categories/communication/rules-to-better-email.md
  rules/add-context-reasoning-to-emails/rule.md
  rules/dones-do-you-include-useful-details-in-your-done-email/rule.md
  rules/dones-do-your-dones-include-a-url/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8292 Cms/calinator444/ssw.rules.content/rule/do you minimize team distractions/rule
  rules/do-you-minimize-team-distractions/customize-notification-settings.jpg
  rules/do-you-minimize-team-distractions/ensure-teams-always-on.jpg
  rules/do-you-minimize-team-distractions/only-show-feed.jpg
  rules/do-you-minimize-team-distractions/open-teams-settings.jpg
  rules/do-you-minimize-team-distractions/rule.md
  rules/do-you-minimize-team-distractions/teams-open-on-startup.jpg
Labels: Age: 🐓 - Old

#8305 Fix typo on the rules I created recently
  rules/allocate-expenses-per-office/rule.md
  rules/manage-travel-in-centralized-systems/rule.md
Labels: Age: 🐤 - Mature

#8307 Update Rule “do-you-have-mfa-multi-factor-authentication-enabled/rule”
  categories/infrastructure-and-networking/rules-to-better-system-administrators.md
  rules/multi-factor-authentication-enabled/rule.md
Labels: Age: 🥚 - New

#8223 Migrating Rule “use-nunit-to-write-unit-tests/rule”
  rules/use-nunit-to-write-unit-tests/rule.md
  rules/use-nunit-to-write-unit-tests/unittestsinhelpmenu.jpg
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8303 📄 Rule - Find your License
  categories/software-engineering/rules-to-better-github.md
  categories/software-engineering/rules-to-better-open-source-software.md
  rules/find-your-license/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8308 Migrating Rule “desired-features-of-structuring-large-builds-in-vsnet/rule”
  rules/desired-features-of-structuring-large-builds-in-vsnet/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8314 XS✔ ◾ Fix bad markdown
  rules/manage-travel-in-centralized-systems/rule.md
Labels: Age: 🍗 - Ancient

#8315 Update Rule “brainstorming-idea-champion/rule”
  rules/brainstorming-idea-champion/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8319 XS✔ ◾ Fixing markdown + other internal standards
  rules/do-you-make-business-travel-easier/rule.md
Labels: Age: 🐣 - Young

#8320 XS✔ ◾ Adding a new redirect found by Google
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🐣 - Young

#8321 Assign category for SSW Rule: Do you make business travel easier
  categories/company-operations/rules-to-better-flights.md
Labels: Age: 🥚 - New

#8318 Create Rule “show-certification-award/rule”
  categories/company-operations/rules-to-better-accounting.md
  rules/show-certification-award/rule.md
Labels: Age: 🐓 - Old

#8317 Create Rule “show-long-service-leave-on-your-payslip/rule”
  categories/company-operations/rules-to-better-accounting.md
  rules/show-long-service-leave-on-your-payslip/bad-example-lsl.jpg
  rules/show-long-service-leave-on-your-payslip/good-example-lsl.jpg
  rules/show-long-service-leave-on-your-payslip/rule.md
Labels: Age: 🐓 - Old

#8323 XS✔ ◾ Spelling and grammar
  rules/what-is-mentoring/rule.md
Labels: Age: 🥚 - New

#8324 XS✔ ◾ Fixed image Markdown + other improvements
  rules/do-you-create-an-online-itinerary/rule.md
Labels: Age: 🥚 - New

#8326 Update Rule “do-you-encourage-your-boss-to-put-new-appointments-directly-into-his-phone/rule”
  rules/do-you-encourage-your-boss-to-put-new-appointments-directly-into-his-phone/rule.md
Labels: Age: 🐣 - Young

#8322 XS✔ ◾ Fix URI in Bicep user-defined data types rule
  rules/bicep-user-defined-data-types/rule.md
Labels: Age: 🐤 - Mature

#8329 XS✔ ◾ CodeAuditor - Fixed absolute internal links
  rules/communicate-your-product-status/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#8330 XS✔ ◾ Related capitalization rules
  rules/scrum-should-be-capitalized/rule.md
  rules/use-the-right-capitalization/rule.md
Labels: Age: 🐥 - Adolescent

#8331 XS✔ ◾ CodeAuditor - Fix absolute internal links
  rules/do-you-make-your-team-meetings-easy-to-find/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8332 XS✔ ◾ CodeAuditor - Fix absolute internal link
  rules/do-you-prepare-then-confirm-conversations-decisions/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8333 XS✔ ◾ CodeAuditor - Fix absolute internal path
  rules/typescript-enums/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8334 XS✔ ◾ CodeAuditor - Fix broken link
  rules/monitor-seo-effectively/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8336 XS✔ ◾ CodeAuditor - Fix common spelling mistake
  rules/turn-emails-into-pbis/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8325 XS✔ ◾ Update check-duplicate-images.yml
  .github/workflows/check-duplicate-images.yml
Labels: Age: 🐓 - Old

#8316 XS✔ ◾ Added missing image (unsure how it got missing)
  rules/multi-factor-authentication-enabled/backup-authenticator.jpg
  rules/multi-factor-authentication-enabled/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8209 Update Rule “disagreeing-with-powerful-stakeholders/rule”
  rules/disagreeing-with-powerful-stakeholders/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8337 XS✔ ◾ Fixed OK spelling mistakes
  rules/angular-separate-component-concerns/rule.md
  rules/business-cards-branding/rule.md
  rules/desk-setups/rule.md
  rules/disagreeing-with-powerful-stakeholders/rule.md
  rules/do-you-add-end-screen-to-your-youtube-videos/rule.md
  rules/do-you-avoid-using-out-of-office/rule.md
  rules/do-you-use-gzip/rule.md
  rules/document-discoveries/rule.md
  rules/follow-up-effectively/rule.md
  rules/forms-value/rule.md
  rules/implement-business-logic-in-middle-tier/rule.md
  rules/make-complaints-a-positive-experience/rule.md
  rules/manage-youtube-livestream-content/rule.md
  rules/management-do-you-know-who-has-authority/rule.md
  rules/minimize-unrelated-interruptions/rule.md
  rules/review-automated-tests/rule.md
  rules/take-care-of-your-personal-presentation-for-remote-meetings/rule.md
  rules/tell-chatgpt-to-ask-questions/rule.md
  rules/ticks-crosses/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8340 XS✔ ◾ 🎨 Update Better Rules to SAFe - prioritise-value-streams-over-individual-projects
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/do-you-prioritize-value-streams-over-individual-projects/rule.md
Labels: Age: 🥚 - New

#8352 XS✔ ◾ fixing typo
  rules/use-pull-request-templates-to-communicate-expectations/rule.md
Labels: Age: 🥚 - New

#8354 XS✔ ◾ Fix pipeline 💚
  rules/allocate-expenses-per-office/rule.md
  rules/angular-separate-component-concerns/rule.md
  rules/bicep-user-defined-data-types/rule.md
  rules/brainstorming-idea-champion/rule.md
  rules/communicate-your-product-status/rule.md
  rules/desired-features-of-structuring-large-builds-in-vsnet/rule.md
  rules/disagreeing-with-powerful-stakeholders/rule.md
  rules/do-you-add-end-screen-to-your-youtube-videos/rule.md
  rules/do-you-create-an-online-itinerary/rule.md
  rules/do-you-establish-a-Lean-Agile-mindset-across-all-teams/rule.md
  rules/do-you-make-business-travel-easier/rule.md
  rules/document-discoveries/rule.md
  rules/find-your-license/rule.md
  rules/forms-value/rule.md
  rules/implement-business-logic-in-middle-tier/rule.md
  rules/limit-duration/rule.md
  rules/make-complaints-a-positive-experience/rule.md
  rules/manage-travel-in-centralized-systems/rule.md
  rules/manage-youtube-livestream-content/rule.md
  rules/minimize-unrelated-interruptions/rule.md
  rules/prioritise-value-streams-over-individual-projects/Adaption.png
  rules/prioritise-value-streams-over-individual-projects/Alignment.png
  rules/prioritise-value-streams-over-individual-projects/Deployment.png
  rules/prioritise-value-streams-over-individual-projects/rule.md
  rules/review-automated-tests/rule.md
  rules/show-certification-award/rule.md
  rules/show-long-service-leave-on-your-payslip/rule.md
  rules/take-care-of-your-personal-presentation-for-remote-meetings/rule.md
  rules/tell-chatgpt-to-ask-questions/rule.md
  rules/ticks-crosses/rule.md
  rules/use-nunit-to-write-unit-tests/rule.md
  rules/use-pull-request-templates-to-communicate-expectations/rule.md
  rules/use-the-right-capitalization/rule.md
  rules/what-is-mentoring/rule.md
Labels: Age: 🥚 - New

#8355 XS✔ ◾ Added related + improved title + other small changes
  rules/use-pull-request-templates-to-communicate-expectations/rule.md
Labels: Age: 🐣 - Young

#8356 XS✔ ◾ 📝 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Age: 🥚 - New

#8359 XS✔ ◾ 📝Added two sub headings on how sealed classes improve performance.
  rules/seal-your-classes-by-default/ArrayCovariance_PerfResults.png
  rules/seal-your-classes-by-default/ArrayCovariance_code.png
  rules/seal-your-classes-by-default/Casting_PerfResult.png
  rules/seal-your-classes-by-default/Casting_code.png
  rules/seal-your-classes-by-default/rule.md
Labels: Age: 🐤 - Mature

#8357 XS✔ ◾ 🎨 Update Better Rules to SAFe - Change folder names to match new URIs
  rules/ensure-compliance-and-governance-without-compromising-agility/Bad_over_compliance.jpeg
  rules/ensure-compliance-and-governance-without-compromising-agility/Good_compliance_and_agility.jpeg
  rules/ensure-compliance-and-governance-without-compromising-agility/rule.md
  rules/establish-a-Lean-Agile-mindset-across-all-teams/Consistency.png
  rules/establish-a-Lean-Agile-mindset-across-all-teams/Delivery.png
  rules/establish-a-Lean-Agile-mindset-across-all-teams/rule.md
  rules/foster-a-culture-of-relentless-improvement/rule.md
  rules/implement-DevOps-practices-for-continuous-delivery/Agile_Development.png
  rules/implement-DevOps-practices-for-continuous-delivery/DevOps_Collaboration.png
  rules/implement-DevOps-practices-for-continuous-delivery/Risky_deployments.png
  rules/implement-DevOps-practices-for-continuous-delivery/rule.md
  rules/involve-stakeholders-in-pi-planning/rule.md
  rules/measure-success-using-lean-agile-metrics/Data-Driven-Decisions.png
  rules/measure-success-using-lean-agile-metrics/rule.md
  rules/regularly-inspect-and-adapt-at-scale/rule.md
  rules/use-safe-to-align-multiple-scrum-teams/BadExample_Governance.png
  rules/use-safe-to-align-multiple-scrum-teams/Essential.png
  rules/use-safe-to-align-multiple-scrum-teams/Large_solution.png
  rules/utilize-a-release-train/Safe_RTE_Good.png
  rules/utilize-a-release-train/rule.md
Labels: Age: 🐤 - Mature

#8365 ✨ Moving rule for VB6 migration
  categories/software-engineering/index.md
  categories/software-engineering/rules-to-better-large-builds-in-visual-studionet.md
  categories/software-engineering/rules-to-better-vb6-migration-to-net.md
Labels: Age: 🐤 - Mature

#8364 Migrating Rule “use-net-built-in-visual-basic-upgrade-wizard/rule”
  rules/use-net-built-in-visual-basic-upgrade-wizard/2024-04-13_15-29-58.png
  rules/use-net-built-in-visual-basic-upgrade-wizard/rule.md
  rules/use-net-built-in-visual-basic-upgrade-wizard/vb6upgradereport.gif
  rules/use-net-built-in-visual-basic-upgrade-wizard/vbupgradewizard.gif
Labels: Age: 🐤 - Mature

#8363 Migrating Rule “do-you-know-why-you-should-move-vb6-applications-to-net/rule”
  rules/do-you-know-why-you-should-move-vb6-applications-to-net/rule.md
Labels: Age: 🐤 - Mature

#8362 Migrating Rule “use-visual-basic-6-upgrade-assessment-tool/rule”
  rules/use-visual-basic-6-upgrade-assessment-tool/rule.md
  rules/use-visual-basic-6-upgrade-assessment-tool/vbupgradeassessmenttool.gif
  rules/use-visual-basic-6-upgrade-assessment-tool/vbupgradeassessmenttoolestimate.gif
  rules/use-visual-basic-6-upgrade-assessment-tool/vbupgradeassessmenttoolguidance.gif
Labels: Age: 🐤 - Mature

#8361 Merge rule sections for "Desired features of structuring large builds in VS.NET"
  rules/desired-features-of-structuring-large-builds-in-vsnet/betterlargedotnet_fileref.gif
  rules/desired-features-of-structuring-large-builds-in-vsnet/betterlargedotnet_projref.gif
  rules/desired-features-of-structuring-large-builds-in-vsnet/rule.md
Labels: Age: 🐓 - Old

#8366 XS✔ ◾ Update rule.md
  rules/seal-your-classes-by-default/rule.md
Labels: Age: 🥚 - New

#8342 XS✔ ◾ 🎨 Update Better Rules to SAFe - implement-DevOps-practices-for-continuous-delivery
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/implement-DevOps-practices-for-continuous-delivery/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8343 XS✔ ◾ 🎨 Update Better Rules to SAFe - utilize-a-release-train
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/utilize-a-release-train/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8344 XS✔ ◾ 🎨 Update Better Rules to SAFe - involve-stakeholders-in-pi-planning
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/involve-stakeholders-in-pi-planning/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8345 XS✔ ◾ 🎨 Update Better Rules to SAFe - measure-success-using-lean-agile-metrics
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/measure-success-using-lean-agile-metrics/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8346 XS✔ ◾ 🎨 Update Better Rules to SAFe - do-you-regularly-inspect-and-adapt-at-scale
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/regularly-inspect-and-adapt-at-scale/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8347 XS✔ ◾ 🎨 Update Better Rules to SAFe - do-you-foster-a-culture-of-relentless-improvement
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/foster-a-culture-of-relentless-improvement/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8348 XS✔ ◾ 🎨 Update Better Rules to SAFe - do-you-ensure-compliance-and-governance-without-compromising-agility
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/ensure-compliance-and-governance-without-compromising-agility/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8368 XS✔ ◾ CodeAuditor - Fix broken link
  rules/dones-do-your-dones-include-a-url/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#8370 XS✔ ◾ Prioritise value streams - Use american spelling
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
  rules/prioritize-value-streams-over-individual-projects/Adaption.png
  rules/prioritize-value-streams-over-individual-projects/Alignment.png
  rules/prioritize-value-streams-over-individual-projects/Deployment.png
  rules/prioritize-value-streams-over-individual-projects/rule.md
Labels: Age: 🐥 - Adolescent

#8312 :memo: Moving large .NET projects rules
  categories/software-engineering/rules-to-better-large-builds-in-visual-studionet.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8311 Migrating Rule “scenarios-of-building-the-system/rule”
  rules/scenarios-of-building-the-system/betterlargedotnet_scenario.gif
  rules/scenarios-of-building-the-system/betterlargedotnet_scenario1.gif
  rules/scenarios-of-building-the-system/betterlargedotnet_scenario2.gif
  rules/scenarios-of-building-the-system/betterlargedotnet_scenario3.gif
  rules/scenarios-of-building-the-system/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8371 XS✔ ◾ Update rule common design patterns
  rules/do-you-know-the-common-design-patterns-part-1/rule.md
Labels: Age: 🐣 - Young

#8372 XS✔ ◾ updated rule - fixed formatting and added more content
  rules/do-you-know-the-common-design-patterns-part-2-example/rule.md
Labels: Age: 🥚 - New

#8369 XS✔ ◾ Good PRs - link to PR template rule
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🐓 - Old

#8375 XS✔ ◾ Merged similar lists + other improvements for consistency "limit-duration"
  rules/limit-duration/rule.md
Labels: Age: 🥚 - New

#8374 XS✔ ◾ Archived "do-you-have-a-consistent-search-results-screen-aka-the-google-grid"
  rules/do-you-have-a-consistent-search-results-screen-aka-the-google-grid/rule.md
Labels: Age: 🥚 - New

#8377 XS✔ ◾ Ensure PO and Scrum Master informed of URGENT email tasks
  rules/work-in-order-of-importance-aka-priorities/rule.md
Labels: Age: 🥚 - New

#8367 Create Rule “summary-recording-sprint-reviews/rule”
  rules/summary-recording-sprint-reviews/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8373 XS✔ ◾ Flights - remove unhelpful noise from subject
  rules/create-appointment-for-flights/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8378 XS✔ ◾ New question, example in "Communication - Do you know how to communicate Product Progress?"
  rules/communicate-your-product-status/product-roadmap.png
  rules/communicate-your-product-status/rule.md
  rules/communicate-your-product-status/sugarlearning-availability.png
  rules/communicate-your-product-status/sugarlearning-user-metrics.png
  rules/communicate-your-product-status/viva-goals-roadmap.png
Labels: Age: 🥚 - New

#8380 XS✔ ◾ Adding video to rule
  rules/do-you-know-the-common-design-patterns-part-1/rule.md
Labels: Age: 🥚 - New

#8382 XS✔ ◾ ♻️ Design patterns rules refactor
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  rules/code-against-interfaces/Code against interfaces - bad.png
  rules/code-against-interfaces/Code against interfaces - good.png
  rules/code-against-interfaces/rule.md
  rules/common-design-patterns/design-patterns.png
  rules/common-design-patterns/rule.md
  rules/dependency-injection/rule.md
  rules/do-you-know-the-common-design-patterns-part-1/rule.md
Labels: Age: 🥚 - New

#8383 XS✔ ◾ Design patterns - Add redirect from old part 2 rule url
  rules/common-design-patterns/rule.md
  rules/dependency-injection/rule.md
Labels: Age: 🐥 - Adolescent

#8384 XS✔ ◾ Added related + intro tag + improved title "/unique-office-backgrounds"
  rules/unique-office-backgrounds/rule.md
  rules/video-background/rule.md
Labels: Age: 🐤 - Mature

#8386 XS✔ ◾ ✨Added a video to rules to better SAFe
  categories/project-delivery/rules-to-better-scaled-agile-framework.md
Labels: Age: 🐣 - Young

#8390 XS✔ ◾ Archived rules-to-better-wpf-and-silverlight.md
  categories/software-engineering/rules-to-better-wpf-and-silverlight.md
Labels: Age: 🥚 - New

#8411 ✨ Moved remaining 4 rule categories from Software enginnering section
  categories/software-engineering/index.md
  categories/software-engineering/rules-to-better-command-lines.md
  categories/software-engineering/rules-to-better-dotnetnuke.md
  categories/software-engineering/rules-to-better-exchange-server.md
  categories/software-engineering/rules-to-better-windows-forms-applications-clickonce.md
Labels: Age: 🐓 - Old

#8392 Migrating Rule “the-assembly-and-file-version-should-be-the-same-by-default/rule”
  rules/the-assembly-and-file-version-should-be-the-same-by-default/rule.md
  rules/the-assembly-and-file-version-should-be-the-same-by-default/versionnumbers.gif
Labels: Age: 🐓 - Old

#8393 Migrating Rule “keep-the-version-in-sync/rule”
  rules/keep-the-version-in-sync/rule.md
Labels: Age: 🐓 - Old

#8394 Migrating Rule “set-the-appropriate-download-for-your-web-users/rule”
  rules/set-the-appropriate-download-for-your-web-users/rule.md
Labels: Age: 🐓 - Old

#8395 Migrating ule “using-a-clickonce-version-application/rule”
  rules/using-a-clickonce-version-application/clickoncesymbol.jpg
  rules/using-a-clickonce-version-application/nonclickonce.jpg
  rules/using-a-clickonce-version-application/rule.md
Labels: Age: 🐓 - Old

#8397 Migrating Rule “use-async-code-to-do-the-check-for-update/rule”
  rules/use-async-code-to-do-the-check-for-update/rule.md
Labels: Age: 🐓 - Old

#8399 Migrating Rule “pros-and-cons-of-dotnetnuke/rule”
  rules/pros-and-cons-of-dotnetnuke/rule.md
Labels: Age: 🐓 - Old

#8401 Migrating Rule “latest-dnn-version/rule”
  rules/latest-dnn-version/dnnlatestversion.jpg
  rules/latest-dnn-version/dnnoldversion.jpg
  rules/latest-dnn-version/rule.md
Labels: Age: 🐓 - Old

#8400 Migrating Rule “ssw-dotnetnuke-induction-training/rule”
  rules/ssw-dotnetnuke-induction-training/rule.md
Labels: Age: 🐓 - Old

#8402 Migrating Rule “update-the-dotnetnuke-style-sheets-to-underline-a-link/rule”
  rules/update-the-dotnetnuke-style-sheets-to-underline-a-link/rule.md
Labels: Age: 🐓 - Old

#8403 Migrating Rule “dnn-can-update-the-schema-of-your-database-without-warning/rule”
  rules/dnn-can-update-the-schema-of-your-database-without-warning/rule.md
Labels: Age: 🐓 - Old

#8410 Migrating Rule “provide-list-of-arguments/rule”
  rules/provide-list-of-arguments/listofarguments.jpg
  rules/provide-list-of-arguments/nolistofarguments.jpg
  rules/provide-list-of-arguments/rule.md
Labels: Age: 🐓 - Old

#8409 Migrating Rule “ui-by-default-when-you-type-applicationname-exe/rule”
  rules/ui-by-default-when-you-type-applicationname-exe/commandlineopenuiwithargument.jpg
  rules/ui-by-default-when-you-type-applicationname-exe/commandlineopenuiwithoutargument.jpg
  rules/ui-by-default-when-you-type-applicationname-exe/rule.md
Labels: Age: 🐓 - Old

#8408 Migrating Rule “ui-for-a-command-line-utility/rule”
  rules/ui-for-a-command-line-utility/commandlinewithoutui.jpg
  rules/ui-for-a-command-line-utility/commandlinewithui.jpg
  rules/ui-for-a-command-line-utility/rule.md
Labels: Age: 🐓 - Old

#8389 XS✔ ◾ Removed 404 link - https://www.ssw.com.au/rules/screenshots-tools/
  rules/screenshots-tools/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#8414 Improve "Communication - Do you know how to communicate product progress?"
  rules/communicate-your-product-status/rule.md
Labels: Age: 🥚 - New

#8413 XS✔ ◾ Create Severity Levels rule
  categories/project-delivery/rules-to-better-scrum.md
  rules/do-you-assign-severity-to-pbi/rule.md
Labels: Age: 🐥 - Adolescent

#8415 XS✔ ◾ Touch once rule - change from 5 to 15 minutes
  rules/the-touch-it-once-principle/rule.md
Labels: Age: 🥚 - New

#8416 XS✔ ◾ 📄 Update | Do you know the client is not "always' right?
  rules/do-you-know-the-client-is-not-_always_-right/rule.md
Labels: Age: 🥚 - New

#8412 XS✔ ◾ Spec Review presentation - from desision to decision
  rules/specification-review-presentation/rule.md
  rules/specification-review-presentation/spec-review-decision-makers.jpg
Labels: Age: 🐓 - Old

#8387 Update photo on “cars-branding/rule”
  rules/cars-branding/car-stickers-good.jpg
  rules/cars-branding/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8388 XS✔ ◾ Improved title and captions "/prefix-job-title"
  rules/employees-branding/rule.md
  rules/prefix-job-title/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8417 XS✔ ◾ Weekly client love - improving content and shorten URI's
  categories/client-engagement/rules-to-better-account-management.md
  categories/client-engagement/rules-to-better-sales.md
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
  rules/client-love-after-initial-meeting/rule.md
  rules/do-you-build-the-client-relationship-by-completing-client-love-each-week-aka-customer-love/rule.md
  rules/do-you-review-your-team-are-giving-client-love-to-your-customer-every-friday/rule.md
  rules/do-you-send-some-client-love-a-few-days-after-the-initial-meeting/rule.md
  rules/encourage-client-love/rule.md
  rules/weekly-client-love/LoveClientsImage.jpg
  rules/weekly-client-love/rule.md
Labels: Age: 🐥 - Adolescent

#8418 XS✔ ◾ Added link back and forth related rules
  rules/dones-do-your-dones-include-a-url/rule.md
  rules/merge-debt/rule.md
Labels: Age: 🐥 - Adolescent

#8419 XS✔ ◾ Geordie88 patch 2
  rules/weekly-client-love/Keyboard-Heart.jpg
  rules/weekly-client-love/rule.md
Labels: Age: 🐤 - Mature

#8405 Migrating Rule “enable-the-search/rule”
  rules/enable-the-search/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8406 Migrating Rule “customise-outlook-web-access-owa/rule”
  rules/customise-outlook-web-access-owa/custom-owa-bad.jpg
  rules/customise-outlook-web-access-owa/custom-owa.jpg
  rules/customise-outlook-web-access-owa/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8425 XS✔ ◾ Added orphaned rules
  categories/project-delivery/rules-to-better-scrum-using-github.md
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  categories/software-engineering/rules-to-better-power-apps.md
Labels: Age: 🥚 - New

#8424 XS✔ ◾ Fixed link
  rules/there-should-be-a-standard-menu-item-check-for-updates/rule.md
Labels: Age: 🥚 - New

#8426 XS✔ ◾ Improving readablility
  rules/value-of-existing-clients/rule.md
Labels: Age: 🥚 - New

#8427 XS✔ ◾ Added info box to "avoid-repetition/#emojis"
  rules/use-emojis/rule.md
Labels: Age: 🥚 - New

#8430 XS✔ ◾ Further improve "Do you know how to communicate product progress?"
  rules/communicate-your-product-status/github-product-roadmap.png
  rules/communicate-your-product-status/rule.md
  rules/communicate-your-product-status/sugarlearning-availability.png
  rules/communicate-your-product-status/sugarlearning-user-metrics.png
  rules/communicate-your-product-status/user-metrics.png
Labels: Age: 🥚 - New

#8428 XS✔ ◾ Improving readability "/avoid-repetition/#emojis"
  rules/avoid-repetition/rule.md
Labels: Age: 🥚 - New

#8431 XS✔ ◾ Commenting Code - Place 2nd half of split comment on separate line
  rules/what-to-do-with-comments-and-debug-print-statements/rule.md
Labels: Age: 🐤 - Mature

#8420 XS✔ ◾ Adding related rules + content improvements
  rules/meaningful-pbi-titles/rule.md
  rules/work-in-order-of-importance-aka-priorities/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8436 XS✔ ◾ Client love - add APOC email
  rules/weekly-client-love/rule.md
Labels: Age: 🥚 - New

#8437 XS✔ ◾ Client love - improvements
  rules/weekly-client-love/rule.md
Labels: Age: 🥚 - New

#8433 XS✔ ◾ added orphaned rule
  categories/company-operations/rules-to-better-flights.md
Labels: Age: 🐤 - Mature

#8438 XS✔ ◾ Client love - fixing link
  rules/weekly-client-love/rule.md
Labels: Age: 🥚 - New

#8443 XS✔ ◾ Improvments to "/go-beyond-just-using-chat"
  categories/communication/rules-to-better-im.md
  rules/go-beyond-just-using-chat/rule.md
Labels: Age: 🥚 - New

#8442 XS✔ ◾ Fixed links + improved headings "value-of-existing-clients"
  rules/value-of-existing-clients/rule.md
Labels: Age: 🐥 - Adolescent

#8441 XS✔ ◾ Removed broken link "weekly-client-love"
  rules/weekly-client-love/rule.md
Labels: Age: 🐥 - Adolescent

#8429 XS✔ ◾ Added link + improved wording "do-you-prioritize-your-existing-client…
  rules/do-you-prioritize-your-existing-clients-over-prospective-ones/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8444 XS✔ ◾ Updated title "teams-usage"
  rules/teams-usage/rule.md
Labels: Age: 🐣 - Young

#8423 XS✔ ◾ Update rules-to-better-websites-layout-and-formatting.md
  categories/design/rules-to-better-websites-layout-and-formatting.md
  rules/create-a-combo-box-that-has-a-custom-template/rule.md
Labels: rubber stamp, Age: 🍗 - Ancient, 🔥 Merge Debt

#8422 XS✔ ◾ Removed duplicated link
  rules/monitor-seo-effectively/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8445 XS✔ ◾ Fixing broken links
  rules/value-of-existing-clients/rule.md
  rules/weekly-client-love/rule.md
Labels: Age: 🥚 - New

#8447 XS✔ ◾ Link Product Roadmap with Product Goal
  rules/roadmap/rule.md
Labels: Age: 🐥 - Adolescent

#8446 XS✔ ◾ Adds preferred location for Product Goal to 3 Scrum Commitments
  rules/the-3-commitments-in-scrum/rule.md
Labels: Age: 🐥 - Adolescent

#8451 XS✔ ◾ Update rules-to-better-technical-documentation.md
  categories/communication/rules-to-better-technical-documentation.md
  rules/avoid-common-mistakes/rule.md
Labels: Age: 🥚 - New

#8452 XS✔ ◾ Fixed rule URL "create-pbis-under-2-days"
  categories/client-engagement/rules-to-better-specification-reviews.md
  rules/create-PBIs-under-2-days/rule.md
Labels: Age: 🥚 - New

#8460 XS✔ ◾ Removed duplicated URL from rules-to-better-blazor.md
  categories/software-engineering/rules-to-better-blazor.md
Labels: rubber stamp, Age: 🥚 - New

#8463 XS✔ ◾ Fixed URLs rules-to-better-windows-forms-applications.md
  categories/software-engineering/rules-to-better-windows-forms-applications.md
Labels: Age: 🐤 - Mature

#8465 XS✔ ◾ Fixes autonomy-mastery-and-purpose
  rules/autonomy-mastery-and-purpose/rule.md
Labels: rubber stamp, Age: 🥚 - New

#8456 XS✔ ◾ Fixed rule URI casing "call-sysadmins-before-formatting-company-owned-laptops"
  categories/infrastructure-and-networking/rules-to-better-pcs.md
Labels: rubber stamp, Age: 🍗 - Ancient, 🔥 Merge Debt

#8454 Added image to close off thread rule
  rules/close-off-thread/done-see-email.png
  rules/close-off-thread/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8455 XS✔ ◾ Fix URLs for "conduct-a-test-please"
  categories/company-operations/rules-to-successful-projects.md
  rules/conduct-a-test-please/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8453 XS✔ ◾ Fixed renamed rule on how-to-enter-a-xero-me-receipt
  categories/company-operations/rules-to-better-accounting.md
  rules/how-to-enter-a-xero-me-receipt/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8457 XS✔ ◾ Fixed URL "consistent-sharepoint-sites"
  categories/infrastructure-and-networking/rules-to-better-sharepoint-for-end-users.md
  categories/software-engineering/rules-to-better-sharepoint-for-developers.md
Labels: rubber stamp, Age: 🍗 - Ancient, 🔥 Merge Debt

#8458 XS✔ ◾ Fixed URLs under video production
  categories/marketing-and-video/rules-to-better-video-recording.md
  rules/chatgpt-prompts-for-video-production/rule.md
  rules/do-you-know-how-to-record-the-screen-on-a-mac/rule.md
  rules/review-videos-collaboratively/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8459 XS✔ ◾ Fixed URLs on tfs 2010 and 2015 migration
  categories/project-delivery/rules-to-better-tfs-2010-migration.md
  categories/project-delivery/rules-to-better-tfs-2015-migration.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8461 XS✔ ◾ Removed URL not found rules-to-better-entity-framework.md
  categories/software-engineering/rules-to-better-entity-framework.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8462 XS✔ ◾ Improved URL and updated links "add-redirect-from-http-to-https-for-owa"
  categories/software-engineering/rules-to-better-exchange-server.md
  rules/add-redirect-from-http-to-https-for-owa/rule.md
  rules/do-you-add-a-redirect-from-http-to-https-for-owa/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8466 XS✔ ◾ Add Workflow to Trigger Rules Build
  .github/workflows/TriggerRulesBuild.yml
Labels: code change, Age: 🥚 - New

#8467 XS✔ ◾ Adding Strasbourg to the list of offices
  rules/elevator-pitch/rule.md
Labels: Age: 🥚 - New

#8469 Update Rule “autonomy-mastery-and-purpose/rule”
  rules/autonomy-mastery-and-purpose/rule.md
Labels: Age: 🥚 - New

#8472 XS✔ ◾ Rename the folders to match the rules URI
  rules/a-way-of-selling-tickets/rule.md
  rules/block-lsass-credential-dumping/credential-guard-gpo.png
  rules/block-lsass-credential-dumping/credential-guard-mem.png
  rules/block-lsass-credential-dumping/lsass-dump.png
  rules/block-lsass-credential-dumping/rule.md
  rules/bring-evaluation-forms-to-every-event-you-speak-at/rule.md
  rules/catering-for-events/rule.md
  rules/check-the-calendar-when-planning-an-event/rule.md
  rules/contact-the-media-from-time-to-time/rule.md
  rules/content-marketing-strategy-for-your-business/contentmkt.png
  rules/content-marketing-strategy-for-your-business/rule.md
  rules/contract-before-work/rule.md
  rules/devops-master/rule.md
  rules/do-you-assign-severity-levels/rule.md
  rules/do-you-receive-copy-of-your-email-into-your-inbox/outlook-web-enable-group-settings.jpg
  rules/do-you-receive-copy-of-your-email-into-your-inbox/rule.md
  rules/evaluate-your-event-feedback/rule.md
  rules/have-a-consistent-brand-image/rule.md
  rules/migration-plans/good-example-vs-bad-example-tfms.png
  rules/migration-plans/legacy-vs-sdk.png
  rules/migration-plans/related-runtimes.png
  rules/migration-plans/rule.md
  rules/minimum-number-for-live-events/rule.md
  rules/testing-pyramid/bug-filter.jpg
  rules/testing-pyramid/rule.md
  rules/testing-pyramid/test-pyramid-cohn.jpg
  rules/use-and-indicate-draft-pull-requests/devops-good-example.png
  rules/use-and-indicate-draft-pull-requests/github-bad-example.png
  rules/use-and-indicate-draft-pull-requests/github-good-example.png
  rules/use-and-indicate-draft-pull-requests/github-wip.png
  rules/use-and-indicate-draft-pull-requests/rule.md
  rules/use-https-text/rule.md
  rules/use-https-text/url-https-image-1.png
  rules/use-https-text/url-https-image-2.png
Labels: Age: 🥚 - New
