Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-05, with the labels that each got.

#8479 XS✔ ◾ Use-github-app-authentication
  .github/dependabot.yml
  .github/workflows/SyncIssuesToDevOps.yml
  .github/workflows/Trigger-DevOps-Staging-Build.yml
  .github/workflows/TriggerDevOpsBuild.yml
  .github/workflows/check-duplicate-images.yml
  .github/workflows/check-extension-case.yml
  .github/workflows/check-images.yml
  .github/workflows/main-trigger-rules-deploy.yml
  .github/workflows/pr-manage-stale.yml
  .github/workflows/pr-metrics.yml
  .github/workflows/zz-update-history.yml
Labels: Age: 🥚 - New

#8483 XS✔ ◾ cross repo build - specify owner/repo to generate the token for
  .github/workflows/main-trigger-rules-deploy.yml
Labels: Age: 🥚 - New

#8475 LinkedIn - How to connect rule - Integrating Adam's feedback
  rules/linkedin-connect-with-people/rules.md
Labels: Age: 🐤 - Mature

#8487 XS✔ ◾ 📄 Update Rule - Do you know how to Connect on LinkedIn
  rules/linkedin-connect-with-people/rules.md
Labels: Age: 🥚 - New

#8484 XS✔ ◾ LinkedIn QR Scanner addition
  rules/business-cards-branding/linkedin-qr-code.png
  rules/business-cards-branding/rule.md
Labels: Age: 🐓 - Old

#8490 XS✔ ◾ Update rule.md
  rules/checked-by-xxx/rule.md
Labels: Age: 🥚 - New

#8489 XS✔ ◾ Modified 'for-the-record' rule
  rules/for-the-record/disagree-and-commit.png
  rules/for-the-record/rule.md
  rules/for-the-record/winning-by-attrition.png
Labels: Age: 🥚 - New

#8493 XS✔ ◾ CodeAuditor - Fix broken link
  rules/how-to-see-what-is-going-on-in-your-project/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8496 XS✔ ◾ Reduced QR code image size + other improvements "bussiness-cards"
  rules/business-cards-branding/rule.md
Labels: Age: 🐣 - Young

#8396 Migrating Rule “use-click-once-or-msi/rule”
  rules/use-click-once-or-msi/clickonce_publishtab.gif
  rules/use-click-once-or-msi/clickonce_publishwizard.gif
  rules/use-click-once-or-msi/clickonce_securitytab.gif
  rules/use-click-once-or-msi/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8503 XS✔ ◾ fixed syntax and video title
  rules/for-the-record/rule.md
Labels: Age: 🥚 - New

#8502 Added Shorts video to Rule “the-value-of-consistency/rule”
  rules/the-value-of-consistency/rule.md
Labels: Age: 🥚 - New

#8404 Migrating Rule “upgrade-dnn-to-the-latest-version/rule”
  rules/upgrade-dnn-to-the-latest-version/2024-04-20_13-29-45.png
  rules/upgrade-dnn-to-the-latest-version/automaticupgraderunning.jpg
  rules/upgrade-dnn-to-the-latest-version/latestversionandnoupgrade.jpg
  rules/upgrade-dnn-to-the-latest-version/nomaintenance.jpg
  rules/upgrade-dnn-to-the-latest-version/putunderline.jpg
  rules/upgrade-dnn-to-the-latest-version/removeunderline.jpg
  rules/upgrade-dnn-to-the-latest-version/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8398 Migrating Rule “what-the-user-experience-should-be-like/rule”
  rules/what-the-user-experience-should-be-like/checkforupdate_skype.png
  rules/what-the-user-experience-should-be-like/checkforupdate_snagit.png
  rules/what-the-user-experience-should-be-like/codeauditorupdater.png
  rules/what-the-user-experience-should-be-like/diagnosticsupdater01.jpg
  rules/what-the-user-experience-should-be-like/diagnosticsupdater02.jpg
  rules/what-the-user-experience-should-be-like/diagnosticsupdater03.jpg
  rules/what-the-user-experience-should-be-like/diagnosticsupdater04.jpg
  rules/what-the-user-experience-should-be-like/diagnosticsupdater05.jpg
  rules/what-the-user-experience-should-be-like/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8507 XS✔ ◾ Update rule.md
  rules/use-right-site-search-for-your-website/rule.md
Labels: Age: 🥚 - New

#8505 Reduced image + added SEO description + intro to “business-cards-branding/rule”
  rules/business-cards-branding/linkedin-qr-code.png
  rules/business-cards-branding/rule.md
Labels: Age: 🐥 - Adolescent

#8509 XS✔ ◾ Added orphaned rules to categories
  categories/marketing-and-video/rules-to-better-branding.md
  categories/software-engineering/rules-to-better-power-platform.md
Labels: Age: 🥚 - New

#8510 XS✔ ◾ Archived old rule "do-your-label-beside-input-control-have-colon"
  rules/do-your-label-beside-input-control-have-colon/rule.md
Labels: Age: 🥚 - New

#8506 XS✔ ◾ Updated URIs from rules-to-better-windows-forms-applicati…
  categories/software-engineering/rules-to-better-windows-forms-applications.md
Labels: Age: 🐓 - Old

#8512 modernizing rule
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#8511 XS✔ ◾ Update rules-to-better-crm-for-users.md
  categories/company-operations/rules-to-better-crm-for-users.md
Labels: Age: 🐤 - Mature

#8515 Update Rule “shadow-spec-reviews/rule”
  rules/shadow-spec-reviews/rule.md
Labels: Age: 🐤 - Mature

#8514 XS✔ ◾ Changed fire emoji to warning emoji
  rules/allow-multiple-options/rule.md
  rules/do-you-keep-your-presentations-in-a-public-location/rule.md
  rules/migrate-an-existing-user-store-to-an-externalauthprovider/rule.md
  rules/turn-emails-into-a-github-issue/rule.md
  rules/use-icons-sharepoint/rule.md
  rules/use-zendesk-trigger-and-automation/rule.md
  rules/work-in-order-of-importance-aka-priorities/rule.md
Labels: Age: 🐤 - Mature

#8516 XS✔ ◾ Archived irrelevant Re: Do you make yoursel available for emergency c…
  rules/be-available-for-emergency-communication/rule.md
Labels: Age: 🥚 - New

#8518 XS✔ ◾ Update rules-to-better-office-operations.md
  categories/company-operations/rules-to-better-office-operations.md
Labels: Age: 🥚 - New

#8519 XS✔ ◾ Reduce Admin - fix email template
  rules/reduce-your-admin/rule.md
Labels: Age: 🥚 - New

#8523 XS✔ ◾ Update rules-to-better-office-operations.md
  categories/company-operations/rules-to-better-office-operations.md
Labels: Age: 🥚 - New

#8529 XS✔ ◾ Update rules-to-better-health-and-exercise-in-the-workplace.md
  categories/company-operations/rules-to-better-health-and-exercise-in-the-workplace.md
Labels: Age: 🥚 - New

#8527 XS✔ ◾ update-screenshots-and-remove-password-instruction
  rules/set-up-your-mailbox-in-crm/crm-open-mailbox-settings.png
  rules/set-up-your-mailbox-in-crm/rule.md
  rules/set-up-your-mailbox-in-crm/setup-mailbox-crm.png
Labels: Age: 🐤 - Mature

#8526 XS✔ ◾ small grammar changes + add PO check and Sprint Backlog
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🐤 - Mature

#8525 XS✔ ◾ Punctuation and Typo changes
  rules/8-steps-to-scrum/rule.md
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
  rules/meetings-are-you-prepared-for-the-initial-meeting/rule.md
  rules/what-happens-at-a-sprint-planning-meeting/rule.md
Labels: Age: 🐓 - Old

#8524 Update Rule “sales-people-to-work-together-and-keep-each-other-accountable/rule”
  rules/sales-people-to-work-together-and-keep-each-other-accountable/rule.md
Labels: Age: 🐓 - Old

#8521 Update Rule “know-where-your-staff-are/rule”
  rules/know-where-your-staff-are/rule.md
Labels: Age: 🐓 - Old

#8531 XS✔ ◾ Improved title + SEO description "reduce-your-admin"
  rules/reduce-your-admin/rule.md
Labels: Age: 🥚 - New

#8535 XS✔ ◾ Update rule.md
  rules/checked-by-xxx/rule.md
Labels: Age: 🥚 - New

#8538 XS✔ ◾ update rule how to share file folder in sharepoint
  rules/avoid-using-share-functionality/rule.md
  rules/how-to-share-a-file-folder-in-sharepoint/rule.md
  rules/how-to-share-a-file-folder-in-sharepoint/sharepoint-choose-existing-access.png
  rules/how-to-share-a-file-folder-in-sharepoint/sharepoint-link.jpg
  rules/how-to-share-a-file-folder-in-sharepoint/sharepoint-share-email-invite.png
Labels: Age: 🥚 - New

#8540 XS⚠️ ◾ ✨ Add Github Action to Check Folder Name
  .github/workflows/check-folder-name.yml
  .workflow/rename-folders.sh
Labels: code change, Age: 🐓 - Old

#8541 Update rule - Do you know how to share a file/folder in SharePoint.md
  rules/how-to-share-a-file-folder-in-sharepoint/rule.md
Labels: Age: 🐥 - Adolescent

#8542 XS✔ ◾ Update check-folder-name.yml
  .github/workflows/check-folder-name.yml
Labels: Age: 🥚 - New

#8545 XS✔ ◾ Update Do you know how to connect on LinkedIn?
  rules/linkedin-connect-with-people/rules.md
Labels: Age: 🥚 - New

#8546 Update rule-How to share a file folder in SharePoint.md
  rules/how-to-share-a-file-folder-in-sharepoint/rule.md
Labels: Age: 🥚 - New

#8547 XS✔ ◾ Update rule - Do you recognize the effects of anchoring
  rules/recognize-anchoring-effects/rule.md
Labels: Age: 🐓 - Old

#8548 Update Rule “weekly-client-love/rule”
  rules/weekly-client-love/rule.md
Labels: Age: 🐤 - Mature

#8552 XS✔ ◾ Update rule.md
  rules/do-you-create-an-online-itinerary/rule.md
Labels: Age: 🥚 - New

#8553 XS✔ ◾ Amending rule warn to call
  rules/warn-then-call/rule.md
Labels: Age: 🥚 - New

#8554 XS✔ ◾ Update presentation rule.md
  rules/craft-and-deliver-engaging-presentations/rule.md
Labels: Age: 🥚 - New

#8555 XS✔ ◾ Update the Rule on how Google ranks pages for 2024
  rules/how-google-ranks-pages/rule.md
Labels: Age: 🥚 - New

#8556 Update rule.md
  rules/how-google-ranks-pages/rule.md
Labels: Age: 🥚 - New

#8544 Update Rule “reduce-your-admin/rule”
  rules/reduce-your-admin/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8549 Added rule: "Do you check your API serialisation format?"
  categories/software-engineering/rules-to-better-net8-migrations.md
  rules/do-you-check-your-api-serialisation-format/rule.md
  rules/dotnet-upgrade-for-complex-projects/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8558 XS✔ ◾ Update rule - Do you warn then call
  rules/warn-then-call/rule.md
Labels: Age: 🥚 - New

#8559 Update rule.md
  rules/how-google-ranks-pages/rule.md
Labels: Age: 🥚 - New

#8560 XS✔ ◾ Add guidance for how to write a rule
  rules/rule/rule.md
Labels: Age: 🥚 - New

#8561 XS✔ ◾ updating rule - ppc ads tracking
  do-you-know-how-to-keep-track-of-your-ppc-campaign-spend/Campaign-PPC-Spend.xlsx
  rules/do-you-know-how-to-keep-track-of-your-ppc-campaign-spend/rule.md
  rules/track-ppc-campaign-spend/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8565 XS✔ ◾ Update rules-to-better-social-media-for-business.md
  categories/marketing-and-video/rules-to-better-social-media-for-business.md
Labels: Age: 🥚 - New

#8562 XS✔ ◾ New rule - monthly stakeholder videos
  categories/company-operations/rules-to-better-business-management.md
  rules/monthly-stakeholder-video/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8563 XS✔ ◾ Update rules-to-better-accounting.md
  categories/company-operations/rules-to-better-accounting.md
Labels: Age: 🥚 - New

#8568 XS✔ ◾ Update rule.md
  rules/track-ppc-campaign-spend/rule.md
Labels: Age: 🥚 - New

#8569 XS✔ ◾ Update rules-to-better-business-management.md
  categories/company-operations/rules-to-better-business-management.md
  rules/monthly-stakeholder-video/rule.md
Labels: Age: 🥚 - New

#8570 XS✔ ◾ Connect on LinkedIn Update Image
  rules/linkedin-connect-with-people/linkedin-personalize-invite.jpg
  rules/linkedin-connect-with-people/personnalize-invite.jpeg
  rules/linkedin-connect-with-people/rules.md
Labels: Age: 🐤 - Mature

#8572 XS✔ ◾ Update rule.md
  rules/use-var/rule.md
Labels: Age: 🐓 - Old

#8575 XS✔ ◾ Improving readability "harnessing-the-power-of-no/"
  rules/harnessing-the-power-of-no/rule.md
Labels: Age: 🐥 - Adolescent

#8577 XS✔ ◾ Improved few things on "share social media" and "hashtags" rules
  categories/marketing-and-video/rules-to-better-social-media-for-business.md
  rules/best-way-to-share-a-social-media-post/rule.md
  rules/use-hashtags/rule.md
Labels: Age: 🥚 - New

#8578 XS✔ ◾ Sprint review email - Add tina image
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#8582 XS✔ ◾ Updating linkedin rule for camilla
  rules/reply-linkedin-messages/rule.md
Labels: Age: 🥚 - New

#8579 Sprint review email - upload image so its not remote
  rules/sprint-review-retro-email/rule.md
  rules/sprint-review-retro-email/tina-sprint-email.png
Labels: Age: 🐣 - Young

#8585 XS✔ ◾ Rename folder
  rules/get-videos-approved/rule.md
Labels: Age: 🥚 - New

#8588 XS✔ ◾ kpis - make it clearer they are just a convo starter
  rules/employee-kpis/BobNorthwindKpis.png
  rules/employee-kpis/rule.md
Labels: Age: 🥚 - New

#8594 XS✔ ◾ Improved the last sentence which didn't make sense - KPIs rule
  rules/employee-kpis/rule.md
Labels: Age: 🥚 - New

#8593 Update Rule “write-integration-tests-to-validate-your-web-links/rule”
  rules/write-integration-tests-to-validate-your-web-links/rule.md
Labels: Age: 🐤 - Mature

#8601 XS✔ ◾ Fixed bad example + improved URL + better intro "use-images-to-replace-words"
  categories/design/rules-to-better-websites-layout-and-formatting.md
  figures-do-you-use-images-to-reduce-the-words/flower.jpg
  rules/figures-do-you-use-images-to-reduce-the-words/rule.md
  rules/screenshots-avoid-walls-of-text/rule.md
  rules/use-images-to-replace-words/rule.md
Labels: Age: 🐣 - Young

#8602 XS✔ ◾ Improved new section from Piers
  rules/rule/rule.md
Labels: Age: 🐣 - Young

#8600 Update Rule “specification-review-presentation/rule”
  rules/specification-review-presentation/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8603 XS✔ ◾ Added/Fixed some orphaned rules
  categories/marketing-and-video/rules-to-better-branding.md
  categories/marketing-and-video/rules-to-better-google-ads-and-sem.md
  categories/software-engineering/rules-to-better-sharepoint-for-developers.md
  categories/software-engineering/rules-to-better-websites-development.md
  rules/style-files-for-deployment-in-sharepoint/rule.md
Labels: Age: 🐓 - Old

#8598 Major updates to rule about version control for Power BI
  rules/do-you-use-version-control-with-power-bi/bad-example-publish-report-directly.png
  rules/do-you-use-version-control-with-power-bi/enable-pbip-format.png
  rules/do-you-use-version-control-with-power-bi/good-example-compare-changes.png
  rules/do-you-use-version-control-with-power-bi/good-example-history-recorded.png
  rules/do-you-use-version-control-with-power-bi/rule.md
  rules/do-you-use-version-control-with-power-bi/save-as-pbip.png
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8590 XS✔ ◾ Update rule "Do you thoroughly test employment candidates?"
  rules/do-you-thoroughly-test-employment-candidates/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8605 XS✔ ◾ Update rule "Do you thoroughly test employment candidates?"
  rules/do-you-thoroughly-test-employment-candidates/rule.md
Labels: Age: 🥚 - New

#8606 XS✔ ◾ brainstorming agenda - set overtime expectations
  rules/brainstorming-agenda/rule.md
Labels: Age: 🥚 - New

#8608 XS✔ ◾ brainstorming intro - set expectations
  rules/brainstorming-agenda/rule.md
  rules/brainstorming-intro-presentation/rule.md
Labels: Age: 🥚 - New

#8607 XS✔ ◾ Use var2
  categories/software-engineering/rules-to-better-code.md
  rules/use-var/rule.md
Labels: Age: 🐤 - Mature

#8604 Cms/calinator444/ssw.rules.content/rule/azure resources creating/rule
  rules/azure-resources-creating/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8610 Create Rule “best-online-documentation-site/rule”
  rules/best-online-documentation-site/rule.md
Labels: Age: 🥚 - New

#8615 XS✔ ◾ 3 steps to PBI - Add separate step for PR
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#8617 XS✔ ◾ Fixing folder name
  rules/new-job-certification-linkedin/linkedin-new-job-branded.png
  rules/new-job-certification-linkedin/linkedin-new-job-template.png
  rules/new-job-certification-linkedin/rule.md
Labels: Age: 🥚 - New

#8614 XS✔ ◾ update youtube prefix to correct embed link
  rules/craft-and-deliver-engaging-presentations/rule.md
Labels: Age: 🐥 - Adolescent

#8620 Create Rule “inform-others-about-chat-message-updates/rule”
  categories/communication/rules-to-better-im.md
  rules/inform-others-about-chat-message-updates/rule.md
  rules/inform-others-about-chat-message-updates/update-im-message-bad.png
  rules/inform-others-about-chat-message-updates/update-im-message-good.png
  rules/update-or-delete-mistakes/rule.md
Labels: Age: 🐣 - Young

#8621 XS✔ ◾ Improved URL + added another app option "what-happens-at-retro-meetings"
  categories/project-delivery/rules-to-better-scrum.md
  rules/what-happens-at-retro-meetings/rule.md
Labels: Age: 🥚 - New

#8622 XS✔ ◾ Improvements to "Do you build inter-office interaction?"
  rules/build-inter-office-interaction/rule.md
Labels: Age: 🥚 - New

#8612 XS✔ ◾ Improved readability "optimize-android-builds-and-start-up-times"
  rules/optimize-android-builds-and-start-up-times/rule.md
Labels: Age: 🐓 - Old

#8623 XS✔ ◾ Few more small fixes "build-inter-office-interaction"
  rules/build-inter-office-interaction/rule.md
Labels: Age: 🥚 - New

#8624 XS✔ ◾ Added related rule to Cultural Exchange rule
  rules/cultural-exchange/rule.md
Labels: Age: 🥚 - New

#8613 XS✔ ◾ MAUI | Improving the order of the rules
  categories/software-engineering/rules-to-better-maui.md
  rules/conduct-cross-platform-ui-tests/rule.md
  rules/dev-test-maui-apps/rule.md
  rules/use-design-time-data/rule.md
  rules/use-hot-reload/rule.md
Labels: Age: 🐓 - Old

#8625 XS✔ ◾ Defining the difference between "cut away" and "cutaway" -B-Roll
  rules/use-cutaways/rule.md
Labels: Age: 🥚 - New

#8627 XS✔ ◾ New rule - pitching a product
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
  rules/elevator-pitch/rule.md
  rules/pitch-a-product/llama-getting-elevated.jpg
  rules/pitch-a-product/rule.md
Labels: Age: 🥚 - New

#8629 XS✔ ◾ Update rule.md
  rules/pitch-a-product/rule.md
Labels: Age: 🥚 - New

#8631 XS✔ ◾ Related rules back and forth to each other
  rules/avoid-using-share-functionality/rule.md
  rules/change-link-sharing-default-behaviour/rule.md
Labels: Age: 🥚 - New

#8632 XS✔ ◾ trading backlinks with labelbox
  rules/leverage-chatgpt/rule.md
  rules/shot-prompts/rule.md
  rules/train-gpt/rule.md
Labels: Age: 🥚 - New
