Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-03, with the labels that each got.

#8029 XS✔ ◾ Made greybox a section for better visibility
  rules/reply-done-and-delete-the-email/rule.md
Labels: Age: 🥚 - New

#8032 XS✔ ◾ Update rule.md
  rules/digesting-brainstorming/rule.md
Labels: Age: 🐓 - Old

#8037 XS✔ ◾ Adding an image to "do you prepare then confirm conversations decisio…
  assets/as_per_our_conversation.webp
  rules/do-you-prepare-then-confirm-conversations-decisions/rule.md
Labels: Age: 🥚 - New

#8036 XS✔ ◾ Add figma uses rule to Figma category
  categories/design-and-presentation/rules-to-better-figma.md
Labels: Age: 🐣 - Young

#8031 Update Rule “figma-uses/rule”
  rules/figma-uses/rule.md
Labels: Age: 🐓 - Old

#8035 XS✔ ◾ Adding source to DNS picture
  rules/what-is-dns/rule.md
Labels: Age: 🐤 - Mature

#8033 Update Rule “do-you-manage-3rd-party-dependencies/rule”
  rules/do-you-manage-3rd-party-dependencies/rule.md
Labels: Age: 🐓 - Old

#8040 XS✔ ◾ updates and shorten URL for "standards-watchdog" rule
  categories/management/rules-to-better-software-consultants-working-in-a-team.md
  categories/management/rules-to-successful-projects.md
  rules/standards-watchdog/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8039 XS✔ ◾ Added vote link into an info box /report-bugs
  rules/report-bugs-and-suggestions/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8043 XS✔ ◾ Rename rule slug - Do you know what happens at a Sprint Planning meeting?
  categories/application-lifecycle-management-alm/rules-to-better-scrum.md
  rules/8-steps-to-scrum/rule.md
  rules/agreements-do-you-book-the-next-sprint-ahead-of-time/rule.md
  rules/do-you-know-the-how-to-be-a-good-product-owner/rule.md
  rules/do-you-know-what-happens-at-a-sprint-retrospective-meeting/rule.md
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
  rules/how-to-create-a-sprint-backlog/rule.md
  rules/meeting-do-you-update-your-tasks-before-the-daily-scrum/rule.md
  rules/scrum-master-do-you-schedule-the-3-meetings/rule.md
  rules/share-the-agenda/rule.md
  rules/sprint-forecast/rule.md
  rules/tick-and-flick/rule.md
  rules/what-happens-at-a-sprint-planning-meeting/PBI.png
  rules/what-happens-at-a-sprint-planning-meeting/rule.md
  rules/work-in-order-of-importance-aka-priorities/rule.md
Labels: Age: 🥚 - New

#8044 XS⚠️ ◾ Updated production deploy script
  .github/workflows/TriggerDevOpsBuild.yml
  .workflow/build-production.sh
Labels: code change, Age: 🥚 - New

#8045 XS⚠️ ◾ fixed variable
  .workflow/build-production.sh
Labels: Age: 🥚 - New

#8009 XS✔ ◾ Update rule.md - Fixing formatting
  categories/communication/rules-to-better-communication.md
  rules/do-you-know-the-best-tool-for-facilitating-real-time-colloboration/rule.md
  rules/power-automate-flows-convert-timezone/rule.md
  rules/tool-for-facilitating-real-time-collaboration/microsoft-loop-good-example.jpg
  rules/tool-for-facilitating-real-time-collaboration/onenote-bad-example.jpg
  rules/tool-for-facilitating-real-time-collaboration/rule.md
Labels: Age: 🥚 - New, Age: 🦖 - Extinct, 🔥 Merge Debt

#8046 XS✔ ◾ Small tweaks to Do you know what happens at a Sprint Planning meeting? content
  rules/what-happens-at-a-sprint-planning-meeting/rule.md
Labels: Age: 🥚 - New

#8047 Fixing line breaks
  rules/reply-done-and-delete-the-email/rule.md
Labels: Age: 🥚 - New

#8042 XS✔ ◾ Improving URI
  categories/management/rules-to-better-recruiting.md
  rules/find-excellent-candidates/rule.md
Labels: Age: 🐥 - Adolescent

#8051 XS✔ ◾ Add gap between lines to address Rule MD056 error
  rules/reply-done-and-delete-the-email/rule.md
Labels: Age: 🥚 - New

#8038 XS✔ ◾ ✨ New rule - Successful Reachouts
  categories/management/rules-to-better-recruiting.md
  rules/successful-reachouts/developer-reachout-spam.png
  rules/successful-reachouts/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8049 XS✔ ◾ update linting rules
  .markdownlint/config.json
Labels: rubber stamp, Age: 🐥 - Adolescent

#8052 XS✔ ◾ reachouts - make image smaller
  rules/successful-reachouts/rule.md
Labels: Age: 🐤 - Mature

#8053 XS✔ ◾ Loop someone in - add tip to record the summary
  rules/loop-someone-in/rule.md
Labels: Age: 🐥 - Adolescent

#8050 XS✔ ◾ Updated modular monolith rule
  rules/modular-monoliths/modular-monolith.jpg
  rules/modular-monoliths/rule.md
Labels: Age: 🐤 - Mature

#8059 XS✔ ◾ Update_As_Per_Our_Conversation_Rules.md
  assets/as_per_our_conversation.webp
  rules/as-per-our-conversation-emails/as_per_our_conversation.jpg
  rules/as-per-our-conversation-emails/rule.md
  rules/call-first-before-emailing/as_per_our_conversation.jpg
  rules/call-first-before-emailing/rule.md
  rules/do-you-prepare-then-confirm-conversations-decisions/as_per_our_conversation.jpg
  rules/do-you-prepare-then-confirm-conversations-decisions/rule.md
Labels: Age: 🥚 - New

#8058 Fixing a typo
  rules/unexpected-requests/rule.md
Labels: Age: 🐥 - Adolescent

#8057 Archive Rule "Do your page URL’s use dashes between words?"
  categories/websites/rules-to-better-websites-layout-and-formatting.md
  rules/use-dashes-between-words-in-urls/rule.md
Labels: Age: 🐥 - Adolescent

#8055 XS✔ ◾ Fixed related link + improved title + fixed placeholder
  rules/email-copy-to-raise-pbi-visibility/rule.md
Labels: Age: 🐤 - Mature

#8060 XS✔ ◾ Updated the "Do you prepare, then confirm conversations/decision" rule
  rules/as-per-our-conversation-emails/as_per_our_conversation.jpg
  rules/as-per-our-conversation-emails/rule.md
  rules/call-first-before-emailing/as_per_our_conversation.jpg
  rules/call-first-before-emailing/rule.md
  rules/do-you-prepare-then-confirm-conversations-decisions/rule.md
Labels: Age: 🥚 - New

#8056 Update Rule “book-developers-for-a-project/rule”
  rules/book-developers-for-a-project/dynamics-untrack.png
  rules/book-developers-for-a-project/rule.md
Labels: Age: 🐤 - Mature

#8061 XS✔ ◾ Fixed casing on rules-to-better-websites-layout-and-formatting.md
  categories/websites/rules-to-better-websites-layout-and-formatting.md
Labels: rubber stamp, Age: 🥚 - New

#8064 XS✔ ◾ Geordie88 patch 2
  categories/websites/rules-to-better-websites-layout-and-formatting.md
  rules/avoid-unnecessary-css-classes/rule.md
Labels: Age: 🥚 - New

#8062 Update Rule “close-off-thread/rule”
  rules/close-off-thread/rule.md
Labels: Age: 🥚 - New

#8063 XS✔ ◾ Added Matt G as acknowledgements for this rule.
  rules/migrate-an-existing-user-store-to-an-externalauthprovider/rule.md
Labels: Age: 🐣 - Young

#8066 XS✔ ◾ Updating good example
  rules/custom-instructions/custom-good.png
  rules/custom-instructions/rule.md
  rules/custom-instructions/seth-custom-instructions-good.jpg
Labels: Age: 🥚 - New

#8071 XS✔ ◾ Update URI in index
  categories/marketing-and-video/rules-to-better-websites-branding-and-marketing.md
Labels: Age: 🥚 - New

#8068 XS✔ ◾ update rule and add examples
  rules/do-you-gather-more-personal-information-progressively/rule-progressive-info-gathering-bad-example.png
  rules/do-you-gather-more-personal-information-progressively/rule-progressive-info-gathering-good-example.png
  rules/do-you-gather-more-personal-information-progressively/rule.md
  rules/gather-personal-information-progressively/rule.md
Labels: Age: 🐤 - Mature

#8073 XS✔ ◾ 📝 Re-categorise and archive orphaned rules
  categories/infrastructure-and-networking/rules-to-better-pcs.md
  categories/marketing-and-video/rules-to-better-social-media-paid-advertising.md
  rules/do-you-read-timeless-way-of-building-has-relevance-to-software/rule.md
  rules/do-you-review-the-builds/rule.md
  rules/do-you-use-part-of-sprint-review-to-drill-into-the-next-most-important-number-in-this-list/rule.md
  rules/do-you-use-the-web-api-rest/rule.md
  rules/memory-leak-do-you-look-for-native-code-thats-missing-dispose/rule.md
  rules/use-mobile-devops/rule.md
Labels: Age: 🥚 - New

#8075 XS✔ ◾ added figure captions
  rules/gather-personal-information-progressively/rule.md
Labels: Age: 🥚 - New

#8076 XS✔ ◾ Update full stops rule
  rules/avoid-full-stops-in-bullet-point-lists/rule.md
Labels: Age: 🥚 - New

#8065 XS✔ ◾ New rule JWTs - this weeks CTF.
  rules/do-you-know-how-modern-stateless-auth-works/jwt-how-its-used.png
  rules/do-you-know-how-modern-stateless-auth-works/rule.md
Labels: Age: 🐓 - Old

#8079 XS✔ ◾ Dhruv patch - embed the video properly.
  rules/do-you-know-how-modern-stateless-auth-works/rule.md
Labels: Age: 🥚 - New

#8081 XS✔ ◾ CTF rule intro fix - showing pain points.
  rules/do-you-know-how-modern-stateless-auth-works/rule.md
Labels: Age: 🥚 - New

#8082 XS⚠️ ◾ Updated Lint Frontmatter to Fix Schema Match Error
  scripts/frontmatter-validator/frontmatter-validator.js
Labels: Age: 🥚 - New

#8084 XS✔ ◾ Hand over - remove resignation stuff
  rules/hand-over/handover-project.gif
  rules/hand-over/rule.md
Labels: Age: 🥚 - New

#8086 XS✔ ◾ "Full-stop" rule - Fixing caption and trying to improve reading
  rules/avoid-full-stops-in-bullet-point-lists/rule.md
Labels: Age: 🥚 - New

#8070 XS✔ ◾ ✨ New rule - POC and MVP
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
  categories/client-engagement/rules-to-better-software-consultants-happy-clients.md
  categories/communication/rules-to-better-communication.md
  categories/company-operations/rules-to-better-research-and-development.md
  categories/company-operations/rules-to-successful-projects.md
  rules/poc-vs-mvp/rule.md
Labels: Age: 🐓 - Old

#8090 XS✔ ◾ fix rule modern-stateless-authentication
  rules/modern-stateless-authentication/jwt-how-its-used.png
  rules/modern-stateless-authentication/rule.md
Labels: Age: 🥚 - New

#8087 XS✔ ◾ Fixed title casing + added relevant link
  rules/corridor-conversations/rule.md
Labels: Age: 🐣 - Young

#8088 XS✔ ◾ Improved intro + moved links from "Extra" to related section
  rules/do-you-manage-clients-expectations/rule.md
Labels: Age: 🐣 - Young

#8085 XS✔ ◾ ✨ New rule - handover responsibilities
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  categories/company-operations/rules-to-successful-projects.md
  rules/hand-over-projects/handover-project.gif
  rules/hand-over-projects/rule.md
  rules/hand-over-resposibilities/angry-dev-beach.png
  rules/hand-over-resposibilities/rule.md
Labels: Age: 🐤 - Mature

#8094 XS✔ ◾ CodeAuditor - Fix using internal path
  rules/educate-your-developer/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#8093 XS✔ ◾ CodeAuditor - Fix using internal path
  rules/brainstorming-intro-presentation/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#8098 XS✔ ◾ ✨ New Rule - Do you use canonical tags to prevent duplicate content?
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  rules/seo-canonical-tags/rule.md
Labels: Age: 🐣 - Young

#8097 XS✔ ◾ no . in lists - change from 'better example' to 'ok example'
  rules/avoid-full-stops-in-bullet-point-lists/rule.md
Labels: Age: 🐣 - Young

#8095 Update rules-to-better-system-administrators.md
  categories/communication/rules-to-better-im.md
  categories/infrastructure-and-networking/rules-to-better-system-administrators.md
Labels: Age: 🐤 - Mature

#8099 XS✔ ◾ Fixed greybox
  rules/do-you-know-what-currency-to-quote-overseas/rule.md
Labels: Age: 🥚 - New

#8106 Create Rule “avoid-putting-connection-strings-in-business-module/rule”
  rules/avoid-putting-connection-strings-in-business-module/2024-03-09_16-10-24.png
  rules/avoid-putting-connection-strings-in-business-module/rule.md
Labels: Age: 🐤 - Mature

#8091 CODE ✨ Add Scheduled Checks for Duplicate Image Names
  .github/workflows/check-duplicate-images.yml
  scripts/rename-duplicate-images/rename-duplicate-images.js
Labels: code change, Age: 🦖 - Extinct, 🔥 Merge Debt

#8100 XS✔ ◾ Improved title and intro
  rules/include-annual-cost/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8111 XS✔ ◾ fixing redirects
  rules/cross-approvals/rule.md
Labels: Age: 🐥 - Adolescent

#8112 XS✔ ◾ fix images in rule
  assets/2015-web-essentials.jpg
  assets/gulp.jpg
  assets/npm-action.jpg
  rules/streamline-development-with-npm-and-task-runners/rule.md
Labels: Age: 🐣 - Young

#8105 Create Rule “how-to-make-connection-strings-in-different-environment/rule”
  rules/how-to-make-connection-strings-in-different-environment/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8108 Create Rule “avoid-using-non-strongly-typed-connection-strings/rule”
  rules/avoid-using-non-strongly-typed-connection-strings/conn.gif
  rules/avoid-using-non-strongly-typed-connection-strings/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8109 Create Rule “best-place-to-place-the-connection-string/rule”
  rules/best-place-to-place-the-connection-string/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8107 ✨ Conn string rule migration
  categories/software-engineering/index.md
  categories/software-engineering/rules-to-better-connection-strings.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8096 XS✔ ◾ Sprint review email - add timesheet data
  rules/sprint-review-retro-email/rule.md
  rules/sprint-review-retro-email/sprint-timesheet-data.png
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8113 XS✔ ◾ Fix broken build - archived reason includes colon “:”
  rules/avoid-using-non-strongly-typed-connection-strings/rule.md
Labels: Age: 🥚 - New

#8114 XS✔ ◾ Add comment to IApiMarker example
  rules/use-iapimarker-with-webapplicationfactory/Using-IApiMarker-interface.jpg
  rules/use-iapimarker-with-webapplicationfactory/rule.md
Labels: Age: 🥚 - New

#8110 Add rule on Power BI Template Apps
  categories/company-operations/rules-to-better-power-bi.md
  categories/reporting-solutions/index.md
  rules/powerbi-template-app/app-connect-data-authenticate.png
  rules/powerbi-template-app/app-connect-data-enter-details.png
  rules/powerbi-template-app/app-connect-data.png
  rules/powerbi-template-app/create-app-button.png
  rules/powerbi-template-app/create-app-database-parameters.png
  rules/powerbi-template-app/create-app-form.png
  rules/powerbi-template-app/create-app-select-reports.png
  rules/powerbi-template-app/create-app.png
  rules/powerbi-template-app/create-workspace-click-advanced.png
  rules/powerbi-template-app/create-workspace-tick.png
  rules/powerbi-template-app/enable-TA-in-current-workspace.png
  rules/powerbi-template-app/powerbi-manage-parameters-popup.png
  rules/powerbi-template-app/powerbi-manage-parameters.png
  rules/powerbi-template-app/powerbi-transform-data-parameters.png
  rules/powerbi-template-app/powerbi-transform-data.png
  rules/powerbi-template-app/release management.png
  rules/powerbi-template-app/rule.md
  rules/powerbi-template-app/workspace-settings.png
Labels: Age: 🐓 - Old

#8118 🐛 Fixed Script to Update Image Paths in the Correct rule.md
  scripts/rename-duplicate-images/rename-duplicate-images.js
Labels: code change

#8116 Brainstorming day - add team allocation rule
  rules/brainstorming-team-allocation/brainstormingday-team-location-allocation.png
  rules/brainstorming-team-allocation/rule.md
Labels: Age: 🐣 - Young

#8122 XS✔ ◾ change to ok example
  rules/fix-problems-quickly/rule.md
Labels: Age: 🥚 - New

#8124 XS✔ ◾ Deleted Unused Images
  rules/bus-test/handover-project.gif
  rules/do-you-know-how-to-laser-in-on-the-smelliest-code/rule.md
  rules/do-you-share-when-you-upgrade-an-application/rule.md
  rules/hand-over/handover-project.gif
  rules/mockups-and-prototypes/bad-uml.jpg
  rules/storyboards/rule.md
Labels: Age: 🥚 - New

#8123 XS✔ ◾ Fix title
  rules/attach-and-copy-emails-to-the-pbi/rule.md
Labels: Age: 🥚 - New

#8128 XS✔ ◾ Updating "Do you prepare, then confirm conversations/decisions?" rule (changing image)
  rules/do-you-prepare-then-confirm-conversations-decisions/as_per_our_conversation.jpg
  rules/do-you-prepare-then-confirm-conversations-decisions/rule.md
Labels: Age: 🥚 - New

#8127 Relating 2 rules together
  rules/give-emails-a-business-value/rule.md
  rules/unexpected-requests/rule.md
Labels: Age: 🥚 - New

#8121 XS✔ ◾ add frontmatter to rule
  rules/powerbi-template-app/rule.md
Labels: Age: 🐤 - Mature

#8129 XS✔ ◾ prepare for convos - link to checked by
  rules/do-you-prepare-then-confirm-conversations-decisions/rule.md
Labels: Age: 🥚 - New

#8134 XS✔ ◾ close with context - add myself as acknowledgement
  rules/close-pbis-with-context/rule.md
Labels: Age: 🐣 - Young

#8138 XS✔ ◾ Update enum rules images and add a enum class
  rules/use-enum-constants-instead-of-magic-numbers/MagicNumberBad.png
  rules/use-enum-constants-instead-of-magic-numbers/MagicNumberGood.png
  rules/use-enum-constants-instead-of-magic-numbers/enumClass.png
  rules/use-enum-constants-instead-of-magic-numbers/rule.md
Labels: Age: 🥚 - New

#8141 Update Rule “fundamentals-of-prompt-engineering/rule”
  rules/fundamentals-of-prompt-engineering/rule.md
Labels: rubber stamp, Age: 🥚 - New

#8142 XS✔ ◾ Update rule.md
  rules/clean-git-history/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#8136 XS✔ ◾ Do-you-prepare-then-confirm-conversations - Updated intro paragraph to be more clear
  rules/do-you-prepare-then-confirm-conversations-decisions/rule.md
Labels: Age: 🐓 - Old

#8143 XS✔ ◾ Fix Folder Name
  rules/hand-over-responsibilities/angry-dev-beach.png
  rules/hand-over-responsibilities/rule.md
Labels: Age: 🥚 - New

#8145 XS✔ ◾ Improving readability
  rules/video-background/rule.md
Labels: Age: 🐤 - Mature

#8146 XS✔ ◾ POC vs MVP - Fixing typos
  rules/poc-vs-mvp/rule.md
Labels: Age: 🐥 - Adolescent

#8144 XS✔ ◾ Cleaning up
  rules/have-a-dedicated-working-space/rule.md
Labels: Age: 🐤 - Mature

#8182 XS✔ ◾ Optimize favicon rule: Fix typo and update image captions
  rules/optimise-favicon/rule.md
Labels: Age: 🥚 - New

#8148 Migrating Rule “do-you-know-why-you-choose-windows-forms/rule”
  rules/do-you-know-why-you-choose-windows-forms/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8149 Migrating Rule “do-you-use-code-generators/rule”
  rules/do-you-use-code-generators/regenerate.jpg
  rules/do-you-use-code-generators/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8150 Migrating Rule “do-you-use-red-and-yellow-colours-to-distinguish-elements-in-the-designer/rule”
  rules/do-you-use-red-and-yellow-colours-to-distinguish-elements-in-the-designer/redyellowdesigner.gif
  rules/do-you-use-red-and-yellow-colours-to-distinguish-elements-in-the-designer/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8151 Migrating Rule “do-your-applications-support-xp-themes/rule”
  rules/do-your-applications-support-xp-themes/badxpthemes.gif
  rules/do-your-applications-support-xp-themes/goodxpthemes.gif
  rules/do-your-applications-support-xp-themes/rule.md
  rules/do-your-applications-support-xp-themes/setbuttonflatstyle.jpg
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8152 Migrating Rule “do-you-use-inherited-forms-for-consistent-behaviour/rule”
  rules/do-you-use-inherited-forms-for-consistent-behaviour/baseform.gif
  rules/do-you-use-inherited-forms-for-consistent-behaviour/dataentrybaseform.gif
  rules/do-you-use-inherited-forms-for-consistent-behaviour/formborderstyle.gif
  rules/do-you-use-inherited-forms-for-consistent-behaviour/rule.md
  rules/do-you-use-inherited-forms-for-consistent-behaviour/startposition.gif
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8153 Migrating Rule “do-you-display-consistent-information/rule”
  rules/do-you-display-consistent-information/codeauditorweb.png
  rules/do-you-display-consistent-information/codeauditorwelcomescreen.gif
  rules/do-you-display-consistent-information/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8154 Migrating Rule “do-you-know-when-to-use-user-controls/rule”
  rules/do-you-know-when-to-use-user-controls/badusercontrol.gif
  rules/do-you-know-when-to-use-user-controls/badusercontrols.gif
  rules/do-you-know-when-to-use-user-controls/goodusercontrol.gif
  rules/do-you-know-when-to-use-user-controls/rule.md
  rules/do-you-know-when-to-use-user-controls/usercontrol.gif
  rules/do-you-know-when-to-use-user-controls/usercontrolintabform.jpg
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8155 Migrating Rule “do-you-know-how-to-design-a-user-friendly-search-system/rule”
  rules/do-you-know-how-to-design-a-user-friendly-search-system/badsearch.gif
  rules/do-you-know-how-to-design-a-user-friendly-search-system/rule.md
  rules/do-you-know-how-to-design-a-user-friendly-search-system/searchform.gif
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8156 Migrating Rule “do-you-use-validator-controls/rule”
  rules/do-you-use-validator-controls/errorprovider.gif
  rules/do-you-use-validator-controls/extendedprovider.gif
  rules/do-you-use-validator-controls/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8157 Migrating Rule “do-you-encapsulate-aka-lock-values-of-forms/rule”
  rules/do-you-encapsulate-aka-lock-values-of-forms/fontpropertyhidden.gif
  rules/do-you-encapsulate-aka-lock-values-of-forms/fontpropertyvisible.gif
  rules/do-you-encapsulate-aka-lock-values-of-forms/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8158 Migrating Rule “do-you-use-datasets-or-create-your-own-business-objects/rule”
  rules/do-you-use-datasets-or-create-your-own-business-objects/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8159 Migrating Rule “do-your-windows-forms-have-a-statusbar-that-shows-the-time-to-load/rule”
  rules/do-your-windows-forms-have-a-statusbar-that-shows-the-time-to-load/doesntperformsowellwhenrunoveravpn2.jpg
  rules/do-your-windows-forms-have-a-statusbar-that-shows-the-time-to-load/rule.md
  rules/do-your-windows-forms-have-a-statusbar-that-shows-the-time-to-load/statusbarpanel.gif
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8160 Migrating Rule “do-you-not-cache-lookup-data-in-your-windows-forms-application/rule”
  rules/do-you-not-cache-lookup-data-in-your-windows-forms-application/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8162 Migrating Rule “do-you-always-use-the-visual-studio-designer-for-data-binding-where-possible/rule”
  rules/do-you-always-use-the-visual-studio-designer-for-data-binding-where-possible/complexdatabindingdesigner.gif
  rules/do-you-always-use-the-visual-studio-designer-for-data-binding-where-possible/rule.md
  rules/do-you-always-use-the-visual-studio-designer-for-data-binding-where-possible/simpledatabindingdesigner.gif
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8161 Migrating Rule “do-you-use-the-designer-for-all-visual-elements/rule-1”
  rules/do-you-use-the-designer-for-all-visual-elements/rule-1.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8163 Migrating Rule “do-you-avoid-using-mdi-forms/rule”
  rules/do-you-avoid-using-mdi-forms/rule.md
  rules/do-you-avoid-using-mdi-forms/sdiexample.jpg
  rules/do-you-avoid-using-mdi-forms/vs.net.jpg
  rules/do-you-avoid-using-mdi-forms/wordmdibad.gif
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8164 Migrating Rule “do-you-have-a-correctly-structured-common-code-assembly/rule”
  rules/do-you-have-a-correctly-structured-common-code-assembly/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8172 Migrating Rule “do-your-list-views-support-multiple-selection-and-copying/rule”
  rules/do-your-list-views-support-multiple-selection-and-copying/listview_bad.png
  rules/do-your-list-views-support-multiple-selection-and-copying/listview_good.png
  rules/do-your-list-views-support-multiple-selection-and-copying/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8165 Migrating Rule “are-your-data-access-layers-compatible-with-web-services/rule”
  rules/are-your-data-access-layers-compatible-with-web-services/rule.md
  rules/are-your-data-access-layers-compatible-with-web-services/timepronetoptionsconnection.jpg
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8166 Migrating Rule “do-you-log-all-errors-with-ssw-exception-manager/rule”
  rules/do-you-log-all-errors-with-ssw-exception-manager/exceptionreportingservice.gif
  rules/do-you-log-all-errors-with-ssw-exception-manager/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8167 Migrating Rule “do-you-implement-trace-logging-with-log4net/rule”
  rules/do-you-implement-trace-logging-with-log4net/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8168 Migrating Rule “do-you-make-a-strongly-typed-wrapper-for-appconfig/rule”
  rules/do-you-make-a-strongly-typed-wrapper-for-appconfig/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8169 Migrating Rule “do-you-keep-the-standard-net-datagrid/rule”
  rules/do-you-keep-the-standard-net-datagrid/exceptionreportingservice.gif
  rules/do-you-keep-the-standard-net-datagrid/infragisticsultragrid.gif
  rules/do-you-keep-the-standard-net-datagrid/janusgridex.gif
  rules/do-you-keep-the-standard-net-datagrid/rule.md
  rules/do-you-keep-the-standard-net-datagrid/timepronetoptionsconnection.jpg
  rules/do-you-keep-the-standard-net-datagrid/vs2003datagrid.gif
  rules/do-you-keep-the-standard-net-datagrid/whidbeydatagridview.gif
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8171 Migrating Rule “do-you-avoid-3rd-party-menus-and-toolbars/rule”
  rules/do-you-avoid-3rd-party-menus-and-toolbars/rule.md
  rules/do-you-avoid-3rd-party-menus-and-toolbars/whidbeytoolstripdesigner.gif
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8170 Migrating Rule “do-you-replace-the-standard-net-date-time-picker/rule”
  rules/do-you-replace-the-standard-net-date-time-picker/datetimepickerproperties.gif
  rules/do-you-replace-the-standard-net-date-time-picker/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8173 Migrating Rule “do-you-use-an-image-button-for-opening-a-web-page-taking-action/rule”
  rules/do-you-use-an-image-button-for-opening-a-web-page-taking-action/openningweblink.gif
  rules/do-you-use-an-image-button-for-opening-a-web-page-taking-action/openningweblinkbtnblue.gif
  rules/do-you-use-an-image-button-for-opening-a-web-page-taking-action/openningwebnormalbtn.gif
  rules/do-you-use-an-image-button-for-opening-a-web-page-taking-action/openningweboptions.gif
  rules/do-you-use-an-image-button-for-opening-a-web-page-taking-action/openningwebxp.gif
  rules/do-you-use-an-image-button-for-opening-a-web-page-taking-action/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8184 Update Rule “recognizing-scam-emails/rule”
  rules/recognizing-scam-emails/rule.md
Labels: Age: 🐓 - Old

#8185 XS✔ ◾ add reason
  rules/email-send-a-v2/rule.md
Labels: Age: 🐣 - Young

#8183 Update Rule “store-sensitive-information-securely/rule”
  rules/store-sensitive-information-securely/rule.md
Labels: Age: 🐓 - Old

#8139 XS✔ ◾ Update rule.md
  rules/indicate-ai-helped/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8175 Migrating Rule “do-your-forms-have-accept-and-cancel-buttons/rule”
  rules/do-your-forms-have-accept-and-cancel-buttons/acceptbuttonexample_good.jpg
  rules/do-your-forms-have-accept-and-cancel-buttons/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8176 Migrating Rule “do-you-name-all-your-ok-buttons-to-be-an-action-eg-save-open-etc/rule”
  rules/do-you-name-all-your-ok-buttons-to-be-an-action-eg-save-open-etc/rule.md
  rules/do-you-name-all-your-ok-buttons-to-be-an-action-eg-save-open-etc/skypetoolsoptions.png
  rules/do-you-name-all-your-ok-buttons-to-be-an-action-eg-save-open-etc/vstoolsoptions.png
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8177 Migrating Rule “do-you-make-enter-go-to-the-next-line-when-you-have-a-multi-line-textbox-rather-than-hit-the-ok-button/rule”
  rules/do-you-make-enter-go-to-the-next-line-when-you-have-a-multi-line-textbox-rather-than-hit-the-ok-button/developernotesscreen1.gif
  rules/do-you-make-enter-go-to-the-next-line-when-you-have-a-multi-line-textbox-rather-than-hit-the-ok-button/developernotesscreen2.gif
  rules/do-you-make-enter-go-to-the-next-line-when-you-have-a-multi-line-textbox-rather-than-hit-the-ok-button/rule.md
  rules/do-you-make-enter-go-to-the-next-line-when-you-have-a-multi-line-textbox-rather-than-hit-the-ok-button/setupformtxt2.gif
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8174 Migrating Rule “do-you-use-ok-instead-of-ok/rule”
  rules/do-you-use-ok-instead-of-ok/okbadexample.png
  rules/do-you-use-ok-instead-of-ok/okgoodexample.png
  rules/do-you-use-ok-instead-of-ok/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8191 XS✔ ◾ Trying to make a better readability
  rules/do-you-display-information-consistently/rule.md
Labels: Age: 🥚 - New

#8192 XS✔ ◾ Moved the very long caption to be a related link + paragraph
  rules/descriptive-links/rule.md
Labels: Age: 🥚 - New

#8147 📝 Moving rule category for WinForms
  categories/software-engineering/index.md
  categories/software-engineering/rules-to-better-windows-forms-applications.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8190 XS✔ ◾ Added "OK" example so we can archive the other rule
  rules/avoid-common-mistakes/rule.md
Labels: Age: 🥚 - New

#8194 XS✔ ◾ Mention GitHub Discussions
  rules/reply-done-and-delete-the-email/rule.md
Labels: Age: 🥚 - New

#8195 XS✔ ◾ Reworded GitHub part on URLs
  rules/reply-done-and-delete-the-email/rule.md
Labels: Age: 🥚 - New

#8196 XS✔ ◾ Improved section about using text instead of images
  rules/reply-done-and-delete-the-email/rule.md
Labels: Age: 🥚 - New

#8197 Power BI Version Control - Added instructions on editing & committing reports for Business users and Developers
  rules/do-you-use-version-control-with-power-bi/SyncChanges.png
  rules/do-you-use-version-control-with-power-bi/rule.md
Labels: Age: 🐤 - Mature

#8199 Update Rule “responsive-design/rule”
  rules/responsive-design/rule.md
  rules/responsive-design/ssw-france-mobile-performance-google-pagespeed.png
Labels: Age: 🥚 - New

#8201 XS✔ ◾ add bad example and fix bugs
  rules/disagreeing-with-powerful-stakeholders/rule.md
Labels: Age: 🥚 - New

#8202 XS✔ ◾ Editing w/ Piers for CTF
  rules/disagreeing-with-powerful-stakeholders/rule.md
Labels: Age: 🥚 - New

#8203 XS✔ ◾ Disagree with stakeholder - Improvements with Adam
  categories/communication/rules-to-better-giving-and-taking-feedback.md
  categories/project-delivery/rules-to-better-product-owners.md
  rules/disagreeing-with-powerful-stakeholders/rule.md
Labels: Age: 🥚 - New

#8204 XS✔ ◾ Send done videos - Add redirect to fix broken links
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  categories/company-operations/rules-to-better-remote-work.md
  categories/project-delivery/rules-to-better-scrum.md
  rules/close-pbis-with-context/rule.md
  rules/do-you-make-sure-you-get-brownie-points/rule.md
  rules/record-a-quick-and-dirty-done-video/rule.md
  rules/send-done-videos/rule.md
Labels: Age: 🐥 - Adolescent

#8205 XS✔ ◾ i18n - Add link to consulting page
  categories/software-engineering/rules-to-better-internationalization.md
Labels: Age: 🐣 - Young

#8208 XS✔ ◾ Fixed bad example + small improvements "avoid labels"
  rules/avoid-labels/rule.md
Labels: Age: 🐣 - Young

#8210 XS✔ ◾ Archived IIS Search Engine Optimization Toolkit rule
  rules/know-the-iis-things-to-do/rule.md
Labels: Age: 🥚 - New

#8219 XS✔ ◾ SSRS versions - Added more versions
  rules/reporting-services-version/rule.md
Labels: Age: 🐤 - Mature

#8218 XS✔ ◾ Page header rule - Updated title and figure caption
  rules/least-content-in-page-header/rule.md
Labels: Age: 🐤 - Mature

#8211 XS✔ ◾ 📝 Clearer language in disagreeing-with-powerful-stakeholders
  rules/disagreeing-with-powerful-stakeholders/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8247 Small improvements about Power BI source control and squash merging
  rules/do-you-use-version-control-with-power-bi/bad-example-pbix-source-control.png
  rules/do-you-use-version-control-with-power-bi/rule.md
  rules/merge-open-source-pull-requests-using-the-squash-and-merge-option/merge-bad-example.png
Labels: Age: 🐣 - Young

#8248 XS✔ ◾ Add rule 'Do you know how to communicate Product Progress?'
  rules/communicate-your-product-status/rule.md
  rules/communicate-your-product-status/user-metrics.png
  rules/communicate-your-product-status/viva-goals-roadmap.png
Labels: Age: 🥚 - New, Age: 🐣 - Young

#8252 XS✔ ◾ Migrated rule - Do you show the past 6 months of totals in a chart?
  categories/company-operations/rules-to-better-reporting-services.md
  rules/show-past-six-months-in-chart/RSRules6MonthChart.gif
  rules/show-past-six-months-in-chart/RSRules6MonthChart_AddParameter.gif
  rules/show-past-six-months-in-chart/RSRules6MonthChart_Layout.gif
  rules/show-past-six-months-in-chart/rule.md
Labels: Age: 🥚 - New

#8254 XS✔ ◾ Migrated rule - Do you show data and chart in one?
  categories/company-operations/rules-to-better-reporting-services.md
  rules/show-data-and-chart-in-one/BadDataChartReport.jpg
  rules/show-data-and-chart-in-one/BadDataReport.jpg
  rules/show-data-and-chart-in-one/GoodDataChartReport.jpg
  rules/show-data-and-chart-in-one/rule.md
Labels: Age: 🥚 - New

#8220 Migrating Rule “make-common-controls-with-consistent-widths/rule”
  rules/make-common-controls-with-consistent-widths/adddeletebad.gif
  rules/make-common-controls-with-consistent-widths/adddeletegood.gif
  rules/make-common-controls-with-consistent-widths/commoncontrolbad.gif
  rules/make-common-controls-with-consistent-widths/commoncontrolgood.gif
  rules/make-common-controls-with-consistent-widths/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8221 Migrating Rule “windows-forms-applications-support-urls/rule”
  rules/windows-forms-applications-support-urls/outlookaddressbar.gif
  rules/windows-forms-applications-support-urls/rule.md
  rules/windows-forms-applications-support-urls/runshortcut.gif
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8256 XS✔ ◾ Adjust "email-to-PBI rule" email reply to mention prioritization
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🐤 - Mature

#8249 XS✔ ◾ Added relation between two rules about Done
  rules/close-off-thread/rule.md
  rules/dones-do-you-include-useful-details-in-your-done-email/rule.md
Labels: Age: 🐤 - Mature

#8250 Update Rule “do-you-constantly-add-to-the-backlog/rule”
  rules/do-you-constantly-add-to-the-backlog/rule.md
Labels: Age: 🐤 - Mature

#8251 Update Rule “report-bugs-and-suggestions/rule”
  rules/report-bugs-and-suggestions/rule.md
Labels: Age: 🐤 - Mature
