Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-09, with the labels that each got.

#9083 XS✔ ◾ Archive duplicate rule
  rules/do-you-know-how-to-lay-out-your-solution/rule.md
  rules/do-you-review-the-solution-and-project-names/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9087 Create Rule “do-you-do-youtube-livestreams/rule”
  rules/do-you-do-youtube-livestreams/rule.md
Labels: Age: 🥚 - New

#9086 XS✔ ◾ new rule - send links to support
  categories/communication/rules-to-better-technical-documentation.md
  categories/company-operations/rules-to-successful-projects.md
  rules/knowledge-base-kb/rule.md
  rules/support-send-links/rule.md
Labels: Age: 🐣 - Young

#9082 Cms/calinator444/ssw.rules.content/rule/do you use cdn for js files/rule
  rules/do-you-use-cdn-for-js-files/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9078 Update Rule “add-useful-and-concise-figure-captions/rule”
  rules/add-useful-and-concise-figure-captions/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9089 CDN - update the uri
  categories/software-engineering/rules-to-better-internationalization.md
  rules/handle-redirects/rule.md
  rules/use-a-cdn/5-28.4.png
  rules/use-a-cdn/5-28.5.png
  rules/use-a-cdn/rule.md
Labels: Age: 🐤 - Mature

#9085 XS✔ ◾ Added related + crossed out Cortana
  rules/collaborate-across-timezones/rule.md
Labels: Age: 🐓 - Old

#9091 XS✔ ◾ fix bad url in frontmatter
  rules/create-comprehensive-tender-proposal/rule.md
Labels: Age: 🥚 - New

#9084 XS✔ ◾ Fixed list to have line breaks and better positioning "/power-automate-flows-convert-timezone/rule.md"
  rules/automate-schedule-meetings/rule.md
  rules/power-automate-flows-convert-timezone/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9092 XS✔ ◾ removed copyrighted image
  rules/add-useful-and-concise-figure-captions/good-caption.jpg
Labels: Age: 🥚 - New

#9093 XS✔ ◾ Fix bad markdown
  rules/listed-on-tender-platforms/rule.md
Labels: Age: 🥚 - New

#9090 Cms/stef star/ssw.rules.content/rule/youtube livestreams/rule
  categories/marketing-and-video/rules-to-better-youtube.md
  rules/do-you-do-youtube-livestreams/rule.md
  rules/youtube-livestreams/rule.md
Labels: Age: 🐣 - Young

#9098 XS✔ ◾ Remove "User Stories" references
  rules/acceptance-criteria/13_Anvil_1408_Customer.pdf
  rules/acceptance-criteria/rule.md
Labels: Age: 🥚 - New

#9094 Moved deprecated Cortana content “microsoft-cortana-scheduler/rule”
  rules/automate-schedule-meetings/rule.md
  rules/microsoft-cortana-scheduler/CortanaContact.jpg
  rules/microsoft-cortana-scheduler/confirmation.jpg
  rules/microsoft-cortana-scheduler/cortana-scheduler-mobile.jpg
  rules/microsoft-cortana-scheduler/rule.md
Labels: Age: 🐥 - Adolescent

#9096 XS✔ ◾ Removed broken link + better wording "the-outcomes-from-your-initial-meeting"
  rules/the-outcomes-from-your-initial-meeting/rule.md
Labels: Age: 🐣 - Young

#9097 XS✔ ◾ fixing broken links
  rules/4-quadrants-important-and-urgent/rule.md
  rules/avoid-clear-text-email-addresses-in-web-pages/rule.md
  rules/do-you-always-carry-your-tool-box/rule.md
  rules/do-you-carry-more-than-just-the-microsoft-tool-box/rule.md
  rules/do-you-know-how-to-format-dates-to-include-the-weekday/rule.md
  rules/do-you-know-how-to-make-net-wrapper-work-on-both-x64-and-x86-platforms/rule.md
  rules/do-you-know-the-best-nuget-packages/rule.md
  rules/do-you-make-it-easy-to-your-users-to-add-an-event-to-their-calendar/rule.md
  rules/do-you-use-an-internet-intranet-for-sharing-common-information-such-as-company-standards/rule.md
  rules/do-you-use-code-generators/rule.md
  rules/ensure-zendesk-is-not-marked-as-spam/rule.md
  rules/manage-javascript-projects-with-nx/rule.md
  rules/management-do-you-have-a-release-update-debrief-meeting-on-a-weekly-basis/rule.md
  rules/train-gpt/rule.md
  rules/use-icons-to-not-surprise-users/rule.md
Labels: codeauditor fix, Age: 🐣 - Young

#9099 XS✔ ◾ Archive Blazor rule
  categories/software-engineering/rules-to-better-blazor.md
  rules/blazor-does-not-support-stopping-event-propogation/rule.md
Labels: Age: 🐣 - Young

#9075 Create Rule “do-you-know-how-to-use-single-codebase-for-multiple-domains-with-tinacm-and-nextjs/rule”
  rules/single-codebase-for-multiple-domains-with-tinacm-nextjs/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9100 XS✔ ◾ changes as per Adam
  rules/unexpected-requests/rule.md
Labels: Age: 🐤 - Mature

#9095 XS✔ ◾ Improved intro and examples "how-to-capitalize-titles"
  rules/how-to-capitalize-titles/rule.md
Labels: Age: 🐓 - Old

#9104 XS✔ ◾ Removed a few of too many related
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🐥 - Adolescent

#9105 XS✔ ◾ Removed bug caused by spaces
  rules/microsoft-cortana-scheduler/rule.md
Labels: rubber stamp, Age: 🐣 - Young

#9106 XS✔ ◾ New rule - Do you know the best way to suggest changes on a Pull Request?
  rules/pr-suggest-changes/bad-pr-suggest-changes.png
  rules/pr-suggest-changes/good-pr-suggestions.png
  rules/pr-suggest-changes/good-suggest-a-change-button.png
  rules/pr-suggest-changes/rule.md
Labels: Age: 🥚 - New

#9107 XS✔ ◾ suggest changes on a Pull Request add to category
  categories/software-engineering/rules-to-better-github.md
  categories/software-engineering/rules-to-better-pull-requests.md
Labels: Age: 🥚 - New

#9110 XS✔ ◾ Updating figure captions
  rules/pr-suggest-changes/rule.md
Labels: Age: 🥚 - New

#9108 Update Rule “config-over-keyvault/rule”
  rules/config-over-keyvault/rule.md
  rules/config-over-keyvault/screenshot-2024-09-05-183121.png
Labels: Age: 🐤 - Mature

#9103 XS✔ ◾ Improved INVEST section
  rules/have-a-definition-of-ready/rule.md
Labels: Age: 🐓 - Old

#9112 XS✔ ◾ added a note to avoid confusion
  rules/how-to-capitalize-titles/rule.md
Labels: Age: 🥚 - New

#9111 XS✔ ◾ Add files via upload
  rules/image-formats/Screen-JPGQuality1.jpg
  rules/image-formats/Screen-JPGQuality2.jpg
  rules/image-formats/Screen-JPGQuality3.jpg
  rules/image-formats/svg-good.jpg
  rules/image-formats/svg_bad.jpg
Labels: Age: 🐣 - Young

#9113 XS✔ ◾ Update rule.md
  rules/pr-suggest-changes/rule.md
Labels: Age: 🥚 - New

#9115 XS✔ ◾ Fixed image name + sentence
  rules/turn-emails-into-pbis/rule.md
  rules/turn-emails-into-pbis/urgent-flowchart.svg
Labels: Age: 🥚 - New

#9117 XS✔ ◾ added section to avoid dots in file names
  rules/how-to-name-documents/rule.md
Labels: Age: 🥚 - New

#9114 Cms/calinator444/ssw.rules.content/rule/pr suggest changes/rule
  rules/pr-suggest-changes/batch-suggesions.png
  rules/pr-suggest-changes/rule.md
Labels: Age: 🥚 - New

#9116 XS✔ ◾ Rename CRM2015Theme.JPG to CRM2015Theme.jpg
  rules/do-you-identify-development-test-and-production-crm-web-servers-by-colors/CRM2015Theme.jpg
Labels: Age: 🐓 - Old

#9119 XS✔ ◾ break lines inside greybox
  rules/have-a-definition-of-ready/rule.md
Labels: Age: 🍗 - Ancient

#9121 XS✔ ◾ Improved URL "work-in-pairs"
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  rules/work-in-pairs/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9126 XS✔ ◾ SEO tools - add a few others
  rules/seo-tools/rule.md
Labels: Age: 🥚 - New

#9125 Update Rule “request-a-test-please/rule”
  rules/request-a-test-please/rule.md
Labels: Age: 🥚 - New

#9128 XS✔ ◾ Adding email template
  rules/monthly-stakeholder-video/rule.md
Labels: Age: 🥚 - New

#9122 ⛓️‍💥 Broken links - Alumni profiles not getting redirections
  rules/use-system-prompt/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9130 XS✔ ◾ Adding line breaks
  rules/have-a-definition-of-ready/rule.md
Labels: Age: 🐣 - Young

#9127 Update Rule “keep-your-urls-clean/rule”
  rules/keep-your-urls-clean/rule.md
Labels: Age: 🐤 - Mature

#9120 XS✔ ◾ Added Time Zone Converter – Time Difference Calculator section to "collaborate-across-timezones"
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  categories/communication/rules-to-better-outsourcing.md
  rules/collaborate-across-timezones/rule.md
  rules/collaborate-across-timezones/time-and-date-screenshot.png
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9129 Create Rule “spike-vs-poc/rule”
  rules/encourage-spikes-when-a-story-is-inestimable/rule.md
  rules/generate-ui-mockups-with-ai/rule.md
  rules/spike-vs-poc/rule.md
Labels: Age: 🐣 - Young

#9133 XS✔ ◾ From .JPG to .jpg
  rules/do-you-identify-development-test-and-production-crm-web-servers-by-colors/rule.md
Labels: Age: 🥚 - New

#9135 XS✔ ◾ changes as per Adam and Nick
  rules/loop-someone-in/rule.md
Labels: Age: 🥚 - New

#9137 XS✔ ◾ Fixed broken links
  rules/do-you-need-to-migrate-the-history-from-vss-to-tfs/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#9138 XS✔ ◾ adding story of lee lacocca
  rules/do-you-prioritize-your-existing-clients-over-prospective-ones/rule.md
Labels: Age: 🥚 - New

#9139 XS✔ ◾ Updated name and URI, added headings and stats
  rules/do-you-prioritize-your-existing-clients-over-prospective-ones/rule.md
Labels: Age: 🥚 - New

#9143 XS✔ ◾ Fix filename long issue
  categories/communication/rules-to-better-outsourcing.md
  rules/record-your-sales-meetings/professional-sales-call-between-two-individuals.webp
  rules/record-your-sales-meetings/rule.md
Labels: Age: 🥚 - New

#9144 XS✔ ◾ Added spike-vs-poc to category
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
Labels: Age: 🥚 - New

#9146 XS✔ ◾ Removed: rules-to-better-software-consultants-dealing-with-clients.md
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
Labels: Age: 🥚 - New

#9145 XS✔ ◾ Shorten URL identify-web-servers-by-colors
  categories/company-operations/rules-to-successful-projects.md
  categories/software-engineering/rules-to-better-crm-for-developers.md
  rules/identify-crm-web-servers-by-colors/rule.md
Labels: Age: 🥚 - New

#9148 XS✔ ◾ Update rules-to-better-email - add add-days-to-dates
  categories/communication/rules-to-better-email.md
Labels: Age: 🥚 - New

#9147 Create Rule “add-days-to-dates/rule”
  rules/add-days-to-dates/date-bad-example.jpg
  rules/add-days-to-dates/date-good-example.jpg
  rules/add-days-to-dates/rule.md
Labels: Age: 🥚 - New

#9149 XS✔ ◾ new rule - match tone and intent
  rules/match-tone-with-intent/rule.md
Labels: Age: 🥚 - New

#9151 XS✔ ◾ Add match-tone-with-intent to categories
  categories/communication/rules-to-better-communication.md
  categories/marketing-and-video/rules-to-better-inbound-calls.md
  categories/marketing-and-video/rules-to-better-video-recording.md
Labels: Age: 🐥 - Adolescent

#9152 XS✔ ◾ improved intro + removed unnecessary greybox
  rules/match-tone-with-intent/rule.md
Labels: Age: 🥚 - New

#9157 XS✔ ◾ Tone - Fix nested list
  rules/match-tone-with-intent/rule.md
Labels: Age: 🥚 - New

#9156 XS✔ ◾ Update the Cultural exchange rule.md
  rules/cultural-exchange/rule.md
Labels: Age: 🥚 - New

#9158 XS✔ ◾ from lists to headings
  rules/build-inter-office-interaction/rule.md
Labels: Age: 🥚 - New

#9159 XS✔ ◾ Fixing a heading
  rules/do-you-prioritize-your-existing-clients-over-prospective-ones/rule.md
Labels: Age: 🥚 - New

#9160 XS✔ ◾ Add note about change management procedures to "touch it once"
  rules/the-touch-it-once-principle/rule.md
Labels: Age: 🥚 - New

#9162 XS✔ ◾ tone rule - update content
  rules/match-tone-with-intent/rule.md
Labels: Age: 🥚 - New

#9140 XS✔ ◾ Improvements to cross approvals
  rules/cross-approvals/TeamsApprovalsTemplate.png
  rules/cross-approvals/rule.md
Labels: Age: 🐓 - Old

#9166 XS✔ ◾ tone - update exercise and tip
  rules/match-tone-with-intent/rule.md
Labels: Age: 🥚 - New

#9168 XS✔ ◾ tone - sml fixes
  rules/match-tone-with-intent/rule.md
Labels: Age: 🥚 - New

#9171 XS✔ ◾ Wording improvements
  rules/match-tone-with-intent/rule.md
Labels: Age: 🥚 - New

#9164 XS✔ ◾ reachouts - add video link
  rules/successful-reachouts/rule.md
Labels: Age: 🐤 - Mature

#9167 XS✔ ◾ add related rules
  rules/creating-action-items/rule.md
  rules/do-you-know-you-should-write-notes-when-an-activity-is-going/rule.md
  rules/take-effective-notes/rule.md
Labels: Age: 🐤 - Mature

#9172 XS✔ ◾ Improved video links + small stuff
  rules/match-tone-with-intent/rule.md
Labels: Age: 🥚 - New

#9161 XS✔ ◾ Adding Video Update rule.md
  rules/sqlperf-reduce-table-size/rule.md
Labels: Age: 🐤 - Mature

#9154 XS✔ ◾ Fixed images syntax + capitalization
  rules/serialize-view-models-not-domain-entities/rule.md
Labels: Age: 🐓 - Old

#9155 XS✔ ◾ Added related rules + improved URI automated-webinars-for-multiple-time-zones
  categories/marketing-and-video/rules-to-better-marketing.md
  rules/automate-schedule-meetings/rule.md
  rules/automated-webinars-for-multiple-time-zones/rule.md
Labels: Age: 🐓 - Old

#9153 XS✔ ◾ rewrote rule on domain registering for long term
  rules/does-your-domain-have-power/rule.md
  rules/register-your-domain-for-a-long-time/rule.md
Labels: Age: 🐓 - Old

#9173 XS✔ ◾ Changed image extensions to lowercase
  assets/burndown.jpg
  assets/project-progress-capture.jpg
  assets/stories-overview.jpg
  rules/architecture-diagram/reward-hand-drawn-sketch-office-lens.jpg
  rules/architecture-diagram/rewards-hand-drawn-sketch.jpg
  rules/architecture-diagram/rule.md
  rules/avoid-deploying-source-code-on-the-production-server/publish-web-app-dialog.jpg
  rules/avoid-deploying-source-code-on-the-production-server/publish-web-app.jpg
  rules/avoid-deploying-source-code-on-the-production-server/publish-website-dialog.jpg
  rules/avoid-deploying-source-code-on-the-production-server/publish-website.jpg
  rules/avoid-deploying-source-code-on-the-production-server/rule.md
  rules/burndown-and-stories-overview-reports-updates/rule.md
  rules/sprint-review-retro-email/application-insights.jpg
  rules/sprint-review-retro-email/burndown.jpg
  rules/sprint-review-retro-email/release-burnup.jpg
  rules/sprint-review-retro-email/rule.md
  rules/sprint-review-retro-email/thumbnail-image.png
Labels: Age: 🐥 - Adolescent

#9177 XS✔ ◾ ♻️ Fixed image extensions and names
  assets/interface-selected-rows-bad.jpg
  assets/interface-selected-rows-good.jpg
  rules/controls-do-you-make-the-selected-enabled-rows-stand-out-in-a-datagrid/rule.md
  rules/customization-do-you-export-only-the-customizations-of-entities-that-you-did-customize/crm-cus-01.jpg
  rules/customization-do-you-export-only-the-customizations-of-entities-that-you-did-customize/rule.md
  rules/customization-do-you-use-a-supported-method-of-customization/crm-customization-architecture.jpg
  rules/customization-do-you-use-a-supported-method-of-customization/rule.md
  rules/do-you-avoid-using-auto-archive/ContactorNoAging.JPG
  rules/do-you-avoid-using-auto-archive/OutlookAutoArchive.gif
  rules/do-you-avoid-using-auto-archive/outlook-auto-archive.png
  rules/do-you-avoid-using-auto-archive/rule.md
Labels: Age: 🐓 - Old

#9178 XS✔ ◾ ♻️ Fixed image extensions and names 2
  assets/ticking-clock.jpg
  rules/do-you-colour-code-your-keys/bad-example-keys.jpg
  rules/do-you-colour-code-your-keys/good-example-keys.jpg
  rules/do-you-colour-code-your-keys/rule.md
  rules/do-you-know-how-to-recall-an-email/recall-in-outlook-2010.jpg
  rules/do-you-know-how-to-recall-an-email/recall-message.jpg
  rules/do-you-know-how-to-recall-an-email/rule.md
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/bad-screenshot-with-personal-data.jpg
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/good-auto-hide-taskbar.gif
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/good-no-personal-info.jpg
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/rule.md
  rules/do-you-reliably-deliver-your-tasks/rule.md
  rules/go-the-extra-mile/cows-bum.jpg
  rules/go-the-extra-mile/rule.md
  rules/have-a-healthcheck-page-to-make-sure-your-website-is-healthy/check-everything.jpg
  rules/have-a-healthcheck-page-to-make-sure-your-website-is-healthy/rule.md
Labels: Age: 🐓 - Old

#9179 XS✔ ◾ ♻️ Fixed image extensions and names 3
  assets/long-process-bad.jpg
  rules/long-process-do-you-know-how-to-make-long-running-processes-user-friendly/rule.md
  rules/production-do-you-use-proper-production-design/bad-set-design-example.jpg
  rules/production-do-you-use-proper-production-design/good-set-design-example.png
  rules/production-do-you-use-proper-production-design/japan-by-dhatt.jpg
  rules/production-do-you-use-proper-production-design/lighting-bad-example.jpg
  rules/production-do-you-use-proper-production-design/props-bad-example.jpg
  rules/production-do-you-use-proper-production-design/props-good-example.jpg
  rules/production-do-you-use-proper-production-design/rule.md
  rules/screenshots-avoid-walls-of-text/arrow-bad-example.png
  rules/screenshots-avoid-walls-of-text/arrow-example.png
  rules/screenshots-avoid-walls-of-text/arrow-good-example.png
  rules/screenshots-avoid-walls-of-text/balloon-bad-example.jpg
  rules/screenshots-avoid-walls-of-text/balloon-good-example.jpg
  rules/screenshots-avoid-walls-of-text/balloon-not-needed.jpg
  rules/screenshots-avoid-walls-of-text/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9180 XS✔ ◾ ♻️ Fixed image extensions and names 4
  rules/create-primary-key-on-your-tables/rule.md
  rules/create-primary-key-on-your-tables/sql-table-with-primary-key.png
  rules/create-primary-key-on-your-tables/sql-table-without-primary-key.png
  rules/do-not-allow-nulls-in-text-fields/null-value-on-ui.jpg
  rules/do-not-allow-nulls-in-text-fields/rule.md
  rules/do-not-allow-nulls-in-text-fields/sql-table-with-null-value.png
  rules/do-you-have-a-dress-code/rule.md
  rules/do-you-have-a-dress-code/sean-connery-dressed-up.jpg
  rules/do-you-have-a-dress-code/ssw-dresscode-poster-v2.png
  rules/do-you-know-the-crm-roadmap/DynamicsRoadmap.PNG
  rules/do-you-know-the-crm-roadmap/dynamics-release-plans.png
  rules/do-you-know-the-crm-roadmap/rule.md
  rules/do-you-use-suspend-on-your-notebook/power-options.png
  rules/do-you-use-suspend-on-your-notebook/rule.md
  rules/do-you-use-the-correct-input-type/field-type-tel.png
  rules/do-you-use-the-correct-input-type/field-type-text.png
  rules/do-you-use-the-correct-input-type/rule.md
  rules/use-temporal-tables-to-audit-data-changes/rule.md
  rules/use-temporal-tables-to-audit-data-changes/shippers-temporal-table.png
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9175 XS✔ ◾ Merging limit-text-on-slides rules
  categories/communication/rules-to-better-powerpoint-presentations.md
  rules/do-you-limit-the-amount-of-text-on-your-slides/rule.md
  rules/limit-text-on-slides/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9176 XS✔ ◾ Added video and many improvements to the rule "draft-and-deliver-engag…
  rules/craft-and-deliver-engaging-presentations/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9189 XS✔ ◾ Update rules-to-better-code.md
  categories/software-engineering/rules-to-better-code.md
Labels: Age: 🐥 - Adolescent

#9181 XS✔ ◾ categorize share-product-improvements
  categories/software-engineering/rules-to-better-open-source-software.md
  rules/share-product-improvements/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9183 XS✔ Archive Old Accounting Rule
  rules/do-you-print-out-your-general-ledger-for-the-week-and-ask-your-boss-to-initial/rule.md
Labels: Age: 🐤 - Mature

#9190 XS✔ ◾ Sprint Review Email - improve template
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🐤 - Mature

#9194 XS✔ ◾ Fixing caption for videos
  rules/craft-and-deliver-engaging-presentations/rule.md
Labels: Age: 🐥 - Adolescent

#9195 XS✔ ◾ Fixing broken links
  rules/create-separate-virtual-directory-for-admin-access/rule.md
  rules/do-you-know-how-to-lay-out-your-solution/rule.md
  rules/show-errors-in-red/rule.md
Labels: Age: 🥚 - New

#9196 XS✔ ◾ Updated links
  rules/follow-naming-conventions/rule.md
Labels: Age: 🥚 - New

#9182 XS✔ ◾ Migrated SSRS Rules - part 4/4
  categories/company-operations/rules-to-better-reporting-services.md
  rules/add-report-owner/ReportOwner.gif
  rules/add-report-owner/ReportOwnerCRM.gif
  rules/add-report-owner/rule.md
  rules/change-name-of-site-settings/BadSiteSetting.gif
  rules/change-name-of-site-settings/GoodSiteSetting2005.gif
  rules/change-name-of-site-settings/GoodSiteSetting2008.gif
  rules/change-name-of-site-settings/rule.md
  rules/display-reports-in-firefox-chrome-safari/report-display-bad.jpg
  rules/display-reports-in-firefox-chrome-safari/report-display-good.jpg
  rules/display-reports-in-firefox-chrome-safari/rule.md
  rules/display-reports-properly-in-firefox-chrome/report-display-bad.jpg
  rules/display-reports-properly-in-firefox-chrome/report-display-good.jpg
  rules/display-reports-properly-in-firefox-chrome/rule.md
  rules/embed-rs-report-in-asp-net-page/IFrame.gif
  rules/embed-rs-report-in-asp-net-page/ReportViewer.gif
  rules/embed-rs-report-in-asp-net-page/rule.md
  rules/follow-naming-convention-standards-in-reporting-service/rule.md
  rules/get-email-list-of-report-subscription/DatasetParam.gif
  rules/get-email-list-of-report-subscription/GlobalParam.gif
  rules/get-email-list-of-report-subscription/rule.md
  rules/have-clear-labelling-for-including-excluding-gst/ClearText.jpg
  rules/have-clear-labelling-for-including-excluding-gst/UnclearText.jpg
  rules/have-clear-labelling-for-including-excluding-gst/rule.md
  rules/report-that-refreshes-data-source/ReportRefreshData.jpg
  rules/report-that-refreshes-data-source/rule.md
  rules/summary-and-detailed-version-of-report/DetailReport.jpg
  rules/summary-and-detailed-version-of-report/SummaryReport.jpg
  rules/summary-and-detailed-version-of-report/rule.md
  rules/url-access-link-for-report/BetterRS_URLAccess.jpg
  rules/url-access-link-for-report/rule.md
  rules/use-correct-authentication-for-report/rule.md
  rules/use-live-data-feed-in-excel/ExcelData.jpg
  rules/use-live-data-feed-in-excel/LiveData.jpg
  rules/use-live-data-feed-in-excel/rule.md
  rules/use-sharepoint-integration-reporting-mode/NativeMode.jpg
  rules/use-sharepoint-integration-reporting-mode/SharePointIntegratedMode.jpg
  rules/use-sharepoint-integration-reporting-mode/rule.md
  rules/use-single-line-box/Bad_DoubleBox.gif
  rules/use-single-line-box/Good_Report.gif
  rules/use-single-line-box/rule.md
Labels: Age: 🐓 - Old

#9201 XS✔ ◾ Adding video to Update rule.md
  rules/sqlperf-use-and-instead-of-or/rule.md
Labels: Age: 🥚 - New

#9198 XS✔ ◾ Adding Video to Update rule.md
  rules/sqlperf-verify-indexes-used/rule.md
Labels: Age: 🥚 - New

#9200 XS✔ ◾ Adding video to Update rule.md
  rules/sqlperf-avoid-looping/rule.md
Labels: Age: 🥚 - New

#9199 XS✔ ◾ Adding video to Update rule.md
  rules/sqlperf-avoid-implicit-type-conversions/rule.md
Labels: Age: 🥚 - New

#9197 XS✔ ◾ Adding Rule video Update rule.md
  rules/sqlperf-select-required-columns/rule.md
Labels: Age: 🥚 - New

#9193 XS✔ ◾ Made all images img-medium
  rules/limit-text-on-slides/rule.md
Labels: Age: 🐤 - Mature

#9192 XS✔ ◾ Removed redundant link
  rules/over-the-shoulder/rule.md
Labels: Age: 🐤 - Mature

#9191 Cms/jean thirion/ssw.rules.content/rule/identify crm web servers by colors/rule
  rules/identify-crm-web-servers-by-colors/2024-09-16_18-03-50.jpg
  rules/identify-crm-web-servers-by-colors/2024-09-16_18-06-09.jpg
  rules/identify-crm-web-servers-by-colors/2024-09-16_18-10-35.jpg
  rules/identify-crm-web-servers-by-colors/rule.md
Labels: Age: 🐤 - Mature

#9205 XS✔ ◾ Adding video to Update rule.md
  rules/sqlperf-top-for-sampling/rule.md
Labels: Age: 🐤 - Mature

#9204 XS✔ ◾ Adding video to Update rule.md
  rules/sqlperf-join-over-where/rule.md
Labels: Age: 🐤 - Mature

#9202 XS✔ ◾ Adding video to Update rule.md
  rules/sqlperf-wildcards/rule.md
Labels: Age: 🐓 - Old

#9206 XS✔ ◾ Adding prefix/ suffix to all Accounting Rules & reorder Accounting catagory
  categories/company-operations/rules-to-better-accounting.md
  rules/allocate-expenses-per-office/rule.md
  rules/apple-google-pay-for-expenses/rule.md
  rules/compliance-sheet/read.md
  rules/do-you-calculate-payroll-tax-correctly/rule.md
  rules/do-you-have-monthly-accounting-meetings/rule.md
  rules/do-you-involve-cross-checks-in-your-procedures/rule.md
  rules/do-you-tie-knowledge-to-the-role/rule.md
  rules/do-you-treat-freebies-as-real-customers/rule.md
  rules/importance-of-reconciliation/rule.md
  rules/manage-travel-in-centralized-systems/rule.md
  rules/pay-invoices-completely/rule.md
  rules/report-gas-in-the-tank/rule.md
  rules/salary-sacrifice-electronic-devices/rule.md
  rules/salary-sacrifice-novated-lease/rule.md
  rules/salary-terminology/rule.md
  rules/show-certification-award/rule.md
  rules/show-long-service-leave-on-your-payslip/rule.md
  rules/tax-invoice-vs-eftpos-receipt/rule.md
Labels: Age: 🐓 - Old

#9186 XS✔ ◾ Update rule - Do you know how to handle noise email.md
  rules/handle-noise-email/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9207 XS✔ ◾ Update rule.md
  rules/linkedin-profile/rule.md
Labels: Age: 🥚 - New

#9187 XS✔ ◾ Add resources to learning devops
  rules/do-you-know-the-best-free-resources-for-learning-devops/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9209 XS✔ ◾ New rule - weekly-ai-meetings
  categories/artificial-intelligence/rules-to-better-gpt.md
  rules/weekly-ai-meetings/rule.md
Labels: Age: 🥚 - New

#9208 Update Rule “turn-emails-into-pbis/rule”
  rules/turn-emails-into-pbis/rule.md
  rules/turn-emails-into-pbis/urgent-flowchart.png
Labels: Age: 🐤 - Mature

#9165 Renaming Azure AD to Microsoft Entra ID
  categories/infrastructure-and-networking/rules-to-better-office-365.md
  rules/have-azure-active-directory-password-hash-synchronization-activated/aad-phs.png
  rules/have-azure-active-directory-password-hash-synchronization-activated/rule.md
  rules/have-entra-id-password-hash-synchronization-activated/entra-id-phs.png
  rules/have-entra-id-password-hash-synchronization-activated/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9213 XS✔ ◾ 📝 Assign yourself when picking a PBI
  rules/3-steps-to-a-pbi/rule.md
Labels: Age: 🥚 - New

#9211 XS✔ ◾ Fix formatting in gitignore rule.md
  rules/do-you-use-gitignore-for-your-repo/rule.md
Labels: Age: 🥚 - New

#9212 XS✔ ◾ Add gitignore to git category
  categories/project-delivery/rules-to-better-version-control-with-git.md
Labels: Age: 🥚 - New

#9214 XS✔ ◾ fix list styling
  rules/do-you-use-gitignore-for-your-repo/rule.md
Labels: Age: 🥚 - New

#9220 XS✔ ◾ Improved links and readability
  rules/do-you-keep-your-system-up-to-date/rule.md
  rules/git-based-cms-solutions/rule.md
  rules/have-good-lighting-on-your-home-office/rule.md
  rules/merge-debt/rule.md
Labels: Age: 🥚 - New

#9219 XS✔ ◾ Fixed link + improved URL event-feedback
  categories/marketing-and-video/rules-to-better-event-management.md
  categories/marketing-and-video/rules-to-running-better-user-groups.md
  rules/event-feedback/rule.md
Labels: Age: 🥚 - New

#9218 XS✔ ◾ Improved rule for CTF
  rules/tick-and-flick/rule.md
Labels: Age: 🐥 - Adolescent

#9215 XS✔ ◾ 📷 Updated CheckExtensionCase workflow for image extensions
  .github/workflows/check-extension-case.yml
Labels: Age: 🐓 - Old

#9224 XS✔ ◾ fix rules formatting for special character
  rules/do-you-use-gitignore-for-your-repo/rule.md
Labels: Age: 🥚 - New

#9222 XS✔ ◾ 📄 Added note about automatically closing PBI when PR is merged
  rules/close-pbis-with-context/rule.md
Labels: Age: 🥚 - New, Age: 🐣 - Young

#9221 XS✔ ◾ Improved capitalization and readability
  rules/avoid-auto-closing-issues/rule.md
  rules/do-you-save-failed-experiments-in-abandoned-pull-requests/rule.md
  rules/dont-push-your-pull-requests/rule.md
Labels: Age: 🐤 - Mature

#9228 XS✔ ◾ Add intro to SSRS Rules category
  categories/company-operations/rules-to-better-reporting-services.md
Labels: Age: 🥚 - New

#9225 XS✔ ◾ archived duplicated rule
  rules/bring-evaluation-forms-to-every-event-you-speak-at/rule.md
  rules/event-feedback/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9227 XS✔ ◾ Update Scrum email template
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🐓 - Old

#9233 XS✔ ◾ 🔉Added Adam's audio podcast
  categories/company-operations/rules-to-better-reporting-services.md
Labels: Age: 🥚 - New

#9234 XS✔ ◾ create rule and added to categories
  categories/communication/rules-to-better-meetings.md
  categories/communication/rules-to-better-microsoft-teams.md
  rules/start-meetings-with-energy/meeting-energy-bad-example.png
  rules/start-meetings-with-energy/rule.md
Labels: Age: 🥚 - New

#9232 XS✔ ◾ Update rules-to-better-im.md
  categories/communication/rules-to-better-im.md
Labels: Age: 🥚 - New

#9239 XS✔ ◾ new-rule-meet-now-and-format-changes
  categories/communication/rules-to-better-microsoft-teams.md
  rules/start-meetings-with-energy/rule.md
  rules/when-to-use-meet-now/meet-now-in-teams.png
  rules/when-to-use-meet-now/rule.md
  rules/when-to-use-meet-now/video-call-no-notice.png
Labels: Age: 🥚 - New

#9242 Update rule.md
  rules/when-to-use-meet-now/rule.md
Labels: Age: 🥚 - New

#9243 XS✔ ◾ Update rule.md
  rules/start-meetings-with-energy/rule.md
Labels: Age: 🥚 - New

#9244 Update rule.md
  rules/when-to-use-meet-now/rule.md
Labels: Age: 🥚 - New

#9248 XS✔ ◾ Update rule.md
  rules/start-meetings-with-energy/rule.md
Labels: Age: 🥚 - New

#9249 XS✔ ◾ Update rule.md
  rules/start-meetings-with-energy/rule.md
Labels: Age: 🥚 - New

#9250 XS✔ ◾ Adding an exception
  rules/inform-others-about-chat-message-updates/rule.md
Labels: Age: 🥚 - New

#9251 XS✔ ◾ New rule - company-ai-tools
  categories/artificial-intelligence/rules-to-better-gpt.md
  rules/company-ai-tools/rule.md
  rules/company-gpts/gpt-page.jpg
Labels: Age: 🥚 - New

#9252 XS✔ ◾ Adding examples and shortening the walls of text
  rules/cross-approvals/eagle-eye-report.jpg
  rules/cross-approvals/rule.md
  rules/cross-approvals/teams-approvals-report.jpg
Labels: Age: 🥚 - New

#9254 XS✔ ◾ improving rule so it doesn't get outdated
  rules/do-you-minimize-team-distractions/rule.md
Labels: Age: 🐣 - Young

#9240 Create Rule “archive-mailboxes/rule”
  rules/archive-mailboxes/archive-mailbox.png
  rules/archive-mailboxes/archive-outlook.png
  rules/archive-mailboxes/archive-policy.png
  rules/archive-mailboxes/archive-tags.png
  rules/archive-mailboxes/rule.md
Labels: Age: 🐤 - Mature

#9241 categorizing archive-mailboxes
  categories/communication/rules-to-better-outlook.md
  categories/infrastructure-and-networking/rules-to-better-office-365.md
Labels: Age: 🐤 - Mature

#9229 XS✔ ◾ rewrote rule on keeping devs away from design work
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  categories/design/rules-to-better-websites-layout-and-formatting.md
  rules/do-you-keep-developers-away-from-anything-related-to-design-or-look-and-feel/rule.md
  rules/keep-developers-away-from-design-work/rule.md
Labels: Age: 🐓 - Old

#9247 ✨ Set up TinaCMS for Local Dev
  rules/8-steps-to-scrum/rule.md
  rules/rule/rule.md
  tina/.gitignore
  tina/tina-lock.json
Labels: Age: 🐤 - Mature

#9256 XS✔ ◾ 💄 SSRS rules - Improve style for Adam's podcast link
  categories/company-operations/rules-to-better-reporting-services.md
Labels: Age: 🥚 - New

#9255 XS✔ ◾ Reorder-IM-Rules
  categories/communication/rules-to-better-im.md
Labels: Age: 🥚 - New

#9257 Create Rule “archive-mailboxes/rule”
  rules/archive-mailboxes/rule.md
Labels: Age: 🥚 - New

#9259 XS✔ ◾ v2-reordering-IM-rules
  categories/communication/rules-to-better-im.md
  rules/answer-im-questions-in-order/rule.md
  rules/avoid-sending-unnecessary-messages/rule.md
  rules/make-the-communication-more-efficient-by-referring-back-to-a-subject-of-an-email/rule.md
Labels: Age: 🥚 - New

#9258 XS✔ ◾ fix broken link for rule never-throw-exception-using-system-exception
  rules/never-throw-exception-using-system-exception/rule.md
Labels: Age: 🥚 - New

#9253 XS✔ ◾ fixing markdown
  rules/cross-approvals/rule.md
Labels: Age: 🐓 - Old

#9261 XS✔ ◾ Updated intro for rules to better SSRS
  categories/company-operations/rules-to-better-reporting-services.md
Labels: Age: 🐥 - Adolescent

#9246 Update Rule “do-you-know-the-common-design-principles-part-1/rule”
  rules/do-you-know-the-common-design-principles-part-1/rule.md
Labels: Age: 🐓 - Old

#9237 Update Rule “give-emails-a-business-value/rule”
  rules/give-emails-a-business-value/rule.md
Labels: Age: 🍗 - Ancient

#9230 Update Rule “do-you-know-when-to-enter-your-timesheets/rule”
  rules/do-you-know-when-to-enter-your-timesheets/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9262 XS⚠️ ◾ Add Tina Config
  tina/.gitignore
  tina/collection/rule.ts
  tina/config.ts
  tina/tina-lock.json
Labels: Age: 🥚 - New
