Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-12, with the labels that each got.

#9635 XS✔ ◾ new-rule-and-addition-to-category
  categories/communication/rules-to-better-giving-and-taking-feedback.md
  rules/handle-passive-aggressive-comments/rule.md
Labels: Age: 🥚 - New

#9636 XS✔ ◾ update url
  rules/salary-sacrificing/rule.md
Labels: Age: 🐣 - Young

#9632 XS✔ ◾ Removed broken link "do-you-manage-3rd-party-dependencies/"
  rules/do-you-manage-3rd-party-dependencies/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#9637 XS✔ ◾ new-rule-use-quiet-hours-in-teams
  categories/communication/rules-to-better-im.md
  categories/communication/rules-to-better-microsoft-teams.md
  rules/avoid-sending-unnecessary-messages/rule.md
  rules/know-that-im-interrupts/rule.md
  rules/use-email-for-tasks-only/rule.md
  rules/use-quiet-hours-teams/rule.md
Labels: Age: 🥚 - New

#9638 XS✔ ◾ update-handle-passive-aggressive-comments-rule
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  rules/accepting-unsolicited-feedback/rule.md
  rules/handle-passive-aggressive-comments/rule.md
  rules/understand-the-power-of-empathy/rule.md
Labels: Age: 🥚 - New

#9640 XS✔ ◾ update-quiet-hours-rule
  rules/use-quiet-hours-teams/rule.md
Labels: Age: 🥚 - New

#9641 XS✔ ◾ ♻️ Added missing Uri fronmatter field
  rules/handle-passive-aggressive-comments/rule.md
Labels: Age: 🥚 - New

#9633 XS✔ ◾ Removed broken link + improved readability "best-static-site-tech-stack"
  rules/best-static-site-tech-stack/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt

#9634 XS✔ ◾ Update rule.md
  rules/go-the-extra-mile/rule.md
Labels: Age: 🐤 - Mature

#9643 XS✔ ◾ update-related-rules-correct-uri
  rules/know-that-im-interrupts/rule.md
  rules/use-email-for-tasks-only/rule.md
Labels: Age: 🥚 - New

#9642 XS✔ ◾ Fixed image markdown + simplified the title
  rules/do-you-set-your-application-default-language-to-automatically-change-to-local-language/rule.md
Labels: Age: 🐓 - Old

#9644 Update Rule “do-you-have-monthly-accounting-meetings/rule”
  categories/company-operations/rules-to-better-accounting.md
  rules/do-you-have-monthly-accounting-meetings/rule.md
  rules/monthly-financial-meetings/rule.md
Labels: Age: 🐤 - Mature

#9646 XS✔ ◾ Clipchamp data warning update.md
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🥚 - New

#9647 XS✔ ◾ Update rule adding clipchamp details.md
  rules/recording-screen/rule.md
Labels: Age: 🥚 - New

#9648 XS✔ ◾ Update rule adding good example image.md
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🥚 - New

#9650 XS✔ ◾ Added Done Video
  rules/best-commenting-engine/rule.md
Labels: Age: 🥚 - New

#9652 XS✔ ◾ Update rules-to-better-accounting.md
  categories/company-operations/rules-to-better-accounting.md
Labels: Age: 🐓 - Old

#9656 XS✔ ◾ Update rule added cta to end of Rule.md
  rules/easy-recording-space/rule.md
Labels: Age: 🥚 - New

#9655 Create rule for different symbols mean in npm version selection
  rules/npm-packages-version-symbols/rule.md
Labels: Age: 🥚 - New

#9659 XS✔ ◾ Editing content - adding questions at the end of the rule
  rules/the-value-of-consistency/rule.md
Labels: Age: 🥚 - New

#9653 XS✔ ◾ Update rule.md
  rules/do-you-have-an-engagement-lifecycle/rule.md
Labels: Age: 🐓 - Old

#9651 Update Rule “fix-small-web-errors/rule”
  rules/fix-small-web-errors/rule.md
Labels: Age: 🍗 - Ancient

#9660 XS✔ ◾ Better content design
  rules/do-you-know-the-6-stages-in-the-sales-pipeline/rule.md
Labels: Age: 🥚 - New

#9663 XS✔ ◾ Update rules-to-better-social-media-personal.md
  categories/marketing-and-video/rules-to-better-social-media-personal.md
Labels: Age: 🥚 - New

#9665 XS✔ ◾ wording cut down
  rules/follow-semver-when-publishing-npm-packages/rule.md
Labels: Age: 🥚 - New

#9661 XS✔ ◾ Improved rule to follow standards
  rules/linkedin-job-experience/rule.md
Labels: Age: 🐣 - Young

#9662 XS✔ ◾ Improved headings
  rules/do-you-treat-freebies-as-real-customers/rule.md
Labels: Age: 🐣 - Young

#9669 XS✔ ◾ related rules
  rules/follow-semver-when-publishing-npm-packages/rule.md
Labels: Age: 🥚 - New

#9672 XS✔ ◾ add good example
  rules/follow-semver-when-publishing-npm-packages/rule.md
Labels: Age: 🥚 - New

#9670 XS✔ ◾ add rules to web deployment category
  categories/software-engineering/rules-to-better-websites-deployment.md
Labels: Age: 🐤 - Mature

#9671 XS✔ ◾ add rule to rules-to-better-websites-development.md
  categories/software-engineering/rules-to-better-websites-development.md
Labels: Age: 🐤 - Mature

#9673 Create Rule “limit-mac-addresses-network-switches/rule”
  rules/limit-mac-addresses-network-switches/badexampleports.png
  rules/limit-mac-addresses-network-switches/goodexampleports.png
  rules/limit-mac-addresses-network-switches/rule.md
Labels: Age: 🐤 - Mature

#9674 XS✔ ◾ Update rules-to-better-internet-and-networks.md
  categories/infrastructure-and-networking/rules-to-better-internet-and-networks.md
Labels: Age: 🐤 - Mature

#9675 Zeno Wang - Induction 2 - Content Change to SSW Rules
  rules/chatgpt-cheat-sheet/rule.md
Labels: Age: 🐣 - Young

#9666 XS✔ ◾ fix url and remove unnecessary wording
  rules/npm-packages-version-symbols/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9565 Do you use logging fakes
  categories/software-engineering/rules-to-better-testing.md
  rules/do-you-use-logging-fakes/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9676 XS✔ ◾ Embed the links between related form rules
  rules/data-entry-forms-for-web/rule.md
  rules/do-you-know-how-to-arrange-forms/rule.md
  rules/how-to-align-your-form-labels/rule.md
Labels: Age: 🐤 - Mature

#9682 XS✔ ◾ Added emojis + link to Retro rule
  rules/do-a-retrospective/rule.md
Labels: Age: 🐥 - Adolescent

#9683 XS✔ ◾ Updating images for "definition-of-a-bug" rule
  rules/definition-of-a-bug/YellowScreenofDeath.jpg
  rules/definition-of-a-bug/adding-pbi-to-backlog.png
  rules/definition-of-a-bug/rule.md
  rules/definition-of-a-bug/work-items-type-options.png
Labels: Age: 🐣 - Young

#9681 XS✔ ◾ Added AI emoji to the emoji rule + improvements
  rules/use-emojis/Teams_Emojis_Bad.png
  rules/use-emojis/Teams_Emojis_Good.png
  rules/use-emojis/calendar-emoji.png
  rules/use-emojis/control4-emojis.png
  rules/use-emojis/rule.md
Labels: Age: 🐤 - Mature

#9684 XS✔ ◾ Update react rule syntax (backticks)
  rules/do-you-use-these-useful-react-hooks/rule.md
Labels: Age: 🥚 - New

#9686 XS✔ ◾ Updating section regarding sending an appointment
  rules/specification-review-presentation/rule.md
Labels: Age: 🥚 - New

#9688 XS✔ ◾ Feedback Updates rule.md
  rules/easy-recording-space/rule.md
Labels: Age: 🥚 - New

#9690 Create Rule “host-classic-asp-on-azure/rule”
  categories/software-engineering/rules-to-better-azure.md
  rules/host-classic-asp-on-azure/rule.md
Labels: Age: 🥚 - New

#9566 Do you handle multi os dev teams
  categories/project-delivery/rules-to-better-version-control-with-git.md
  categories/project-delivery/rules-to-better-version-control-with-tfs-aka-source-control.md
  categories/software-engineering/rules-to-better-testing.md
  rules/do-you-handle-multi-os-dev-teams-in-source-control/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9678 XS✔ ◾ ♻️ Update rule uri from `continual-improvement` to `wise-men-improve-rules`
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  categories/company-operations/rules-to-successful-projects.md
  rules/wise-men-improve-rules/rule.md
  rules/wise-men-improve-rules/white-sign.jpg
Labels: rubber stamp, Age: 🍗 - Ancient

#9695 XS✔ ◾ Added missing image extension
  rules/definition-of-a-bug/rule.md
Labels: rubber stamp, Age: 🥚 - New

#9541 Do you use LoggerMessageAttribute
  categories/software-engineering/index.md
  rules/do-you-use-loggermessage-in-net.md/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9693 XS✔ ◾ Improved "maximize-superannuation-benefits" readability
  rules/maximize-superannuation-benefits/rule.md
Labels: Age: 🐤 - Mature

#9698 XS✔ ◾ Add jar of coins image back
  rules/maximize-superannuation-benefits/rule.md
Labels: Age: 🥚 - New

#9649 Create Rule “mdx-vs-markdown/rule”
  rules/mdx-vs-markdown/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9692 Update Rule “appointments-do-you-send-outlook-calendar-appointments-when-appropriate/rule”
  rules/appointments-do-you-send-outlook-calendar-appointments-when-appropriate/rule.md
  rules/appointments-do-you-send-outlook-calendar-appointments-when-appropriate/sugarlearning.jpg
Labels: Age: 🐓 - Old

#9700 Update Rule “for-the-record/rule”
  rules/for-the-record/rule.md
Labels: Age: 🐓 - Old

#9704 XS✔ ◾ adding author
  rules/keep-prompts-concise-and-clear/rule.md
Labels: Age: 🥚 - New

#9706 XS✔ ◾ fixing syntax bug
  rules/keep-prompts-concise-and-clear/rule.md
Labels: Age: 🥚 - New

#9701 XS✔ ◾ Making links descriptive "application insights in sharepoint" rule
  rules/application-insights-in-sharepoint/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9703 XS✔ ◾ Fixed link + more "web tests app insights monitos trends" rule
  rules/do-you-add-web-tests-to-application-insights-to-montior-trends-over-time/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9705 XS✔ ◾ Making form label alignment have good and bad examples
  rules/how-to-align-your-form-labels/adaptative-labels.gif
  rules/how-to-align-your-form-labels/labels-left-aligned.png
  rules/how-to-align-your-form-labels/labels-right-aligned.png
  rules/how-to-align-your-form-labels/labels-top-aligned.png
  rules/how-to-align-your-form-labels/rule.md
  rules/use-adaptive-placeholders-on-your-forms/rule.md
Labels: Age: 🍗 - Ancient

#9702 XS✔ ◾ Fixed links and list "set up application insights" rule
  rules/how-to-set-up-application-insights/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9711 XS✔ ◾ Update rules-to-better-azure.md
  categories/software-engineering/rules-to-better-azure.md
Labels: Age: 🥚 - New

#9713 XS✔ ◾ Aspire Rule - Extend good and bad examples
  rules/aspire/rule.md
Labels: Age: 🥚 - New

#9712 XS✔ ◾ Add image from form
  rules/aspire/aspire-cool-stuff.png
  rules/aspire/rule.md
Labels: Age: 🥚 - New

#9716 XS✔ ◾ Delete rules/hand-over-responsibilities/angry-dev-beach.png
  rules/hand-over-responsibilities/angry-dev-at-beach-red.png
  rules/hand-over-responsibilities/angry-dev-beach.png
  rules/hand-over-responsibilities/rule.md
Labels: Age: 🥚 - New

#9717 XS✔ ◾ Update rule.md
  rules/how-to-hand-over-tasks-to-others/rule.md
Labels: Age: 🥚 - New

#9707 New Rule securely-share-sensitive-information
  categories/infrastructure-and-networking/rules-to-better-security.md
  rules/best-practices-office-automation/rule.md
  rules/securely-share-sensitive-information/SecureSprintReviews.png
  rules/securely-share-sensitive-information/SecureSprintReviewsBad.png
  rules/securely-share-sensitive-information/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9720 XS✔ ◾ 🔗 Added related links to rules
  rules/do-you-cc-your-account-manager-on-emails-relating-to-new-work/rule.md
  rules/know-the-non-scrum-roles/rule.md
Labels: Age: 🥚 - New

#9719 Update Rule “send-email-tasks-to-individuals/rule”
  rules/send-email-tasks-to-individuals/rule.md
Labels: Age: 🐓 - Old

#9722 Update Rule “pick-a-chinese-name/rule”
  rules/pick-a-chinese-name/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9721 XS✔ ◾ Adding related, improving template, adding image
  rules/making-a-great-done-video/rule.md
  rules/monthly-stakeholder-video/reports-list-marketing.jpg
  rules/monthly-stakeholder-video/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9723 XS✔ ◾ Improved rule
  rules/securely-share-sensitive-information/rule.md
Labels: Age: 🐥 - Adolescent

#9724 XS✔ ◾ Fixed the example which was plain text
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  rules/cc-account-manager-on-emails-related-to-new-work/rule.md
  rules/do-you-cc-your-account-manager-on-emails-relating-to-new-work/rule.md
Labels: Age: 🐓 - Old

#9726 XS✔ ◾ Update rule.md
  rules/definition-of-a-bug/rule.md
Labels: Age: 🥚 - New
