Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-02, with the labels that each got.

#7886 XS✔ ◾ Fixed up bullet spacing
  rules/use-mass-transit/rule.md
Labels: Age: 🥚 - New

#7885 XS✔ ◾ Added more examples to Hours abbreviation
  rules/right-format-to-write-videos-time-length/rule.md
Labels: Age: 🥚 - New

#7897 XS✔ ◾ Update rule.md
  rules/git-based-cms-solutions/rule.md
Labels: Age: 🥚 - New

#7900 XS✔ ◾ Update title
  rules/git-based-cms-solutions/rule.md
Labels: Age: 🥚 - New

#7898 XS✔ ◾ CodeAuditor - Fix Tom I's broken image
  rules/migrating-web-apps/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7896 XS✔ ◾ Updated CMS rule
  categories/websites/rules-to-better-websites-development.md
  rules/cms-solutions/rule.md
Labels: Age: 🐣 - Young

#7899 XS✔ ◾ CodeAuditor - Fix broken link
  rules/understanding-data-lakes/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7894 updateRule/the-best-dependency-injection-container
  rules/the-best-dependency-injection-container/Autofac_web.png
  rules/the-best-dependency-injection-container/di-container-bad.png
  rules/the-best-dependency-injection-container/dic-bad.png
  rules/the-best-dependency-injection-container/dic-good.png
  rules/the-best-dependency-injection-container/rule.md
Labels: Age: 🐓 - Old

#7906 XS✔ ◾ Updates to /the-best-mobile-app-for-expenses
  rules/do-you-use-the-best-mobile-app-for-expenses/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7903 XS✔ ◾ fixed heading inside info box
  rules/do-you-know-what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7913 Update Rule “add-attributes-to-picture-links/rule”
  rules/add-attributes-to-picture-links/rule.md
Labels: Age: 🐤 - Mature

#7912 Update Rule “make-title-h1-and-h2-tags-descriptive/rule”
  rules/make-title-h1-and-h2-tags-descriptive/rule.md
Labels: Age: 🐤 - Mature

#7910 Update Rule “use-robots-txt-effectively/rule”
  rules/use-robots-txt-effectively/rule.md
Labels: Age: 🐤 - Mature

#7911 Update Rule “descriptive-links/rule”
  rules/descriptive-links/rule.md
Labels: Age: 🐤 - Mature

#7905 XS✔ ◾ Update index.md
  categories/artificial-intelligence/index.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7883 XS✔ ◾ Added link to consulting pages from categories
  categories/application-lifecycle-management-alm/rules-to-better-scrum.md
  categories/artificial-intelligence/rules-to-better-gpt.md
  categories/communication/rules-to-better-microsoft-teams.md
  categories/communication/rules-to-better-remote-work.md
  categories/design-and-presentation/rules-to-better-designers.md
  categories/infrastructure-and-networking/rules-to-better-backups.md
  categories/infrastructure-and-networking/rules-to-better-data-protection-manager-dpm.md
  categories/infrastructure-and-networking/rules-to-better-hyper-v.md
  categories/infrastructure-and-networking/rules-to-better-office-365.md
  categories/infrastructure-and-networking/rules-to-better-security.md
  categories/infrastructure-and-networking/rules-to-better-sharepoint-for-end-users.md
  categories/management/rules-to-better-crm.md
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  categories/marketing-and-video/rules-to-better-video-recording.md
  categories/others/rules-to-better-brainstorming.md
  categories/products/rules-to-better-zendesk.md
  categories/reporting-solutions/rules-to-better-business-intelligence.md
  categories/reporting-solutions/rules-to-better-power-bi.md
  categories/software-development/rules-to-better-apps-mobile.md
  categories/software-development/rules-to-better-architecture-and-code-review.md
  categories/software-development/rules-to-better-azure.md
  categories/software-development/rules-to-better-blazor.md
  categories/software-development/rules-to-better-bots.md
  categories/software-development/rules-to-better-clean-architecture.md
  categories/software-development/rules-to-better-devops.md
  categories/software-development/rules-to-better-internationalization.md
  categories/software-development/rules-to-better-maui.md
  categories/software-development/rules-to-better-net-projects.md
  categories/software-development/rules-to-better-net8-migrations.md
  categories/software-development/rules-to-better-power-platform.md
  categories/software-development/rules-to-better-powershell.md
  categories/software-development/rules-to-better-sharepoint-for-developers.md
  categories/software-development/rules-to-better-sql-databases-admin.md
  categories/software-development/rules-to-better-sql-databases-developers.md
  categories/software-development/rules-to-better-sql-databases-performance.md
  categories/software-development/rules-to-better-web-api.md
  categories/websites/rules-to-better-nextjs.md
  categories/websites/rules-to-better-react.md
  categories/websites/rules-to-better-vue.md
  categories/websites/rules-to-better-wordpress.md
  rules/implementing-intune/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7917 XS✔ ◾ add hard-tasks first rule
  categories/communication/rules-to-better-communication.md
  categories/management/rules-to-successful-projects.md
  rules/attention-to-detail/rule.md
  rules/hard-tasks-first/rule.md
  rules/tofu/rule.md
Labels: Age: 🥚 - New

#7915 XS✔ ◾ Improvements to rules format and markdown
  rules/do-you-know-yarp-is-awesom/rule.md
Labels: Age: 🥚 - New

#7914 XS✔ ◾ Improvements to the rule format and markdown
  rules/do-you-know-how-to-configure-yarp/rule.md
Labels: Age: 🥚 - New

#7919 XS✔ ◾ Renamed "Rules to Better AI Image Generators" to "Rules to Better AI Generated Media"
  categories/artificial-intelligence/index.md
  categories/artificial-intelligence/rules-to-better-ai-generated-media.md
Labels: Age: 🥚 - New

#7873 Create Rule “source-control-tools/rule”
  assets/fork.jpg
  assets/gitkraken.png
  assets/sourcetree.png
  categories/application-lifecycle-management-alm/rules-to-better-version-control-with-tfs-aka-source-control.md
  rules/source-control-tools/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7918 XS✔ ◾ Add related rules
  categories/application-lifecycle-management-alm/rules-to-better-scrum.md
  rules/attention-to-detail/rule.md
  rules/break-tasks/rule.md
  rules/follow-up-effectively/rule.md
  rules/professional-integrity/rule.md
  rules/tofu/rule.md
Labels: Age: 🐤 - Mature

#7904 XS✔ ◾ Update rule.md
  rules/ai-tools-voice-translations/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7921 XS✔ ◾ Updated greybox with the link to template
  rules/seo-checklist/rule.md
Labels: Age: 🥚 - New

#7923 XS✔ ◾ Fixed formatting and improved content
  rules/include-important-keywords-where-it-matters/rule.md
Labels: Age: 🥚 - New

#7922 XS✔ ◾ removed caption from google logo
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
Labels: Age: 🥚 - New

#7924 XS✔ ◾ CodeAuditor - Fix syntax error
  rules/tofu/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#7927 XS✔ ◾ Update Piers' new rules
  rules/attention-to-detail/rule.md
Labels: Age: 🥚 - New

#7928 XS✔ ◾ Update rules-for-error-handling.md - says error instead of application wrong meaning
  categories/software-development/rules-for-error-handling.md
Labels: Age: 🐤 - Mature

#7925 XS✔ ◾ Fixed punctuation + added missing space after link
  rules/do-you-run-events/rule.md
Labels: Age: 🐓 - Old

#7926 XS✔ ◾ Fixed lists + removed the extra icon image
  rules/do-you-follow-up-with-people-who-register-for-webinars/rule.md
Labels: Age: 🐓 - Old

#7931 add interfaces abstract classes rule
  categories/software-development/rules-to-better-code.md
  rules/interfaces-abstract-classes/rule.md
  rules/read-source-code/rule.md
Labels: Age: 🥚 - New

#7932 XS✔ ◾ Grammar changes
  rules/interfaces-abstract-classes/rule.md
Labels: Age: 🥚 - New

#7933 XS✔ ◾ minor grammar changes
  rules/interfaces-abstract-classes/rule.md
Labels: Age: 🥚 - New

#7936 Update Rule “interfaces-abstract-classes/rule”
  rules/interfaces-abstract-classes/rule.md
Labels: Age: 🐣 - Young

#7938 XS✔ ◾ 🐛 Fix Duplicate Image Name
  rules/architecture-diagram/bad-azure-resource-screenshot.jpg
  rules/architecture-diagram/rule.md
  rules/azure-devops-permissions/rule.md
  rules/azure-devops-permissions/team-administrator.png
  rules/do-you-know-how-to-enter-a-hubdoc-receipt/folders-in-Hubdoc.png
  rules/do-you-know-how-to-enter-a-hubdoc-receipt/rule.md
  rules/do-you-use-gzip/rule.md
  rules/do-you-use-gzip/use-gzip-2.png
  rules/do-you-use-gzip/use-gzip-3.png
  rules/do-you-use-gzip/use-gzip-4.png
  rules/do-you-use-gzip/use-gzip-5.png
  rules/do-you-use-gzip/use-gzip-6.png
  rules/do-you-use-gzip/use-gzip-7.png
  rules/do-you-use-lead-magnets-as-part-of-your-marketing-strategy/lead-magnet.png
  rules/do-you-use-lead-magnets-as-part-of-your-marketing-strategy/rule.md
  rules/do-you-use-optinmonster-for-your-content-downloads/example-OptinMonster.png
  rules/do-you-use-optinmonster-for-your-content-downloads/rule.md
  rules/do-you-use-pagespeed/compressed-result.png
  rules/do-you-use-pagespeed/rule.md
  rules/do-you-use-the-best-code-analysis-tools/ReSharper-green.png
  rules/do-you-use-the-best-code-analysis-tools/rule.md
  rules/have-good-lighting-on-your-home-office/rule.md
  rules/have-good-lighting-on-your-home-office/video-background.png
  rules/how-to-install-skypepop/example-email-a-link.png
  rules/how-to-install-skypepop/rule.md
  rules/how-to-install-skypepop/send-email.png
  rules/linkedin-creator-mode/bad-no-hashtag.png
  rules/linkedin-creator-mode/rule.md
  rules/make-sure-all-software-uses-english/install-language-pack.png
  rules/make-sure-all-software-uses-english/rule.md
  rules/tax-invoice-vs-eftpos-receipt/invoice-receipt-1.png
  rules/tax-invoice-vs-eftpos-receipt/invoice-receipt-4.png
  rules/tax-invoice-vs-eftpos-receipt/rule.md
  rules/use-branch-protection/bad-unprotected-main-branch.jpg
  rules/use-branch-protection/rule.md
  rules/website-heatmaps/rule.md
  rules/website-heatmaps/ssw-heatmap.png
Labels: Age: 🥚 - New

#7937 XS✔ ◾ ⚡️Update do you ensure compliance and governance without compromising agility
  rules/do-you-ensure-compliance-and-governance-without-compromising-agility/Bad_over_compliance.jpeg
  rules/do-you-ensure-compliance-and-governance-without-compromising-agility/Good_compliance_and_agility.jpeg
  rules/do-you-ensure-compliance-and-governance-without-compromising-agility/rule.md
Labels: Age: 🐤 - Mature

#7942 XS✔ ◾ CodeAuditor - Fix broken content
  rules/attention-to-detail/rule.md
Labels: Age: 🐤 - Mature

#7941 XS✔ ◾ CodeAuditor - Fix broken link
  rules/include-important-keywords-where-it-matters/rule.md
Labels: Age: 🐤 - Mature

#7940 XS✔ ◾ CodeAuditor - Fix broken link
  rules/why-use-data-protection-manager/rule.md
Labels: Age: 🐤 - Mature

#7951 XS✔ ◾ CodeAuditor - Fix broken link
  rules/use-code-migrations/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7950 XS✔ ◾ CodeAuditor - Fix broken link
  rules/do-you-respond-to-blogs-and-forums-with-the-standard-footer/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7949 XS✔ ◾ CodeAuditor - Fix broken link
  rules/do-you-advise-staff-members-you-are-about-to-perform-a-migration/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7948 XS✔ ◾ CodeAuditor - Fix broken link
  rules/do-you-know-how-to-upgrade-your-tfs2010-databases-the-big-one/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7954 XS✔ ◾ CodeAuditor - Fix broken link
  rules/do-you-avoid-reviewing-performance-without-metrics/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7955 XS✔ ◾ CodeAuditor - Fix broken link
  rules/do-you-use-the-best-code-analysis-tools/rule.md
Labels: codeauditor fix, Age: 🐤 - Mature

#7956 XS✔ ◾ CodeAuditor - Fix broken link
  rules/follow-naming-conventions-for-your-boolean-property/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#7952 Cms/calinator444/ssw.rules.content/rule/interfaces abstract classes/rule
  rules/interfaces-abstract-classes/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7964 XS✔ ◾ General improvements to the rule /gather-insights-from-company-emails/
  rules/gather-insights-from-company-emails/rule.md
Labels: Age: 🐣 - Young

#7972 XS✔ ◾ 💄Added prefix "Layout" to some rules
  rules/avoid-using-word-report/rule.md
  rules/consistent-report-name/rule.md
  rules/include-feedback-information-in-report/rule.md
  rules/include-useful-footer/rule.md
  rules/least-content-in-page-header/rule.md
  rules/print-and-display-report-on-web/rule.md
  rules/reporting-services-version/rule.md
  rules/show-errors-in-red/rule.md
  rules/underline-items-with-hyperlink-action/rule.md
Labels: Age: 🥚 - New

#7973 XS✔ ◾ Update rule.md - better formatting and new uri
  categories/websites/rules-to-better-website-development-asp-net.md
  rules/packages-to-add-to-your-mvc-project/rule.md
Labels: Age: 🐤 - Mature

#7970 XS✔ ◾ CodeAuditor - Fix broken link
  rules/tick-and-flick/rule.md
Labels: Age: 🐤 - Mature

#7971 XS✔ ◾ CodeAuditor - Fix broken link
  rules/understand-the-dangers-of-social-engineering/rule.md
Labels: Age: 🐤 - Mature

#7968 Update Rule “harnessing-the-power-of-no/rule”
  rules/harnessing-the-power-of-no/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7824 XS✔ ◾ Update cross platform UI Tests for Xamarin rule
  rules/conduct-cross-platform-ui-tests/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#7980 XS✔ ◾ fixed formatting for bullet points
  rules/packages-to-add-to-your-mvc-project/rule.md
Labels: Age: 🥚 - New

#7985 Add 'Sample Names' prefix to consistent examples rule
  rules/use-generic-consistent-names-on-examples/rule.md
Labels: Age: 🥚 - New

#7978 XS✔ ◾ Fixed captions + links
  rules/do-you-use-gzip/rule.md
Labels: Age: 🐥 - Adolescent

#7979 XS✔ ◾ Fixed acknowledgments
  rules/appointments-throw-it-in-their-calendar/rule.md
Labels: Age: 🐥 - Adolescent

#7981 XS✔ ◾ CodeAuditor - Fix broken link
  rules/task-board/rule.md
Labels: Age: 🐣 - Young

#7986 XS✔ ◾ Fix Broken Alumni Link
  rules/use-icons-sharepoint/rule.md
Labels: Age: 🐥 - Adolescent

#7976 XS✔ ◾ Fixed Scrum terms + fixed captions "merge-PRs" rule
  rules/merge-open-source-pull-requests-using-the-squash-and-merge-option/rule.md
Labels: Age: 🐓 - Old

#7974 Figure: Added bad example figures in 2 rules - one for branch merging, and another for pbix files in source control
  rules/do-you-use-version-control-with-power-bi/bad-example-pbix-source-control.png
  rules/do-you-use-version-control-with-power-bi/rule.md
  rules/merge-open-source-pull-requests-using-the-squash-and-merge-option/merge-bad-example.png
  rules/merge-open-source-pull-requests-using-the-squash-and-merge-option/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7987 XS✔ ◾ Made title more clear + moved bad examples together
  rules/custom-instructions/rule.md
Labels: Age: 🐣 - Young

#7988 XS✔ ◾ Rename rule.md to rule.md
  rules/use-squash-and-merge-for-open-source-projects/rule.md
Labels: Age: 🥚 - New

#7996 XS✔ ◾ move test please earlier in agenda
  rules/brainstorming-agenda/rule.md
Labels: Age: 🥚 - New

#7997 XS✔ ◾ add agenda link
  categories/others/rules-to-better-brainstorming.md
  rules/brainstorming-intro-presentation/rule.md
Labels: Age: 🥚 - New

#7991 Create rule on using comments for feedback in PowerPoint
  categories/communication/rules-to-better-powerpoint-presentations.md
  rules/powerpoint-comments/assign-task.png
  rules/powerpoint-comments/create-new-comment.png
  rules/powerpoint-comments/resolve-task.png
  rules/powerpoint-comments/rule.md
  rules/powerpoint-comments/task-completed.png
Labels: Age: 🐓 - Old

#7984 Update rule about K6
  rules/do-you-avoid-reviewing-performance-without-metrics/rule.md
  rules/have-tests-for-performance/rule.md
  rules/have-tests-for-performance/run-script-with-k6-cloud.png
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#7998 XS✔ ◾ add see appointment
  rules/brainstorming-intro-presentation/rule.md
Labels: Age: 🥚 - New

#8000 XS✔ ◾ Fixed a filename that breaks windows filesystem
  rules/shadow-spec-reviews/architects.png
  rules/shadow-spec-reviews/rule.md
Labels: Age: 🥚 - New

#7982 XS✔ ◾ CodeAuditor - Ignored sample broken link
  rules/do-you-know-how-to-delete-orphaned-users-from-the-people-picker/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#8001 GitHub Notification - Update Rule with newest UI and make it easier to understand
  rules/github-notifications/actions-notification.png
  rules/github-notifications/rule.md
  rules/github-notifications/screen-shot-2022-03-03-at-2.20.33-pm.png
  rules/github-notifications/watching-notification.png
Labels: Age: 🐤 - Mature

#7995 Updated Rule “clean-git-history/rule” to include paragraph about descriptive commit messages
  rules/clean-git-history/rule.md
Labels: Age: 🐓 - Old

#8003 XS✔ ◾ Improvements to @mentions in PBI rule
  rules/when-you-use-mentions-in-a-pbi/rule.md
Labels: Age: 🥚 - New

#8002 XS✔ ◾ Added word "duplicated" + related rule + other improvements "avoid-redundant-links
  rules/avoid-redundant-links/rule.md
Labels: Age: 🥚 - New

#7999 XS✔ ◾ Trying to make caption instructions more clear
  rules/rule/rule.md
Labels: Age: 🐓 - Old

#7989 XS✔ ◾ Added note about raising major bugs to the PO
  rules/escalate-key-updates/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#8007 XS✔ ◾ Adding a new rule for Microsoft Loop
  categories/communication/rules-to-better-communication.md
  rules/do-you-know-the-best-tool-for-facilitating-real-time-colloboration/microsoft-loop-good-example.jpg
  rules/do-you-know-the-best-tool-for-facilitating-real-time-colloboration/onenote-bad-example.jpg
  rules/do-you-know-the-best-tool-for-facilitating-real-time-colloboration/rule.md
Labels: Age: 🥚 - New

#8006 XS✔ ◾ CodeAuditor - Fix absolute internal path
  rules/do-you-make-business-travel-easier/rule.md
Labels: Age: 🐣 - Young

#8005 XS✔ ◾ CodeAuditor - Fix absolute internal urls
  rules/manage-travel-in-centralized-systems/rule.md
Labels: Age: 🐣 - Young

#8008 XS✔ ◾ removed backslashes created by CMS + small improvements
  rules/when-you-use-mentions-in-a-pbi/rule.md
Labels: Age: 🐓 - Old

#8012 XS✔ ◾ General improvements to /captions rule
  rules/add-useful-and-concise-figure-captions/rule.md
Labels: Age: 🥚 - New

#8010 XS✔ ◾ Making where to @mention more clear
  rules/when-you-use-mentions-in-a-pbi/rule.md
Labels: Age: 🐓 - Old

#8013 XS✔ ◾ Create rules-to-better-board-meetings.md
  categories/communication/rules-to-better-board-meetings.md
Labels: Age: 🥚 - New

#8020 DNS - new rule for CTF this week.
  rules/dns-what-and-how-it-works/DNS-how-it-works.png
  rules/dns-what-and-how-it-works/rule.md
Labels: Age: 🥚 - New

#8022 XS✔ ◾ Update category rules-to-better-internet-and-networks.md - add the ne…
  categories/infrastructure-and-networking/rules-to-better-internet-and-networks.md
  categories/infrastructure-and-networking/rules-to-better-system-administrators.md
Labels: Age: 🥚 - New

#8025 XS✔ ◾ Update rule.md - add related rule
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🐤 - Mature

#8024 XS✔ ◾ Update rule.md - Add another option for 'Not Done'
  rules/reply-done-and-delete-the-email/rule.md
Labels: Age: 🐤 - Mature

#8028 XS✔ ◾ Manage up - Make it clear that options should be enumerate
  rules/do-you-manage-up/rule.md
Labels: Age: 🐤 - Mature
