Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2024-10, with the labels that each got.

#9317 XS✔ ◾ relate-date-format-rules
  rules/add-days-to-dates/rule.md
  rules/do-you-display-dates-in-a-human-friendly-format/rule.md
  rules/do-you-know-how-to-format-dates-to-include-the-weekday/rule.md
Labels: Age: 🥚 - New

#9319 XS✔ ◾ Update rule.md
  rules/scrum-should-be-capitalized/rule.md
Labels: Age: 🥚 - New

#9320 XS✔ ◾ new rule video-topic-ideas
  rules/video-topic-ideas/rule.md
Labels: Age: 🥚 - New

#9322 XS✔ ◾ fixing email template syntax
  rules/video-topic-ideas/rule.md
Labels: Age: 🥚 - New

#9323 XS✔ ◾ fixing bold for consistency
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#9324 XS✔ ◾ Updates to calling when blocked + IM ordering
  categories/communication/rules-to-better-im.md
  rules/if-communication-is-not-simple-call-the-person-instead-of-im/rule.md
  rules/warn-then-call/rule.md
  rules/when-to-email-chat-call-or-meet/rule.md
Labels: Age: 🐣 - Young

#9318 XS✔ ◾ ✨ New Rule - Do you know how to automatically move emails into specific folders?
  categories/communication/rules-to-better-email.md
  rules/move-emails-into-folders/figure-1-open-rules-dialog.png
  rules/move-emails-into-folders/figure-2-setup-the-rule.png
  rules/move-emails-into-folders/rule.md
Labels: Age: 🐓 - Old

#9325 XS✔ ◾ Fixed title, fixed markdown for figures, improved content and captions /add-days-to-dates/
  rules/add-days-to-dates/rule.md
Labels: Age: 🥚 - New

#9328 XS✔ ◾ Updating image to latest outlook v2
  rules/do-you-ring-a-bell-or-similar-when-you-secure-a-big-deal-make-a-sale-or-get-some-great-feedback/rule.md
Labels: Age: 🥚 - New

#9329 XS✔ ◾ Fixed typo
  rules/password-manager/rule.md
Labels: Age: 🥚 - New

#9326 XS✔ ◾ Fixed heading + image markdown "easy-questions"
  rules/easy-questions/rule.md
Labels: Age: 🐤 - Mature

#9332 XS✔ ◾ Improved readability "for-the-record" rule
  rules/for-the-record/rule.md
  rules/rule/rule.md
Labels: Age: 🐣 - Young

#9334 Fix broken info box
  rules/request-a-test-please/rule.md
Labels: Age: 🥚 - New

#9333 XS✔ ◾ ✏️ Added headings - Do you know how to automatically move emails into specific folders?
  rules/move-emails-into-folders/rule.md
Labels: Age: 🥚 - New

#9336 XS✔ ◾ AI pair programming - new copilot features
  rules/ai-pair-programming/rule.md
Labels: Age: 🥚 - New

#9337 XS✔ ◾ emails into PBIs - fix email template
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🐥 - Adolescent

#9338 XS✔ ◾ Update rule.md
  rules/ai-pair-programming/rule.md
Labels: Age: 🐣 - Young

#9330 XS✔ ◾ fixing capitalizations in Scrum terms
  categories/project-delivery/rules-to-better-product-owners.md
  rules/do-you-assign-severity-levels/rule.md
  rules/scrum-in-github/rule.md
  rules/tasks-with-a-ticking-clock/rule.md
Labels: Age: 🐓 - Old

#9331 XS✔ ◾ new rule best-ai-tools
  best-ai-tools/rule.md
  categories/artificial-intelligence/rules-to-better-gpt.md
Labels: Age: 🐓 - Old

#9345 XS✔ ◾ ✏️ Updated rule - Do you know why Angular is great?
  rules/why-angular-is-great/rule.md
Labels: Age: 🥚 - New

#9344 XS✔ ◾ ✨ New Rule - Do you know to stretch when working at a desk?
  rules/stretch-when-working-on-desk/bad-example-bad-posture.png
  rules/stretch-when-working-on-desk/good-example-stretch-back.png
  rules/stretch-when-working-on-desk/good-example-stretch-chest.png
  rules/stretch-when-working-on-desk/good-example-stretch-hip-flexors.png
  rules/stretch-when-working-on-desk/rule.md
Labels: Age: 🥚 - New

#9346 XS✔ ◾ new-rule-integration-tests-for-llm-prompts
  categories/artificial-intelligence/rules-to-better-ai-development.md
  rules/write-integration-tests-for-llm-prompts/EagleEye.png
  rules/write-integration-tests-for-llm-prompts/rule.md
Labels: Age: 🥚 - New

#9343 XS✔ ◾ new-rule-evaluate-slms-vs-azure-cloud-llms
  categories/artificial-intelligence/rules-to-better-ai-development.md
  rules/evaluate-slms-vs-azure-cloud-llms/rule.md
Labels: Age: 🐣 - Young

#9347 XS✔ ◾ ✏️ Added rule to category - Better Health
  categories/company-operations/rules-to-better-health-and-exercise-in-the-workplace.md
Labels: Age: 🥚 - New

#9342 XS✔ ◾ Sprint Review Videos - Be Visible You Saw It
  rules/summary-recording-sprint-reviews/rule.md
Labels: Age: 🐥 - Adolescent

#9341 XS✔ ◾ Do you use AI pair programming? - specify Copilot (product name) instead of the website url
  rules/ai-pair-programming/rule.md
Labels: Age: 🐤 - Mature

#9340 XS✔ ◾ Small changes for consistency
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🐓 - Old

#9350 XS✔ ◾ Pr suggestions - add video
  rules/pr-suggest-changes/rule.md
Labels: Age: 🐤 - Mature

#9354 XS✔ ◾ Added YakShaver box
  rules/when-to-use-meet-now/rule.md
Labels: Age: 🥚 - New

#9352 XS✔ ◾ Small improvements "ethodology-daily-scrums"
  rules/methodology-daily-scrums/rule.md
Labels: Age: 🐥 - Adolescent

#9357 XS✔ ◾ Improved rule "use-https-text/"
  rules/use-https-text/rule.md
Labels: Age: 🐣 - Young

#9351 XS✔ ◾ Fixed captions "/complete-major-changes-on-another-repo"
  rules/complete-major-changes-on-another-repo/rule.md
Labels: Age: 🐤 - Mature

#9353 XS✔ ◾ Added codeauditor box
  rules/avoid-clear-text-email-addresses-in-web-pages/rule.md
Labels: Age: 🐥 - Adolescent

#9362 XS✔ ◾ Improved readability "for-the-record"
  rules/for-the-record/rule.md
Labels: Age: 🥚 - New

#9363 XS✔ ◾ Be more specific on which platform to interact on
  rules/summary-recording-sprint-reviews/rule.md
Labels: Age: 🥚 - New

#9366 XS✔ ◾ Added graphic vs ux design rule
  categories/design/rules-to-better-designers.md
Labels: Age: 🥚 - New

#9355 XS✔ ◾ Added/updated prefixes, removed many unrelated, and added box
  categories/marketing-and-video/rules-to-better-social-media-for-business.md
  rules/do-you-know-how-to-deal-with-negative-comments/rule.md
  rules/do-you-know-how-to-use-social-media-effectively-in-china/rule.md
  rules/do-you-know-that-every-comment-gets-a-tweet/rule.md
  rules/do-you-know-what-to-tweet/rule.md
  rules/do-you-know-when-to-use-a-hashtag-vs-a-mention/rule.md
  rules/ok-words-in-china/rule.md
  rules/promotion-do-people-know-about-your-event/rule.md
  rules/thank-others-for-each-reference-to-you/rule.md
  rules/twitter-for-professionals/rule.md
  rules/twitter-how-to-verify-your-account/rule.md
  rules/twitter-tip-content-creators/rule.md
  rules/weed-out-spammers/rule.md
Labels: Age: 🐥 - Adolescent

#9361 XS✔ ◾ Added new rules on AI
  categories/artificial-intelligence/rules-to-better-gpt.md
Labels: Age: 🐣 - Young

#9367 XS✔ ◾ Improvements to the rule "graphic-vs-ui-ux-design"
  rules/graphic-vs-ui-ux-design/rule.md
Labels: Age: 🥚 - New

#9349 XS✔ ◾ Updating rules on Scrum
  categories/project-delivery/rules-to-better-scrum.md
  rules/8-steps-to-scrum/rule.md
  rules/meeting-do-you-update-your-tasks-before-the-daily-scrum/rule.md
  rules/methodology-daily-scrums/rule.md
  rules/scrum-master-do-you-schedule-the-3-meetings/8StepstoScrum-meetings.png
  rules/scrum-master-do-you-schedule-the-3-meetings/rule.md
  rules/what-happens-at-a-sprint-planning-meeting/rule.md
  rules/what-happens-at-a-sprint-review-meeting/rule.md
  rules/what-happens-at-retro-meetings/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9373 🗑️ Removed whitespace after backslash
  rules/scrum-master-do-you-schedule-the-3-meetings/rule.md
Labels: Age: 🥚 - New

#9371 Update Rule “windows-hello/rule”
  rules/windows-hello/rule.md
  rules/windows-hello/whfb.png
Labels: Age: 🥚 - New

#9368 XS✔ ◾ Restructure the Done Video rule + make the points more specific
  rules/making-a-great-done-video/rule.md
Labels: Age: 🐣 - Young

#9374 XS✔ ◾ Updating GPT and URI
  rules/meetings-are-you-prepared-for-the-initial-meeting/rule.md
Labels: Age: 🥚 - New

#9372 XS✔ ◾ Fixed casing
  rules/twitter-for-professionals/rule.md
Labels: rubber stamp, Age: 🐥 - Adolescent

#9348 XS✔ ◾ new rule github-mobile
  categories/software-engineering/rules-to-better-github.md
  rules/github-mobile/contributions-mobile.png
  rules/github-mobile/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9380 XS✔ ◾ Updating URI
  categories/client-engagement/rules-to-better-sales.md
Labels: Age: 🥚 - New

#9377 XS✔ ◾ Fixed broken link + other improvements
  rules/linkedin-profile/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#9375 XS✔ ◾ updated link text for better reading
  rules/scrum-master-do-you-schedule-the-3-meetings/rule.md
Labels: Age: 🐥 - Adolescent

#9379 XS✔ ◾ Removed broken links
  rules/avoid-using-if-else-instead-of-switch-block/rule.md
  rules/do-you-use-datasets-or-create-your-own-business-objects/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#9381 XS✔ ◾ ✏️ Updated table in Sprint Review email
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#9382 XS✔ ◾ ✏️ Updated table in Sprint Forecast email
  rules/sprint-forecast/rule.md
Labels: Age: 🥚 - New

#9384 XS✔ ◾ Adding Image
  rules/meetings-are-you-prepared-for-the-initial-meeting/rule.md
Labels: Age: 🥚 - New

#9387 XS✔ 🐛Update wording in do-you-know-the-how-to-be-a-good-product-owner
  rules/do-you-know-the-how-to-be-a-good-product-owner/rule.md
Labels: Age: 🥚 - New

#9388 XS✔ ◾ 🐛Fix rule: scrum-master-support-product-owner
  rules/scrum-master-support-po/rule.md
Labels: Age: 🥚 - New

#9383 Update Rule “the-best-ai-image-generators/rule”
  rules/the-best-ai-image-generators/rule.md
Labels: Age: 🐥 - Adolescent

#9385 S⚠️ ◾ 🦙 Adds the Sidebar collection
  tina/collections/rules.ts
  tina/collections/schemas/bodySchema.json
  tina/collections/sidebar.ts
  tina/config.ts
  tina/tina-lock.json
Labels: Age: 🐣 - Young

#9393 XS✔ ◾ initial meeting prep - add video
  rules/prepare-for-initial-meetings/rule.md
Labels: Age: 🥚 - New

#9395 XS✔ ◾ updating good example
  rules/video-background/good-background-seth.png
  rules/video-background/jimmy-teams.jpg
  rules/video-background/rule.md
Labels: Age: 🥚 - New

#9396 XS✔ ◾ Improvements to /prepare-for-initial-meetings/
  rules/prepare-for-initial-meetings/rule.md
Labels: Age: 🥚 - New

#9397 XS✔ ◾ Update rule.md
  rules/prepare-for-initial-meetings/rule.md
Labels: Age: 🥚 - New

#9398 XS✔ ◾ Adds appointment template to Roadmap Rodeo
  rules/communicate-your-product-status/rule.md
Labels: Age: 🥚 - New

#9268 XS✔ ◾ ♻️ Do you generate dependency graph
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  rules/architecture-diagram/rule.md
  rules/do-you-generate-the-dependency-graph/nDepend-dependency-graph.png
  rules/do-you-generate-the-dependency-graph/rule.md
  rules/do-you-generate-the-dependency-graph/sugarlearning-dependency-graph-by-rider.png
  rules/do-you-generate-the-dependency-graph/sugarlearning-dependency-graph-by-visual-studio.png
  rules/do-you-generate-the-dependency-graph/sugarlearning-dependency-graph-by-vs-and-resharper.png
  rules/do-you-generate-the-dependency-graph/vs-installer-with-graph-feature.png
  rules/do-you-generate-the-vs-dependency-graph/TimePRODependence-good.png
  rules/do-you-generate-the-vs-dependency-graph/TimePRODependence.png
  rules/do-you-generate-the-vs-dependency-graph/rule.md
  rules/do-you-know-what-to-do-about-asp-net-core-aka-asp-net-5-default-dependency-injection/rule.md
  rules/do-you-look-at-the-architecture/ArchitectureToolsVS11.png
  rules/do-you-look-at-the-architecture/DependencyDiagramInVS11.png
  rules/do-you-look-at-the-architecture/rule.md
  rules/do-you-look-for-grasp-patterns/rule.md
  rules/look-at-the-architecture-of-javascript-projects/rule.md
  rules/the-best-dependency-injection-container/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9399 XS✔ ◾ Making good image bigger
  rules/video-background/good-background-seth.png
Labels: Age: 🥚 - New

#9400 XS✔ ◾ Converted long list into "heading + paragraph" for better reading
  rules/scrum-master-do-you-schedule-the-3-meetings/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9405 XS✔ ◾ Update rule.md
  rules/manage-security-risks-when-adopting-ai-solutions/rule.md
Labels: Age: 🥚 - New

#9404 XS✔ ◾ New rule - Priority alignment meetings
  categories/company-operations/rules-to-better-bench-management.md
  rules/bench-master/rule.md
  rules/internal-priority-alignment/rule.md
Labels: Age: 🐓 - Old

#9403 XS✔ ◾ Update "dependency graph" rule
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  rules/architecture-diagram/rule.md
  rules/do-you-know-what-to-do-about-asp-net-core-aka-asp-net-5-default-dependency-injection/rule.md
  rules/generate-dependency-graphs/nDepend-dependency-graph.png
  rules/generate-dependency-graphs/rule.md
  rules/generate-dependency-graphs/sugarlearning-dependency-graph-by-rider.png
  rules/generate-dependency-graphs/sugarlearning-dependency-graph-by-visual-studio.png
  rules/generate-dependency-graphs/sugarlearning-dependency-graph-by-vs-and-resharper.png
  rules/generate-dependency-graphs/vs-installer-with-graph-feature.png
  rules/the-best-dependency-injection-container/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9401 XS✔ ◾ Fixed Markdown
  rules/chatgpt-cheat-sheet/rule.md
  rules/design-for-database-change/rule.md
  rules/do-you-know-how-to-send-a-schedule/rule.md
  rules/do-you-know-how-to-upgrade-crm-2015-to-2016/rule.md
  rules/do-you-provide-security-to-your-website-visitors/rule.md
  rules/do-you-use-dynamics-365-app-for-outlook/rule.md
  rules/how-to-provide-best-database-schema-document/rule.md
  rules/let-your-clients-know-they-are-valued/rule.md
  rules/use-sql-views/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9412 XS✔ ◾ Update rules-to-better-video-recording.md
  categories/marketing-and-video/rules-to-better-video-recording.md
Labels: Age: 🥚 - New

#9413 XS✔ ◾ Fix author image
  rules/generate-dependency-graphs/rule.md
Labels: Age: 🐣 - Young

#9411 Create Rule “easy-recording-space/rule”
  rules/easy-recording-space/rule.md
Labels: Age: 🐓 - Old

#9409 XS✔ ◾ work hours - fix list
  rules/calendar-do-you-set-your-work-hours-in-your-calendars/rule.md
Labels: Age: 🐓 - Old

#9407 XS✔ ◾ Improving rule - shortening and clarifying
  rules/website-chatbot/rule.md
Labels: Age: 🐓 - Old

#9414 Update Rule “manage-security-risks-when-adopting-ai-solutions/rule”
  rules/manage-security-risks-when-adopting-ai-solutions/rule.md
Labels: Age: 🐓 - Old

#9410 Update Rule “record-a-quick-and-dirty-done-video/rule”
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🐓 - Old

#9417 XS✔ ◾ Updated Do you know when and how to send a v2 of an email?
  rules/email-send-a-v2/rule.md
  rules/explain-deleted-or-modified-appointments/rule.md
Labels: Age: 🥚 - New

#9415 XS✔ ◾ Fixed images' syntax
  rules/do-you-know-to-delete-workspaces-older-than-6-months-and-warn-on-3/rule.md
  rules/do-you-know-to-get-visual-studio-to-remind-you-to-check-in/rule.md
  rules/do-you-know-to-make-using-check-in-policies-easier-by-adding-a-recent-query/rule.md
  rules/do-you-know-to-never-give-sql-server-all-your-ram/rule.md
  rules/do-you-know-windows-forms-should-have-a-minimum-size-to-avoid-unexpected-ui-behavior/rule.md
  rules/do-you-use-access-request-on-your-sharepoint-site/rule.md
Labels: Age: 🐤 - Mature

#9416 XS✔ ◾ Fixed Capitalization + moved related to the right place
  rules/do-you-use-a-dependency-injection-centric-architecture/rule.md
Labels: Age: 🐥 - Adolescent

#9421 XS✔ ◾ Turned video with old standard to be a link in the note
  rules/email-send-a-v2/rule.md
Labels: Age: 🥚 - New

#9426 XS✔ ◾ Fixed bug - good example of note was in the same line
  rules/format-new-lines/rule.md
Labels: Age: 🥚 - New

#9425 XS✔ ◾ added missing class for images
  rules/rule/rule.md
Labels: Age: 🥚 - New

#9427 XS✔ ◾ Added WebM as an option on image formats
  rules/image-formats/rule.md
Labels: Age: 🐣 - Young

#9429 XS✔ ◾ Improved content + readability "set-language-on-code-blocks"
  rules/set-language-on-code-blocks/rule.md
Labels: Age: 🥚 - New

#9430 XS✔ ◾ Improved rule overall "display-code"
  rules/best-way-to-display-code-on-your-website/rule.md
Labels: Age: 🥚 - New

#9431 XS✔ ◾ Improved title and examples "close-quotations"
  rules/close-quotations-of-html-attributes/rule.md
Labels: Age: 🥚 - New

#9428 XS✔ ◾ Added link to rule
  rules/do-you-have-essential-fields-for-your-timesheets/rule.md
Labels: Age: 🥚 - New

#9433 XS✔ ◾ Merge debt - add video
  rules/merge-debt/rule.md
Labels: Age: 🥚 - New

#9435 XS✔ ◾ Merge debt - improve rules
  rules/merge-debt/rule.md
  rules/over-the-shoulder/over-the-shoulder-old-PR.png
  rules/over-the-shoulder/over-the-shoulder-pr.png
  rules/over-the-shoulder/rule.md
  rules/over-the-shoulder/screenshot-2023-06-12-at-07.41.59.png
Labels: Age: 🥚 - New

#9437 XS✔ ◾ adding good example image
  rules/video-background/good-office-background.png
  rules/video-background/rule.md
Labels: Age: 🥚 - New

#9434 New Rule - Do you monitor Uber for Business expenses?
  categories/company-operations/rules-to-better-travel.md
  rules/do-you-make-business-travel-easier/rule.md
  rules/monitor-uber-expenses/rule.md
Labels: Age: 🐤 - Mature

#9438 XS✔ ◾ Improved office background rule
  rules/send-done-videos/rule.md
  rules/take-care-of-your-personal-presentation-for-remote-meetings/rule.md
  rules/video-background/rule.md
Labels: Age: 🐥 - Adolescent

#9432 XS✔ ◾ Updated link + improved list readability "/best-tips-for-getting-started-on-tiktok"
  rules/best-tips-for-getting-started-on-tiktok/rule.md
Labels: Age: 🐓 - Old

#9439 XS✔ ◾ Updated Retro meeting links
  rules/methodology-daily-scrums/rule.md
  rules/what-happens-at-a-sprint-review-meeting/rule.md
  rules/what-happens-at-retro-meetings/rule.md
Labels: Age: 🐥 - Adolescent

#9444 XS✔ ◾ Update rule.md
  rules/easy-recording-space/rule.md
Labels: Age: 🥚 - New

#9443 XS✔ ◾ Update list of options for GitHub Issue Template
  rules/github-issue-templates/list-of-options.png
Labels: Age: 🐤 - Mature

#9442 XS✔ ◾ Improved rule reading "merge-debt"
  rules/merge-debt/rule.md
Labels: Age: 🐓 - Old

#9448 XS✔ ◾ Improved TOFU rule
  rules/tofu/rule.md
Labels: Age: 🐥 - Adolescent

#9449 XS✔ ◾ Updated "ai-pair-programming" rule
  rules/ai-pair-programming/rule.md
Labels: Age: 🐥 - Adolescent

#9450 XS✔ ◾ Improvements to "Work in pairs" rule
  rules/work-in-pairs/rule.md
Labels: Age: 🐣 - Young

#9418 🎥 Record a quick and dirty done video - end video with eye contact
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9451 Update Rule “chatgpt-security-risks/rule”
  rules/chatgpt-security-risks/rule.md
Labels: Age: 🥚 - New

#9462 XS✔ ◾ Updated image in architecture decision tree
  rules/software-architecture-decision-tree/architecture-decision-tree-v2.jpg
  rules/software-architecture-decision-tree/architecture-decision-tree-v3.jpg
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#9465 XS✔ ◾ ✏️ Fixed wrong section names and images
  rules/stretch-when-working-on-desk/rule.md
Labels: Age: 🥚 - New

#9466 XS✔ ◾ Update rule- adding images.md
  rules/easy-recording-space/rule.md
Labels: Age: 🥚 - New

#9464 Update Rule “what-unit-tests-to-write-and-how-many/rule”
  rules/what-unit-tests-to-write-and-how-many/rule.md
Labels: Age: 🐓 - Old

#9460 Update Rule “chatgpt-cheat-sheet/rule”
  rules/chatgpt-cheat-sheet/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9463 Create Rule “maximize-superannuation-benefits/rule”
  categories/company-operations/rules-to-better-accounting.md
  rules/maximize-superannuation-benefits/ato-comparison-tool.jpg
  rules/maximize-superannuation-benefits/coumpound-interest-1.jpg
  rules/maximize-superannuation-benefits/coumpound-interest-2.jpg
  rules/maximize-superannuation-benefits/coumpound-interest-3.jpg
  rules/maximize-superannuation-benefits/rule.md
Labels: Age: 🐓 - Old

#9467 XS✔ ◾ Update rule.md
  rules/easy-recording-space/rule.md
Labels: Age: 🥚 - New

#9468 Update rule.md
  rules/maximize-superannuation-benefits/rule.md
Labels: Age: 🥚 - New

#9472 XS✔ ◾ ♻️ Fixed typo error
  rules/generate-dependency-graphs/rule.md
Labels: Age: 🐥 - Adolescent

#9474 XS✔ ◾ ✏️ Updated rule URI and sections order
  rules/stretch-at-work/bad-example-bad-posture.png
  rules/stretch-at-work/good-example-stretch-back.png
  rules/stretch-at-work/good-example-stretch-chest.png
  rules/stretch-at-work/good-example-stretch-hip-flexors.png
  rules/stretch-at-work/rule.md
Labels: Age: 🥚 - New

#9479 XS✔ ◾ stretch - add it to a category
  categories/company-operations/rules-to-better-health-and-exercise-in-the-workplace.md
Labels: Age: 🥚 - New

#9473 Update Rule “sprint-forecast/rule”
  rules/sprint-forecast/rule.md
Labels: Age: 🐓 - Old

#9481 XS✔ ◾ Updates to CTF rule on stretch
  rules/stretch-at-work/rule.md
Labels: Age: 🥚 - New

#9482 XS✔ ◾ Moved Benefits up
  rules/stretch-at-work/rule.md
Labels: Age: 🥚 - New

#9478 add new rule best Framework Rule
  categories/software-engineering/rules-to-better-websites-development.md
  rules/do-you-know-the-best-framework-to-build-an-admin-interface/rule.md
Labels: Age: 🐤 - Mature

#9483 XS✔ ◾ Product Owners - Simplified description of how to be good PO
  rules/do-you-know-the-how-to-be-a-good-product-owner/rule.md
Labels: Age: 🥚 - New

#9484 XS✔ ◾ Stories - Replace with PBIs in Sprint Review rule
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#9489 Create Rule “maximize-superannuation-benefits/rule”
  rules/maximize-superannuation-benefits/rule.md
Labels: Age: 🐣 - Young

#9491 XS✔ ◾ Product Owner - Co-locates decision-making authority and prioritization
  rules/do-you-know-the-how-to-be-a-good-product-owner/rule.md
Labels: Age: 🥚 - New

#9485 XS✔ ◾ Multi tenancy solution
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  rules/multi-tenancy-models/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9493 XS✔ ◾ Do you know how to indicate mandatory vs suggested PR changes?
  categories/software-engineering/rules-to-better-pull-requests.md
  rules/mandatory-vs-suggested-pr-changes/rule.md
Labels: Age: 🥚 - New

#9490 XS✔ ◾ Improvements to Bahjat's rule "easy-recording-space/"
  rules/easy-recording-space/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9492 XS✔ ◾ Added 'Do you use Directory.Build.Props to simplify multi-project bui…
  categories/software-engineering/rules-to-better-net-projects.md
  rules/directory-build-props/rule.md
Labels: Age: 🐓 - Old

#9487 XS✔ ◾ added devx in microservices rule
  categories/software-engineering/rules-to-better-microservices.md
  rules/prioritize-devx-in-microservices/rule.md
Labels: Age: 🥚 - New, Age: 🦖 - Extinct, 🔥 Merge Debt

#9486 XS✔ ◾ added microservice boundary rule
  categories/software-engineering/rules-to-better-microservices.md
  rules/review-microservice-boundaries/bad-example-microservice-map.png
  rules/review-microservice-boundaries/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9494 XS✔ ◾ Refreshing rule and adding image
  rules/good-email-subject/rule.md
Labels: Age: 🍗 - Ancient

#9488 XS✔ ◾ ✨ New Rule - Do you know the key principles of API Design?
  categories/software-engineering/rules-to-better-web-api-rest.md
  rules/key-principles-of-rest-api-design/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9495 XS✔ ◾ Improved content and added examples "concise-writing"
  rules/concise-writing/rule.md
Labels: Age: 🐓 - Old

#9500 XS✔ ◾ Changing image figure
  rules/good-email-subject/rule.md
Labels: Age: 🥚 - New

#9503 XS✔ ◾ Update rule.md
  categories/design/rules-to-better-figma.md
  rules/use-figma-dev-mode/rule.md
Labels: Age: 🥚 - New

#9501 XS✔ ◾ Improving readability, cleaning up, and shortening URI
  categories/software-engineering/rules-to-better-web-api-rest.md
  rules/key-principles-of-rest-api-design/rule.md
  rules/rest-api-design/rule.md
Labels: Age: 🐣 - Young

#9506 XS✔ ◾ 🐛 Fixed broken greybox
  rules/rest-api-design/rule.md
Labels: Age: 🥚 - New

#9505 XS✔ ◾ Update rule.md
  rules/use-figma-dev-mode/figma-dev-mode.png
  rules/use-figma-dev-mode/rule.md
Labels: Age: 🥚 - New

#9510 XS✔ ◾ Rename use-figma-dev-mode folder to figma-dev-mode
  rules/figma-dev-mode/figma-dev-mode.png
  rules/figma-dev-mode/figma-preview.png
  rules/figma-dev-mode/rule.md
Labels: Age: 🥚 - New

#9504 Create Rule “css-changes/rule”
  categories/design/rules-to-better-websites-layout-and-formatting.md
  rules/css-changes/rule.md
  rules/css-changes/working-with-css.gif
Labels: Age: 🐤 - Mature

#9509 Create Rule “brand-more-than-logo/rule”
  categories/marketing-and-video/rules-to-better-branding.md
  rules/branding-is-more-than-logo/rule.md
Labels: Age: 🐓 - Old

#9507 XS✔ ◾ improving heading sizes
  rules/rest-api-design/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9513 XS✔ ◾ ✏️ Changed POST to GET
  rules/rest-api-design/rule.md
Labels: Age: 🥚 - New
