Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-09, with the labels that each got.

#10692 Update Rule “the-best-boardroom-av-solution/rule”
  rules/the-best-boardroom-av-solution/rally-bar-tap-ip-gallery-1.png
  rules/the-best-boardroom-av-solution/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10693 Update Rule “use-microsoft-teams-room/rule”
  rules/use-microsoft-teams-room/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10699 XS ◾ Update rule.md
  rules/import-your-google-campaigns-to-your-microsoft-ads/rule.md
Labels: Age: 🥚 - New

#10679 S ◾ Add Camtasia video tutorial to Done video rules
  rules/done-video/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10704 Cms/louisroa8189/ssw.rules.content/rule/use ai to edit images/rule
  categories/artificial-intelligence/rules-to-better-ai-generated-media.md
  rules/use-ai-to-edit-images/generated-image-september-04-2025-12_19pm.jpeg
  rules/use-ai-to-edit-images/gz1gbfmaoaavuob.jpg
  rules/use-ai-to-edit-images/gz4kb-fbaaayj5n.jpg
  rules/use-ai-to-edit-images/gzsnxlyxcaasy2_.jpg
  rules/use-ai-to-edit-images/gzsnzhtwoaapceg.jpg
  rules/use-ai-to-edit-images/gzwtouzbyaamxak.jpg
  rules/use-ai-to-edit-images/gzyyduowiaa8x0l.jpg
  rules/use-ai-to-edit-images/midjourney-progression.webp
  rules/use-ai-to-edit-images/rule.md
  rules/use-ai-to-edit-images/xen-create-image-blog-fail-1.webp
Labels: Age: 🥚 - New

#10705 S ◾ generate api clients rule - added Orval
  rules/generate-api-clients/rule.md
Labels: Age: 🥚 - New

#10709 XS ◾ Update rule.md
  rules/use-ai-to-edit-images/rule.md
Labels: Age: 🥚 - New

#10714 XS ◾ Update rule.md
  rules/use-ai-to-edit-images/rule.md
Labels: Age: 🥚 - New

#10706 XS ◾ Add related rule for using figures in estimates
  rules/do-you-manage-clients-expectations/rule.md
Labels: Age: 🐥 - Adolescent

#10715 M ◾ Revise AI editing guidelines for clarity and formatting
  rules/use-ai-to-edit-images/rule.md
Labels: Age: 🐣 - Young

#10718 Create Rule “avoid-unclear-terms/rule”
  categories/communication/rules-to-better-technical-documentation.md
  rules/avoid-common-mistakes/rule.md
  rules/avoid-unclear-terms/rule.md
  rules/spelling-do-you-use-us-english/rule.md
Labels: Age: 🐥 - Adolescent

#10719 XS - Update rule.md
  rules/use-correct-time-format/rule.md
Labels: Age: 🐤 - Mature

#10723 Create rule for leaving explanatory notes for non-standard code
  categories/software-engineering/rules-to-better-code-commenting.md
  rules/code-commenting/rule.md
  rules/leave-explanatory-notes-for-non-standard-code/rule.md
Labels: Age: 🐤 - Mature

#10724 XS ◾ fixed some formatting for Do you leave explanatory notes for non-standard code?
  rules/leave-explanatory-notes-for-non-standard-code/rule.md
Labels: Age: 🥚 - New

#10725 Update note format for non-standard code explanations
  rules/leave-explanatory-notes-for-non-standard-code/rule.md
Labels: Age: 🥚 - New

#10753 XS ◾ updated "the-best-way-to-find-recent-files/rule.md" to update Delve, …
  rules/the-best-way-to-find-recent-files/copilot-recent-files.png
  rules/the-best-way-to-find-recent-files/rule.md
Labels: Age: 🥚 - New

#10755 XS ◾ Add links to the backlog refinement using AI rule
  rules/backlog-refinement-meeting/rule.md
  rules/use-ai-manage-backlog/rule.md
  rules/use-mcp-to-standardize-llm-connections/rule.md
Labels: Age: 🥚 - New

#10729 Create Rule “avoid-short-ambiguous-dates/rule”
  categories/communication/rules-to-better-technical-documentation.md
  rules/avoid-short-ambiguous-dates/rule.md
  rules/dates-do-you-keep-date-formats-consistent-across-your-application/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10756 M ◾ Update AI manage backlog with feedback from Adam
  rules/use-ai-manage-backlog/Dependencies-GitHub.png
  rules/use-ai-manage-backlog/Estimate-GitHub.png
  rules/use-ai-manage-backlog/Grouping-GitHub.png
  rules/use-ai-manage-backlog/Large-Items-GitHub.png
  rules/use-ai-manage-backlog/Prioritize-GitHub.png
  rules/use-ai-manage-backlog/rule.md
Labels: Age: 🐤 - Mature

#10764 XS ◾ Update branding guidelines and resource links
  rules/set-design-guidelines/rule.md
Labels: Age: 🥚 - New

#10763 Update Rule Non Scrum Roles
  categories/client-engagement/rules-to-better-software-consultants-happy-clients.md
  categories/company-operations/rules-to-better-recruiting.md
  rules/avoid-but/rule.md
  rules/know-the-non-scrum-roles/rule.md
Labels: Age: 🐥 - Adolescent

#10771 XS ◾ Update rule.md
  rules/mockups-and-prototypes/rule.md
Labels: Age: 🥚 - New

#10774 XS ◾ Removed the double quote to make consistent with others
  rules/use-passkeys/rule.md
Labels: Age: 🥚 - New

#10775 XS ◾ Update AI backlog management rule with new video
  rules/use-ai-manage-backlog/rule.md
Labels: Age: 🥚 - New

#10778 XS ◾ Add example queries text to each example
  rules/use-ai-manage-backlog/rule.md
Labels: Age: 🥚 - New

#10782 S ◾ Fix Ugly formatting - Do you know the non-Scrum roles of a project?
  rules/know-the-non-scrum-roles/rule.md
Labels: Age: 🥚 - New

#10789 XS ◾ fix uri
  rules/do-you-use-azure-migrate-to-move-to-cloud/rule.md
Labels: Age: 🥚 - New

#10792 XS ◾ Add learning suggestion for Azure
  rules/learn-azure/rule.md
Labels: Age: 🐤 - Mature

#10801 XS ◾ Update rule.md
  rules/do-you-ring-a-bell-or-similar-when-you-secure-a-big-deal-make-a-sale-or-get-some-great-feedback/rule.md
Labels: Age: 🐤 - Mature

#10800 XS ◾ Update rule.md
  rules/spelling-do-you-use-us-english/rule.md
Labels: Age: 🐓 - Old

#10799 Update Rule “sprint-review-retro-email/rule”
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🐓 - Old

#10810 XS ◾ Replace wording for v2 rule
  rules/email-send-a-v2/rule.md
Labels: Age: 🥚 - New

#10815 XS ◾ Fixed the formatting of bullet points
  rules/use-passkeys/rule.md
Labels: Age: 🐣 - Young

#10819 S ◾ 📝 Added webp to rule
  rules/image-formats/rule.md
Labels: Age: 🐣 - Young

#10830 M ◾ Updating the rule, fixing the build
  rules/why-working-website-break-for-global-users/rule.md
Labels: Age: 🥚 - New

#10821 Create Rule “heading-to-anchor-targets/rule-1”
  categories/design/rules-to-better-websites-navigation.md
  categories/software-engineering/rules-to-better-websites-development.md
  rules/efficient-anchor-names/rule.md
  rules/heading-to-anchor-targets/heading-anchor-link-good-example.png
  rules/heading-to-anchor-targets/rule-1.md
Labels: Age: 🐓 - Old

#10823 Create Rule “presenter-icon/rule”
  categories/communication/rules-to-better-powerpoint-presentations.md
  rules/craft-and-deliver-engaging-presentations/rule.md
  rules/demo-slides/rule.md
  rules/do-you-use-standard-question-mark-when-you-are-going-to-ask-the-audience-something/rule.md
  rules/presenter-icon/presenter-icon-bad.png
  rules/presenter-icon/presenter-icon-good.png
  rules/presenter-icon/rule.md
Labels: Age: 🍗 - Ancient

#10837 XS ◾ Fixing broken link and Youtube video Figure
  rules/add-multilingual-support-on-angular/rule.md
  rules/why-your-website-might-break-for-global-users/rule.md
Labels: Age: 🥚 - New

#10838 S ◾ I18n hugo jeoffrey feedback
  rules/add-multilingual-support-on-angular/rule.md
  rules/why-your-website-might-break-for-global-users/rule.md
Labels: Age: 🥚 - New

#10842 XS ◾ Added "do-you-do-cold-emailing-right" to rules-to-better-sales.md
  categories/client-engagement/rules-to-better-sales.md
Labels: Age: 🥚 - New
