Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-06, with the labels that each got.

#10272 XS ◾ Removed broken link "be-available-for-emergency-communication"
  rules/be-available-for-emergency-communication/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10268 M ◾ MoMo - Add module overview rule
  categories/software-engineering/rules-to-better-modular-monoliths.md
  rules/module-overview-document/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10275 XS ◾ Moved duplicated info on not using h1 to be together
  rules/rule/rule.md
Labels: Age: 🥚 - New

#10278 XS ◾ Add preparation guidelines for Sprint Meeting recordings (#10276)
  rules/summary-recording-sprint-reviews/rule.md
Labels: Age: 🐥 - Adolescent

#10281 XS ◾ fixing image bug
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🥚 - New

#10282 XS ◾ Update rule.md "test-please-for-video" and "conduct-a-test-please"
  rules/conduct-a-test-please/rule.md
  rules/test-please-for-video/rule.md
Labels: Age: 🥚 - New

#10280 XS ◾ Update rule.md "request-test-please"
  rules/request-a-test-please/rule.md
Labels: Age: 🥚 - New

#10271 XS ◾ fixed broken links and improved headings "do-you-know-when-to-branch/"
  rules/do-you-know-when-to-branch/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10283 XS ◾ Update "/acceptance-criteria/"
  rules/acceptance-criteria/rule.md
Labels: Age: 🐥 - Adolescent

#10287 Create Rule “trim-input-whitespace/rule”
  rules/trim-input-whitespace/bad-example-trailing-white-space-validation-failed.jpeg
  rules/trim-input-whitespace/rule.md
Labels: Age: 🐓 - Old

#10289 XS ◾ Add `trim-input-whitespace` rule to this category
  categories/design/rules-to-better-interfaces-forms.md
Labels: Age: 🥚 - New

#10290 XS ◾ Add `trim-input-whitespace` rule to this category
  categories/design/rules-to-better-websites-layout-and-formatting.md
Labels: Age: 🥚 - New

#10292 XS ◾ Update and rename uri
  rules/strongly-typed-ids/rule.md
Labels: Age: 🥚 - New

#10293 XS ◾ Update category name rules-to-better-clean-architecture.md
  categories/software-engineering/rules-to-better-clean-architecture.md
Labels: Age: 🥚 - New

#10296 XS ◾ Improvced "software-architecture-decision-tree" rule readability
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🥚 - New

#10301 XS ◾ fix spelling error and wording
  rules/monthly-stakeholder-video/rule.md
Labels: Age: 🥚 - New

#10300 XS ◾ Fixed "Just Enough Refactoring" rule
  rules/just-enough-refactoring/rule.md
Labels: Age: 🥚 - New

#10307 XS ◾ update rule for formatting
  rules/follow-up-lost-opportunities/rule.md
Labels: Age: 🥚 - New

#10303 XS ◾ Update "weekdays-on-date-selectors"
  rules/weekdays-on-date-selectors/rule.md
Labels: rubber stamp, Age: 🦖 - Extinct, 🔥 Merge Debt

#10310 S ◾ change uri for momo rule
  categories/software-engineering/rules-to-better-modular-monoliths.md
  rules/modular-monolith-architecture/rule.md
Labels: Age: 🥚 - New

#10315 Recommending Biome over Eslint
  rules/do-you-use-the-code-health-extensions-in-vs-code/biome-csslint.png
  rules/do-you-use-the-code-health-extensions-in-vs-code/rule.md
Labels: Age: 🥚 - New

#10312 XS ◾ Update rule.md
  rules/enable-presentation-mode-in-visual-studio/rule.md
Labels: Age: 🐤 - Mature

#10319 XS ◾ test fix path to match uri
  rules/vertical-slice-architecture/rule.md
Labels: Age: 🥚 - New

#10321 XS ◾ Update rule.md
  rules/ai-assisted-development-workflow/rule.md
Labels: Age: 🥚 - New

#10320 Update Rule “record-a-quick-and-dirty-done-video/rule”
  rules/record-a-quick-and-dirty-done-video/bad_example_email.png
  rules/record-a-quick-and-dirty-done-video/good_example_email.png
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🐤 - Mature

#10323 XS ◾ AI development - add image and video
  rules/ai-assisted-development-workflow/goofy-ai-car.jpg
  rules/ai-assisted-development-workflow/rule.md
Labels: Age: 🥚 - New

#10325 XS ◾ Update rule.md
  rules/ai-assisted-development-workflow/rule.md
Labels: Age: 🥚 - New

#10331 XS ◾ updated "ai-assisted-development-workflow/rule.md"
  rules/agentic-ai/rule.md
  rules/ai-assisted-development-workflow/rule.md
Labels: Age: 🐥 - Adolescent

#10336 XS ◾ New Action - notify n8n of new rules #10335
  .github/workflows/rule-notify.yml
Labels: Age: 🐣 - Young

#10337 XS ◾ Actions - fixing rule-notify
  .github/workflows/rule-notify.yml
Labels: Age: 🥚 - New

#10338 XS ◾ FFS why is it so hard to make a simple edit on this sodding system! lol
  rules/get-chatgpt-to-answer-step-by-step/rule.md
Labels: Age: 🥚 - New

#10340 XS ◾ Update rules-to-better-social-media-for-business.md
  categories/marketing-and-video/rules-to-better-social-media-for-business.md
Labels: Age: 🥚 - New

#10346 XS ◾ Update "/where-to-upload-work-related-videos" rule
  rules/where-to-upload-work-related-videos/rule.md
Labels: Age: 🥚 - New

#10342 XS ◾ Updated "request-a-test-please"
  rules/request-a-test-please/rule.md
Labels: Age: 🐓 - Old

#10351 XS ◾ Update "underlined-links/rule.md" title
  rules/underlined-links/rule.md
Labels: Age: 🥚 - New

#10343 Create Rule “meaningful-chat-reactions/rule”
  categories/communication/rules-to-better-im.md
  rules/easy-questions/rule.md
  rules/meaningful-chat-reactions/rule.md
Labels: Age: 🐓 - Old

#10352 XS ◾ Archived duplicated old rule "intuitive-links"
  rules/do-you-make-your-links-intuitive/rule.md
Labels: Age: 🥚 - New

#10348 📝New Rule - Do you automate code reviews on GitHub?
  categories/artificial-intelligence/rules-to-better-ai.md
  categories/project-delivery/rules-to-better-devops.md
  rules/automatic-code-reviews-github/auto-code-review-tina.png
  rules/automatic-code-reviews-github/coderabbit.webp
  rules/automatic-code-reviews-github/cursor-bugbot-example.png
  rules/automatic-code-reviews-github/rule.md
  rules/automatic-code-reviews-github/yakshaver-code-review.png
Labels: Age: 🐓 - Old

#10354 XS ◾ Update "process-approvals-in-a-timely-manner" rule.md
  rules/process-approvals-in-a-timely-manner/rule.md
Labels: Age: 🥚 - New

#10355 XS ◾ Update cross-approvals/rule.md
  rules/cross-approvals/rule.md
Labels: Age: 🥚 - New

#10358 XS ◾ Update "easy-to-view-screen-recordings"
  rules/easy-to-view-screen-recordings/rule.md
Labels: Age: 🥚 - New

#10359 XS ◾ README - Fixed rule masters text
  README.md
Labels: Age: 🥚 - New

#10363 XS ◾ Clara fang ssw patch 2
  rules/create-appointment-for-flights/creating two appointments for connecting flights.png
  rules/create-appointment-for-flights/creating-two-appointments-for-connecting-flights.png
  rules/create-appointment-for-flights/only one appointment for connecting flights.png
  rules/create-appointment-for-flights/only-one-appointment-for-connecting-flights.png
  rules/create-appointment-for-flights/rule.md
Labels: Age: 🥚 - New

#10364 XS ◾ Adding more info about Ocoya
  rules/post-using-social-media-management-tools/rule.md
Labels: Age: 🥚 - New

#10361 Update Rule “ai-assisted-development-workflow/rule”
  rules/ai-assisted-development-workflow/rule.md
Labels: Age: 🐣 - Young

#10368 XS ◾ Update rule.md
  rules/do-you-use-the-best-code-analysis-tools/rule.md
Labels: Age: 🥚 - New

#10373 XS ◾ Added alternatives section for ai code reviewers
  rules/automatic-code-reviews-github/rule.md
Labels: Age: 🐥 - Adolescent

#10378 S ◾ Update automatic-code-reviews-github/rule.md
  rules/automatic-code-reviews-github/rule.md
Labels: Age: 🥚 - New

#10377 XS ◾ Update design-debt/rule.md
  rules/design-debt/rule.md
Labels: rubber stamp, Age: 🐣 - Young

#10382 XS ◾ Update "underlined-links/rule.md"
  rules/underlined-links/rule.md
Labels: Age: 🥚 - New

#10388 Update Rule “do-you-offer-specific-criticism/rule”
  rules/do-you-offer-specific-criticism/rule.md
Labels: Age: 🐤 - Mature

#10383 Do you automate code reviews on GitHub? - 🧠CTF Feedback
  rules/automatic-code-reviews-github/github-copilot-review-low-confidence.png
  rules/automatic-code-reviews-github/github-suggested-pr-description.png
  rules/automatic-code-reviews-github/rule.md
  rules/automatic-code-reviews-github/tina-starter-reveiew-code-review.png
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10389 L ◾ Created new rule on bread daily scrum
  categories/project-delivery/rules-to-better-scrum.md
  rules/bread-daily-scrums/bread-daily-scrums.png
  rules/bread-daily-scrums/rule.md
Labels: Age: 🥚 - New

#10398 XS ◾ Update rule.md
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10392 S ◾ 📝 Added steps to zz video on YouTube
  rules/zz-files/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10390 Create Rule “hamburger-menu/rule”
  rules/hamburger-menu/hamburger-menu-bad-example.png
  rules/hamburger-menu/hamburger-menu-good-example.png
  rules/hamburger-menu/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10399 XS ◾ Update meaningful-chat-reactions/rule.md
  rules/meaningful-chat-reactions/rule.md
Labels: Age: 🥚 - New

#10402 XS ◾ Adding new rule to categories /use-hamburger-menu-wisely
  categories/design/rules-to-better-interfaces-mobile.md
  categories/design/rules-to-better-websites-navigation.md
  rules/hamburger-menu/rule.md
Labels: Age: 🥚 - New

#10409 L ◾ Update and rename /do-you-know-these-important-git-commands/rule.md
  rules/important-git-commands/rule.md
Labels: Age: 🐣 - Young

#10400 XS ◾ Adding Space and changing title
  rules/summary-recording-sprint-reviews/rule.md
Labels: Age: 🐓 - Old

#10421 XS ◾ Update /do-you-calculate-payroll-tax-correctly/rule.md
  rules/do-you-calculate-payroll-tax-correctly/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#10422 XS ◾ Update /encourage-daily-exercise/rule.md
  rules/encourage-daily-exercise/rule.md
Labels: codeauditor fix, Age: 🍗 - Ancient, 🔥 Merge Debt

#10411 XS ◾ Relating stakeholder and sprint review recording rules
  rules/monthly-stakeholder-video/rule.md
  rules/summary-recording-sprint-reviews/rule.md
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10429 XS ◾ Add file extension to rules-to-better-tinacms
  categories/software-engineering/rules-to-better-tinacms.md
Labels: Age: 🥚 - New

#10426 XS ◾ Update image so CRM link is not shared on public internet.
  rules/integrate-dynamics-365-and-microsoft-teams/bad-url.png
Labels: Age: 🐤 - Mature

#10420 XS ◾ Removed broken link and content
  rules/best-ide-for-vue/rule.md
Labels: codeauditor fix, Age: 🦖 - Extinct, 🔥 Merge Debt
