Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-10, with the labels that each got.

#10841 XS ◾ Clean up Do you turn your headings into anchor links? by removing info block
  rules/heading-to-anchor-targets/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10854 L ◾ Update rule.md
  rules/i18n-with-ai/RTL_mobile.jpg
  rules/i18n-with-ai/first_language_vs_web.png
  rules/i18n-with-ai/rule.md
  rules/i18n-with-ai/web_content_languages_2025.png
Labels: Age: 🥚 - New

#10857 M ◾ Add rule about no uat phase in Scrum
  categories/project-delivery/rules-to-better-scrum.md
  rules/no-uat-phase-in-scrum/dev-uat.png
  rules/no-uat-phase-in-scrum/rule.md
Labels: Age: 🥚 - New

#10855 XS ◾ Update rule.md
  rules/i18n-with-ai/rule.md
  rules/i18n-with-ai/web_content_languages_2025.png
Labels: Age: 🐤 - Mature

#10859 XS ◾ update no-uat-phase rule
  rules/no-uat-phase-in-scrum/cooperative-devs.png
  rules/no-uat-phase-in-scrum/rule.md
Labels: Age: 🥚 - New

#10868 XS ◾ Fix code formatting in Bicep module examples
  rules/bicep-use-module-templates/rule.md
Labels: Age: 🥚 - New

#10873 M ◾ Joeffrey's feedback - v1
  rules/i18n-with-ai/rule.md
Labels: Age: 🥚 - New

#10874 Update rule.md
  rules/i18n-with-ai/rule.md
Labels: Age: 🥚 - New

#10875 S ◾ Update rule.md
  rules/i18n-with-ai/rule.md
Labels: Age: 🥚 - New

#10879 L ◾ Create Rule “destructive-button-ui-ux/rule”
  categories/design/rules-to-better-interfaces-general-usability-practices.md
  rules/destructive-button-ui-ux/destruction-button-bad-color.png
  rules/destructive-button-ui-ux/destruction-button-bad-icon.png
  rules/destructive-button-ui-ux/destruction-button-bad-positioning.png
  rules/destructive-button-ui-ux/destruction-button-good-confirmation.png
  rules/destructive-button-ui-ux/destruction-button-good-positioning.png
  rules/destructive-button-ui-ux/destruction-button-good-tooltip.png
  rules/destructive-button-ui-ux/rule.md
Labels: Age: 🥚 - New

#10887 XS ◾ Update rule.md
  rules/choosing-authentication/rule.md
Labels: Age: 🥚 - New

#10888 S ◾ Update rule.md
  rules/i18n-with-ai/rule.md
Labels: Age: 🥚 - New

#10882 Create Rule “supervise-tradespeople/rule”
  rules/supervise-tradespeople/rule.md
  rules/supervise-tradespeople/screenshot-2025-10-07-095917.png
  rules/supervise-tradespeople/screenshot-2025-10-08-094611.png
Labels: Age: 🐓 - Old

#10881 Create Rule “report-defects-to-property-manager/rule”
  categories/company-operations/rules-to-better-office-operations.md
  rules/report-defects-to-property-manager/rule.md
  rules/report-defects-to-property-manager/screenshot-2025-10-07-125246.png
Labels: Age: 🐓 - Old

#10895 XS ◾ Improve table formatting for best practices
  rules/destructive-button-ui-ux/rule.md
Labels: Age: 🥚 - New

#10893 S ◾ Refine SEO description and supervision guidelines
  rules/supervise-tradespeople/rule.md
Labels: Age: 🐤 - Mature
