Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-05, with the labels that each got.

#10175 XS ◾ Update rule.md "Sprint Review email"
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#10166 Create rule - inform-clients-when-developer-leaves
  categories/client-engagement/rules-to-better-account-management.md
  rules/inform-clients-when-developer-leaves/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10180 XS ◾ MCP Server - point to AI consulting page
  rules/mcp-server/rule.md
  rules/use-mcp-to-standardize-llm-connections/rule.md
Labels: Age: 🥚 - New

#10182 S ◾ added demo screenshots section to demo slides rule
  categories/communication/rules-to-better-powerpoint-presentations.md
  rules/demo-slides/DemoBad.gif
  rules/demo-slides/demo.gif
  rules/demo-slides/demobad.jpg
  rules/demo-slides/demogood.jpg
  rules/demo-slides/rule.md
  rules/do-you-know-the-right-way-to-do-a-demo-slide/demobad.jpg
  rules/do-you-know-the-right-way-to-do-a-demo-slide/demogood.jpg
  rules/do-you-know-the-right-way-to-do-a-demo-slide/rule.md
Labels: Age: 🐣 - Young

#10160 Update Rule “avoid-using-any/rule”
  rules/avoid-using-any/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10181 Update Rule “secure-your-wireless-connection/rule”
  rules/easy-wifi-access/rule.md
  rules/secure-your-wireless-connection/ios-wpa3-ent.png
  rules/secure-your-wireless-connection/rule.md
  rules/secure-your-wireless-connection/unifi-radius.png
  rules/secure-your-wireless-connection/wifi-unsecured.jpg
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10183 Update Rule “what-is-chatgpt/rule”
  rules/what-is-chatgpt/rule.md
Labels: Age: 🐤 - Mature

#10184 Create Rule “phone-as-webcam/rule”
  categories/communication/rules-to-better-microsoft-teams.md
  categories/company-operations/rules-to-better-travel.md
  rules/phone-as-webcam/rule.md
  rules/phone-as-webcam/travel-setup.jpeg
Labels: Age: 🥚 - New

#10177 Create Rule “how-to-view-changes-made-to-a-file-in-github/rule”
  categories/software-engineering/rules-to-better-github.md
  rules/view-file-changes-in-github/github-commit-viewer.png
  rules/view-file-changes-in-github/github-diff-view.png
  rules/view-file-changes-in-github/github-file.png
  rules/view-file-changes-in-github/github-history-button.png
  rules/view-file-changes-in-github/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10185 XS ◾ Added section to test please with designers first
  rules/hand-over-mockups-to-developers/rule.md
Labels: Age: 🥚 - New

#10187 S ◾ Update rule.md to add quotes
  rules/distinguish-keywords-from-content/rule.md
  rules/formatting-ui-elements/rule.md
Labels: Age: 🐥 - Adolescent

#10173 M ◾ Updated rules on @mentions, email, and PBI
  rules/3-steps-to-a-pbi/rule.md
  rules/use-email-for-tasks-only/rule.md
  rules/when-you-use-mentions-in-a-pbi/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10131 L ◾ rewrote "quotations highlighting" rule
  rules/indent/rule.md
  rules/style-quotations/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10178 XS ◾ Update MCP rule.md
  rules/use-mcp-to-standardize-llm-connections/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10188 XS ◾ Adding more authors
  rules/agentic-ai/rule.md
Labels: Age: 🐥 - Adolescent

#10189 XS ◾ Improved readability and examples "distinguish-keywords-from-content"
  rules/distinguish-keywords-from-content/rule.md
Labels: Age: 🥚 - New

#10190 XS ◾ Adding a good example
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10192 XS ◾ Update rule.md
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#10193 XS ◾ Update fonts we use
  rules/set-design-guidelines/rule.md
Labels: Age: 🥚 - New

#10198 XS ◾ Fixing broken email template
  rules/inform-clients-when-developer-leaves/rule.md
Labels: Age: 🥚 - New

#10199 S ◾ Updated "agentic-ai" rule
  rules/agentic-ai/rule.md
Labels: Age: 🐤 - Mature

#10201 S ◾ Updated /report-bugs-and-suggestions/rule.md
  rules/report-bugs-and-suggestions/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10203 XS ◾ Updated "descriptive-links/" rule
  rules/descriptive-links/rule.md
Labels: Age: 🥚 - New

#10202 XS ◾ Added link to descriptive URLs to "/format-new-lines"
  rules/format-new-lines/rule.md
Labels: Age: 🥚 - New

#10204 L ◾ Updated "avoid-full-stops-in-bullet-point-lists" rule
  categories/design/rules-to-better-content-design.md
  rules/avoid-full-stops-in-bullet-point-lists/rule.md
  rules/avoid-full-stops/rule.md
Labels: Age: 🥚 - New

#10206 S ◾ updated report-bugs-rule
  rules/report-bugs-and-suggestions/rule.md
Labels: Age: 🥚 - New

#10207 Create rule xml for ai prompts
  categories/artificial-intelligence/rules-to-better-chatgpt-prompt-engineering.md
  rules/ai-prompt-xml/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10211 XS ◾ Update rule.md
  rules/design-system/rule.md
Labels: Age: 🥚 - New

#10210 Create Rule “ui-ux-test-please/rule”
  categories/company-operations/rules-to-successful-projects.md
  rules/conduct-a-test-please/rule.md
  rules/presentation-test-please/rule.md
  rules/test-please-for-video/rule.md
  rules/ui-ux-test-please/rule.md
Labels: Age: 🥚 - New

#10212 XS ◾ Link todo and tech debt rules
  rules/technical-debt/rule.md
  rules/todo-tasks/rule.md
Labels: Age: 🥚 - New

#10213 L ◾ Add rule for using unique DTOs per use case in Clean Architecture
  categories/software-engineering/index.md
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  categories/software-engineering/rules-to-better-clean-architecture.md
  rules/unique-dtos-per-endpoint/rule.md
Labels: Age: 🥚 - New

#10214 XS ◾ Add Daniel Mackay as an author in the unique DTOs rule documentation
  rules/unique-dtos-per-endpoint/rule.md
Labels: Age: 🥚 - New

#10208 Create rule digest microsoft form
  categories/artificial-intelligence/rules-to-better-ai.md
  rules/digest-microsoft-form/bad-unstructured.png
  rules/digest-microsoft-form/good-structured.png
  rules/digest-microsoft-form/good-unstructured.png
  rules/digest-microsoft-form/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10216 XS ◾ Bradystroud patch 17
  rules/brainstorming-day-retro/rule.md
  rules/do-a-retrospective/rule.md
Labels: Age: 🐤 - Mature

#10218 S ◾ Fixed headings and more on "managing-microsoft-entra-id/rule.md"
  rules/managing-microsoft-entra-id/rule.md
Labels: Age: 🥚 - New

#10220 XS ◾ Archived Skype distractions rule
  rules/minimize-skype-distractions/rule.md
Labels: Age: 🥚 - New

#10222 XS ◾ Update turn-emails-into-pbis rule
  rules/turn-emails-into-pbis/rule.md
Labels: Age: 🐥 - Adolescent

#10229 Create Rule “avoid-but/rule”
  categories/communication/rules-to-better-communication.md
  categories/communication/rules-to-better-giving-and-taking-feedback.md
  categories/communication/rules-to-better-technical-documentation.md
  rules/avoid-but/rule.md
  rules/disagreeing-with-powerful-stakeholders/rule.md
  rules/match-tone-with-intent/rule.md
  rules/positive-tone/rule.md
Labels: Age: 🥚 - New

#10230 S ◾ Fixed markdown for "style-quotations" rule
  rules/style-quotations/rule.md
Labels: Age: 🥚 - New

#10219 XS ◾ Archived old Lync rule
  rules/do-you-install-the-ios-versions/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10224 XS ◾ Archived "have-skype-for-business-setup-in-hybrid-to-get-the-full-fun…
  rules/have-skype-for-business-setup-in-hybrid-to-get-the-full-functionality-out-of-teams/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10223 XS ◾ Archived old Lync rule
  rules/do-you-federate-lync-with-skype-and-other-external-im-providers/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10221 M ◾ Removed/Updated Skype references - product retired
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
  rules/communication-do-you-respond-to-queries-quickly/rule.md
  rules/contact-clients-using-im/rule.md
  rules/do-you-turn-off-audio-notifications-on-the-ios-app/rule.md
  rules/go-beyond-just-using-chat/rule.md
  rules/keep-a-history-of-your-im-conversations/rule.md
  rules/know-that-im-interrupts/rule.md
  rules/set-your-display-picture/rule.md
  rules/use-your-company-name-as-part-of-your-display-name/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10231 XS ◾ Fixed typo "do-you-create-friendly-short-urls/rule.md"
  rules/do-you-create-friendly-short-urls/rule.md
Labels: rubber stamp, Age: 🍗 - Ancient, 🔥 Merge Debt

#10237 XS ◾ Deleted category reference which doesn't exist
  categories/marketing-and-video/index.md
Labels: Age: 🥚 - New

#10238 XS ◾ Moved categories to project-delivery folder as they are referenced on that top category only
  categories/project-delivery/rules-to-better-devops-using-azure-devops.md
  categories/project-delivery/rules-to-better-devops-using-github.md
  categories/project-delivery/rules-to-better-devops.md
  categories/project-delivery/rules-to-better-github.md
  categories/project-delivery/rules-to-better-pull-requests.md
Labels: Age: 🥚 - New

#10239 S ◾ Added video to use-ai-responsibly rule
  rules/use-ai-responsibly/rule.md
Labels: Age: 🥚 - New

#10233 XS ◾ Update website-heatmaps rule.md
  rules/website-heatmaps/rule.md
Labels: Age: 🐓 - Old

#10200 Create Rule “use-ai-for-meeting-notes/rule”
  categories/communication/rules-to-better-meetings.md
  rules/still-taking-manual-meeting-notes/67621ffc-meeting-notes_1000000000000000000028.png
  rules/still-taking-manual-meeting-notes/bad_note.png
  rules/use-ai-for-meeting-notes/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10235 Create Rule “measure-website-changes-impact/rule”
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  rules/measure-website-changes-impact/rule.md
  rules/report-seo-results/rule.md
  rules/website-heatmaps/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10242 XS ◾ Standardise "health check"
  rules/have-a-health-check-page-to-make-sure-your-website-is-healthy/rule.md
  rules/infrastructure-health-checks/rule.md
Labels: Age: 🥚 - New

#10240 M ◾ New rule - low code and AI
  categories/artificial-intelligence/rules-to-better-ai-development.md
  rules/low-code-and-ai/rule.md
Labels: Age: 🐣 - Young

#10248 XS ◾ Update infrastructure-health-checks/rule.md
  rules/infrastructure-health-checks/rule.md
Labels: Age: 🥚 - New

#10253 XS ◾ Updates scheduling-do-you-have-a-consistent-naming-convention-for-you…
  rules/scheduling-do-you-have-a-consistent-naming-convention-for-your-bookings/rule.md
Labels: Age: 🐓 - Old

#10252 M ◾ Improved rule content and examples - appointments-do-you-show-all-the…
  rules/appointments-do-you-show-all-the-necessary-information-in-the-subject/rule.md
  rules/create-appointment-for-flights/rule.md
Labels: Age: 🐓 - Old

#10256 XS ◾ fix embedded youtube video
  rules/underpromise-overdeliver/rule.md
Labels: Age: 🥚 - New

#10258 XS ◾ fix title capitalization and video figure
  categories/client-engagement/rules-to-better-software-consultants-happy-clients.md
  rules/underpromise-overdeliver/rule.md
Labels: Age: 🥚 - New

#10261 XS ◾ fix casing of rule
  rules/underpromise-overdeliver/rule.md
Labels: Age: 🥚 - New

#10265 M ◾ Improved "PBI-sizing" rule
  categories/project-delivery/rules-to-better-scrum.md
  rules/size-pbis-effectively/rule.md
Labels: Age: 🥚 - New

#10269 XS ◾ underpromise overdeliver - fix Sprint casing
  rules/underpromise-overdeliver/rule.md
Labels: Age: 🥚 - New
