Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-01, with the labels that each got.

#9730 Create Rule “best-ai-powered-ide/rule”
  rules/best-ai-powered-ide/bad-example-chatgpt.png
  rules/best-ai-powered-ide/cursor-chat-context.png
  rules/best-ai-powered-ide/cursor-command-generation.gif
  rules/best-ai-powered-ide/good-example-using-agent.png
  rules/best-ai-powered-ide/rule.md
Labels: Age: 🐣 - Young

#9732 Update Rule “best-ai-powered-ide/rule”
  categories/artificial-intelligence/rules-to-better-ai-development.md
  rules/best-ai-powered-ide/rule.md
Labels: Age: 🥚 - New

#9736 XS✔ ◾ best AI powered IDE - Add .NET debugger warning
  rules/best-ai-powered-ide/rule.md
Labels: Age: 🥚 - New

#9740 Update Rule “fixed-price-deliver-the-project-and-start-the-warranty-period/rule”
  rules/fixed-price-deliver-the-project-and-start-the-warranty-period/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9739 Update Rule “do-you-know-the-difference-between-fixed-price-and-time-and-materials-work/rule”
  rules/do-you-know-the-difference-between-fixed-price-and-time-and-materials-work/refusing-meal-restaurant.jpg
  rules/do-you-know-the-difference-between-fixed-price-and-time-and-materials-work/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9738 XS✔ ◾ Archiving rule
  rules/do-you-know-how-to-share-links-to-specific-tabs-in-power-bi-reports/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9735 Update Rule “best-ai-powered-ide/rule”
  rules/best-ai-powered-ide/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9737 XS✔ ◾ fixed info box in rule
  rules/github-issue-templates/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9728 XS✔ ◾ Fixed broken links
  rules/how-to-set-up-application-insights/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9743 XS✔ ◾ Update rule.md
  rules/monthly-stakeholder-video/rule.md
Labels: Age: 🥚 - New

#9744 XS✔ ◾ Update rule.md
  rules/monthly-stakeholder-video/rule.md
Labels: Age: 🥚 - New

#9745 XS✔ ◾ CTF Updates – Updating the component library rules
  rules/do-you-use-the-best-web-ui-libraries/bootstrap.png
  rules/do-you-use-the-best-web-ui-libraries/rule.md
  rules/generate-ui-mockups-with-ai/matrix.gif
  rules/generate-ui-mockups-with-ai/rule.md
  rules/generate-ui-mockups-with-ai/v0_user_form.png
Labels: Age: 🐓 - Old

#9748 XS✔ ◾ Update rule.md (best web ui libraries)
  rules/do-you-use-the-best-web-ui-libraries/rule.md
Labels: Age: 🥚 - New

#9750 XS✔ ◾ Update rule.md
  rules/do-you-use-the-best-web-ui-libraries/rule.md
Labels: Age: 🥚 - New

#9752 XS✔ ◾ Update rule.md
  rules/do-you-use-the-best-web-ui-libraries/rule.md
Labels: Age: 🐣 - Young

#9746 Update Rule “do-you-incentivize-a-quick-spec-review-sale/rule”
  rules/do-you-incentivize-a-quick-spec-review-sale/rule.md
Labels: Age: 🐤 - Mature

#9731 Create Rule “branch-naming/rule”
  rules/branch-naming/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9760 XS✔ ◾ Update branching in git rule to link to branch naming rule
  rules/do-you-know-when-to-branch-in-git/rule.md
Labels: Age: 🥚 - New

#9757 Update Rule “do-you-use-twitter-bootstrap/rule”
  rules/do-you-use-bootstrap/bootstrap-1.jpg
  rules/do-you-use-bootstrap/bootstrap-3.jpg
  rules/do-you-use-bootstrap/iphonenonresponsive.png
  rules/do-you-use-bootstrap/rule.md
  rules/do-you-use-twitter-bootstrap/rule.md
Labels: Age: 🐣 - Young

#9766 XS✔ ◾ Condensing rule
  rules/website-chatbot/botpress-interface.png
  rules/website-chatbot/rule.md
Labels: Age: 🥚 - New

#9768 XS✔ ◾ refining the rule and adding my learnings
  rules/the-best-practices-for-google-ads/rule.md
Labels: Age: 🥚 - New

#9759 XS✔ ◾ Adding categories to new rule branch-naming
  categories/project-delivery/rules-to-better-branching-and-builds.md
  categories/software-engineering/rules-to-better-github.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9755 XS✔ ◾ Added warning to not try other effects in text hover
  rules/underlined-links/bad-example-bold-hover.gif
  rules/underlined-links/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9771 XS✔ ◾ PR template - improve pair programming bit
  .github/pull_request_template.md
Labels: Age: 🥚 - New

#9769 XS✔ ◾ Improved URl and other things
  categories/software-engineering/rules-to-better-architecture-and-code-review.md
  categories/software-engineering/rules-to-better-javascript-and-jquery.md
  categories/software-engineering/rules-to-better-website-development-asp-net.md
  rules/web-ui-libraries/rule.md
Labels: Age: 🍗 - Ancient

#9772 XS✔ ◾ Updating recommended option
  rules/end-user-documentation/rule.md
Labels: Age: 🥚 - New

#9767 Update Rule “send-delayed-message-in-microsoft-teams/rule”
  rules/send-delayed-message-in-microsoft-teams/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9777 XS✔ ◾ Update rules-to-better-giving-and-taking-feedback.md
  categories/communication/rules-to-better-giving-and-taking-feedback.md
Labels: Age: 🥚 - New

#9775 Create Rule “double-diamond/rule”
  categories/design/rules-to-better-designers.md
  rules/double-diamond/rule.md
  rules/double-diamond/the-double-diamond-design-process.jpg
Labels: Age: 🐤 - Mature

#9778 XS✔ ◾ relating IM rules
  rules/easy-questions/rule.md
  rules/separate-messages/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9774 XS✔ ◾ added breadcrumb mention
  rules/underlined-links/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9782 XS✔ ◾ Linking related rules
  rules/4-quadrants-important-and-urgent/rule.md
  rules/know-that-im-interrupts/rule.md
  rules/work-in-order-of-importance-aka-priorities/rule.md
Labels: Age: 🥚 - New

#9781 XS✔ ◾ Adding recommended tools
  rules/website-heatmaps/rule.md
Labels: Age: 🥚 - New

#9780 XS✔ ◾ SEO rules - Adding prefixes
  rules/add-attributes-to-picture-links/rule.md
  rules/avoid-content-in-javascript/rule.md
  rules/avoid-link-farms/rule.md
  rules/avoid-using-frames-on-your-website/rule.md
  rules/best-ways-to-generate-traffic-to-your-website/rule.md
  rules/core-web-vitals/rule.md
  rules/descriptive-links/rule.md
  rules/do-you-have-a-schema-code-on-your-website/rule.md
  rules/do-you-know-anything-about-brand-power-and-social-signals/rule.md
  rules/do-you-know-that-content-is-king/rule.md
  rules/do-you-provide-a-good-user-experience/rule.md
  rules/do-you-provide-security-to-your-website-visitors/rule.md
  rules/does-your-domain-have-power/rule.md
  rules/give-the-written-text-in-an-image/rule.md
  rules/have-a-google-places-entry/rule.md
  rules/how-google-ranks-pages/rule.md
  rules/how-to-find-inbound-links-to-your-pages/rule.md
  rules/html-meta-tags/rule.md
  rules/include-important-keywords-where-it-matters/rule.md
  rules/keep-files-under-the-google-file-size-limit/rule.md
  rules/lowercase-urls/rule.md
  rules/make-title-h1-and-h2-tags-descriptive/rule.md
  rules/monitor-seo-effectively/rule.md
  rules/page-indexed-by-google/rule.md
  rules/page-rank-is-no-longer-relevant/rule.md
  rules/register-your-domain-for-a-long-time/rule.md
  rules/report-seo-results/rule.md
  rules/responsive-design/rule.md
  rules/seo-canonical-tags/rule.md
  rules/seo-checklist/rule.md
  rules/seo-nofollow/rule.md
  rules/seo-tools/rule.md
  rules/spelling-do-you-use-us-english/rule.md
  rules/use-301-redirect-on-renamed-or-moved-pages/rule.md
  rules/use-dashes-in-urls/rule.md
  rules/use-robots-txt-effectively/rule.md
  rules/use-subdirectories-not-domains/rule.md
  rules/website-heatmaps/rule.md
  rules/website-page-speed/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9784 XS ◾ pr-metrics.yml - treat markdown as code change
  .github/workflows/pr-metrics.yml
  rules/best-ai-tools/rule.md
Labels: Age: 🥚 - New

#9785 XS ◾ Improved readability "professional-integrity-tools" + added m"follow-up-effectively/" to new category
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  rules/professional-integrity-tools/rule.md
Labels: Age: 🥚 - New

#9786 L ◾ Updated "add-days-to-dates/"
  categories/communication/rules-to-better-technical-documentation.md
  rules/add-days-to-dates/rule.md
  rules/do-you-know-how-to-format-dates-to-include-the-weekday/rule.md
  rules/right-format-to-write-videos-time-length/rule.md
Labels: Age: 🥚 - New

#9789 XS ◾ Fixed email template markdown
  rules/add-days-to-dates/rule.md
Labels: Age: 🥚 - New

#9788 XS ◾ Archived deprecated rule
  rules/submit-software-to-download-sites/rule.md
Labels: Age: 🐣 - Young

#9790 XS ◾ Added gravatar rule to Chinafy category
  categories/software-engineering/rules-to-better-internationalization.md
  rules/do-you-use-gravatar-for-your-profile-pictures/rule.md
Labels: Age: 🥚 - New

#9791 M ◾ Rewrote the rule for data-driven pages and SEO
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  rules/make-your-data-driven-pages-easier-to-find/rule.md
  rules/structured-data/rule.md
Labels: Age: 🐥 - Adolescent

#9797 XS ◾ Update rules-to-better-ai-development.md
  categories/artificial-intelligence/rules-to-better-ai-development.md
Labels: Age: 🥚 - New

#9794 S ◾ GitHub issue label when to review
  rules/do-you-know-how-to-use-tags-for-github-issues/label_bad_example.png
  rules/do-you-know-how-to-use-tags-for-github-issues/label_good_example.png
  rules/do-you-know-how-to-use-tags-for-github-issues/rule.md
Labels: Age: 🐥 - Adolescent

#9800 S ◾ Improvements to rule readability
  rules/website-chatbot/rule.md
Labels: Age: 🥚 - New

#9799 XS ◾ Fixed image bug + other improvements
  rules/write-integration-tests-for-llm-prompts/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9809 XS ◾ Improvements to "how-to-hand-over-tasks-to-others/"
  rules/how-to-hand-over-tasks-to-others/rule.md
Labels: Age: 🥚 - New

#9805 XS ◾ Added related links to "replying-in-the-same-medium/"
  rules/replying-in-the-same-medium/rule.md
Labels: Age: 🥚 - New

#9802 XS ◾ Update Double Diamond image
  rules/double-diamond/rule.md
  rules/double-diamond/the-double-diamond-design-process.jpg
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9808 XS ◾ Improved intro and more "important-chats-should-be-in-an-email"
  rules/important-chats-should-be-in-an-email/rule.md
Labels: Age: 🥚 - New

#9810 XS ◾ Reordering SEO rules
  categories/marketing-and-video/rules-to-better-google-rankings-and-seo.md
  rules/structured-data/rule.md
Labels: Age: 🥚 - New

#9803 XS ◾ Improved PPT test please rule
  categories/communication/rules-to-better-powerpoint-presentations.md
  rules/pptx-test-please/rule.md
  rules/presentation-test-please/rule.md
Labels: Age: 🐓 - Old

#9813 XS ◾ Improved line breaks inside email examples
  rules/how-to-hand-over-tasks-to-others/rule.md
Labels: Age: 🐣 - Young

#9807 S ◾ Fixed URL and intro sentence "snipping-im-chats"
  categories/communication/rules-to-better-im.md
  rules/snipping-im-chats/rule.md
  rules/you-make-the-email-readable-by-snipping-and-formatting-the-im-chat/rule.md
Labels: Age: 🐓 - Old

#9804 XS ◾ Improved rule on "test please" readability
  rules/conduct-a-test-please/rule.md
Labels: Age: 🐓 - Old

#9815 XS ◾ Update rules-to-better-gpt.md
  categories/artificial-intelligence/rules-to-better-gpt.md
Labels: Age: 🥚 - New

#9816 M ◾ Updated "pencil in" rule
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
  rules/do-you-always-pencil-in-the-next-date-on-your-last-day-at-the-client/rule.md
  rules/do-you-know-to-make-sure-that-you-book-the-next-appointment-before-you-leave-the-client/rule.md
  rules/pencil-in-the-next-booking/rule.md
Labels: Age: 🐥 - Adolescent

#9818 S ◾ From "quote" to "estimate" + other improvements
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
  rules/call-clients-before-sending-an-estimate/rule.md
  rules/for-existing-clients-do-you-always-call-them-before-sending-a-quote/rule.md
Labels: Age: 🥚 - New

#9817 M ◾ Update standards watchdog rule
  rules/standards-watchdog/rule.md
Labels: Age: 🥚 - New

#9819 Cms/calinator444/ssw.rules.content/rule/choosing large language models/rule
  rules/choosing-large-language-models/rule.md
Labels: Age: 🥚 - New

#9820 S ◾ Github models - add to category
  categories/artificial-intelligence/rules-to-better-ai-development.md
  rules/choosing-large-language-models/rule.md
Labels: Age: 🥚 - New

#9822 L ◾ Updated "cc-and-reply-to-all" and related rules
  categories/communication/rules-to-better-email.md
  rules/avoid-replying-to-all-when-bcced/rule.md
  rules/cc-and-reply-to-all/rule.md
  rules/do-you-cc-everyone-and-reply-to-all-when-necessary/rule.md
  rules/email-add-or-remove-someone-from-conversation/rule.md
Labels: Age: 🥚 - New

#9823 XS ◾ Added section about people sitting next to each other
  rules/when-to-create-a-group-chat/rule.md
Labels: Age: 🥚 - New

#9825 S ◾ General improvements LLM rule
  rules/choosing-large-language-models/rule.md
Labels: Age: 🥚 - New
