Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-04, with the labels that each got.

#10087 XL ◾ Add new rule on choosing Azure database models with accompanying…
  categories/software-engineering/rules-to-better-azure.md
  rules/azure-database-models-choosing/elastic-pool-good.png
  rules/azure-database-models-choosing/rule.md
  rules/azure-database-models-choosing/single-db-per-tenant-bad.png
Labels: Age: 🥚 - New

#10088 XS ◾ fixing broken markdown
  rules/birthdays/rule.md
Labels: Age: 🥚 - New

#10089 XS ◾ Clarifying the concept of chained prompts
  rules/chained-prompting/rule.md
Labels: Age: 🐤 - Mature

#10091 XS ◾ Fixed caption + improved title "good subjects" rule
  rules/good-email-subject/rule.md
Labels: Age: 🐣 - Young

#10098 XS ◾ Revert "Update Rule “sprint-review-retro-email/rule”"
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#10099 XS ◾ Archiving rule
  categories/marketing-and-video/rules-to-better-social-media-personal.md
  rules/linkedin-creator-mode/rule.md
Labels: Age: 🥚 - New

#10105 M ◾ Create rule.md
  rules/apply-grey-background-formulas-excel/rule.md
Labels: Age: 🥚 - New

#10106 XS ◾ Update rules-to-better-communication.md
  categories/communication/rules-to-better-communication.md
Labels: Age: 🥚 - New

#10107 XS ◾ Add files via upload
  categories/communication/rules-to-better-communication.md
  categories/company-operations/rules-to-better-accounting.md
  rules/apply-grey-background-formulas-excel/excelgreygoodexample.png
  rules/apply-grey-background-formulas-excel/rule.md
Labels: Age: 🥚 - New

#10108 XS ◾ Fixing URI
  rules/excel-distinguish-calculated-cells/rule.md
Labels: Age: 🥚 - New

#10109 XS ◾ fixing frontmatter
  rules/excel-distinguish-calculated-cells/rule.md
Labels: Age: 🥚 - New

#10113 XS ◾ Updating rule body - moving steps further up
  rules/discord-communities/rule.md
Labels: Age: 🥚 - New

#10114 XS ◾ Change the title to be shorter
  rules/discord-communities/rule.md
Labels: Age: 🥚 - New

#10115 Move URL blog post to the top
  rules/discord-communities/rule.md
Labels: Age: 🥚 - New

#10119 XS ◾ Update rules-to-better-communication.md
  categories/communication/rules-to-better-communication.md
Labels: Age: 🥚 - New

#10117 XS ◾ Add good wording
  rules/discord-communities/rule.md
Labels: Age: 🐓 - Old

#10116 XS ◾ Add community Discord link again
  rules/discord-communities/rule.md
Labels: Age: 🐓 - Old

#10121 XS ◾ Fixed broken link
  rules/cms-solutions/rule.md
Labels: codeauditor fix, Age: 🥚 - New

#10123 XS ◾ Fixed from Twitter to X
  rules/image-standard-sizes-on-social-media/rule.md
Labels: rubber stamp, Age: 🥚 - New

#10124 S ◾ Added link to trimming videos + other readability improvements "summary-recording-sprint-reviews"
  rules/summary-recording-sprint-reviews/rule.md
Labels: Age: 🥚 - New

#10125 XS ◾ moved tip up and improved sentence "summary-recording-sprint-reviews"
  rules/summary-recording-sprint-reviews/rule.md
Labels: Age: 🥚 - New

#10122 XS ◾ Removed broken link + improved title
  rules/avoid-using-if-else-instead-of-switch-block/rule.md
Labels: codeauditor fix, Age: 🐥 - Adolescent

#10120 XS ◾ Improved "Teams meeting chats " rule
  rules/teams-meetings-vs-group-chats/rule.md
Labels: Age: 🐤 - Mature

#10128 XS ◾ Adding Spec Review
  rules/track-your-initial-meetings/rule.md
Labels: Age: 🥚 - New

#10126 XS ◾ remove highlight from "meeting chat" so users aren't confused
  rules/teams-meetings-vs-group-chats/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10129 Change "Chaining your prompts" to "Prompt chaining"
  rules/chained-prompting/rule.md
  rules/chatgpt-cheat-sheet/rule.md
Labels: Age: 🐓 - Old

#10130 XS ◾ Update rule.md
  rules/use-emojis/rule.md
Labels: Age: 🥚 - New

#10127 M ◾ Updated rule on clean labels
  categories/design/rules-to-better-interfaces-forms.md
  categories/design/rules-to-better-interfaces-general-usability-practices.md
  rules/avoid-clutter-in-form-labels/rule.md
  rules/avoid-ending-labels-text-with-a-colon/rule.md
  rules/avoid-labels/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10134 XS ◾ Adding a good example of warning stakeholders
  rules/sprint-review-retro-email/rule.md
  rules/what-happens-at-a-sprint-review-meeting/rule.md
  rules/what-happens-at-a-sprint-review-meeting/sprint-review-stakeholders.png
Labels: Age: 🥚 - New

#10135 XS ◾ adding SEO description
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10136 removing 'archivedreason' field
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10137 XS ◾ trying to fix rule
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10138 XS ◾ Removed duplicated links
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10139 XS ◾ trying #2 to fix rule
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10140 Fixed title frontmatter of rule
  rules/track-your-initial-meetings/rule.md
Labels: Age: 🥚 - New

#10132 XS ◾ Improved title and examples "space after commas/full stops" rule
  rules/commas-and-full-stops-always-should-have-1-space-after-them/rule.md
Labels: Age: 🍗 - Ancient

#10141 XS ◾ Fixed list in the rule
  rules/track-your-initial-meetings/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10142 XS ◾ Added line breaks for list of usage "use-emojis"
  rules/use-emojis/rule.md
Labels: Age: 🐣 - Young

#10146 XS ◾ Update infrastructure healthcheck
  rules/infrastructure-healthchecks/rule.md
Labels: Age: 🥚 - New

#10145 Cms/louisroa8189/ssw.rules.content/rule/use mcp to standardize llm connections/rule
  rules/use-mcp-to-standardize-llm-connections/rule.md
Labels: Age: 🥚 - New

#10147 S ◾ add implementation health check guide
  rules/infrastructure-healthchecks/rule.md
Labels: Age: 🥚 - New

#10144 Update Rule “custom-instructions/rule”
  rules/custom-instructions/eli-custom-bad.png
  rules/custom-instructions/eli-custom-good.png
  rules/custom-instructions/rule.md
Labels: Age: 🐓 - Old

#10150 L ◾ update mcp rules
  categories/artificial-intelligence/rules-to-better-ai.md
  rules/mcp-server/rule.md
  rules/mcp-server/with-mcp.png
  rules/use-mcp-to-standardize-llm-connections/mcp.png
  rules/use-mcp-to-standardize-llm-connections/rule.md
Labels: Age: 🥚 - New

#10153 XS ◾ Update Use NextJs rule.md
  rules/use-nextjs/rule.md
Labels: Age: 🥚 - New

#10156 Cms/pothieu g/ssw.rules.content/rule/do you know how to use nextjs caching system/rule
  categories/software-engineering/rules-to-better-websites-development.md
  rules/do-you-know-how-to-use-nextjs-caching-system/rule.md
Labels: Age: 🐓 - Old

#10155 XS ◾ Update fetch data nextjs.md
  rules/fetch-data-nextjs/rule.md
Labels: Age: 🐓 - Old

#10148 XS ◾ 📝Do you Healthcheck your Infrastructure? - Update good example figure
  rules/infrastructure-healthchecks/infra-good-example.png
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10158 XS ◾ relating "clean URLs" and "New line" rules
  rules/format-new-lines/rule.md
  rules/keep-your-urls-clean/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10157 XS ◾ Made the recommended term bold
  rules/salary-terminology/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10163 XS ◾ use MCP rule
  rules/use-mcp-to-standardize-llm-connections/rule.md
Labels: Age: 🥚 - New

#10162 M ◾ Updated MCP rules
  rules/mcp-server/rule.md
  rules/use-mcp-to-standardize-llm-connections/rule.md
Labels: Age: 🐓 - Old

#10165 XS ◾ fixed frontmatter issues for infrastructure healthchecks rule
  rules/infrastructure-healthchecks/rule.md
Labels: Age: 🥚 - New

#10168 XS ◾ Screenshots rule - replaced bad quality images with the better one
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/bad-screenshot-with-personal-data.jpg
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/bad-screenshot-with-personal-data.png
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/good-no-personal-info.jpg
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/good-no-personal-info.png
  rules/do-you-know-not-to-include-toolbar-and-taskbar-junk-in-screenshots/rule.md
Labels: Age: 🥚 - New

#10170 Update Rule “infrastructure-healthchecks/rule”
  rules/infrastructure-healthchecks/image-3-.png
  rules/infrastructure-healthchecks/rule.md
Labels: Age: 🥚 - New

#10167 Update Rule “avoid-ai-hallucinations/rule”
  rules/avoid-ai-hallucinations/rule.md
Labels: Age: 🐓 - Old

#10164 Create Rule “reducing-design-debt/rule”
  rules/design-debt/rule.md
  rules/reducing-design-debt/design-debt-bad-ex.png
  rules/reducing-design-debt/design-debt-good-ex.png
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10174 Moving images to the right folder
  rules/design-debt/design-debt-bad-ex.png
  rules/design-debt/design-debt-good-ex.png
Labels: Age: 🥚 - New
