Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-07, with the labels that each got.

#10423 XS ◾ Update support-send-links/rule.md
  rules/support-send-links/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10425 XS ◾ Update rule.md to have the dotted line examples
  rules/design-debt/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10434 Create Rule “remove-confidential-information-from-github/rule”
  categories/infrastructure-and-networking/rules-to-better-security.md
  categories/project-delivery/rules-to-better-github.md
  rules/remove-confidential-information-from-github/confidential-info-removed-comment.png
  rules/remove-confidential-information-from-github/confidential-info-removed-revision-deletion.png
  rules/remove-confidential-information-from-github/rule.md
Labels: Age: 🥚 - New

#10435 Create Rule “self-contained-images-and-content/rule”
  categories/software-engineering/rules-to-better-websites-development.md
  rules/self-contained-images-and-content/rule.md
Labels: Age: 🐥 - Adolescent

#10442 XS ◾ Update rule about optimizing tina project
  rules/do-you-optimize-tinacms-project/2024-08-28_16-21-56.png
  rules/do-you-optimize-tinacms-project/rule.md
Labels: Age: 🥚 - New

#10448 Design Debt - fix images
  rules/design-debt/design-debt-bad-ex.png
  rules/design-debt/design-debt-bad.png
  rules/design-debt/design-debt-good-ex.png
  rules/design-debt/design-debt-good.png
  rules/design-debt/rule.md
Labels: Age: 🥚 - New

#10443 XS ◾ Update /self-contained-images-and-content/rule.md
  rules/self-contained-images-and-content/rule.md
Labels: Age: 🐤 - Mature

#10449 XS ◾ Add video to rule
  rules/hamburger-menu/rule.md
Labels: Age: 🐓 - Old

#10444 M ◾ Update clean URLs rule + added related
  rules/keep-your-urls-clean/rule.md
  rules/video-editing-terms/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10454 XS ◾ Update /the-best-chat-tools-for-your-employees/rule.md
  rules/the-best-chat-tools-for-your-employees/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10453 Create Rule “do-you-know-the-right-copilot-lingo/rule”
  categories/artificial-intelligence/rules-to-better-ai.md
  rules/do-you-know-the-right-copilot-lingo/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10417 L ◾ Created new rule on using the BannedApiAnalyzer
  categories/software-engineering/rules-to-better-net8-migrations.md
  rules/use-banned-api-analyzers/banned-api-lists-errors.png
  rules/use-banned-api-analyzers/banned-api-project-building.png
  rules/use-banned-api-analyzers/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10447 XS ◾ Update /request-test-please/ rule.md
  rules/request-a-test-please/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10459 XS ◾ Remove EagleEye link rule.md
  rules/design-debt/design-debt-good.png
  rules/design-debt/design-dept-good.png
  rules/design-debt/rule.md
Labels: Age: 🥚 - New

#10460 XS ◾ Update /record-a-quick-and-dirty-done-video/rule.md
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🥚 - New

#10462 XS ◾ Rename design-dept-good.png to design-debt-good.png
  rules/design-debt/design-debt-good.png
Labels: Age: 🥚 - New

#10457 XS ◾ Update /avoid-repetition/rule.md
  rules/avoid-repetition/crtlc-ctrlv.png
  rules/avoid-repetition/rule.md
Labels: Age: 🐥 - Adolescent

#10466 XS ◾ Update /separate-messages/rule.md
  rules/separate-messages/rule.md
Labels: Age: 🥚 - New

#10456 Migrate history.json to frontmatter of rules/categories
  categories/artificial-intelligence/index.mdx
  categories/artificial-intelligence/rules-to-better-ai.mdx
  categories/artificial-intelligence/rules-to-better-chatgpt-prompt-engineering.mdx
  categories/client-engagement/index.mdx
  categories/client-engagement/rules-to-better-account-management.mdx
  categories/client-engagement/rules-to-better-specification-reviews.mdx
  categories/index.mdx
  history.json
  public/uploads/rules/ai-prompt-xml/rule.mdx
  public/uploads/rules/best-ai-tools/rule.mdx
  public/uploads/rules/corridor-conversations/rule.mdx
  public/uploads/rules/fundamentals-of-prompt-engineering/rule.mdx
  public/uploads/rules/meeting-bookings/rule.mdx
  public/uploads/rules/perform-client-follow-ups/rule.mdx
  public/uploads/rules/what-is-a-spec-review/rule.mdx
  public/uploads/rules/what-is-chatgpt/rule.mdx
  scripts/tina-migration/migrate-history.py
  tina/tina-lock.json
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10477 M ◾ Improvements to R&D rules
  categories/company-operations/rules-to-better-research-and-development.md
  rules/do-you-know-how-painful-rd-is/rule.md
  rules/do-you-link-your-commits-to-a-pbi/rule.md
  rules/do-you-record-your-failures/abandoned-pr-for-branch.png
  rules/do-you-record-your-failures/create-pr-for-failed-branch.png
  rules/do-you-record-your-failures/rule.md
  rules/do-you-record-your-research-under-the-pbi/rule.md
  rules/do-you-save-failed-experiments-in-abandoned-pull-requests/rule.md
  rules/poc-vs-mvp/rule.md
Labels: Age: 🐣 - Young

#10483 XS ◾ 📽️ Video - Adds small section on recording Sprint Review Retro summaries on email rule
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#10485 XS ◾ Update /replying-in-the-same-medium/rule.md
  rules/replying-in-the-same-medium/rule.md
Labels: Age: 🐤 - Mature

#10488 S ◾ Update rule.md
  rules/website-page-speed/performance-tab.png
  rules/website-page-speed/rule.md
Labels: Age: 🥚 - New

#10489 Update Rule “best-ai-powered-ide/rule”
  rules/best-ai-powered-ide/rule.md
Labels: Age: 🐓 - Old

#10498 XS ◾ Adding 'human approval'
  rules/low-code-and-ai/rule.md
Labels: Age: 🥚 - New

#10276 L ◾ add rule on risk multipliers
  categories/client-engagement/rules-to-better-software-consultants-happy-clients.md
  rules/risk-multipliers/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10499 XL ◾ Add new rule: Run LLMs locally for enhanced privacy and control
  categories/artificial-intelligence/rules-to-better-ai.md
  rules/run-llms-locally/rule.md
Labels: Age: 🥚 - New

#10502 S ◾ Update rule "Technical - Do you check your website performance?"
  rules/website-page-speed/bad-performance.png
  rules/website-page-speed/lighthouse.png
  rules/website-page-speed/rule.md
Labels: Age: 🥚 - New

#10490 Update Rule “automatic-code-reviews-github/rule”
  rules/automatic-code-reviews-github/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10501 XS ◾ Add performance measurement tools and related rules to the performance review guideline
  rules/do-you-avoid-reviewing-performance-without-metrics/chrome-perf-tools.png
  rules/do-you-avoid-reviewing-performance-without-metrics/rule.md
Labels: Age: 🐤 - Mature

#10514 XS ◾ Update rule.md
  rules/video-editing-terms/rule.md
Labels: Age: 🥚 - New

#10508 XS ◾ Update /share-source-files-with-video-editor/rule.md
  rules/share-source-files-with-video-editor/rule.md
Labels: Age: 🐤 - Mature

#10519 S ◾ Update /rules/use-ai-receptionist/
  categories/artificial-intelligence/rules-to-better-ai.md
  categories/marketing-and-video/rules-to-better-inbound-calls.md
  rules/be-prepared-for-inbound-calls/rule.md
  rules/use-ai-receptionist/rule.md
Labels: Age: 🐥 - Adolescent

#10518 Update Rule “software-architecture-decision-tree/rule”
  rules/software-architecture-decision-tree/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10521 Create Rule “handover-best-practices/rule”
  categories/company-operations/rules-to-successful-projects.md
  rules/handover-best-practices/rule.md
Labels: Age: 🐣 - Young

#10525 XS ◾ FIx formatting
  rules/mix-user-research-methods/rule.md
Labels: Age: 🥚 - New

#10524 XS ◾ Fix formatting
  rules/handover-best-practices/rule.md
Labels: Age: 🥚 - New

#10527 XS ◾ Adding XLS and GitHub to spec review rule
  rules/spec-do-you-create-an-initial-release-plan-and-ballpark/rule.md
Labels: Age: 🥚 - New

#10493 M ◾ Archiving old and outdated rules 2
  rules/do-you-integrate-crm-with-microsoft-lync/rule.md
  rules/do-you-know-how-to-correctly-use-the-terms-configuration-and-customization-in-the-tfs-context/rule.md
  rules/do-you-know-how-to-create-a-meeting-request-for-an-online-meeting-or-conference-call/rule.md
  rules/do-you-know-how-to-troubleshoot-lync-connectivity-or-configuration-issues/rule.md
  rules/do-you-know-how-to-use-snom-voip-phones-physical-phones-microsoft-lync/rule.md
  rules/do-you-know-the-primary-features-of-lync-software-phones-with-microsoft-lync/rule.md
  rules/do-you-know-what-ip-phones-are-supported-by-microsoft-lync/rule.md
  rules/do-you-setup-lync-conference-calls-that-makes-you-the-organizer-leader-presenter/rule.md
  rules/do-you-start-from-a-built-in-process-template/rule.md
  rules/do-you-use-global-list/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10492 S ◾ Archiving old and outdated rules
  rules/are-your-developers-managing-your-projects-with-tfs-with-proven-agile-scrum-and-alm-strategies/rule.md
  rules/do-you-bundle-and-minify-your-javascript/rule.md
  rules/do-you-install-sharepoint-designer-when-using-a-sharepoint-vhd/rule.md
  rules/do-you-know-that-you-cant-use-2010-managed-metadata-with-office-2007-out-of-the-box/rule.md
  rules/do-you-know-the-6-ways-to-integrate-your-crm-2011-data-into-sharepoint-2010/rule.md
  rules/do-you-know-the-best-sharepoint-2010-development-environment/rule.md
  rules/do-you-use-content-editor-web-part-with-care/rule.md
  rules/rollback-plan-tfs2010-migration/rule.md
  rules/sharepoint-rules-categories-do-you-know-how-to-make-the-title-consistent/rule.md
  rules/what-does-a-sharepoint-image-need/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10530 XS ◾ Archived Lync category as it's been replaced by Teams
  categories/infrastructure-and-networking/rules-to-better-skype-for-business-formerly-lync.md
Labels: Age: 🥚 - New

#10535 XS ◾ Update URI for Done rules
  categories/communication/rules-to-better-email.md
  categories/communication/rules-to-better-inbox-management.md
  categories/company-operations/rules-to-successful-projects.md
  categories/marketing-and-video/rules-to-better-video-recording.md
  categories/project-delivery/rules-to-better-scrum.md
  rules/done-video/rule.md
  rules/reply-done/rule.md
Labels: Age: 🥚 - New

#10531 XS ◾ Update rules-to-better-testing.md
  categories/software-engineering/rules-to-better-testing.md
Labels: Age: 🐣 - Young

#10537 XS ◾ Add support for raw image handling in MDX conversion
  scripts/tina-migration/convert-rule-md-to-mdx.py
Labels: Age: 🥚 - New

#10529 XS ◾ Update /relational-database-design/rule.md
  rules/relational-database-design/rule.md
Labels: Age: 🐓 - Old

#10533 S ◾ Update /mix-user-research-methods/rule.md
  rules/mix-user-research-methods/rule.md
Labels: Age: 🐓 - Old

#10532 XS ◾ Archiving rules-to-better-tfs-administration replaced by Azure DevOps
  categories/project-delivery/rules-to-better-tfs-administration.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10547 XS ◾ Micsblank patch 7
  rules/design-debt/design-debt-bad.png
  rules/design-debt/design-debt-good.png
  rules/design-debt/rule.md
Labels: Age: 🥚 - New

#10550 XS ◾ Update rule.md
  rules/protect-your-teams-creativity/rule.md
Labels: Age: 🥚 - New

#10555 XS ◾ Relating LinkedIn rules
  rules/have-urls-to-your-main-services-on-linkedin/rule.md
  rules/linkedin-connect-your-microsoft-account/rule.md
  rules/linkedin-profile/rule.md
Labels: Age: 🥚 - New

#10558 XS ◾ Update /linkedin-connect-your-microsoft-account/rule.md
  rules/linkedin-connect-your-microsoft-account/rule.md
Labels: Age: 🥚 - New

#10565 XS ◾ Archiving duplicate rule
  rules/spec-do-you-create-an-initial-release-plan-and-ballpark/rule.md
Labels: Age: 🥚 - New

#10567 Update rule.md
  rules/copilot-lingo/rule.md
  rules/do-you-know-the-right-copilot-lingo/rule.md
Labels: Age: 🐤 - Mature

#10564 S ◾ Updated - do-you-know-the-best-way-to-give-the-best-customer-support
  rules/do-you-know-the-best-way-to-give-the-best-customer-support/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10568 M ◾ ➕ New rule - Do you record incidents and perform root cause analysis with clear actions?
  categories/project-delivery/rules-to-better-devops.md
  rules/record-incidents-and-perform-root-cause-analysis-with-clear-actions/rule.md
Labels: Age: 🥚 - New

#10571 XS ◾ 📈 Project portals - Updates 'as of' date for GitHub projects
  rules/use-a-project-portal-for-your-team-and-client/rule.md
Labels: Age: 🥚 - New

#10572 XS ◾ Update rule.md
  rules/use-esignature-solutions/rule.md
Labels: Age: 🐤 - Mature

#10577 Update rule use-esignature-solutions.md
  rules/use-esignature-solutions/rule.md
Labels: Age: 🥚 - New

#10579 XS ◾ Update rule use-esignature-solutions.md
  rules/use-esignature-solutions/rule.md
Labels: Age: 🥚 - New

#10575 XS ◾ Update /do-you-use-the-correct-input-type/rule.md
  rules/do-you-use-the-correct-input-type/rule.md
Labels: Age: 🐥 - Adolescent

#10539 XS ◾ Archiving Rules in - rules-to-better-net-projects
  rules/do-you-add-ssw-code-auditor-nunit-and-microsoft-fxcop-project-files-to-your-solution/rule.md
  rules/do-you-avoid-microsoft-visualbasic-compatibility-dll-for-visual-basic-net-projects/rule.md
  rules/do-you-know-changes-on-datetime-in-net-2-0-and-net-1-1-1-0/rule.md
  rules/do-you-know-the-right-methodology-to-choose-new-project-in-vs-2012/rule.md
  rules/do-you-know-what-files-not-to-put-into-vss/rule.md
  rules/do-you-use-microsoft-visualbasic-dll-for-visual-basic-net-projects/rule.md
  rules/do-you-use-the-sharepoint-portal-in-vsts-2012/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10582 XS ◾ More updates to design debt
  rules/design-debt/rule.md
  rules/design-system/rule.md
Labels: Age: 🐥 - Adolescent

#10583 M ◾ Update /add-a-spot-of-color-for-emphasis/rule.md
  rules/add-a-spot-of-color-for-emphasis/rule.md
  rules/add-a-spot-of-color-for-emphasis/text-color-bad.png
  rules/add-a-spot-of-color-for-emphasis/text-color-good.png
Labels: Age: 🐥 - Adolescent

#10566 L ◾ Created new rule on regex tools
  categories/software-engineering/rules-to-better-regular-expressions.md
  rules/do-you-use-online-regex-tools/regexr-password-validation.png
  rules/do-you-use-online-regex-tools/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10574 L ◾ Update and rename why-nextjs-is-great
  categories/software-engineering/rules-to-better-nextjs.md
  categories/software-engineering/rules-to-better-websites-development.md
  rules/use-nextjs/rule.md
  rules/why-angular-is-great/rule.md
  rules/why-blazor-is-great/rule.md
  rules/why-nextjs-is-great/rule.md
  rules/why-react-is-great/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10586 XS ◾ Typo - Update rule.md
  rules/run-llms-locally/rule.md
Labels: Age: 🥚 - New

#10592 XS ◾ Update rules titles to remove unnecessary prefixes
  rules/avoid-repetition/rule.md
  rules/loop-someone-in/rule.md
  rules/the-best-chat-tools-for-your-employees/rule.md
  rules/use-digits-instead-of-words/rule.md
  rules/zooming-in-and-out/rule.md
Labels: Age: 🐣 - Young

#10594 XS ◾ local llms rule - refine it a bit
  rules/run-llms-locally/rule.md
Labels: Age: 🥚 - New

#10601 update: rule avoid sending emails immediately to also add mac outlook instructions
  rules/avoid-sending-emails-immediately/outlook-composing.png
  rules/avoid-sending-emails-immediately/outlook-settings.png
  rules/avoid-sending-emails-immediately/rule.md
  rules/avoid-sending-emails-immediately/test-delayed-email.png
  rules/avoid-sending-emails-immediately/undo-send.png
Labels: Age: 🐥 - Adolescent

#10606 XS ◾ Update /browser-add-branding/rule.md
  rules/browser-add-branding/rule.md
Labels: Age: 🥚 - New

#10605 M ◾ Improving rules titles
  rules/avoid-using-request-a-receipt/rule.md
  rules/bounces-do-you-know-what-to-do-with-bounced-email/rule.md
  rules/correct-a-wrong-email-bounce/rule.md
  rules/do-you-avoid-using-words-that-make-your-email-like-junk-mail/rule.md
  rules/do-you-know-when-to-use-plus-one/rule.md
  rules/enable-presentation-mode-in-visual-studio/rule.md
Labels: Age: 🐥 - Adolescent
