Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-02, with the labels that each got.

#9830 XS ◾ Adding image and grey box
  rules/work-in-order-of-importance-aka-priorities/Urgent-or-Important.png
  rules/work-in-order-of-importance-aka-priorities/rule.md
Labels: Age: 🥚 - New

#9829 Update Rule “request-a-test-please/rule”
  rules/request-a-test-please/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9831 S ◾ Improved URL and content "fixed-price-vs-time-and-materials"
  categories/client-engagement/rules-to-better-software-consultants-dealing-with-clients.md
  rules/fixed-price-vs-time-and-materials/refusing-meal-restaurant.jpeg
  rules/fixed-price-vs-time-and-materials/rule.md
Labels: Age: 🥚 - New

#9834 XS ◾ Archived obsolete rule on graphics
  rules/do-you-use-image-sprites-to-reduce-http-requests/rule.md
Labels: Age: 🥚 - New

#9835 S ◾ Improvements to "write-a-good-pull-request" rule
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#9836 S ◾ Improvements to "close-pbis-with-context" rule
  rules/close-pbis-with-context/rule.md
Labels: Age: 🥚 - New

#9838 S ◾ ✨ New Rule - Use eye toggle to see password
  categories/infrastructure-and-networking/rules-to-better-security.md
  rules/use-eye-toggle-to-see-password/bad-example-no-eye-toggle.png
  rules/use-eye-toggle-to-see-password/good-example-eye-toggle.png
  rules/use-eye-toggle-to-see-password/rule.md
Labels: Age: 🥚 - New

#9839 XS ◾ ✏️ Fixed typo
  rules/use-eye-toggle-to-see-password/rule.md
Labels: Age: 🥚 - New

#9841 XS ◾ Added missing closing quotes + small improvements
  rules/close-pbis-with-context/rule.md
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#9844 XS ◾ Fixed headings and content for "/chatgpt-prompts-for-video-production…
  rules/chatgpt-prompts-for-video-production/rule.md
Labels: Age: 🐥 - Adolescent

#9832 S ◾ Fixed broken links + more
  rules/do-you-calculate-payroll-tax-correctly/rule.md
  rules/do-you-know-the-best-online-accommodation-websites/rule.md
  rules/make-sure-all-software-uses-english/rule.md
  rules/web-ui-libraries/rule.md
Labels: codeauditor fix, Age: 🐓 - Old

#9833 S ◾ Merged similar rules with improvements
  rules/analyze-website-performance/rule.md
  rules/do-you-use-pagespeed/rule.md
  rules/website-page-speed/rule.md
Labels: Age: 🐓 - Old

#9845 S ◾ Improved "work-in-order-of-importance-aka-priorities /" readability
  rules/work-in-order-of-importance-aka-priorities/rule.md
Labels: Age: 🐥 - Adolescent

#9846 XS ◾ Improved "refer-to-email-subject" rule + added related
  rules/refer-to-email-subject/rule.md
  rules/write-a-good-pull-request/rule.md
Labels: Age: 🥚 - New

#9843 XS ◾ Fixed headings for "chatgpt-for-email" rule
  rules/chatgpt-for-email/rule.md
Labels: Age: 🐤 - Mature

#9852 XS ◾ Added author to Gravatar rule
  categories/design/rules-to-better-websites-layout-and-formatting.md
  categories/software-engineering/rules-to-better-internationalization.md
  rules/gravatar-for-profile-management/rule.md
Labels: Age: 🐣 - Young

#9851 XS ◾ Added redirect URL to the rule
  categories/software-engineering/rules-to-better-code-quality.md
  rules/get-code-line-metrics/rule.md
Labels: Age: 🐣 - Young

#9842 XS ◾ Added missing code language + other improvements
  rules/ensure-language-follows-user-regional-settings/rule.md
Labels: Age: 🐓 - Old

#9856 Create Rule “sysadmin-cybersecurity-tools/rule”
  rules/sysadmin-cybersecurity-tools/rule.md
Labels: Age: 🥚 - New

#9857 XS ◾ Update rules-to-better-security.md
  categories/infrastructure-and-networking/rules-to-better-security.md
Labels: Age: 🥚 - New

#9858 Create Rule “developer-cybersecurity-tools/rule”
  rules/developer-cybersecurity-tools/rule.md
Labels: Age: 🥚 - New

#9863 XS ◾ Fixing Do you know how to prevent phishing for payments? URI format
  rules/phishing-for-payments/rule.md
Labels: Age: 🥚 - New

#9864 XS ◾ Update rule.md
  rules/phishing-for-payments/rule.md
Labels: Age: 🥚 - New

#9865 XS ◾ Added video to Pen Test rule
  rules/penetration-testing/rule.md
Labels: Age: 🥚 - New

#9866 S ◾ Added related rules on pishing
  rules/recognizing-phishing-urls/rule.md
  rules/recognizing-scam-emails/rule.md
Labels: Age: 🥚 - New

#9872 XS ◾ ✏️ Update rule - Do you know how to speak up in meetings?
  rules/speak-up-in-meetings/rule.md
Labels: Age: 🥚 - New

#9875 XS ◾ Add files via upload
  rules/do-you-have-a-dress-code/rule.md
  rules/do-you-have-a-dress-code/tina-london.png
Labels: Age: 🥚 - New

#9874 XS ◾ ✏️ Updated rule - Do you know how to speak up in meetings?
  rules/speak-up-in-meetings/rule.md
Labels: Age: 🐣 - Young

#9873 XS ◾ Improvement in content - Key differences between Graphic Design and UI/UX Design
  rules/graphic-vs-ui-ux-design/rule.md
Labels: Age: 🐥 - Adolescent

#9878 XS ◾ Improved examples table "video time length" rule
  rules/right-format-to-write-videos-time-length/rule.md
Labels: Age: 🥚 - New

#9879 XS ◾ ✨ Rule update: healthchecks for infrastructure
  categories/software-engineering/rules-to-better-unit-tests.md
  rules/have-a-healthcheck-page-to-test-your-website-dependencies/infra-bad-example.png
  rules/have-a-healthcheck-page-to-test-your-website-dependencies/infra-good-example.png
  rules/have-a-healthcheck-page-to-test-your-website-dependencies/rule.md
Labels: Age: 🥚 - New

#9883 XS ◾ Remove brackets from description
  rules/installing-3rd-party-libraries/rule.md
Labels: Age: 🥚 - New

#9886 XS ◾ 📄 Updated speak up rule to add retro sub-heading
  rules/infrastructure-healthchecks/rule.md
  rules/speak-up-in-meetings/rule.md
Labels: Age: 🥚 - New

#9888 XS ◾ Adding a LinkedIn note
  rules/prefix-job-title/rule.md
Labels: Age: 🥚 - New

#9889 XS ◾ Fix Markdown for email template
  rules/request-a-test-please/rule.md
Labels: Age: 🥚 - New

#9892 Create Rule “do-you-print-your-travel-schedule/rule”
  rules/do-you-print-your-travel-schedule/pa-rule-1.png
  rules/do-you-print-your-travel-schedule/pa-rule-2.png
  rules/do-you-print-your-travel-schedule/pa-rule-3.png
  rules/do-you-print-your-travel-schedule/pa-rule-4.png
  rules/do-you-print-your-travel-schedule/rule.md
Labels: Age: 🥚 - New

#9893 XS ◾ Update rule.md
  rules/do-you-print-your-travel-schedule/rule.md
Labels: Age: 🥚 - New

#9869 L ◾ Fixed new line issues on cybersecurity rules
  rules/developer-cybersecurity-tools/rule.md
  rules/sysadmin-cybersecurity-tools/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9895 Create Rule “sysadmin-cybersecurity-tools/rule”
  rules/sysadmin-cybersecurity-tools/rule.md
Labels: Age: 🐤 - Mature

#9876 Create Rule “do-you-canary-deploy-your-new-features-using-a-spreadsheet/rule”
  assets/canary-deployment.png
  categories/project-delivery/index.md
  categories/project-delivery/rules-to-better-continuous-deployment-with-tfs.md
  categories/software-engineering/rules-to-better-testing.md
  rules/canary-deploy/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9897 XS ◾ Fixed images + URL + more "dress-code"
  rules/do-you-have-a-dress-code/tina-london.png
  rules/dress-code/dresscode-linkedin.png
  rules/dress-code/rule.md
  rules/dress-code/sean-connery-dressed-up.jpg
  rules/dress-code/ssw-dresscode-poster-v2.png
  rules/dress-code/tina-london.png
Labels: Age: 🐥 - Adolescent

#9899 XS ◾ Update rule.md
  rules/image-formats/rule.md
Labels: Age: 🥚 - New

#9901 XS ◾ Update rule.md
  rules/add-useful-and-concise-figure-captions/rule.md
Labels: Age: 🥚 - New

#9898 XS ◾ Added link to Employment page on -use-the-brains rule
  rules/use-the-brains-of-your-company/rule.md
Labels: Age: 🥚 - New

#9896 XS ◾ Update LinkedIn image example
  rules/linkedin-profile/good-linkedin.jpg
  rules/linkedin-profile/rule.md
Labels: Age: 🐤 - Mature

#9903 XS ◾ Update rule.md
  rules/change-the-subject/rule.md
Labels: Age: 🐤 - Mature

#9906 Update Rule “penetration-testing/rule”
  rules/penetration-testing/rule.md
Labels: Age: 🐤 - Mature

#9912 XS ◾ Adding section about copilot
  rules/website-chatbot/rule.md
Labels: Age: 🥚 - New

#9913 Update Rule “change-the-subject/rule”
  rules/change-the-subject/rule.md
Labels: Age: 🥚 - New

#9914 XS ◾ Update rule.md
  rules/add-useful-and-concise-figure-captions/rule.md
Labels: Age: 🥚 - New

#9900 S ◾ Update rule.md
  rules/add-useful-and-concise-figure-captions/rule.md
Labels: Age: 🐓 - Old

#9916 XS ◾ Update rule.md
  rules/add-useful-and-concise-figure-captions/rule.md
Labels: Age: 🥚 - New

#9877 S ◾ Improved rules + related them "sending emails/message separated"
  categories/communication/rules-to-better-email.md
  rules/email-unrelated-individually/rule.md
  rules/separate-messages/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9910 Change X to Y - Fixed indentation and add >
  rules/change-from-x-to-y/rule.md
Labels: Age: 🐤 - Mature

#9915 Add information regarding OBS FPS
  rules/record-a-quick-and-dirty-done-video/rule.md
Labels: Age: 🐥 - Adolescent

#9917 S ◾ Archiving duplicated rule + relating rules
  rules/do-you-respond-to-each-email-individually/rule.md
  rules/reply-done-and-delete-the-email/rule.md
  rules/split-emails-by-topic/rule.md
Labels: Age: 🥚 - New

#9918 XS ◾ Update and rename rule.md to rule.md
  categories/communication/rules-to-better-email.md
  categories/software-engineering/rules-to-better-github.md
  rules/change-from-x-to-y/rule.md
  rules/indent/rule.md
Labels: Age: 🥚 - New

#9920 XS ◾ "indent" update
  rules/indent/rule.md
Labels: Age: 🐣 - Young

#9919 S ◾ "number tasks" update
  rules/number-tasks-questions/rule.md
Labels: Age: 🐣 - Young

#9924 XS ◾ 🐛 Fixed the GUID of rule
  rules/developer-cybersecurity-tools/rule.md
Labels: Age: 🐤 - Mature

#9907 Update rule.md
  rules/dates-do-you-keep-date-formats-consistent-across-your-application/PowerBI-wrong-date-format.png
  rules/dates-do-you-keep-date-formats-consistent-across-your-application/browser-language-setting.png
  rules/dates-do-you-keep-date-formats-consistent-across-your-application/operatingsystem-language-setting.png
  rules/dates-do-you-keep-date-formats-consistent-across-your-application/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9925 XS ◾ Improved readability and syntax on "include-links-in-emails" rule
  rules/include-links-in-emails/rule.md
Labels: Age: 🐥 - Adolescent

#9926 S ◾ removed greater sign on "x-to-y" + bad example + line break on Note for "indent" rule
  rules/change-from-x-to-y/rule.md
  rules/indent/rule.md
Labels: Age: 🐥 - Adolescent

#9929 XS ◾ Update and rename rules-to-better-gpt.md to rules-to-better-ai.md
  categories/artificial-intelligence/index.md
  categories/artificial-intelligence/rules-to-better-ai.md
Labels: Age: 🥚 - New

#9930 XS ◾ Adding info about holidats
  rules/check-the-calendar-when-planning-an-event/rule.md
Labels: Age: 🥚 - New

#9927 XS ◾ Change from BCC to CC "followupthen"
  rules/follow-up-effectively/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9923 Create "Do you know how to link local dependency for npm?"
  rules/link-local-npm-dependency/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9934 XS ◾ Fixed greybox
  rules/remind-your-staff-to-dress-well/rule.md
Labels: Age: 🐥 - Adolescent

#9933 XS ◾ Updating all links o rule to relative paths
  rules/request-a-test-please/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9932 Update Rule “monitor-the-uptimes-of-all-your-servers-daily/rule”
  rules/monitor-the-uptimes-of-all-your-servers-daily/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9931 Update Rule “monitor-failed-login-attempts/rule”
  rules/monitor-failed-login-attempts/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9938 XS ◾ updating summary recording URL
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#9936 Update Rule “calendar-do-you-allow-full-access-to-calendar-admins/rule”
  rules/calendar-do-you-allow-full-access-to-calendar-admins/calendar-share.png
  rules/calendar-do-you-allow-full-access-to-calendar-admins/rule.md
Labels: Age: 🐓 - Old

#9937 Update Rule “report-bugs-and-suggestions/rule”
  rules/report-bugs-and-suggestions/rule.md
Labels: Age: 🐓 - Old

#9939 XL ◾ Migrate to App Router
  categories/software-engineering/rules-to-better-nextjs.md
  rules/migrate-to-app-router/rule.md
Labels: Age: 🐣 - Young

#9941 M ◾ Updated outdated rule about MVC
  categories/software-engineering/rules-to-better-mvc.md
  rules/do-you-use-view-models-instead-of-viewdata/rule.md
Labels: Age: 🐣 - Young
