Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-08, with the labels that each got.

#10608 XS ◾ Update consistency rule
  rules/the-value-of-consistency/consistency.png
  rules/the-value-of-consistency/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10607 XS ◾ Update /review-prs-when-not-required/rule.md
  rules/review-prs-when-not-required/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10614 Update Rule “design-system/rule”
  rules/design-system/rule.md
Labels: Age: 🥚 - New

#10616 XS ◾ Remove third goal option
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#10617 XS ◾ Fixed orphaned rule
  categories/company-operations/rules-to-successful-projects.md
  categories/software-engineering/rules-to-better-application-performance.md
  categories/software-engineering/rules-to-better-internationalization.md
Labels: Age: 🐤 - Mature

#10618 XS ◾ Update /the-value-of-consistency/rule.md
  rules/the-value-of-consistency/rule.md
Labels: Age: 🐥 - Adolescent

#10619 XS ◾ Update /add-attributes-to-picture-links/rule.md to fix broken image
  rules/add-attributes-to-picture-links/rule.md
Labels: rubber stamp, Age: 🐣 - Young

#10620 XS ◾ Update /responsive-design/rule.md
  rules/lowercase-urls/rule.md
  rules/responsive-design/rule.md
Labels: Age: 🐣 - Young

#10622 S ◾ Update /avoid-unnecessary-css-classes/rule.md
  rules/avoid-unnecessary-css-classes/rule.md
  rules/css-frameworks/rule.md
Labels: Age: 🥚 - New

#10621 XS ◾ Update /reply-done/rule.md
  rules/reply-done/rule.md
Labels: Age: 🥚 - New

#10628 S ◾ Update /use-icons-to-not-surprise-users/rule.md
  rules/use-icons-to-not-surprise-users/rule.md
Labels: Age: 🥚 - New

#10630 XS ◾ Update rule.md
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10631 XS ◾ Update rule.md
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🐥 - Adolescent

#10629 XS ◾ Edits with Brady and Calum
  rules/design-system/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10636 M ◾ Update /risk-multipliers/rule.md
  rules/risk-multipliers/rule.md
Labels: Age: 🥚 - New

#10637 XS ◾ Removing duplicate author
  rules/risk-multipliers/rule.md
Labels: Age: 🥚 - New

#10641 M ◾ Update and rename /devops-things-to-measure
  categories/project-delivery/rules-to-better-devops-using-azure-devops.md
  categories/project-delivery/rules-to-better-devops-using-github.md
  categories/project-delivery/rules-to-better-devops.md
  rules/devops-things-to-measure/jotform-things-to-measure.png
  rules/devops-things-to-measure/rule.md
  rules/things-to-measure/rule.md
Labels: Age: 🥚 - New

#10644 M ◾ Update and rename "forgot-password" rule
  categories/design/rules-to-better-interfaces-forms.md
  categories/design/rules-to-better-websites-layout-and-formatting.md
  rules/authentication-do-you-have-a-forgot-my-password-link/rule.md
  rules/forgot-password/forgot-password-bad.png
  rules/forgot-password/forgot-password-good.png
  rules/forgot-password/reset-password-example.png
  rules/forgot-password/rule.md
  rules/forgot-password/username-enumeration-bad.png
  rules/forgot-password/username-enumeration-good.png
Labels: Age: 🐓 - Old

#10645 XS ◾ Update /user-authentication-terms/rule.md
  categories/design/rules-to-better-interfaces-forms.md
  rules/label-buttons-consistently/rule.md
  rules/user-authentication-terms/rule.md
Labels: Age: 🐓 - Old

#10650 M ◾ Update Rule "Run LLMs Locally"
  rules/run-llms-locally/cline-local.webm
  rules/run-llms-locally/ollama-or-lmstudio-ui.png
  rules/run-llms-locally/rule.md
Labels: Age: 🥚 - New

#10653 S ◾ Update /run-llms-locally/rule.md
  rules/run-llms-locally/rule.md
Labels: Age: 🥚 - New

#10657 XS ◾ Archived /do-you-have-a-devops-checklist/rule.md
  rules/do-you-have-a-devops-checklist/rule.md
Labels: Age: 🐣 - Young

#10660 XS ◾ Update run-llms-locally
  rules/run-llms-locally/rule.md
Labels: Age: 🥚 - New

#10658 M ◾ CTF Circus - Accessibility
  rules/wcag-compliance/rule.md
Labels: Age: 🥚 - New

#10662 Update Rule “email-send-a-v2/rule”
  rules/email-send-a-v2/rule.md
Labels: Age: 🐣 - Young

#10667 XS ◾ Update wcag rule
  rules/seo-tools/rule.md
  rules/wcag-compliance/rule.md
Labels: Age: 🥚 - New

#10669 M ◾ Update /wcag-compliance/rule.md
  rules/wcag-compliance/rule.md
Labels: Age: 🐣 - Young

#10668 XS ◾ Update descriptive-links/rule.md
  rules/descriptive-links/rule.md
Labels: Age: 🐣 - Young

#10673 M ◾ Refine humanize AI content guidelines and formatting
  rules/humanise-ai-generated-content/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10674 S ◾ Refine AI training guide and SEO description
  rules/train-ai-to-write-in-your-style/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10677 Update Rule “install-dynamics-iphone-android-app/rule”
  rules/install-dynamics-iphone-android-app/rule.md
Labels: Age: 🐓 - Old

#10680 XS ◾ Update rule.md
  rules/production-do-you-manage-audience-interactivity/rule.md
Labels: Age: 🐓 - Old

#10670 M ◾ Update /prefixes/rule.md
  categories/design/rules-to-better-content-design.md
  rules/prefixes/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10681 XS ◾ Update rule.md - add point for ensuring production environments and c…
  rules/done-video/rule.md
Labels: Age: 🥚 - New

#10682 S ◾ Enhance rule.md with examples for lists
  rules/prefixes/rule.md
Labels: Age: 🥚 - New

#10686 XS ◾ Update rule.md
  rules/what-happens-at-a-sprint-review-meeting/rule.md
Labels: Age: 🥚 - New

#10688 XS ◾ Fixed inconsistent heading on /humanise-ai-generated-content/rule.md
  rules/humanise-ai-generated-content/rule.md
Labels: rubber stamp, Age: 🐥 - Adolescent

#10690 M ◾ Improve architecture diagram rule to follow standards
  rules/architecture-diagram/rule.md
Labels: Age: 🐣 - Young
