Repository SSWConsulting/SSW.Rules.Content, pull requests merged in 2025-03, with the labels that each got.

#9942 S ◾ updating twitter rules
  categories/marketing-and-video/rules-to-better-social-media-paid-advertising.md
  categories/marketing-and-video/rules-to-better-social-media-personal.md
  rules/do-you-know-that-every-comment-gets-a-tweet/rule.md
  rules/do-you-know-what-to-tweet/rule.md
  rules/thank-others-for-each-reference-to-you/rule.md
  rules/x-ads-best-practices/rule.md
  rules/x-business/rule.md
  rules/x-change-name-when-travelling/rule.md
  rules/x-hashtag-vs-mention/rule.md
  rules/x-tip-creators/rule.md
  rules/x-verify-your-account
Labels: Age: 🥚 - New

#9943 XS ◾ Fixing orphaned rules
  categories/client-engagement/rules-to-better-software-consultants-working-in-a-team.md
  categories/communication/rules-to-better-microsoft-teams.md
  categories/communication/rules-to-better-technical-documentation.md
  categories/company-operations/rules-to-better-offices.md
  categories/infrastructure-and-networking/rules-to-better-automation.md
  categories/infrastructure-and-networking/rules-to-better-control4.md
Labels: Age: 🐥 - Adolescent

#9944 XS ◾ Making Bootstrap rule more generic
  categories/design/rules-to-better-websites-layout-and-formatting.md
  categories/project-delivery/rules-to-better-version-control-with-git.md
  categories/software-engineering/rules-to-better-net-projects.md
  categories/software-engineering/rules-to-better-ui-bootstrap.md
  categories/software-engineering/rules-to-better-websites-development.md
  rules/css-frameworks/rule.md
Labels: Age: 🐤 - Mature

#9945 M ◾ Updating instructions
  categories/marketing-and-video/rules-to-better-marketing.md
  rules/how-to-optimize-your-google-my-business-profile/rule.md
  rules/optimize-google-my-business-profile/rule.md
Labels: Age: 🥚 - New

#9946 XS ◾ Adding image to Google business rule
  rules/optimize-google-my-business-profile/google-business.jpg
  rules/optimize-google-my-business-profile/rule.md
Labels: Age: 🐥 - Adolescent

#9949 XS ◾ Add categories for follow semver
  categories/software-engineering/rules-to-better-devops.md
  rules/follow-semver-when-publishing-npm-packages/rule.md
Labels: Age: 🐥 - Adolescent

#9947 Update Rule “meeting-do-you-update-your-tasks-before-the-daily-scrum/rule”
  rules/meeting-do-you-update-your-tasks-before-the-daily-scrum/rule.md
Labels: Age: 🐤 - Mature

#9953 XS ◾ Change "master" to "main"
  rules/do-you-know-when-to-branch-in-git/rule.md
Labels: Age: 🥚 - New

#9952 XS ◾ Add spaces between image and caption
  rules/add-useful-and-concise-figure-captions/rule.md
Labels: Age: 🐣 - Young

#9950 Update Rule “modular-monolith-testing/rule”
  rules/modular-monolith-testing/rule.md
Labels: Age: 🐓 - Old

#9940 Updating content of do you know how to manage objections and created rule Managing Entra ID
  categories/infrastructure-and-networking/rules-to-better-cloud-security.md
  rules/do-you-know-how-to-manage-objections/rule.md
  rules/managing-microsoft-entra-id/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9964 XS ◾ fix build
  rules/managing-microsoft-entra-id/rule.md
Labels: Age: 🥚 - New

#9970 XS ◾ Updating Manage objections
  rules/manage-objections/rule.md
Labels: Age: 🥚 - New

#9971 M ◾ ✨ Screen Recording - Do you wear company t-shirt?
  categories/marketing-and-video/rules-to-better-video-recording.md
  rules/do-you-wear-company-tshirt-during-screen-recording/rule.md
Labels: Age: 🥚 - New

#9974 S ◾ Improvements to manage-objections rule
  rules/manage-objections/rule.md
Labels: Age: 🥚 - New

#9975 XS ◾ 🐛 Fix image extension from jpg to png
  rules/wear-company-tshirt-during-screen-recording/rule.md
Labels: Age: 🥚 - New

#9961 M ◾ Several improvements to google-my-business-profile
  rules/optimize-google-my-business-profile/rule.md
  rules/why-your-business-should-be-on-google-my-business/rule.md
Labels: Age: 🐓 - Old

#9960 XS ◾ Improved "monitor-external-reviews" rule
  rules/monitor-external-reviews/rule.md
Labels: Age: 🐓 - Old

#9959 XS ◾ Relating formatting rules
  rules/address-formatting/rule.md
  rules/right-format-to-show-phone-numbers/rule.md
Labels: Age: 🐓 - Old

#9954 S ◾ Updated rules on bug reporting
  rules/report-bugs-and-suggestions/rule.md
  rules/reporting-net-applications-errors/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9956 XS ◾ Add good and bad examples captions to the figures
  rules/do-you-highlight-the-search-term/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9978 XS ◾ Added good and bad
  rules/use-system-prompt/rule.md
Labels: Age: 🥚 - New

#9979 XS ◾ Fixed problem in content
  rules/specification-review-presentation/rule.md
Labels: Age: 🥚 - New

#9977 XL ◾ Adding new rule for ef core optimization strategies
  categories/software-engineering/rules-to-better-entity-framework.md
  rules/optimise-ef-core-queries/rule.md
Labels: Age: 🐤 - Mature

#9980 S ◾ Fixing captions on good and bad examples
  rules/conduct-a-spec-review/rule.md
  rules/spec-do-you-use-user-stories/rule.md
  rules/specification-review-presentation/rule.md
  rules/use-ai-to-generate-spec-reviews/rule.md
Labels: Age: 🐥 - Adolescent

#9957 XS ◾ Fix formatting and emojis on captions
  rules/do-you-know-to-use-save-save-and-close-on-a-webpage/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9983 Create Rule “react-to-github/rule”
  categories/software-engineering/rules-to-better-github.md
  rules/like-and-comment-on-videos/rule.md
  rules/react-to-github/github-reaction.png
  rules/react-to-github/github-vote-up.png
  rules/react-to-github/rule.md
Labels: Age: 🥚 - New

#9982 XS ◾ Added box about the benefits of voting in GitHub Discussions
  rules/use-github-discussions/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#9962 Update Rule “choosing-authentication/rule”
  rules/choosing-authentication/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#9986 XS ◾ Remove Skype & TeamViewer reference
  rules/meeting-do-you-know-what-to-prepare-for-each-meeting/rule.md
Labels: Age: 🐥 - Adolescent

#9994 XS ◾ 🔧 Type - Fix caption for editing calendar appointment
  rules/do-you-make-your-team-meetings-easy-to-find/rule.md
Labels: Age: 🥚 - New

#9996 XS ◾ ✏️ Formatting - Fix 'Do you know how to manage objections?'
  rules/manage-objections/rule.md
Labels: Age: 🥚 - New

#10001 XS ◾ fix merge issue
  rules/how-to-make-decisions/rule.md
Labels: Age: 🥚 - New

#10002 XS ◾ desisions - make title consistent
  rules/how-to-make-decisions/rule.md
Labels: Age: 🥚 - New

#10003 XS ◾ fix styling on Edison quote
  rules/how-to-make-decisions/rule.md
Labels: Age: 🥚 - New

#10004 Update Rule “how-to-make-decisions/rule”
  rules/how-to-make-decisions/rule.md
Labels: Age: 🐣 - Young

#9984 M ◾ New rule - drip campaigns
  categories/marketing-and-video/rules-to-better-marketing.md
  rules/email-drip-campaign/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10000 XS ◾ Github issue templates - mention issue forms
  rules/github-issue-templates/rule.md
Labels: Age: 🐥 - Adolescent

#10006 XS ◾ Improvements to CTF decision-making rule
  rules/how-to-make-decisions/rule.md
Labels: Age: 🥚 - New

#10007 XS ◾ Added type 3 to decision making rule
  rules/how-to-make-decisions/rule.md
Labels: Age: 🥚 - New

#10009 XS ◾ Fix typo in 'Do you know how to make business decisions?'
  rules/how-to-make-decisions/rule.md
Labels: Age: 🥚 - New

#10011 XS ◾ remove author from rule
  rules/how-to-make-decisions/rule.md
Labels: Age: 🥚 - New

#10010 XS ◾ Update rule.md
  rules/use-the-best-email-templates/rule.md
Labels: Age: 🥚 - New

#10016 XS ◾ Adding new video to rule
  rules/end-user-documentation/rule.md
Labels: Age: 🥚 - New

#10013 Update Rule “methodology-daily-scrums/rule”
  rules/methodology-daily-scrums/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10017 Update Rule “expiring-app-secrets-certificates/rule”
  categories/infrastructure-and-networking/rules-to-better-system-administrators.md
  rules/expiring-app-secrets-certificates/rule.md
Labels: Age: 🐥 - Adolescent

#10023 S ◾ New rule - dashes
  categories/communication/rules-to-better-technical-documentation.md
  rules/dashes/rule.md
Labels: Age: 🥚 - New

#10020 S ◾ added bad example to making names as headings
  rules/include-names-as-headings/rule.md
Labels: Age: 🐤 - Mature

#10021 XS ◾ Made headings consistent "report-bugs-and-suggestions"
  rules/report-bugs-and-suggestions/rule.md
Labels: Age: 🐥 - Adolescent

#10014 XS ◾ remove 3rd decision type
  rules/how-to-make-decisions/rule.md
Labels: Age: 🦖 - Extinct, 🔥 Merge Debt

#10019 M ◾ rewrote "formatting-ui-elements" rule
  categories/communication/rules-to-better-technical-documentation.md
  rules/formatting-ui-elements/rule.md
  rules/use-quotation-mark-for-controls/rule.md
Labels: Age: 🐓 - Old

#10025 XS ◾ fix formatting on How To Make Decisions rule
  rules/how-to-make-decisions/rule.md
Labels: Age: 🥚 - New

#10018 Create Rule “avoid-ai-hallucinations/rule”
  categories/artificial-intelligence/rules-to-better-ai-development.md
  rules/avoid-ai-hallucinations/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10022 Update Rule “azure-naming-resource-groups/rule”
  rules/azure-naming-resource-groups/rule.md
  rules/azure-naming-resource-groups/screenshot-2025-03-18-080729.png
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10029 XS ◾ Fixing title and slug
  categories/artificial-intelligence/rules-to-better-ai-development.md
  rules/make-your-website-llm-friendly/rule.md
Labels: Age: 🥚 - New

#10032 XS ◾ fixed broken links
  rules/make-your-website-llm-friendly/rule.md
Labels: Age: 🥚 - New

#10027 M ◾ Updated few rules on dates formatting
  categories/design/rules-to-better-websites-layout-and-formatting.md
  categories/software-engineering/rules-to-better-sharepoint-for-developers.md
  rules/add-days-to-dates/rule.md
  rules/date-and-time-of-change-as-tooltip/rule.md
  rules/do-you-display-dates-in-a-human-friendly-format/rule.md
  rules/human-friendly-date-and-time/rule.md
  rules/sharepoint-format-dates-to-include-the-weekday/rule.md
Labels: Age: 🐤 - Mature

#10033 XS ◾ added video tor rule
  rules/make-your-website-llm-friendly/rule.md
Labels: Age: 🥚 - New

#10026 XL ◾ Create - Adding new rule to optimize the bundle size
  rules/optimize-bundle-size/optimized-bundle-size.png
  rules/optimize-bundle-size/rule.md
  rules/optimize-bundle-size/unoptimized-bundle-size.png
Labels: Age: 🐓 - Old

#10035 S ◾ Update rule LLM-friendly
  rules/make-your-website-llm-friendly/rule.md
Labels: Age: 🐥 - Adolescent

#10041 S ◾ Added Caleb's video to meta tags rule
  rules/html-meta-tags/dorybadmetadescription.jpg
  rules/html-meta-tags/metadescriptionsswdory.jpg
  rules/html-meta-tags/rule.md
Labels: Age: 🐓 - Old

#10040 XS ◾ Updated "the-6-ways-to-integrate-your-crm-2011-data-into-sharepoint-2010"
  rules/do-you-know-the-6-ways-to-integrate-your-crm-2011-data-into-sharepoint-2010/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10042 XS ◾ added missing "good" class
  rules/html-meta-tags/rule.md
Labels: Age: 🥚 - New

#10039 XS ◾ Updated "best-ui-framework-react" rule
  rules/tools-do-you-know-the-best-ui-framework-for-react/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10047 S ◾ Update track important emails
  rules/avoid-ai-hallucinations/rule.md
  rules/track-important-emails/Track-from-web.png
  rules/track-important-emails/rule.md
Labels: Age: 🥚 - New

#10048 XS ◾ Fixed duplicate rule GUID
  rules/managing-microsoft-entra-id/rule.md
Labels: Age: 🐣 - Young

#10043 Update Rule “do-you-know-how-to-reduce-spam/rule”
  rules/do-you-know-how-to-reduce-spam/rule.md
Labels: Age: 🐤 - Mature

#10046 XS ◾ Update markup to render properly.
  rules/avoid-ai-hallucinations/rule.md
Labels: Age: 🐥 - Adolescent

#10044 XS ◾ Make sure technology is up to date
  rules/meeting-do-you-know-what-to-prepare-for-each-meeting/rule.md
Labels: Age: 🐓 - Old

#10055 XS ◾ Update security-email-account
  rules/security-email-account/rule.md
Labels: Age: 🥚 - New

#10051 XS ◾ Add Eddie and Calum as authors
  rules/track-important-emails/rule.md
Labels: Age: 🐤 - Mature

#10053 XS ◾ Avoid ai hallucinations fix 2
  rules/avoid-ai-hallucinations/rule.md
Labels: Age: 🐤 - Mature

#10056 XS ◾ Added YakShaver to AI tools
  rules/best-ai-tools/rule.md
Labels: Age: 🐥 - Adolescent

#10059 XS ◾ Fixed folder name
  rules/use-gitignore-for-clean-repo/rule.md
Labels: Age: 🥚 - New

#10050 S ◾ Fixed Markdown for old rule
  rules/do-you-know-how-to-rollback-changes-in-tfs/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10049 XS ◾ Fixed URl and improved example "exclude-width-and-height-properties-f…
  categories/software-engineering/rules-to-better-websites-graphics.md
  rules/exclude-width-and-height-properties-from-images/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10060 XS ◾ Update different-types-of-testing rule
  rules/different-types-of-testing/rule.md
Labels: Age: 🥚 - New

#10058 L ◾ CTF - exercise rule
  rules/do-you-encourage-daily-exercise-at-work/rewards-mi-band.jpg
  rules/do-you-encourage-daily-exercise-at-work/rule.md
Labels: Age: 🐓 - Old

#10061 M ◾ Improving CTF rule
  rules/do-you-encourage-daily-exercise-at-work/rule.md
Labels: Age: 🥚 - New

#10062 XS ◾ updating CTF rule
  rules/do-you-encourage-daily-exercise-at-work/rule.md
Labels: Age: 🥚 - New

#10064 XS ◾ Rename and improve CTF rule
  rules/encourage-daily-exercise/rule.md
Labels: Age: 🥚 - New

#10066 XS ◾ Update rule.md
  rules/encourage-daily-exercise/rule.md
Labels: Age: 🥚 - New

#10067 XS ◾ Update rule.md
  categories/company-operations/rules-to-better-health-and-exercise-in-the-workplace.md
  rules/encourage-daily-exercise/rule.md
Labels: Age: 🥚 - New

#10068 M ◾ New rule about comparing PR performance with Production
  categories/software-engineering/rules-to-better-application-performance.md
  categories/software-engineering/rules-to-better-pull-requests.md
  rules/compare-pr-performance-with-production/pr-comparison-with-prod.png
  rules/compare-pr-performance-with-production/rule.md
  rules/optimize-bundle-size/rule.md
Labels: Age: 🥚 - New

#10071 XS ◾ Added link to stakeholders in Sprint review meeting template
  rules/scrum-master-do-you-schedule-the-3-meetings/rule.md
Labels: Age: 🥚 - New

#10074 XS ◾ Adding AI tools to email template
  rules/sprint-review-retro-email/rule.md
Labels: Age: 🥚 - New

#10077 XS ◾ updating video
  rules/encourage-daily-exercise/rule.md
Labels: Age: 🥚 - New

#10078 XS ◾ adding related rules
  rules/do-you-know-the-dangers-of-sitting/rule.md
  rules/encourage-daily-exercise/rule.md
  rules/lasting-habits/rule.md
  rules/stretch-at-work/rule.md
Labels: Age: 🥚 - New

#10075 L ◾ Update 404 page rule
  rules/404-useful-error-page/404-bad.jpg
  rules/404-useful-error-page/404-bad.png
  rules/404-useful-error-page/404-good.jpg
  rules/404-useful-error-page/404-good.png
  rules/404-useful-error-page/rule.md
Labels: Age: 🐓 - Old

#10072 📝Do you know how to find broken links? | Added heading about CodeAuditor
  rules/how-to-find-broken-links/broken-link-summary.png
  rules/how-to-find-broken-links/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10073 Update Rule “optimize-bundle-size/rule”
  rules/optimize-bundle-size/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10079 L ◾ new birthday rule
  categories/company-operations/rules-to-better-office-operations.md
  rules/birthdays/rule.md
  rules/do-you-reward-your-employees-for-doing-their-timesheets-on-time/rule.md
Labels: Age: 🍗 - Ancient, 🔥 Merge Debt

#10082 Cms/edkranz/ssw.rules.content/rule/agentic ai/rule
  rules/agentic-ai/rule.md
Labels: Age: 🐣 - Young

#10083 XS ◾ Remove extra title. Remove extra table. Add star next to Autogen
  rules/agentic-ai/rule.md
Labels: Age: 🥚 - New

#10084 XS ◾ Added intro + moved video down on "daily exercise" rule
  rules/encourage-daily-exercise/rule.md
Labels: Age: 🥚 - New

#10086 XS ◾ Add rule to category, add related rule
  categories/artificial-intelligence/rules-to-better-ai-development.md
  rules/agentic-ai/rule.md
Labels: Age: 🥚 - New
